package com.erp.inv;

import com.erp.common.ServiceException;
import com.erp.dao.inv.InvBatchDao;
import com.erp.dao.mdm.MdmItemDao;
import com.erp.entity.inv.InvBatch;
import com.erp.entity.mdm.MdmItem;
import com.erp.service.impl.inv.BatchServiceImpl;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * 批次台账规则单测（4.2.1，spec batch-master，任务 2.2/2.3/2.4）：
 * 自动编号格式、同物料唯一 409、编号锁定 422、效期必填/顺序校验（BR-4.1-08）、权限。
 */
class BatchRulesUnitTest {

    private InvBatchDao batchDao;
    private MdmItemDao itemDao;
    private BatchServiceImpl service;

    @BeforeEach
    void loginAsWarehouse() {
        SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(
                "junit", "n/a", List.of(new SimpleGrantedAuthority("ROLE_WAREHOUSE"))));
        batchDao = mock(InvBatchDao.class);
        itemDao = mock(MdmItemDao.class);
        service = new BatchServiceImpl(batchDao, itemDao);
        when(batchDao.insert(any(InvBatch.class))).thenAnswer(inv -> 1);
        when(batchDao.selectCount(any())).thenReturn(0L);
        when(batchDao.selectBatchNosByPrefix(anyString())).thenReturn(List.of());
    }

    @AfterEach
    void logout() {
        SecurityContextHolder.clearContext();
    }

    private MdmItem item(String code, String batchFlag) {
        MdmItem it = new MdmItem();
        it.setItemCode(code);
        it.setItemName("测试物料");
        it.setBatchFlag(batchFlag);
        return it;
    }

    private InvBatch payload(String itemCode, String batchNo) {
        InvBatch b = new InvBatch();
        b.setItemCode(itemCode);
        b.setBatchNo(batchNo);
        return b;
    }

    // ---- 2.2 批次号生成与唯一 ----

    @Test
    void autoGeneratedBatchNoFollowsFormat() {
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "0"));
        InvBatch created = service.create(payload("IT-001", null));
        String today = LocalDate.now().format(DateTimeFormatter.ofPattern("yyMMdd"));
        assertEquals("B" + today + "-0001", created.getBatchNo());
    }

    @Test
    void autoGenerationContinuesDailySequence() {
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "0"));
        String today = LocalDate.now().format(DateTimeFormatter.ofPattern("yyMMdd"));
        when(batchDao.selectBatchNosByPrefix("B" + today + "-"))
                .thenReturn(List.of("B" + today + "-0003", "B" + today + "-0007"));
        InvBatch created = service.create(payload("IT-001", null));
        assertEquals("B" + today + "-0008", created.getBatchNo());
    }

    @Test
    void duplicateBatchNoInSameItem409() {
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "0"));
        when(batchDao.selectCount(any())).thenReturn(1L);
        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.create(payload("IT-001", "B261008-0001")));
        assertEquals(409, ex.getCode());
        verify(batchDao, never()).insert(any(InvBatch.class));
    }

    @Test
    void batchNoLockedAfterCreate() {
        InvBatch stored = payload("IT-001", "B261008-0001");
        stored.setId("batch-id");
        when(batchDao.selectById("batch-id")).thenReturn(stored);
        InvBatch edit = payload("IT-001", "CHANGED");
        edit.setId("batch-id");
        ServiceException ex = assertThrows(ServiceException.class, () -> service.update(edit));
        assertEquals(422, ex.getCode());
        assertTrue(ex.getMessage().contains("不可修改"));
    }

    // ---- 2.3 效期校验（BR-4.1-08）----

    @Test
    void batchManagedItemRequiresExpiry422() {
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "1"));
        InvBatch b = payload("IT-001", null);
        b.setProductionDate(LocalDate.of(2026, 10, 1));
        ServiceException ex = assertThrows(ServiceException.class, () -> service.create(b));
        assertEquals(422, ex.getCode());
        assertTrue(ex.getMessage().contains("有效期至"));
    }

    @Test
    void expiryMustBeAfterProductionDate422() {
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "1"));
        InvBatch b = payload("IT-001", null);
        b.setProductionDate(LocalDate.of(2026, 10, 5));
        b.setExpiryDate(LocalDate.of(2026, 10, 1));
        ServiceException ex = assertThrows(ServiceException.class, () -> service.create(b));
        assertEquals(422, ex.getCode());
        assertTrue(ex.getMessage().contains("晚于"));
    }

    @Test
    void nonBatchManagedItemExpiryOptional() {
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "0"));
        InvBatch created = service.create(payload("IT-001", null));
        assertNotNull(created);
        verify(batchDao).insert(any(InvBatch.class));
    }

    @Test
    void unknownItemRejected422() {
        when(itemDao.selectOne(any())).thenReturn(null);
        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.create(payload("IT-NOPE", null)));
        assertEquals(422, ex.getCode());
        assertTrue(ex.getMessage().contains("物料不存在"));
    }

    // ---- 2.4 权限 ----

    @Test
    void roleUserWriteForbidden403() {
        SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(
                "junit", "n/a", List.of(new SimpleGrantedAuthority("ROLE_USER"))));
        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.create(payload("IT-001", null)));
        assertEquals(403, ex.getCode());
        verify(batchDao, never()).insert(any(InvBatch.class));
    }

    @Test
    void unauthenticated401() {
        SecurityContextHolder.clearContext();
        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.create(payload("IT-001", null)));
        assertEquals(401, ex.getCode());
    }

    @Test
    void adminWriteAllowed() {
        SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(
                "junit", "n/a", List.of(new SimpleGrantedAuthority("ROLE_ADMIN"))));
        when(itemDao.selectOne(any())).thenReturn(item("IT-001", "0"));
        assertNotNull(service.create(payload("IT-001", null)));
    }
}
