-- 001 基础：系统用户、角色、用户角色关联（InnoDB + utf8mb4）

CREATE TABLE IF NOT EXISTS erp_admin_user (
    ID VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    NICK_NAME VARCHAR(64),
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SYS_USER_USERNAME (USERNAME),
    KEY IDX_SYS_USER_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_admin_role (
    ID VARCHAR(64) NOT NULL,
    ROLE_CODE VARCHAR(64) NOT NULL,
    ROLE_NAME VARCHAR(64) NOT NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SYS_ROLE_CODE (ROLE_CODE),
    KEY IDX_SYS_ROLE_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_admin_user_role (
    ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    ROLE_ID VARCHAR(64) NOT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY IDX_SYS_UR_USER (USER_ID),
    KEY IDX_SYS_UR_ROLE (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 角色种子
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS) VALUES
('role-admin', 'ROLE_ADMIN', '系统管理员', 10, '1'),
('role-user', 'ROLE_USER', '普通用户', 20, '1'),
('role-pm', 'ROLE_PM', '项目经理', 30, '1');

-- 用户种子（密码均为 Admin@123 的 BCrypt 哈希）
INSERT IGNORE INTO erp_admin_user (ID, USERNAME, PASSWORD, NICK_NAME, STATUS) VALUES
('user-admin', 'admin', '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W', '系统管理员', '1'),
('user-zhangsan', 'zhangsan', '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W', '张三', '1');

INSERT IGNORE INTO erp_admin_user_role (ID, USER_ID, ROLE_ID) VALUES
('ur-admin', 'user-admin', 'role-admin'),
('ur-zhangsan', 'user-zhangsan', 'role-user');
