-- 002 菜单表 erp_admin_menu（层次化导航，基准清单见 docs/design/08-erp-menu.md）

CREATE TABLE IF NOT EXISTS erp_admin_menu (
    ID VARCHAR(64) NOT NULL,
    PARENT_ID VARCHAR(64) NOT NULL DEFAULT '',
    MENU_CODE VARCHAR(32),
    TITLE VARCHAR(128) NOT NULL,
    PATH VARCHAR(255) NOT NULL DEFAULT '',
    ICON VARCHAR(64) NOT NULL DEFAULT '',
    SORT_ORDER INT NOT NULL DEFAULT 0,
    PERM VARCHAR(255) NOT NULL DEFAULT '',
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SYS_MENU_STATUS (STATUS),
    KEY IDX_SYS_MENU_PARENT (PARENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
