-- 010 MDM 法人主体（组织管理 1.1.1，域前缀 erp_mdm，规范见 docs/design/01-architecture-style.md 1.4）

CREATE TABLE IF NOT EXISTS erp_mdm_legal_entity (
    ID VARCHAR(64) NOT NULL,
    LE_CODE VARCHAR(32) NOT NULL,
    LE_NAME VARCHAR(128) NOT NULL,
    USCC VARCHAR(32),
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    BOOKKEEPING_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'CNY',
    REG_PLACE VARCHAR(64),
    FISCAL_CALENDAR_TYPE VARCHAR(16) NOT NULL DEFAULT 'NATURAL',
    DEFAULT_TIMEZONE VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    CURRENCY_DECIMALS INT NOT NULL DEFAULT 2,
    L10N_PACK VARCHAR(32),
    LOCAL_TAX_NO VARCHAR(32),
    LEGAL_REPRESENTATIVE VARCHAR(64),
    REGISTERED_CAPITAL DECIMAL(18,2),
    REG_ADDRESS VARCHAR(255),
    BANK_NAME VARCHAR(128),
    COST_CENTER_CODE VARCHAR(32),
    PROFIT_CENTER_CODE VARCHAR(32),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_LE_CODE (LE_CODE),
    UNIQUE KEY UK_MDM_LE_USCC (USCC),
    KEY IDX_MDM_LE_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_legal_entity_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_LEV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 示例种子（USCC 为占位格式，投产前须替换为真实信用代码）
INSERT IGNORE INTO erp_mdm_legal_entity
    (ID, LE_CODE, LE_NAME, USCC, STATUS, BOOKKEEPING_CURRENCY, REG_PLACE, FISCAL_CALENDAR_TYPE, DEFAULT_TIMEZONE, CURRENCY_DECIMALS, L10N_PACK, CREATE_BY)
VALUES
    ('le-0001', 'LE-0001', '示例法人主体（上海）', '91310000MA1FL0000X', '1', 'CNY', '上海', 'NATURAL', 'Asia/Shanghai', 2, 'CN', 'system');
