-- 011 MDM 成本中心（组织管理 1.1.2，树形 3 级，域前缀 erp_mdm，规范见 docs/design/01-architecture-style.md 1.4）

CREATE TABLE IF NOT EXISTS erp_mdm_cost_center (
    ID VARCHAR(64) NOT NULL,
    CC_CODE VARCHAR(32) NOT NULL,
    CC_NAME VARCHAR(128) NOT NULL,
    LEGAL_ENTITY_ID VARCHAR(64) NOT NULL,
    PARENT_ID VARCHAR(64) NOT NULL DEFAULT '',
    TREE_LEVEL INT NOT NULL DEFAULT 1,
    COST_TYPE VARCHAR(16) NOT NULL,
    IS_DEFAULT VARCHAR(1) NOT NULL DEFAULT '0',
    OWNER_NAME VARCHAR(64),
    REMARK VARCHAR(255),
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_CC_CODE (CC_CODE),
    KEY IDX_MDM_CC_LE (LEGAL_ENTITY_ID),
    KEY IDX_MDM_CC_STATUS (STATUS),
    KEY IDX_MDM_CC_PARENT (PARENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_cost_center_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_CCV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 示例种子：生产类根节点，挂示例法人主体
INSERT IGNORE INTO erp_mdm_cost_center
    (ID, CC_CODE, CC_NAME, LEGAL_ENTITY_ID, PARENT_ID, TREE_LEVEL, COST_TYPE, IS_DEFAULT, STATUS, CREATE_BY)
VALUES
    ('cc-prod-01', 'CC-PROD-01', '生产制造中心', 'le-0001', '', 1, 'PROD', '1', '1', 'system');
