-- 012 MDM 利润中心（组织管理 1.1.3，平铺单级，域前缀 erp_mdm，规范见 docs/design/01-architecture-style.md 1.4）

CREATE TABLE IF NOT EXISTS erp_mdm_profit_center (
    ID VARCHAR(64) NOT NULL,
    PC_CODE VARCHAR(32) NOT NULL,
    PC_NAME VARCHAR(128) NOT NULL,
    LEGAL_ENTITY_ID VARCHAR(64) NOT NULL,
    OWNER_NAME VARCHAR(64),
    REMARK VARCHAR(255),
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_PC_CODE (PC_CODE),
    KEY IDX_MDM_PC_LE (LEGAL_ENTITY_ID),
    KEY IDX_MDM_PC_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_profit_center_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_PCV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 示例种子，投产前须替换为真实利润中心
INSERT IGNORE INTO erp_mdm_profit_center
    (ID, PC_CODE, PC_NAME, LEGAL_ENTITY_ID, STATUS, CREATE_BY)
VALUES
    ('pc-0001', 'PC-0001', '示例利润中心（上海）', 'le-0001', '1', 'system');
