-- 014 MDM 组织单元（组织管理 1.1.4，树形 3 级 + 六类类型，域前缀 erp_mdm，规范见 docs/design/01-architecture-style.md 1.4）

CREATE TABLE IF NOT EXISTS erp_mdm_org_unit (
    ID VARCHAR(64) NOT NULL,
    OU_CODE VARCHAR(32) NOT NULL,
    OU_NAME VARCHAR(128) NOT NULL,
    LEGAL_ENTITY_ID VARCHAR(64) NOT NULL,
    PARENT_ID VARCHAR(64) NOT NULL DEFAULT '',
    TREE_LEVEL INT NOT NULL DEFAULT 1,
    OU_TYPE VARCHAR(16) NOT NULL,
    OWNER_NAME VARCHAR(64),
    REMARK VARCHAR(255),
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_OU_CODE (OU_CODE),
    KEY IDX_MDM_OU_LE (LEGAL_ENTITY_ID),
    KEY IDX_MDM_OU_STATUS (STATUS),
    KEY IDX_MDM_OU_PARENT (PARENT_ID),
    KEY IDX_MDM_OU_TYPE (OU_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_org_unit_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_OUV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 示例种子：工厂型根节点（六类：FACTORY/WAREHOUSE/PROC/SALE/STORE/RD），挂示例法人主体
INSERT IGNORE INTO erp_mdm_org_unit
    (ID, OU_CODE, OU_NAME, LEGAL_ENTITY_ID, PARENT_ID, TREE_LEVEL, OU_TYPE, STATUS, CREATE_BY)
VALUES
    ('ou-factory-01', 'OU-FACTORY-01', '示例工厂（上海）', 'le-0001', '', 1, 'FACTORY', '1', 'system');
