-- 016 MDM 物料主数据（物料管理 1.2.1 物料新建，依赖 015 分类/字典种子）

CREATE TABLE IF NOT EXISTS erp_mdm_item (
    ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(32) NOT NULL,
    ITEM_NAME VARCHAR(128) NOT NULL,
    CATEGORY_CODE VARCHAR(8) NOT NULL,
    BASE_UNIT VARCHAR(32) NOT NULL,
    MATERIAL_GROUP VARCHAR(32) NOT NULL,
    PURCHASE_TYPE VARCHAR(16) NOT NULL,
    STORAGE_CONDITION VARCHAR(16) NOT NULL,
    ALT_ITEM_CODE VARCHAR(32),
    SAFETY_STOCK DECIMAL(18,3),
    LEAD_TIME_DAYS INT,
    BATCH_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    SHELF_LIFE_DAYS INT,
    PACKING_SPEC VARCHAR(255),
    BARCODE VARCHAR(64),
    BOM_VERSION VARCHAR(32),
    DUP_NOTE VARCHAR(255),
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_ITEM_CODE (ITEM_CODE),
    KEY IDX_MDM_ITEM_CAT (CATEGORY_CODE),
    KEY IDX_MDM_ITEM_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_item_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_ITEMV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 示例物料种子（RM0001 下流水从 000001 起，投产前须替换为真实数据）
INSERT IGNORE INTO erp_mdm_item
    (ID, ITEM_CODE, ITEM_NAME, CATEGORY_CODE, BASE_UNIT, MATERIAL_GROUP, PURCHASE_TYPE, STORAGE_CONDITION,
     BATCH_FLAG, SHELF_LIFE_DAYS, STATUS, CREATE_BY)
VALUES
    ('item-rm-000001', 'RM0001000001', '不锈钢管 DN50 304L', 'RM0001', 'M', 'STRUCT', 'BUY', 'NORMAL',
     '1', 3650, '1', 'system');
