-- 020 MDM 客户准入（客户管理 1.3.1，流程六 FR-4.1-6-1/6-2；BR-4.1-04/30/31/34）

CREATE TABLE IF NOT EXISTS erp_mdm_customer_group (
    ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) NOT NULL,
    CUSTOMER_NAME VARCHAR(128) NOT NULL,
    TAX_NO VARCHAR(32),
    USCC VARCHAR(32),
    CREDIT_RATING VARCHAR(16),
    CREDIT_LIMIT_TOTAL DECIMAL(18,2),
    -- 1 启用 / 0 停用 / 2 冻结（级联法人视图，BR-4.1-34）/ 3 已合并（终态，编码锁定 C-4.1-10）
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    MERGED_TO VARCHAR(32),
    DUP_NOTE VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_CG_CODE (CUSTOMER_CODE),
    KEY IDX_MDM_CG_TAX (TAX_NO),
    KEY IDX_MDM_CG_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_customer_view (
    ID VARCHAR(64) NOT NULL,
    GROUP_ID VARCHAR(64) NOT NULL,
    LEGAL_ENTITY_ID VARCHAR(64) NOT NULL,
    SHIP_ADDRESS VARCHAR(255),
    CONTACT_NAME VARCHAR(64),
    CONTACT_PHONE VARCHAR(32),
    PAYMENT_TERMS VARCHAR(32),
    CREDIT_LIMIT DECIMAL(18,2),
    -- 1 启用 / 0 停用 / 2 冻结（由集团级联写入）
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_CV_GROUP_LE (GROUP_ID, LEGAL_ENTITY_ID),
    KEY IDX_MDM_CV_GROUP (GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_customer_group_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_CGV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_customer_view_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_CVV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
