-- 022 跨域共享（客户管理 1.3.3，7.2 事件契约 + Outbox + FR-4.1-6-2 价格协议缺口）
-- 4 表：通用事件表（ops 域）+ 价格协议头/行/版本（mdm 域）；IF NOT EXISTS 幂等

CREATE TABLE IF NOT EXISTS erp_ops_outbox (
    ID VARCHAR(64) NOT NULL,
    EVENT_ID VARCHAR(64) NOT NULL,
    EVENT_TYPE VARCHAR(64) NOT NULL,
    VERSION INT NOT NULL DEFAULT 1,
    RECORD_VERSION INT NOT NULL DEFAULT 1,
    OCCURRED_AT DATETIME NOT NULL,
    SOURCE VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL,
    LEGAL_ENTITY_ID VARCHAR(64),
    PAYLOAD LONGTEXT,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    CONSUMER_NOTE VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_OB_EVENT_ID (EVENT_ID),
    UNIQUE KEY UK_OB_IDEMPOTENCY (IDEMPOTENCY_KEY),
    KEY IDX_OB_TYPE (EVENT_TYPE),
    KEY IDX_OB_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_price_agreement (
    ID VARCHAR(64) NOT NULL,
    PA_CODE VARCHAR(32) NOT NULL,
    PA_NAME VARCHAR(128) NOT NULL,
    -- EXCLUSIVE 客户专属价 / LADDER 量价阶梯 / TIME 时间价（渠道基准价 CHANNEL 属销售域 Non-Goal）
    AGREEMENT_TYPE VARCHAR(16) NOT NULL,
    CUSTOMER_GROUP_ID VARCHAR(64),
    CUSTOMER_VIEW_ID VARCHAR(64),
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRE_DATE DATE,
    -- 0 未生效 / 1 生效中 / 2 过期 / 3 停用
    STATUS VARCHAR(1) NOT NULL DEFAULT '0',
    STOP_REASON VARCHAR(255),
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_PA_CODE (PA_CODE),
    KEY IDX_MDM_PA_GROUP (CUSTOMER_GROUP_ID),
    KEY IDX_MDM_PA_VIEW (CUSTOMER_VIEW_ID),
    KEY IDX_MDM_PA_TYPE_STATUS (AGREEMENT_TYPE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_price_agreement_line (
    ID VARCHAR(64) NOT NULL,
    PA_ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(32) NOT NULL,
    UNIT_PRICE DECIMAL(18,4) NOT NULL,
    MIN_QTY DECIMAL(18,3),
    MAX_QTY DECIMAL(18,3),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MDM_PAL_PA (PA_ID),
    KEY IDX_MDM_PAL_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_price_agreement_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_PAV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
