-- 023 供应商准入（供方管理 1.4.1，行 550 四组字段 + S-4.1-10 证照治理 + BR-4.2-18 五态）
-- 状态机：PENDING 待审核 / QUALIFIED 合格 / FROZEN 冻结 / DISABLED 停用 / CERT_EXPIRED 证照过期

CREATE TABLE IF NOT EXISTS erp_mdm_supplier (
    ID VARCHAR(64) NOT NULL,
    SUPPLIER_CODE VARCHAR(32) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(255),
    CONTACT_NAME VARCHAR(64),
    CONTACT_PHONE VARCHAR(32),
    LEGAL_ENTITY_ID VARCHAR(64),
    BANK_NAME VARCHAR(128),
    TAX_NO VARCHAR(32),
    PAYMENT_TERMS VARCHAR(32),
    -- 黑名单筛查结果：CLEAR 未命中 / HIT 命中（HIT → 建档与变更双入口 422）
    BLACKLIST_RESULT VARCHAR(16) NOT NULL DEFAULT 'CLEAR',
    ESG_RATING VARCHAR(16),
    -- PENDING / QUALIFIED / FROZEN / DISABLED / CERT_EXPIRED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    REVIEW_REASON VARCHAR(255),
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_MS_CODE (SUPPLIER_CODE),
    KEY IDX_MDM_MS_STATUS (STATUS),
    KEY IDX_MDM_MS_TAX (TAX_NO),
    KEY IDX_MDM_MS_LE (LEGAL_ENTITY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_supplier_cert (
    ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    -- LICENSE 营业执照 / INDUSTRY 行业认证 / OTHER 其它
    CERT_TYPE VARCHAR(16) NOT NULL,
    CERT_NO VARCHAR(64),
    ISSUE_DATE DATE,
    EXPIRE_DATE DATE NOT NULL,
    VERIFY_NOTE VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MSC_SUPPLIER (SUPPLIER_ID),
    KEY IDX_MSC_EXPIRE (EXPIRE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_supplier_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_MSV (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
