-- 024 供应商合并去重（供方管理 1.4.2，流程五 FR-4.1-5-x + BR-4.1-03/25 + C-4.1-10/11）
-- MySQL 无 ADD COLUMN IF NOT EXISTS，marker 幂等（013 教训：中断须手动补跑）

ALTER TABLE erp_mdm_supplier
    ADD COLUMN MERGED_TO VARCHAR(32) NULL COMMENT '合并指向目标编码（STATUS=MERGED 时非空）' AFTER STATUS,
    ADD COLUMN PRE_STATUS VARCHAR(16) NULL COMMENT '合并前状态（30 天回退恢复用）' AFTER MERGED_TO;

-- 合并日志：永久保留（BR-4.1-03 源编码日志 + C-4.1-11 审计），无 DEL_FLAG 不软删
CREATE TABLE IF NOT EXISTS erp_mdm_supplier_merge_log (
    ID VARCHAR(64) NOT NULL,
    LOG_NO VARCHAR(32) NOT NULL,
    SOURCE_ID VARCHAR(64) NOT NULL,
    SOURCE_CODE VARCHAR(32) NOT NULL,
    TARGET_ID VARCHAR(64) NOT NULL,
    TARGET_CODE VARCHAR(32) NOT NULL,
    PRE_STATUS VARCHAR(16),
    IMPACT_SUMMARY VARCHAR(500),
    -- BR-4.1-28 反查锚点：原单据经此字段追溯合并前归属（= SOURCE_CODE）
    ORIGINAL_SUPPLIER_CODE VARCHAR(32),
    MERGE_AT DATETIME NOT NULL,
    OPERATOR VARCHAR(64),
    REVERTED VARCHAR(1) NOT NULL DEFAULT '0',
    REVERT_AT DATETIME,
    REVERT_REASON VARCHAR(255),
    REVERT_OPERATOR VARCHAR(64),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MDM_MSL_LOGNO (LOG_NO),
    KEY IDX_MDM_MSL_SOURCE (SOURCE_CODE),
    KEY IDX_MDM_MSL_TARGET (TARGET_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
