-- 025 汇率维护（汇率管理 1.5.1，FR-4.1-3-1 + C-4.1-04 + BR-4.1-16/17/18）
-- 区间序列键 = (BASE_CCY, QUOTE_CCY, RATE_TYPE)；闭区间生效日/失效日均必填（消歧无限期占位）
-- MySQL 无 ADD COLUMN IF NOT EXISTS，marker 幂等（013 教训：中断须手动补跑）

CREATE TABLE IF NOT EXISTS erp_mdm_exchange_rate (
    ID VARCHAR(64) NOT NULL,
    BASE_CCY CHAR(3) NOT NULL,
    QUOTE_CCY CHAR(3) NOT NULL,
    -- MIDDLE 中间价 / BUY 买入价 / SELL 卖出价（三类独立区间序列，design D2）
    RATE_TYPE VARCHAR(8) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRE_DATE DATE NOT NULL,
    RATE DECIMAL(18,6) NOT NULL,
    SOURCE_FILE_NO VARCHAR(64) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MER_SEQ (BASE_CCY, QUOTE_CCY, RATE_TYPE, EFFECTIVE_DATE),
    KEY IDX_MER_TYPE (RATE_TYPE),
    KEY IDX_MER_EXPIRE (EXPIRE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_exchange_rate_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MER_VER (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
