-- 026 税码管理（税码维护 1.6.1 / 政策台账 1.6.2，FR-4.1-3-2 + C-4.1-04 + BR-4.1-16/17/18）
-- 序列键 = TAX_CODE；闭区间生效日/失效日均必填；政策关联按 POLICY_NO 文本匹配（design D4，无外键）
-- MySQL 无 ADD COLUMN IF NOT EXISTS，marker 幂等（仅 CREATE TABLE IF NOT EXISTS，无裸 ALTER）

CREATE TABLE IF NOT EXISTS erp_mdm_tax_code (
    ID VARCHAR(64) NOT NULL,
    TAX_CODE VARCHAR(32) NOT NULL,
    TAX_RATE DECIMAL(10,4) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRE_DATE DATE NOT NULL,
    -- DOMESTIC 国内 / EXPORT 出口 / EXEMPT 免税（FR-4.1-3-2 适用范围）
    SCOPE VARCHAR(16) NOT NULL,
    POLICY_NO VARCHAR(64) NOT NULL,
    -- GENERAL 一般 / SIMPLIFIED 简易 / DIFFERENTIAL 差额（4.14 计税方式）
    CALC_TYPE VARCHAR(16) NOT NULL DEFAULT 'GENERAL',
    -- STANDARD 标准 / LOW 低税率 / ZERO 零税率 / EXEMPT 免税
    RATE_KIND VARCHAR(16) NOT NULL DEFAULT 'STANDARD',
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MTC_SEQ (TAX_CODE, EFFECTIVE_DATE),
    KEY IDX_MTC_POLICY (POLICY_NO),
    KEY IDX_MTC_SCOPE (SCOPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_tax_code_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MTC_VER (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_mdm_tax_policy (
    ID VARCHAR(64) NOT NULL,
    POLICY_NO VARCHAR(64) NOT NULL,
    POLICY_NAME VARCHAR(128) NOT NULL,
    ISSUER VARCHAR(64) NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    SUMMARY VARCHAR(500),
    REMARK VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MTP_NO (POLICY_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
