-- 027 政策版本快照（1.6.2 增强，add-tax-policy-workbench D1）
-- 与 026 税码版本表同构；存量政策不回填，首快照由上线后首次写操作生成（V1 起连续）
-- MySQL 无 ADD COLUMN IF NOT EXISTS，仅 CREATE TABLE IF NOT EXISTS 幂等

CREATE TABLE IF NOT EXISTS erp_mdm_tax_policy_version (
    ID VARCHAR(64) NOT NULL,
    ENTITY_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL,
    DIFF_SUMMARY VARCHAR(500),
    OP_TYPE VARCHAR(16) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MTP_VER (ENTITY_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
