-- 028 请购单（采购管理 2.1.1/2.1.2/2.1.4，FR-4.2-1-1/2 + BR-4.2-07/08/09/10/50 + C-4.2-11）
-- 采购域首迁移：PR 头/行/交付计划行/审批任务 四表；单据域沿供应商合并口径（字段留痕，非主数据版本快照）
-- MySQL 无 ADD COLUMN IF NOT EXISTS，仅 CREATE TABLE IF NOT EXISTS 幂等（design D1）

CREATE TABLE IF NOT EXISTS erp_proc_requisition (
    ID VARCHAR(64) NOT NULL,
    PR_NO VARCHAR(32) NOT NULL,
    -- MRP / MANUAL
    SOURCE_TYPE VARCHAR(8) NOT NULL,
    -- 状态机见 design D2：PENDING_CONFIRM/PENDING_BUDGET/PENDING_APPROVAL/PENDING_MODIFY/
    -- CONFIRMED/APPROVING/APPROVED/PENDING_RFQ/CLOSED
    STATUS VARCHAR(24) NOT NULL,
    -- 需求来源三选一（手工 PR）
    REQ_PROJECT_NO VARCHAR(64),
    REQ_COST_CENTER_ID VARCHAR(64),
    REQ_INTERNAL_ORDER_NO VARCHAR(64),
    -- 预算来源三选一（BR-4.2-09）
    BUDGET_SUBJECT VARCHAR(64),
    BUDGET_COST_CENTER_ID VARCHAR(64),
    BUDGET_INTERNAL_ORDER_NO VARCHAR(64),
    REQ_REASON VARCHAR(255),
    REJECT_REASON VARCHAR(255),
    -- 确认/关闭留痕（D2 一般操作）
    CONFIRM_BY VARCHAR(64),
    CONFIRM_DATE DATETIME,
    CLOSE_REASON VARCHAR(255),
    CLOSE_BY VARCHAR(64),
    CLOSE_DATE DATETIME,
    -- 催办/升级标记（BR-4.2-50 懒 sweep）
    REMIND_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ESCALATE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    SCAN_DATE DATETIME,
    -- 判级金额（审批，冗余快照）
    APPROVAL_AMOUNT DECIMAL(18,2),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PR_NO (PR_NO),
    KEY IDX_PR_STATUS (STATUS),
    KEY IDX_PR_SOURCE (SOURCE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_pr_line (
    ID VARCHAR(64) NOT NULL,
    PR_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    QTY DECIMAL(18,4) NOT NULL,
    REQ_DATE DATE NOT NULL,
    EST_UNIT_PRICE DECIMAL(18,4),
    -- 需求来源枚举：WO/PLAN_ORDER/SO/SAFETY_STOCK/SIMULATED
    SOURCE_ENUM VARCHAR(20) NOT NULL,
    SOURCE_DOC_NO VARCHAR(64),
    SUGGESTED_SUPPLIER_ID VARCHAR(64),
    -- MRP 建议量（BR-4.2-08 的 80% 基线；手工行为 NULL 不卡控）
    MRP_SUGGESTED_QTY DECIMAL(18,4),
    REDUCE_REASON VARCHAR(255),
    REVIEWER VARCHAR(64),
    -- 逾期/异常需求标记（FR-4.2-1-1）
    OVERDUE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- OPEN / CLOSED
    LINE_STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    CLOSE_REASON VARCHAR(255),
    CLOSE_DATE DATETIME,
    -- PO 下达反写累计（BR-4.2-51 桩）
    ALLOC_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PRL (PR_ID, LINE_NO),
    KEY IDX_PRL_STATUS (LINE_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_pr_delivery_line (
    ID VARCHAR(64) NOT NULL,
    PR_LINE_ID VARCHAR(64) NOT NULL,
    DELIVERY_DATE DATE NOT NULL,
    QTY DECIMAL(18,4) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY IDX_PDL_LINE (PR_LINE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_pr_approval (
    ID VARCHAR(64) NOT NULL,
    PR_ID VARCHAR(64) NOT NULL,
    -- 重提批次（驳回重提 +1，历史批次保留，design D7）
    SUBMIT_BATCH INT NOT NULL DEFAULT 1,
    NODE_NO INT NOT NULL,
    -- DEPT_MANAGER / DIRECTOR / VP（审计语义记录，动作执行者当前统一 ADMIN）
    NODE_ROLE VARCHAR(20) NOT NULL,
    -- ACTIVE / PASSED / REJECTED / SUPERSEDED
    STATUS VARCHAR(16) NOT NULL,
    -- SUBMIT / PASS / REJECT / TIMEOUT / ESCALATE（审批日志动作）
    ACTION VARCHAR(16),
    ACTION_REASON VARCHAR(255),
    ACTED_BY VARCHAR(64),
    ACTION_DATE DATETIME,
    -- 超时/升级标记（BR-4.2-10 懒 sweep）
    TIMEOUT_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ESCALATE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ESCALATE_TO VARCHAR(20),
    SCAN_DATE DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PRA (PR_ID, SUBMIT_BATCH, NODE_NO),
    KEY IDX_PRA_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
