-- 029 紧急采购（2.1.3，S-4.2-04 + BR-4.2-11 + L1321 异常场景）
-- EA 头（特批留痕直接落列，不复用审批表——design D2）+ 紧急通道台账（按登录账号唯一）
-- MySQL 无 ADD COLUMN IF NOT EXISTS，仅 CREATE TABLE IF NOT EXISTS 幂等

CREATE TABLE IF NOT EXISTS erp_proc_emergency (
    ID VARCHAR(64) NOT NULL,
    EA_NO VARCHAR(32) NOT NULL,
    PR_ID VARCHAR(64) NOT NULL,
    -- STOP_LINE / CUSTOMER_RUSH / OTHER
    REASON_TYPE VARCHAR(20) NOT NULL,
    REASON_DESC VARCHAR(255) NOT NULL,
    EXPECT_ARRIVE_DATE DATE,
    -- PENDING_SPECIAL_APPROVAL / APPROVED_EMERGENCY / FILLING / COMPLETED /
    -- OVERDUE_EXCEPTION / REJECTED / CLOSED
    STATUS VARCHAR(28) NOT NULL,
    -- 申请人账号（冗余列：阻断/例外聚合查询，D1）
    APPLICANT VARCHAR(64) NOT NULL,
    -- 特批留痕（D2 单节点，直接落列）
    SPECIAL_APPROVE_BY VARCHAR(64),
    SPECIAL_APPROVE_DATE DATETIME,
    SPECIAL_REASON VARCHAR(255),
    REJECT_REASON VARCHAR(255),
    -- 放行：补齐截止日 = 特批日 + EMERGENCY_FILL_DAYS（跳周末）
    CLEARANCE_DUE_DATE DATE,
    -- 比价补齐（文本登记 + 附件桩）
    QUOTE_COUNT INT,
    COMPARE_DOC_NO VARCHAR(64),
    FILL_NOTE VARCHAR(500),
    FILL_DATE DATETIME,
    -- 标记（特批超时/升级 懒 sweep + 逾期例外）
    REMIND_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ESCALATE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    EXCEPTION_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    SCAN_DATE DATETIME,
    CLOSE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_EA_NO (EA_NO),
    KEY IDX_EA_PR (PR_ID),
    KEY IDX_EA_STATUS (STATUS),
    KEY IDX_EA_APPLICANT (APPLICANT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_emergency_channel (
    ID VARCHAR(64) NOT NULL,
    -- 登录账号（唯一）；无行 = 已开通（隐式 OPEN，design D1）
    ACCOUNT VARCHAR(64) NOT NULL,
    -- OPEN / BLOCKED
    STATUS VARCHAR(16) NOT NULL,
    BLOCK_REASON VARCHAR(255),
    BLOCK_DATE DATETIME,
    BLOCK_EA_NO VARCHAR(32),
    -- 恢复留痕（总监复核）
    REVIEW_BY VARCHAR(64),
    REVIEW_DATE DATETIME,
    REVIEW_NOTE VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ECA_ACCOUNT (ACCOUNT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
