-- 030 询价比价（2.2.1，FR-4.2-2-1/2 + C-4.2-01 + BR-4.2-12/13/14）
-- RFQ 头 + 行快照 + 供应商清单 + 报价 四表；MySQL 无 ADD COLUMN IF NOT EXISTS，仅 CREATE TABLE IF NOT EXISTS 幂等

CREATE TABLE IF NOT EXISTS erp_proc_rfq (
    ID VARCHAR(64) NOT NULL,
    RFQ_NO VARCHAR(32) NOT NULL,
    PR_ID VARCHAR(64) NOT NULL,
    -- DRAFT / SENT / QUOTING / QUOTED_CLOSED / AWARDED / CLOSED
    STATUS VARCHAR(20) NOT NULL,
    QUOTE_DEADLINE DATE NOT NULL,
    -- OFFLINE / ONLINE（ONLINE 为发送状态桩）
    SEND_MODE VARCHAR(8) NOT NULL DEFAULT 'OFFLINE',
    SEND_STATUS VARCHAR(16),
    SENT_DATE DATETIME,
    -- 矩阵含税试算输入（可空，未填=待税率）
    TAX_CODE_NO VARCHAR(32),
    -- 技术标准/图纸（附件桩：文本说明）
    TECH_NOTE VARCHAR(255),
    -- 紧急放行（clearance 桩消费）：允许最低 1 家
    EMERGENCY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- BR-4.2-13 锁价后不足 MIN
    INSUFFICIENT_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- 定标时权重快照（和=100）
    WEIGHT_PRICE INT,
    WEIGHT_DELIVERY INT,
    AWARD_SUPPLIER_ID VARCHAR(64),
    AWARD_PRICE DECIMAL(18,4),
    -- 比价分析表（编号+结论登记，文档生成桩）
    ANALYSIS_NO VARCHAR(64),
    ANALYSIS_CONCLUSION VARCHAR(500),
    CLOSE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_RFQ_NO (RFQ_NO),
    KEY IDX_RFQ_PR (PR_ID),
    KEY IDX_RFQ_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_rfq_line (
    ID VARCHAR(64) NOT NULL,
    RFQ_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    QTY DECIMAL(18,4) NOT NULL,
    REQ_DATE DATE NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_RFL (RFQ_ID, LINE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_rfq_supplier (
    ID VARCHAR(64) NOT NULL,
    RFQ_ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_RFS (RFQ_ID, SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_quote (
    ID VARCHAR(64) NOT NULL,
    RFQ_ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    UNIT_PRICE DECIMAL(18,4) NOT NULL,
    LEAD_TIME_DAYS INT NOT NULL,
    MOQ DECIMAL(18,4) NOT NULL,
    -- NET30 / NET60 / NET90 / 款到发货
    PAYMENT_TERMS VARCHAR(20) NOT NULL,
    QUOTE_VALID_DATE DATE NOT NULL,
    -- 谈判双轨（BR-4.2-14）：原始保留，谈判后另列
    NEGOTIATED_PRICE DECIMAL(18,4),
    NEGOTIATE_NOTE VARCHAR(255),
    -- BR-4.2-12 异常偏离
    ANOMALY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ANOMALY_CONFIRMED VARCHAR(1) NOT NULL DEFAULT '0',
    ANOMALY_CONFIRM_BY VARCHAR(64),
    ANOMALY_CONFIRM_DATE DATETIME,
    -- 剔除（无效不参与均值/加权/定标）
    EXCLUDED VARCHAR(1) NOT NULL DEFAULT '0',
    EXCLUDED_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QUOTE (RFQ_ID, SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
