-- 031 招标竞价（2.2.2，FR-4.2-10-1/2/3 + BR-4.2-44~48 + BR-4.2-05/06 + C-4.2-10）
-- 7 张招标表 + 2 张协议表 + ROLE_BID_JUDGE 角色种子；参数走 application.yml（design D9），不落 SQL 种子
-- MySQL 无 ADD COLUMN IF NOT EXISTS，仅 CREATE TABLE IF NOT EXISTS 幂等

-- ---------- 招标项目头 ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender (
    ID VARCHAR(64) NOT NULL,
    TENDER_NO VARCHAR(32) NOT NULL,
    TITLE VARCHAR(128) NOT NULL,
    -- OPEN 公开招标 / INVITE 邀请招标
    TENDER_TYPE VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    -- LOWEST 最低价法 / SCORE 综合评分法
    EVAL_METHOD VARCHAR(10) NOT NULL,
    -- 招标品类（BR-4.2-44 门槛统计维度）
    CATEGORY_CODE VARCHAR(64),
    CATEGORY_NAME VARCHAR(128),
    -- 年度预估量（FR-4.2-10-1）
    EST_ANNUAL_QTY DECIMAL(18,4),
    -- 技术规格书（附件桩：文本说明，同 rfq.TECH_NOTE 口径）
    TECH_SPEC VARCHAR(500),
    -- 投标资格门槛（FR-4.2-10-1）
    QUALIFY_REQ VARCHAR(500),
    -- DRAFT / BIDDING / LOCKED / EVALUATING / PENDING_AWARD / AWAITING_PUBLICITY / OBJECTION / AWARDED / CANCELLED
    STATUS VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    -- 报名截止（BR-4.2-45 延期报名期）
    REG_DEADLINE DATETIME,
    -- 报价截止（单一总截止，BR-4.2-06 锁价时点）
    QUOTE_DEADLINE DATETIME,
    -- 转邀请招标待采购总监审批（BR-4.2-45，0 待审批 / 1 已批准 / 2 已驳回）
    INVITE_PENDING VARCHAR(1) NOT NULL DEFAULT '0',
    -- 评分权重快照（和=100，可按品类调整）
    WEIGHT_PRICE INT NOT NULL DEFAULT 40,
    WEIGHT_DELIVERY INT NOT NULL DEFAULT 25,
    WEIGHT_QUALITY INT NOT NULL DEFAULT 25,
    WEIGHT_COOPERATION INT NOT NULL DEFAULT 10,
    -- 拟中标（定标）
    AWARD_SUPPLIER_ID VARCHAR(64),
    AWARD_PRICE DECIMAL(18,4),
    AWARD_SCORE DECIMAL(10,4),
    -- 公示（BR-4.2-48）
    PUBLICITY_START DATETIME,
    PUBLICITY_END DATETIME,
    -- 异议登记（BR-4.2-48 暂停协议生成）
    OBJECTION_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- 围标/串标异常标记（偏差 D6：人工标记，冻结评标）
    ANOMALY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ANOMALY_NOTE VARCHAR(500),
    -- 合格投标方数（BR-4.2-45 判定）
    QUALIFIED_COUNT INT NOT NULL DEFAULT 0,
    ABORT_REASON VARCHAR(255),
    CLOSE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_NO (TENDER_NO),
    KEY IDX_TENDER_STATUS (STATUS),
    KEY IDX_TENDER_DEADLINE (QUOTE_DEADLINE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 招标行（物料） ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_line (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    QTY DECIMAL(18,4) NOT NULL,
    UNIT VARCHAR(16),
    REQ_DATE DATE,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_LINE (TENDER_ID, LINE_NO),
    KEY IDX_TENDER_LINE_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 投标供应商与资格审查 ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_supplier (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128),
    -- 来源：APPLY 报名 / INVITE 邀请
    JOIN_SOURCE VARCHAR(10) NOT NULL DEFAULT 'APPLY',
    -- PENDING 待审 / PASS 合格 / FAIL 不合格
    QUALIFY_STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    QUALIFY_NOTE VARCHAR(500),
    QUALIFY_BY VARCHAR(64),
    QUALIFY_DATE DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_SUP (TENDER_ID, SUPPLIER_ID),
    KEY IDX_TENDER_SUP_QUAL (QUALIFY_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 多轮报价（BR-4.2-06 只降不升） ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_quote (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    ROUND_NO INT NOT NULL,
    UNIT_PRICE DECIMAL(18,4) NOT NULL,
    LEAD_TIME_DAYS INT,
    MOQ DECIMAL(18,4),
    -- NET30 / NET60 / NET90 / 款到发货
    PAYMENT_TERMS VARCHAR(20),
    QUOTE_VALID_DATE DATE,
    QUOTE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 代录人（内部端由采购员代录）
    OPERATOR VARCHAR(64),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    -- 轮次唯一：同一投标方同一轮仅一条（design D2）
    UNIQUE KEY UK_TENDER_QUOTE (TENDER_ID, SUPPLIER_ID, ROUND_NO),
    KEY IDX_TENDER_QUOTE_T (TENDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 评委名单（design D5：ROLE_BID_JUDGE） ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_judge (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    JUDGE_USER_ID VARCHAR(64) NOT NULL,
    JUDGE_NAME VARCHAR(64),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_JUDGE (TENDER_ID, JUDGE_USER_ID),
    KEY IDX_TENDER_JUDGE_USER (JUDGE_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 评分卡（4 维宽表，design D4；BR-4.2-47 提交后不可改） ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_score (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    JUDGE_USER_ID VARCHAR(64) NOT NULL,
    -- 四维原始分（0-100）
    SCORE_PRICE INT,
    SCORE_DELIVERY INT,
    SCORE_QUALITY INT,
    SCORE_COOPERATION INT,
    -- 加权得分（按招标头权重快照）
    WEIGHTED_SCORE DECIMAL(10,4),
    -- DRAFT 草稿 / SUBMITTED 已提交（提交后锁定）
    STATUS VARCHAR(12) NOT NULL DEFAULT 'DRAFT',
    SUBMIT_TIME DATETIME,
    -- 合规审批后修改（BR-4.2-47）
    AMEND_APPROVED VARCHAR(1) NOT NULL DEFAULT '0',
    AMEND_BY VARCHAR(64),
    AMEND_DATE DATETIME,
    AMEND_NOTE VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_SCORE (TENDER_ID, SUPPLIER_ID, JUDGE_USER_ID),
    KEY IDX_TENDER_SCORE_T (TENDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 异议登记（BR-4.2-48） ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_objection (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    OBJECTION_NO VARCHAR(32) NOT NULL,
    -- 形式审查有效的异议（有效才暂停协议生成）
    VALID_FLAG VARCHAR(1) NOT NULL DEFAULT '1',
    OBJECTIONER VARCHAR(64),
    CONTENT VARCHAR(1000),
    SUBMIT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- PENDING 待复核 / MAINTAIN 维持原定标 / REBID 重新招标
    REVIEW_STATUS VARCHAR(12) NOT NULL DEFAULT 'PENDING',
    REVIEW_RESULT VARCHAR(1000),
    REVIEW_BY VARCHAR(64),
    REVIEW_DATE DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_OBJECTION_NO (OBJECTION_NO),
    KEY IDX_TENDER_OBJECTION (TENDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 采购框架协议头（FR-4.2-10-3 产出物；不复用销售侧 erp_mdm_price_agreement） ----------
CREATE TABLE IF NOT EXISTS erp_proc_framework_agreement (
    ID VARCHAR(64) NOT NULL,
    AGREEMENT_NO VARCHAR(32) NOT NULL,
    -- 关联招标（UK_PA_TENDER_NO 保证公示期满只生成一次）
    TENDER_NO VARCHAR(32) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    TITLE VARCHAR(128),
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRE_DATE DATE,
    -- 0 未生效 / 1 生效中 / 2 过期 / 3 停用
    STATUS VARCHAR(1) NOT NULL DEFAULT '1',
    TOTAL_SHARE DECIMAL(7,4),
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PA_NO (AGREEMENT_NO),
    UNIQUE KEY UK_PA_TENDER_NO (TENDER_NO),
    KEY IDX_PA_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 采购框架协议明细（中标单价 + 份额分配） ----------
CREATE TABLE IF NOT EXISTS erp_proc_framework_agreement_line (
    ID VARCHAR(64) NOT NULL,
    AGREEMENT_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    AWARD_SUPPLIER_ID VARCHAR(64),
    AWARD_SUPPLIER_NAME VARCHAR(128),
    UNIT_PRICE DECIMAL(18,4) NOT NULL,
    -- 份额分配（%）
    SHARE_PCT DECIMAL(7,4),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PA_LINE (AGREEMENT_ID, LINE_NO),
    KEY IDX_PA_LINE_SUP (AWARD_SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 角色种子（design D5：评委角色） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, CREATE_DATE) VALUES
('role-bid-judge', 'ROLE_BID_JUDGE', '评标委员', 30, '1', 'system', NOW());
