-- 033 框架协议执行 + 采购订单域（change: add-framework-agreement-order）
-- 含：中标子表、协议行执行列、PO 头/行/版本快照、PO 审批任务/日志、采购预算、价控日志
-- 幂等口径与 031/032 一致：CREATE TABLE IF NOT EXISTS；ALTER 用 information_schema + PREPARE；
-- 数据回填用 INSERT IGNORE / 带 WHERE 的 UPDATE，可重复执行。

-- ---------- 1. 招标中标子表（design D2：多中标人，定标人工录入，Σ份额=100） ----------
CREATE TABLE IF NOT EXISTS erp_proc_tender_award (
    ID VARCHAR(64) NOT NULL,
    TENDER_ID VARCHAR(64) NOT NULL,
    -- 中标顺序（份额从大到小人工录入顺序）
    LINE_NO INT NOT NULL DEFAULT 1,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128),
    -- 中标单价 = 该投标方最终轮有效报价（服务端校验）
    AWARD_PRICE DECIMAL(18,4) NOT NULL,
    -- 份额分配（%），全部中标人合计 = 100
    SHARE_PCT DECIMAL(7,4) NOT NULL,
    REMARK VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TENDER_AWARD (TENDER_ID, SUPPLIER_ID),
    KEY IDX_TENDER_AWARD_SUP (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2. 协议行执行列（design D3：承诺量/已下单量/价格区间） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_framework_agreement_line'
        AND COLUMN_NAME = 'COMMIT_QTY') = 0,
    'ALTER TABLE erp_proc_framework_agreement_line
       ADD COLUMN COMMIT_QTY DECIMAL(18,4) NULL COMMENT ''承诺量，NULL=不限量'',
       ADD COLUMN ORDERED_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT ''已下单累计'',
       ADD COLUMN PRICE_MIN DECIMAL(18,4) NULL COMMENT ''价格区间下限（手工协议）'',
       ADD COLUMN PRICE_MAX DECIMAL(18,4) NULL COMMENT ''价格区间上限（手工协议）''',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 协议头增列：来源（TENDER/MANUAL）与续签关联（design D5/D4）
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_framework_agreement'
        AND COLUMN_NAME = 'SOURCE') = 0,
    'ALTER TABLE erp_proc_framework_agreement
       ADD COLUMN SOURCE VARCHAR(16) NOT NULL DEFAULT ''TENDER'' COMMENT ''来源 TENDER/MANUAL'',
       ADD COLUMN RENEW_OF VARCHAR(64) NULL COMMENT ''续签来源协议ID'',
       ADD COLUMN STOP_REASON VARCHAR(255) NULL COMMENT ''终止原因'',
       ADD COLUMN CHANGE_NOTE VARCHAR(255) NULL COMMENT ''最近变更说明''',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 3. 采购订单头（design D8） ----------
CREATE TABLE IF NOT EXISTS erp_proc_po (
    ID VARCHAR(64) NOT NULL,
    -- PO + yyyyMM + 6 位流水，唯一索引兜底
    PO_NO VARCHAR(32) NOT NULL,
    -- NORMAL 常规 / SPECIAL 特殊（紧急、关联交易）
    PO_TYPE VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    -- AGREEMENT / RFQ / MANUAL
    SOURCE VARCHAR(16) NOT NULL,
    -- 协议ID / RFQ ID / 空（手工）
    SOURCE_ID VARCHAR(64),
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128),
    -- 关联 PR（可空：多PR对一PO时记主PR或为空）
    PR_ID VARCHAR(64),
    PR_NO VARCHAR(64),
    -- DRAFT / APPROVING / APPROVED / CLOSED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    -- 当前审批批次（驳回重提 +1）
    APPROVAL_BATCH INT NOT NULL DEFAULT 0,
    -- 含税总金额
    TOTAL_AMT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TAX_RATE DECIMAL(7,4),
    TAX_CODE VARCHAR(16),
    CURRENCY VARCHAR(8) NOT NULL DEFAULT 'CNY',
    REMARK VARCHAR(500),
    CLOSE_REASON VARCHAR(255),
    CLOSED_BY VARCHAR(64),
    CLOSED_DATE DATETIME,
    -- 当前版本号（变更递增，旧版本只读）
    CURR_VERSION INT NOT NULL DEFAULT 1,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PO_NO (PO_NO),
    KEY IDX_PO_SUPPLIER (SUPPLIER_ID),
    KEY IDX_PO_STATUS (STATUS),
    KEY IDX_PO_SOURCE (SOURCE, SOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4. 采购订单行 ----------
CREATE TABLE IF NOT EXISTS erp_proc_po_line (
    ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    QTY DECIMAL(18,4) NOT NULL,
    UNIT VARCHAR(16),
    -- 协议来源：只读锁定（L908）
    UNIT_PRICE DECIMAL(18,4) NOT NULL,
    TAX_RATE DECIMAL(7,4),
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    REQ_DATE DATE,
    -- 溯源：协议行 / PR 行（可空）
    AGREEMENT_LINE_ID VARCHAR(64),
    PR_LINE_ID VARCHAR(64),
    -- 收货占位列（2.4 落地时消费，本变更仅预留）
    RECEIVED_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- 价控/区间校验结果快照：PASS / ESCALATE / BLOCK
    PRICE_CTRL_RESULT VARCHAR(16),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_PO_LINE_PO (PO_ID),
    KEY IDX_PO_LINE_ITEM (ITEM_CODE),
    KEY IDX_PO_LINE_AGR (AGREEMENT_LINE_ID),
    KEY IDX_PO_LINE_PR (PR_LINE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5. PO 版本快照（design D8：递增版本 + JSON 快照，回滚=按旧版本生成新版本） ----------
CREATE TABLE IF NOT EXISTS erp_proc_po_version (
    ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    -- 变更类型：INIT / QTY / DATE / PRICE / LINE_CANCEL / LINE_ADD / ROLLBACK
    CHG_TYPE VARCHAR(16) NOT NULL,
    CHG_REASON VARCHAR(500),
    -- 头+行完整 JSON 快照（旧版本只读凭据）
    SNAPSHOT_JSON MEDIUMTEXT NOT NULL,
    -- 变更审批结论：NONE / PENDING / APPROVED / REJECTED
    APPROVAL_STATUS VARCHAR(16) NOT NULL DEFAULT 'NONE',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PO_VER (PO_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6. PO 审批任务（design D1：独立三档，不动 2.1.4） ----------
CREATE TABLE IF NOT EXISTS erp_proc_po_approval_task (
    ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64) NOT NULL,
    -- 提交批次，驳回重提 +1，历史保留
    SUBMIT_BATCH INT NOT NULL DEFAULT 1,
    NODE_NO INT NOT NULL,
    -- 角色：PURCHASE_MANAGER / PURCHASE_DIRECTOR / VICE_PRESIDENT
    NODE_ROLE VARCHAR(32) NOT NULL,
    NODE_LABEL VARCHAR(64),
    -- PENDING / APPROVED / REJECTED / SUPERSEDED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    -- PASS / REJECT / CONDITIONAL
    ACTION VARCHAR(16),
    ACTION_REASON VARCHAR(500),
    -- 条件批准附加条件
    CONDITION_TEXT VARCHAR(500),
    ACTED_BY VARCHAR(64),
    ACTED_BY_NAME VARCHAR(64),
    ACTION_DATE DATETIME,
    -- 价控/预算命中的强制加签标记
    ESCALATE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ESCALATE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_PO_TASK_PO (PO_ID, SUBMIT_BATCH, NODE_NO),
    KEY IDX_PO_TASK_ROLE (NODE_ROLE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7. PO 审批日志（批次/节点/动作/原因/人/时间，倒序可查） ----------
CREATE TABLE IF NOT EXISTS erp_proc_po_approval_log (
    ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64) NOT NULL,
    PO_NO VARCHAR(32),
    SUBMIT_BATCH INT NOT NULL,
    NODE_NO INT NOT NULL,
    NODE_ROLE VARCHAR(32),
    -- SUBMIT / PASS / REJECT / CONDITIONAL / ESCALATE
    ACTION VARCHAR(16) NOT NULL,
    ACTION_REASON VARCHAR(500),
    ACTED_BY VARCHAR(64),
    ACTED_BY_NAME VARCHAR(64),
    ACTION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY IDX_PO_LOG_PO (PO_ID, SUBMIT_BATCH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 8. 年度采购预算（design D7：轻量，科目×年度唯一，主数据基线模式） ----------
CREATE TABLE IF NOT EXISTS erp_proc_budget (
    ID VARCHAR(64) NOT NULL,
    BUDGET_YEAR INT NOT NULL,
    CATEGORY_CODE VARCHAR(16) NOT NULL,
    CATEGORY_NAME VARCHAR(128),
    BUDGET_AMT DECIMAL(18,2) NOT NULL,
    CHANGE_REASON VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_BUDGET (BUDGET_YEAR, CATEGORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 9. 价控校验日志（BR-4.2-19 完整校验日志） ----------
CREATE TABLE IF NOT EXISTS erp_proc_po_price_control (
    ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64),
    PO_NO VARCHAR(32),
    LINE_NO INT,
    ITEM_CODE VARCHAR(64),
    -- CONTRACT / HISTORY / BUDGET
    CHECK_LEVEL VARCHAR(16) NOT NULL,
    -- 基准值（协议价 / 历史均价 / 预算×阈值）
    BASE_VALUE DECIMAL(18,4),
    -- 实际值（PO 单价 / 本次金额+累计）
    ACTUAL_VALUE DECIMAL(18,4),
    -- PASS / ESCALATE / BLOCK / NO_HISTORY / NO_BUDGET
    RESULT VARCHAR(16) NOT NULL,
    REASON VARCHAR(500),
    CHK_BY VARCHAR(64),
    CHK_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY IDX_PO_PC_PO (PO_ID),
    KEY IDX_PO_PC_LEVEL (CHECK_LEVEL, RESULT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 10. 数据回填（任务 1.2，全部幂等可重复执行） ----------
-- 10.1 历史单中标招标 → 中标子表补 1 行 100%（ID 确定性生成，INSERT IGNORE 幂等）
INSERT IGNORE INTO erp_proc_tender_award
    (ID, TENDER_ID, LINE_NO, SUPPLIER_ID, SUPPLIER_NAME, AWARD_PRICE, SHARE_PCT, CREATE_BY)
SELECT CONCAT('aw-', t.ID), t.ID, 1, t.AWARD_SUPPLIER_ID,
       (SELECT s.SUPPLIER_NAME FROM erp_mdm_supplier s WHERE s.ID = t.AWARD_SUPPLIER_ID),
       t.AWARD_PRICE, 100, 'system'
FROM erp_proc_tender t
WHERE t.AWARD_SUPPLIER_ID IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM erp_proc_tender_award a WHERE a.TENDER_ID = t.ID);

-- 10.2 既有协议行补已下单量默认值（新增列已有 DEFAULT，双保险回填 NULL）
UPDATE erp_proc_framework_agreement_line SET ORDERED_QTY = 0 WHERE ORDERED_QTY IS NULL;

-- 10.3 品类预算种子（2026 年度，每品类 100 万，保证超预算档可触发；INSERT IGNORE 幂等）
INSERT IGNORE INTO erp_proc_budget
    (ID, BUDGET_YEAR, CATEGORY_CODE, CATEGORY_NAME, BUDGET_AMT, CREATE_BY)
SELECT CONCAT('bud-2026-', c.CATEGORY_CODE), 2026, c.CATEGORY_CODE, c.CATEGORY_NAME,
       1000000.00, 'system'
FROM erp_mdm_item_category c
WHERE c.CATEGORY_CODE IS NOT NULL;
