-- 037 收货管理 2.4（change add-goods-receipt，design D1/D6/D7）
--   1) 收货五表：erp_proc_gr / erp_proc_gr_line / erp_proc_gr_difference /
--      erp_proc_gr_adjustment / erp_inv_stock
--   2) PO 行 LINE_STATUS（默认 OPEN，按 receivedQty>=qty 回填 COMPLETED）
--   3) MdmItem.RISK_GRADE（默认 C）
--   4) 双角色种子 ROLE_RECEIVER / ROLE_WAREHOUSE
-- 幂等：information_schema + PREPARE（033~036 范式）

-- ---------- 1) 收货单头 ----------
CREATE TABLE IF NOT EXISTS erp_proc_gr (
    ID VARCHAR(64) NOT NULL,
    GR_NO VARCHAR(32) NOT NULL,
    -- PO / FREE（无 PO 收货，扩展场景）
    SOURCE_TYPE VARCHAR(8) NOT NULL DEFAULT 'PO',
    PO_ID VARCHAR(64),
    PO_NO VARCHAR(32),
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128),
    -- CREATED / POSTED / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    ARRIVAL_DATE DATE NOT NULL,
    -- 送货单号 / 到货批次号 / 运输信息（车牌或快递单号）/ 外包装状况
    DELIVERY_NOTE VARCHAR(64),
    BATCH_NO VARCHAR(64),
    TRANSPORT_INFO VARCHAR(128),
    PACKAGE_CONDITION VARCHAR(64),
    REMARK VARCHAR(255),
    -- 入库凭证号（过账时生成：IV+YYYYMMDD+NNN）
    POSTING_DOC_NO VARCHAR(32),
    POSTING_DATE DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_GR_NO (GR_NO),
    KEY IDX_GR_PO (PO_ID),
    KEY IDX_GR_STATUS (STATUS),
    KEY IDX_GR_SUPPLIER (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) 收货行 ----------
CREATE TABLE IF NOT EXISTS erp_proc_gr_line (
    ID VARCHAR(64) NOT NULL,
    GR_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    PO_LINE_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    UNIT VARCHAR(16),
    -- 快照：下单量 / 登记时未清量 / 实收
    ORDERED_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    OPEN_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    RECEIVED_QTY DECIMAL(18,4) NOT NULL,
    -- 容差分流结果：OK_OVER / OK_SHORT / OVER / SHORT / FREE
    TOLERANCE_RESULT VARCHAR(16),
    WITHIN_TOLERANCE_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- 超容差冻结量（待处理区，不入待检不过账，BR-4.2-21）
    FROZEN_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- PENDING / POSTED / REJECTED（拒收行不入待检不过账）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    -- 过账单价与金额快照（PO 行单价；FREE 可空）
    UNIT_PRICE DECIMAL(18,4),
    AMOUNT DECIMAL(18,2),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_GRL_GR (GR_ID),
    KEY IDX_GRL_POLINE (PO_LINE_ID),
    KEY IDX_GRL_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 收货差异单（差异对账台，L1064） ----------
CREATE TABLE IF NOT EXISTS erp_proc_gr_difference (
    ID VARCHAR(64) NOT NULL,
    DIFF_NO VARCHAR(32) NOT NULL,
    GR_ID VARCHAR(64) NOT NULL,
    GR_LINE_ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64),
    PO_LINE_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64),
    ITEM_NAME VARCHAR(128),
    -- OVER 超交 / SHORT 短交
    DIFF_TYPE VARCHAR(8) NOT NULL,
    ORDERED_QTY DECIMAL(18,4),
    RECEIVED_QTY DECIMAL(18,4),
    DIFF_QTY DECIMAL(18,4) NOT NULL,
    TOLERANCE_PCT DECIMAL(7,4),
    -- PENDING / ADJUSTED / RETURNED / CLOSED（三出口，无"直接接受超收"）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    CLOSE_REASON VARCHAR(255),
    DISPOSE_BY VARCHAR(64),
    DISPOSE_BY_NAME VARCHAR(64),
    DISPOSE_DATE DATETIME,
    DISPOSE_NOTE VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_DIFF_NO (DIFF_NO),
    KEY IDX_DIFF_GR (GR_ID),
    KEY IDX_DIFF_PO (PO_ID),
    KEY IDX_DIFF_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 收货调整单（BR-4.2-49，P-1 轻量链） ----------
CREATE TABLE IF NOT EXISTS erp_proc_gr_adjustment (
    ID VARCHAR(64) NOT NULL,
    ADJ_NO VARCHAR(32) NOT NULL,
    DIFF_ID VARCHAR(64),
    PO_ID VARCHAR(64) NOT NULL,
    PO_NO VARCHAR(32),
    PO_LINE_ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64),
    -- 追加数量（仅数量方向；价格列有意不设——价格零变化）
    ADD_QTY DECIMAL(18,4) NOT NULL,
    OLD_QTY DECIMAL(18,4) NOT NULL,
    NEW_QTY DECIMAL(18,4) NOT NULL,
    -- DRAFT / PENDING_APPROVE / APPROVED / REJECTED / EXECUTED
    STATUS VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    INITIATOR VARCHAR(64),
    INITIATOR_NAME VARCHAR(64),
    APPROVER VARCHAR(64),
    APPROVER_NAME VARCHAR(64),
    APPROVE_NOTE VARCHAR(500),
    EXECUTE_DATE DATETIME,
    NEW_GR_ID VARCHAR(64),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ADJ_NO (ADJ_NO),
    KEY IDX_ADJ_DIFF (DIFF_ID),
    KEY IDX_ADJ_PO (PO_ID),
    KEY IDX_ADJ_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 最小库存（4.4 承接：待检锁定 / 可领用分离） ----------
CREATE TABLE IF NOT EXISTS erp_inv_stock (
    ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    BATCH_NO VARCHAR(64) NOT NULL DEFAULT '',
    -- 总量 = QC_QTY + AVAILABLE_QTY
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- 待检锁定（FR-4.2-4-2：不可领用）
    QC_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    AVAILABLE_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_STOCK_ITEM_BATCH (ITEM_CODE, BATCH_NO),
    KEY IDX_STOCK_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) PO 行 LINE_STATUS + 回填 ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_po_line'
        AND COLUMN_NAME = 'LINE_STATUS') = 0,
    'ALTER TABLE erp_proc_po_line
       ADD COLUMN LINE_STATUS VARCHAR(16) NOT NULL DEFAULT ''OPEN''
         COMMENT ''行收货状态：OPEN 未完成 / COMPLETED 已收满'' AFTER RECEIVED_QTY',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE erp_proc_po_line
   SET LINE_STATUS = 'COMPLETED'
 WHERE LINE_STATUS = 'OPEN' AND RECEIVED_QTY >= QTY;

-- ---------- 7) 物料风险等级（FR-4.2-4-2 检验时限） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_mdm_item'
        AND COLUMN_NAME = 'RISK_GRADE') = 0,
    'ALTER TABLE erp_mdm_item
       ADD COLUMN RISK_GRADE VARCHAR(4) NOT NULL DEFAULT ''C''
         COMMENT ''风险等级：A 高 / B 中 / C 低（检验时限 24/48/72h）'' AFTER CATEGORY_CODE',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 8) 双角色种子（design D7） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, CREATE_DATE) VALUES
('role-receiver', 'ROLE_RECEIVER', '收货员', 40, '1', 'system', NOW()),
('role-warehouse', 'ROLE_WAREHOUSE', '仓库主管', 41, '1', 'system', NOW());
