-- 039-quality-core.sql
-- 检验标准库（4.12.2.1 五对象）+ 免检 + 检验批两表 + GR 行检验状态列
-- change add-quality-collaboration，design D2/D3；幂等：IF NOT EXISTS / INSERT IGNORE

-- ---------- 1) 检验标准头 ----------
CREATE TABLE IF NOT EXISTS erp_qms_standard (
    ID VARCHAR(64) NOT NULL,
    -- 编码唯一，创建后不可改（spec inspection-standard）
    STANDARD_CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    -- ITEM / CATEGORY / SUPPLIER / PROCESS / CUSTOMER
    SCOPE_TYPE VARCHAR(16) NOT NULL DEFAULT 'ITEM',
    -- A / B / C
    RISK_LEVEL VARCHAR(4) NOT NULL DEFAULT 'C',
    -- DRAFT / ACTIVE / RETIRED（停用不删，仅阻止新任务）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    CURRENT_VERSION INT NOT NULL DEFAULT 0,
    OWNER_ID VARCHAR(64),
    OWNER_NAME VARCHAR(128),
    DESCRIPTION VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_STD_CODE (STANDARD_CODE),
    KEY IDX_QMS_STD_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) 检验标准版本（发布后只读、版本号连续、生效区间不重叠） ----------
CREATE TABLE IF NOT EXISTS erp_qms_standard_version (
    ID VARCHAR(64) NOT NULL,
    STANDARD_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    SAMPLING_PLAN_ID VARCHAR(64),
    -- GB/T 2828.1 一般检验水平 II（AQL_LEVEL）
    AQL_LEVEL VARCHAR(64) NOT NULL DEFAULT 'GB/T 2828.1 一般检验水平 II',
    INSPECTION_LEVEL VARCHAR(16) NOT NULL DEFAULT 'II',
    -- DRAFT / PENDING_APPROVE / RELEASED / RETIRED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    -- 审批底座实例 ID（StandardPublish）
    APPROVAL_ID VARCHAR(64),
    RELEASED_BY VARCHAR(64),
    RELEASED_DATE DATETIME,
    CHANGE_REASON VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_STD_VER (STANDARD_ID, VERSION_NO),
    KEY IDX_QMS_STD_VER_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 检验特性（CTQ / 安全法规标记） ----------
CREATE TABLE IF NOT EXISTS erp_qms_characteristic (
    ID VARCHAR(64) NOT NULL,
    VERSION_ID VARCHAR(64) NOT NULL,
    SEQUENCE_NO INT NOT NULL DEFAULT 1,
    CHARACTERISTIC_NAME VARCHAR(128) NOT NULL,
    -- 1 = CTQ 关键质量特性（必检、必录实测值）
    CTQ_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- 1 = 安全/法规类（禁止让步接收，BR-4.12-26）
    REGULATORY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- NUMERIC 计量型 / COUNT 计数型 / LOOK 外观
    SPEC_TYPE VARCHAR(16) NOT NULL DEFAULT 'NUMERIC',
    LOWER_LIMIT DECIMAL(18,4),
    UPPER_LIMIT DECIMAL(18,4),
    TARGET_VALUE DECIMAL(18,4),
    UNIT VARCHAR(16),
    METHOD_NAME VARCHAR(128),
    INSTRUMENT_TYPE VARCHAR(64),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_CHAR_VER (VERSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 抽样方案 ----------
CREATE TABLE IF NOT EXISTS erp_qms_sampling_plan (
    ID VARCHAR(64) NOT NULL,
    PLAN_CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    INSPECTION_LEVEL VARCHAR(16) NOT NULL DEFAULT 'II',
    AQL_LEVEL VARCHAR(64) NOT NULL DEFAULT 'GB/T 2828.1 一般检验水平 II',
    SAMPLE_SIZE_RULE VARCHAR(255),
    ACCEPT_RULE VARCHAR(255),
    REJECT_RULE VARCHAR(255),
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_PLAN_CODE (PLAN_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 适用范围（优先级 + 生效日期唯一命中） ----------
CREATE TABLE IF NOT EXISTS erp_qms_standard_applicability (
    ID VARCHAR(64) NOT NULL,
    VERSION_ID VARCHAR(64) NOT NULL,
    MATERIAL_ID VARCHAR(64),
    MATERIAL_CODE VARCHAR(64),
    CATEGORY_CODE VARCHAR(64),
    PROCESS_ID VARCHAR(64),
    SUPPLIER_ID VARCHAR(64),
    CUSTOMER_ID VARCHAR(64),
    -- 数值越小越具体/优先
    PRIORITY INT NOT NULL DEFAULT 50,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_APPL_VER (VERSION_ID),
    KEY IDX_QMS_APPL_MAT (MATERIAL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) 免检（物料 + 供应商维度，BR-4.12-12） ----------
CREATE TABLE IF NOT EXISTS erp_qms_exempt (
    ID VARCHAR(64) NOT NULL,
    MATERIAL_ID VARCHAR(64) NOT NULL,
    MATERIAL_CODE VARCHAR(64) NOT NULL,
    MATERIAL_NAME VARCHAR(128),
    SUPPLIER_ID VARCHAR(64),
    SUPPLIER_NAME VARCHAR(128),
    -- PENDING / ACTIVE / DISABLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    APPROVAL_ID VARCHAR(64),
    ENABLED_BY VARCHAR(64),
    ENABLED_DATE DATETIME,
    DISABLE_REASON VARCHAR(255),
    DISABLED_DATE DATETIME,
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_EXEMPT_MAT (MATERIAL_CODE, SUPPLIER_ID),
    KEY IDX_QMS_EXEMPT_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7) 检验批（1 GR 行 = 1 批，生成即固化快照 BR-4.12-56） ----------
CREATE TABLE IF NOT EXISTS erp_qms_inspection_lot (
    ID VARCHAR(64) NOT NULL,
    -- IL + yyyyMMdd + - + 6 位流水
    LOT_NO VARCHAR(32) NOT NULL,
    -- IQC / IPQC / OQC
    LOT_TYPE VARCHAR(8) NOT NULL DEFAULT 'IQC',
    -- GR / MANUAL / PLAN（巡检计划）/ SHIPMENT(OQC 手工)
    SOURCE_TYPE VARCHAR(16) NOT NULL DEFAULT 'GR',
    GR_ID VARCHAR(64),
    GR_LINE_ID VARCHAR(64),
    -- IPQC/OQC 手工与计划来源
    REF_TYPE VARCHAR(32),
    REF_ID VARCHAR(64),
    MATERIAL_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    SUPPLIER_ID VARCHAR(64),
    SUPPLIER_NAME VARCHAR(128),
    BATCH_NO VARCHAR(64),
    -- 实收/待检数量
    LOT_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- A / B / C（自物料主数据快照）
    RISK_GRADE VARCHAR(4) NOT NULL DEFAULT 'C',
    -- 标准与版本快照（无标准 → BLOCKED 占位，两列为空）
    STANDARD_ID VARCHAR(64),
    STANDARD_CODE VARCHAR(64),
    STANDARD_VERSION INT,
    -- 适用范围命中依据（优先级/生效日期）
    APPLICABILITY_BASIS VARCHAR(255),
    -- 抽样取严依据（比例值 / AQL 字码 / 选用说明）C-4.12-13
    SAMPLE_BASIS VARCHAR(500),
    INSPECTION_LEVEL VARCHAR(16),
    AQL_LEVEL VARCHAR(64),
    SAMPLE_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- AQL 判定阈值
    AC_VALUE INT,
    RE_VALUE INT,
    -- NORMAL / TIGHTENED（加严）/ RELAXED（放宽）
    STRICTNESS VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    -- 1 = 免检命中（SKIPPED 依据）
    EXEMPT_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    EXEMPT_ID VARCHAR(64),
    -- BLOCKED(无标准) / PENDING(待检) / INPUTTING(录入中) / REVIEWING(边界复核)
    -- RELEASED(合格放行) / SKIPPED(免检) / CONCESSION(让步批准) / FROZEN(不合格冻结) / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    -- 判定结论 PENDING / PASS / FAIL
    RESULT VARCHAR(8) NOT NULL DEFAULT 'PENDING',
    PRIORITY VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
    INSPECTOR_ID VARCHAR(64),
    INSPECTOR_NAME VARCHAR(128),
    -- 自 GR 登记提交起算的检验时限（D1）
    DUE_TIME DATETIME,
    OVERDUE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    RELEASED_BY VARCHAR(64),
    RELEASED_DATE DATETIME,
    REVIEW_BY VARCHAR(64),
    REVIEW_DATE DATETIME,
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_LOT_NO (LOT_NO),
    KEY IDX_QMS_LOT_STATUS (STATUS),
    KEY IDX_QMS_LOT_GR (GR_ID),
    KEY IDX_QMS_LOT_ITEM (ITEM_CODE),
    KEY IDX_QMS_LOT_SUP (SUPPLIER_ID),
    KEY IDX_QMS_LOT_DUE (DUE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 8) 检验批明细（检验项快照 + 录入结果） ----------
CREATE TABLE IF NOT EXISTS erp_qms_lot_item (
    ID VARCHAR(64) NOT NULL,
    LOT_ID VARCHAR(64) NOT NULL,
    SEQUENCE_NO INT NOT NULL DEFAULT 1,
    CHARACTERISTIC_NAME VARCHAR(128) NOT NULL,
    CTQ_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    REGULATORY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    SPEC_TYPE VARCHAR(16) NOT NULL DEFAULT 'NUMERIC',
    LOWER_LIMIT DECIMAL(18,4),
    UPPER_LIMIT DECIMAL(18,4),
    TARGET_VALUE DECIMAL(18,4),
    UNIT VARCHAR(16),
    METHOD_NAME VARCHAR(128),
    INSTRUMENT_TYPE VARCHAR(64),
    -- 录入：计量型实测值 / 计数型不合格数
    MEASURED_VALUE DECIMAL(18,4),
    -- PENDING / PASS / FAIL
    JUDGE VARCHAR(8) NOT NULL DEFAULT 'PENDING',
    -- 数据异常二次确认（BR-4.12-15）
    ABNORMAL_CONFIRM VARCHAR(1) NOT NULL DEFAULT '0',
    ABNORMAL_ORIGINAL DECIMAL(18,4),
    INSTRUMENT_ID VARCHAR(64),
    INSTRUMENT_CODE VARCHAR(64),
    REMARK VARCHAR(255),
    INSPECT_BY VARCHAR(64),
    INSPECT_TIME DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_LOT_ITEM_LOT (LOT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 9) GR 行检验状态列（spec goods-receipt：仅由检验批动作驱动） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_gr_line'
        AND COLUMN_NAME = 'QC_STATUS') = 0,
    'ALTER TABLE erp_proc_gr_line
       ADD COLUMN QC_STATUS VARCHAR(16) NOT NULL DEFAULT ''NONE''
         COMMENT ''检验状态：NONE/PENDING/RELEASED/CONCESSION/FROZEN/SKIPPED'' AFTER STATUS',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
