-- 040-quality-execution.sql
-- 质量执行域：NCR / 让步接收 / 退货单 / CAPA / COPQ / SCAR / 器具校准 / 可疑批次 / SPC / 严格度
-- change add-quality-collaboration，design D5~D10；幂等：IF NOT EXISTS / INSERT IGNORE

-- ---------- 1) NCR 不合格品报告（design D6 两阶段冻结） ----------
CREATE TABLE IF NOT EXISTS erp_qms_ncr (
    ID VARCHAR(64) NOT NULL,
    -- NCR + yyyyMMdd + - + 6 位流水
    NCR_NO VARCHAR(32) NOT NULL,
    LOT_ID VARCHAR(64),
    LOT_NO VARCHAR(32),
    GR_ID VARCHAR(64),
    GR_LINE_ID VARCHAR(64),
    PO_ID VARCHAR(64),
    PO_NO VARCHAR(64),
    SUPPLIER_ID VARCHAR(64),
    SUPPLIER_NAME VARCHAR(128),
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    BATCH_NO VARCHAR(64),
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- CRITICAL / MAJOR / MINOR（CTQ 或安全法规默认 CRITICAL）
    SEVERITY VARCHAR(16) NOT NULL DEFAULT 'MAJOR',
    DEFECT_ITEM VARCHAR(128),
    DEFECT_DESC VARCHAR(500),
    -- 不合格项是否 CTQ / 安全法规（禁让步 BR-4.12-26）
    CTQ_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    REGULATORY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- CREATED / REVIEWING / RETURNING / SORTING / REWORKING / CONCESSION /
    -- DISPOSED / CLOSED / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'CREATED',
    -- RETURN / SORT / REWORK / CONCESSION
    DISPOSITION VARCHAR(16),
    -- 冻结对象：GR_LINE（未过账）/ STOCK（已入库）/ BOTH
    FREEZE_SCOPE VARCHAR(16) NOT NULL DEFAULT 'GR_LINE',
    FROZEN_FLAG VARCHAR(1) NOT NULL DEFAULT '1',
    -- 评审分级时限（BR-4.12-25）
    REVIEW_DUE_TIME DATETIME,
    REVIEW_BY VARCHAR(64),
    REVIEW_TIME DATETIME,
    REVIEW_OPINION VARCHAR(500),
    -- 处置执行完成
    DISPOSED_DATE DATETIME,
    -- 关闭（CAPA 有效性验证通过方可）
    CLOSED_DATE DATETIME,
    CLOSED_BY VARCHAR(64),
    -- 超期升级（BR-4.2-27 / BR-4.12-30）
    OVERDUE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    ESCALATED_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- 供应商本期绩效评价发布冻结（BR-4.2-27，绩效模块未建 D4）
    PERF_FROZEN_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- 关联 CAPA
    CAPA_ID VARCHAR(64),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_NCR_NO (NCR_NO),
    KEY IDX_QMS_NCR_STATUS (STATUS),
    KEY IDX_QMS_NCR_SUP (SUPPLIER_ID),
    KEY IDX_QMS_NCR_LOT (LOT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) 让步接收申请（C-4.12-01 双签） ----------
CREATE TABLE IF NOT EXISTS erp_qms_concession (
    ID VARCHAR(64) NOT NULL,
    -- CC + yyyyMMdd + - + 6 位流水
    CONCESSION_NO VARCHAR(32) NOT NULL,
    NCR_ID VARCHAR(64),
    NCR_NO VARCHAR(32),
    LOT_ID VARCHAR(64),
    GR_ID VARCHAR(64),
    GR_LINE_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    BATCH_NO VARCHAR(64),
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- 让步原因（BR-4.2-26 必填）
    REASON VARCHAR(500) NOT NULL,
    -- 技术评估结论 / 风险评估
    TECH_ASSESS VARCHAR(1000),
    RISK_ASSESS VARCHAR(1000),
    -- 限制条件：有效期至 / 批准数量上限 / 使用范围（BR-4.12-28）
    LIMIT_UNTIL DATE,
    LIMIT_QTY DECIMAL(18,4),
    LIMIT_SCOPE VARCHAR(500),
    -- DRAFT / PENDING_APPROVE / APPROVED / REJECTED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    APPROVAL_ID VARCHAR(64),
    SUBMITTED_BY VARCHAR(64),
    SUBMITTED_DATE DATETIME,
    REJECT_REASON VARCHAR(500),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_CC_NO (CONCESSION_NO),
    KEY IDX_QMS_CC_NCR (NCR_ID),
    KEY IDX_QMS_CC_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 退货单（2.6.1，BR-4.2-32/33/34） ----------
CREATE TABLE IF NOT EXISTS erp_proc_return (
    ID VARCHAR(64) NOT NULL,
    -- RT + yyyyMMdd + - + 6 位流水
    RETURN_NO VARCHAR(32) NOT NULL,
    -- NCR（质量退货）/ MANUAL（非质量手工退货）
    SOURCE_TYPE VARCHAR(8) NOT NULL DEFAULT 'NCR',
    NCR_ID VARCHAR(64),
    NCR_NO VARCHAR(32),
    PO_ID VARCHAR(64),
    PO_NO VARCHAR(64),
    GR_ID VARCHAR(64),
    GR_NO VARCHAR(32),
    -- 原入库单（已入库退货必填；未过账质检退货可空，BR-4.2-32 例外口）
    ORIGIN_DOC_NO VARCHAR(32),
    SUPPLIER_ID VARCHAR(64),
    SUPPLIER_NAME VARCHAR(128),
    TOTAL_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    TOTAL_AMT DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- DRAFT / PENDING_APPROVE / APPROVED / REJECTED / OUT_DONE / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    APPROVAL_ID VARCHAR(64),
    REJECT_REASON VARCHAR(500),
    -- 退货出库
    OUT_BY VARCHAR(64),
    OUT_DATE DATETIME,
    -- 红字入库凭证号（RV + yyyyMMdd + - + 6 位）
    RED_DOC_NO VARCHAR(32),
    -- 30 天补发/退款跟踪
    TRACK_DUE_DATE DATE,
    -- OPEN / CLOSED / OVERDUE
    TRACK_STATUS VARCHAR(16),
    TRACK_CLOSED_DATE DATETIME,
    -- 质量退货绩效扣分标记（D4：绩效模块未建，标记位留痕）
    PERF_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    RETURN_REASON VARCHAR(500),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PROC_RT_NO (RETURN_NO),
    KEY IDX_PROC_RT_STATUS (STATUS),
    KEY IDX_PROC_RT_SUP (SUPPLIER_ID),
    KEY IDX_PROC_RT_NCR (NCR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_proc_return_line (
    ID VARCHAR(64) NOT NULL,
    RETURN_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    PO_LINE_ID VARCHAR(64),
    GR_LINE_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    UNIT VARCHAR(16),
    BATCH_NO VARCHAR(64),
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    -- 未过账质检退货按 PO 单价；已入库按原入库单价
    UNIT_PRICE DECIMAL(18,4),
    AMOUNT DECIMAL(18,2),
    LINE_REMARK VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_PROC_RT_LINE_RT (RETURN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 库存让步接收限制列（D8：QC_QTY 锁定 + 核销放行） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_stock'
        AND COLUMN_NAME = 'CONCESSION_FLAG') = 0,
    'ALTER TABLE erp_inv_stock
       ADD COLUMN CONCESSION_FLAG VARCHAR(1) NOT NULL DEFAULT ''0''
         COMMENT ''1=让步接收锁定中'' AFTER AVAILABLE_QTY,
       ADD COLUMN CONCESSION_LIMIT VARCHAR(500)
         COMMENT ''限制条件 JSON：有效期/上限/使用范围/剩余'' AFTER CONCESSION_FLAG',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 5) CAPA / 8D ----------
CREATE TABLE IF NOT EXISTS erp_qms_capa (
    ID VARCHAR(64) NOT NULL,
    -- CA + yyyyMMdd + - + 6 位流水
    CAPA_NO VARCHAR(32) NOT NULL,
    NCR_ID VARCHAR(64),
    NCR_NO VARCHAR(32),
    -- REPEAT / EVENT / COMPLAINT / AUDIT / MANUAL
    SOURCE_TYPE VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    TITLE VARCHAR(255) NOT NULL,
    PROBLEM_DESC VARCHAR(1000),
    SCOPE_DESC VARCHAR(500),
    -- CRITICAL / MAJOR / MINOR
    SEVERITY VARCHAR(16) NOT NULL DEFAULT 'MAJOR',
    OWNER_ID VARCHAR(64),
    OWNER_NAME VARCHAR(128),
    -- D1 ~ D8
    CURRENT_STEP VARCHAR(4) NOT NULL DEFAULT 'D1',
    -- OPEN / ANALYZING / VERIFYING / REANALYZING / CLOSED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    -- Critical 24h 遏制倒计时（BR-4.12-32）
    CONTAIN_DUE_TIME DATETIME,
    CONTAIN_CONFIRMED VARCHAR(1) NOT NULL DEFAULT '0',
    CONTAIN_ESCALATED VARCHAR(1) NOT NULL DEFAULT '0',
    ROOT_CAUSE VARCHAR(1000),
    ROOT_CAUSE_EVIDENCE VARCHAR(1000),
    -- VALID / PARTIAL / INVALID / PENDING
    VERIFY_RESULT VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    VERIFY_INDICATOR VARCHAR(255),
    VERIFY_TARGET VARCHAR(255),
    VERIFY_DATA VARCHAR(1000),
    -- 复发重开关联（BR-4.12-36）
    ORIGIN_CAPA_ID VARCHAR(64),
    DUE_DATE DATE,
    CLOSED_DATE DATETIME,
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_CAPA_NO (CAPA_NO),
    KEY IDX_QMS_CAPA_STATUS (STATUS),
    KEY IDX_QMS_CAPA_NCR (NCR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_qms_capa_step (
    ID VARCHAR(64) NOT NULL,
    CAPA_ID VARCHAR(64) NOT NULL,
    STEP_CODE VARCHAR(4) NOT NULL,
    STEP_NAME VARCHAR(64) NOT NULL,
    -- PENDING / DONE
    STATUS VARCHAR(8) NOT NULL DEFAULT 'PENDING',
    OWNER_ID VARCHAR(64),
    OWNER_NAME VARCHAR(128),
    OUTPUT_DESC VARCHAR(1000),
    DONE_TIME DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_CAPA_STEP (CAPA_ID, STEP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_qms_capa_action (
    ID VARCHAR(64) NOT NULL,
    CAPA_ID VARCHAR(64) NOT NULL,
    -- CORRECT / PREVENT
    ACTION_TYPE VARCHAR(16) NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    OWNER_ID VARCHAR(64),
    OWNER_NAME VARCHAR(128),
    DUE_DATE DATE,
    -- PENDING / DONE / OVERDUE
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    EFFECT_DESC VARCHAR(500),
    -- 措施涉及标准/SOP 变更（BR-4.12-34）
    STANDARD_CHANGE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    CHANGE_APPROVAL_ID VARCHAR(64),
    DONE_TIME DATETIME,
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_CAPA_ACT_CAPA (CAPA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) COPQ 质量成本归集（D2：成本类别枚举直存，无会计科目映射） ----------
CREATE TABLE IF NOT EXISTS erp_qms_copq_entry (
    ID VARCHAR(64) NOT NULL,
    -- CO + yyyyMMdd + - + 6 位流水
    ENTRY_NO VARCHAR(32) NOT NULL,
    -- PREVENTION / APPRAISAL / INTERNAL_FAILURE / EXTERNAL_FAILURE
    CATEGORY VARCHAR(24) NOT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- NCR / RETURN / SCAR / CAPA / MANUAL
    SOURCE_TYPE VARCHAR(16) NOT NULL,
    SOURCE_ID VARCHAR(64),
    SOURCE_NO VARCHAR(32),
    NCR_ID VARCHAR(64),
    SCAR_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64),
    BATCH_NO VARCHAR(64),
    SUPPLIER_ID VARCHAR(64),
    SUPPLIER_NAME VARCHAR(128),
    UNATTRIBUTED_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    OCCUR_DATE DATE,
    -- PENDING_FINANCE / CONFIRMED / ANOMALY_HOLD
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING_FINANCE',
    APPROVAL_ID VARCHAR(64),
    CONFIRM_BY VARCHAR(64),
    CONFIRM_DATE DATETIME,
    -- 单笔 ≥10× 近 3 月月均（BR-4.12-39）
    ANOMALY_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_COPQ_NO (ENTRY_NO),
    KEY IDX_QMS_COPQ_CAT (CATEGORY, STATUS),
    KEY IDX_QMS_COPQ_SUP (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7) SCAR 供应商质量索赔（+扣款单） ----------
CREATE TABLE IF NOT EXISTS erp_qms_scar (
    ID VARCHAR(64) NOT NULL,
    -- SC + yyyyMMdd + - + 6 位流水
    SCAR_NO VARCHAR(32) NOT NULL,
    NCR_ID VARCHAR(64),
    NCR_NO VARCHAR(32),
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128),
    -- NCR_RETURN / REPEAT / STOPPAGE
    TRIGGER_TYPE VARCHAR(16) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DEFECT_DESC VARCHAR(1000),
    CLAIM_ITEMS VARCHAR(500),
    CLAIM_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- 回复时限（scar-reply-days=5 工作日）
    REPLY_DUE_DATE DATE,
    -- DRAFT / SENT / REPLYING / VERIFYING / CLOSED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    -- 重大 SCAR 审批（质量经理）
    APPROVAL_ID VARCHAR(64),
    SENT_DATE DATETIME,
    ESCALATED_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    -- SQE 代录供应商 8D 回复（D7）
    REPLY_TEXT VARCHAR(2000),
    REPLY_BY VARCHAR(64),
    REPLY_DATE DATETIME,
    REJECT_COUNT INT NOT NULL DEFAULT 0,
    VERIFY_RESULT VARCHAR(16),
    VERIFY_BY VARCHAR(64),
    VERIFY_DATE DATETIME,
    CLOSED_DATE DATETIME,
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_SCAR_NO (SCAR_NO),
    KEY IDX_QMS_SCAR_SUP (SUPPLIER_ID),
    KEY IDX_QMS_SCAR_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_qms_scar_deduction (
    ID VARCHAR(64) NOT NULL,
    -- SD + yyyyMMdd + - + 6 位流水
    DEDUCT_NO VARCHAR(32) NOT NULL,
    SCAR_ID VARCHAR(64) NOT NULL,
    SCAR_NO VARCHAR(32),
    SUPPLIER_ID VARCHAR(64),
    SUPPLIER_NAME VARCHAR(128),
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- PENDING_FINANCE / CONFIRMED / TO_DEDUCT / DISPUTED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING_FINANCE',
    APPROVAL_ID VARCHAR(64),
    CONFIRM_BY VARCHAR(64),
    CONFIRM_DATE DATETIME,
    DISPUTE_REASON VARCHAR(500),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_SD_NO (DEDUCT_NO),
    KEY IDX_QMS_SD_SCAR (SCAR_ID),
    KEY IDX_QMS_SD_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 8) 计量器具台账 + 校准记录 ----------
CREATE TABLE IF NOT EXISTS erp_qms_gauge (
    ID VARCHAR(64) NOT NULL,
    GAUGE_CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    CATEGORY VARCHAR(64),
    ACCURACY_LEVEL VARCHAR(32),
    -- 校准周期（月）；CTQ 用器具 MUST ≤12
    CAL_CYCLE_MONTHS INT NOT NULL DEFAULT 12,
    -- 1 = 用于 CTQ 项检验
    CTQ_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    DEPT VARCHAR(64),
    LOCATION VARCHAR(128),
    OWNER_NAME VARCHAR(128),
    -- VALID / LIMITED / EXPIRED / DISABLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'VALID',
    LAST_CAL_DATE DATE,
    NEXT_CAL_DATE DATE,
    -- 限用范围（如「仅非 CTQ 项」）
    LIMIT_SCOPE VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_GAUGE_CODE (GAUGE_CODE),
    KEY IDX_QMS_GAUGE_NEXT (NEXT_CAL_DATE),
    KEY IDX_QMS_GAUGE_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_qms_gauge_calibration (
    ID VARCHAR(64) NOT NULL,
    GAUGE_ID VARCHAR(64) NOT NULL,
    PLAN_DATE DATE,
    CAL_DATE DATE,
    -- PASS / LIMITED / FAIL
    RESULT VARCHAR(16),
    CERT_NO VARCHAR(64),
    CAL_ORG VARCHAR(128),
    NEXT_CAL_DATE DATE,
    OPERATOR_NAME VARCHAR(128),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_CAL_GAUGE (GAUGE_ID),
    KEY IDX_QMS_CAL_PLAN (PLAN_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 9) 可疑检验批次清单（BR-4.12-06 / C-4.12-12） ----------
CREATE TABLE IF NOT EXISTS erp_qms_suspect_lot (
    ID VARCHAR(64) NOT NULL,
    GAUGE_ID VARCHAR(64) NOT NULL,
    GAUGE_CODE VARCHAR(64),
    CAL_RECORD_ID VARCHAR(64),
    LOT_ID VARCHAR(64) NOT NULL,
    LOT_NO VARCHAR(32),
    ITEM_CODE VARCHAR(64),
    SUSPECT_REASON VARCHAR(255),
    -- PENDING_EVAL / CLEARED / BLOCKED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING_EVAL',
    EVAL_BY VARCHAR(64),
    EVAL_TIME DATETIME,
    EVAL_CONCLUSION VARCHAR(1000),
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_SUSPECT_LOT (LOT_ID),
    KEY IDX_QMS_SUSPECT_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 10) SPC 采样组与告警（规则版，design D10） ----------
CREATE TABLE IF NOT EXISTS erp_qms_spc_sample (
    ID VARCHAR(64) NOT NULL,
    -- 特性编码（标准特性 ID 或 特性名哈希口径由服务层生成）
    CHAR_CODE VARCHAR(64) NOT NULL,
    CHAR_NAME VARCHAR(128),
    MATERIAL_CODE VARCHAR(64),
    PROCESS_ID VARCHAR(64),
    GROUP_NO INT NOT NULL,
    SAMPLE_QTY INT NOT NULL DEFAULT 5,
    MEAN_VALUE DECIMAL(18,4),
    MIN_VALUE DECIMAL(18,4),
    MAX_VALUE DECIMAL(18,4),
    SPEC_LOWER DECIMAL(18,4),
    SPEC_UPPER DECIMAL(18,4),
    SPEC_TARGET DECIMAL(18,4),
    -- NORMAL / PRE_CONTROL（数据不足标预控制）
    LIMIT_MODE VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    CENTER_VALUE DECIMAL(18,4),
    UCL DECIMAL(18,4),
    LCL DECIMAL(18,4),
    SAMPLE_TIME DATETIME,
    OPERATOR_NAME VARCHAR(128),
    REMARK VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_SPC_CHAR (CHAR_CODE, SAMPLE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS erp_qms_spc_alert (
    ID VARCHAR(64) NOT NULL,
    ALERT_NO VARCHAR(32) NOT NULL,
    CHAR_CODE VARCHAR(64) NOT NULL,
    CHAR_NAME VARCHAR(128),
    -- OVER_LIMIT / SAME_SIDE / TREND
    RULE_CODE VARCHAR(16) NOT NULL,
    RULE_NAME VARCHAR(64),
    HIT_VALUE DECIMAL(18,4),
    DATA_SNAPSHOT VARCHAR(1000),
    -- OPEN / CLOSED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    PUSH_TO VARCHAR(255),
    HANDLE_BY VARCHAR(64),
    HANDLE_TIME DATETIME,
    HANDLE_RESULT VARCHAR(1000),
    OVERDUE_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_SPC_ALERT_NO (ALERT_NO),
    KEY IDX_QMS_SPC_ALERT_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 11) 严格度/加严记录（BR-4.12-02 / C-4.12-10，按物料+供应商维度） ----------
CREATE TABLE IF NOT EXISTS erp_qms_strictness (
    ID VARCHAR(64) NOT NULL,
    MATERIAL_CODE VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64),
    -- NORMAL / TIGHTENED / RELAXED
    STRICTNESS VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    -- 2_FAIL / SCAR / 3_PASS / 5_PASS / MANUAL
    TRIGGER_TYPE VARCHAR(16) NOT NULL,
    TRIGGER_REF VARCHAR(64),
    -- ACTIVE / RELEASED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    ACTIVE_DATE DATETIME,
    -- 解除依据（连续 3 批合格批次号）
    RELEASE_BASIS VARCHAR(255),
    RELEASE_DATE DATETIME,
    CONSEC_PASS INT NOT NULL DEFAULT 0,
    REMARK VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_STRICT_KEY (MATERIAL_CODE, SUPPLIER_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
