-- 041-quality-patrol.sql
-- IPQC 巡检计划（add-quality-collaboration task 5.10，偏差 D5：工单报工触发挂桩，
-- 本期以「手工创建 + 巡检计划定时触发」落地；计划到点自动生成 IPQC 检验批）。
-- 幂等：IF NOT EXISTS / INSERT IGNORE

CREATE TABLE IF NOT EXISTS erp_qms_patrol_plan (
    ID VARCHAR(64) NOT NULL,
    PLAN_CODE VARCHAR(64) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    -- IPQC（本期仅支持过程巡检；OQC 手工创建）
    LOT_TYPE VARCHAR(8) NOT NULL DEFAULT 'IPQC',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128),
    PROCESS_ID VARCHAR(64),
    PROCESS_NAME VARCHAR(64),
    -- 每 N 分钟触发一次（最小 1）
    INTERVAL_MINUTES INT NOT NULL DEFAULT 120,
    -- 每次生成的批量
    LOT_QTY DECIMAL(18,4) NOT NULL DEFAULT 1,
    NEXT_RUN_TIME DATETIME,
    -- ACTIVE / PAUSED / DONE
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    LAST_RUN_TIME DATETIME,
    LAST_LOT_NO VARCHAR(32),
    REMARK VARCHAR(255),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_QMS_PATROL_CODE (PLAN_CODE),
    KEY IDX_QMS_PATROL_DUE (STATUS, NEXT_RUN_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
