-- 043-concession-writeoff.sql
-- 让步接收核销放行（change add-quality-collaboration tasks 7.4，spec concession-acceptance）
-- 逐次校验有效期 / 累计量 / 使用范围，越界 422 且留 REJECTED 记录推送质量经理（BR-4.12-28）
-- 幂等：IF NOT EXISTS

CREATE TABLE IF NOT EXISTS erp_qms_concession_writeoff (
    ID VARCHAR(64) NOT NULL,
    -- 让步接收单
    CONCESSION_ID VARCHAR(64) NOT NULL,
    CONCESSION_NO VARCHAR(32),
    NCR_ID VARCHAR(64),
    ITEM_CODE VARCHAR(64),
    BATCH_NO VARCHAR(64),
    -- 本次核销数量 / 使用范围（出库用途）
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    SCOPE VARCHAR(500),
    -- OK / REJECTED（越界尝试留痕，推送质量经理）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OK',
    REJECT_REASON VARCHAR(500),
    -- 核销后剩余额度快照（留痕：人/时间/剩余额度）
    REMAIN_QTY DECIMAL(18,4),
    -- 关联出库/领用单（4.5 出库接入桩，D8）
    REF_DOC_NO VARCHAR(64),
    OPERATOR VARCHAR(64),
    OPERATOR_NAME VARCHAR(128),
    WRITE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500),
    CREATE_BY VARCHAR(64),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64),
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_QMS_CC_WO_CONC (CONCESSION_ID),
    KEY IDX_QMS_CC_WO_BATCH (ITEM_CODE, BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
