-- 046-accrual-three-way-match.sql
-- 应付暂估（2.7.1）+ 三方匹配（2.7.2）+ 最小总账凭证骨架（change add-accrual-three-way-match）
-- 1) 七表：科目 / 凭证头 / 凭证行 / 暂估单 / 发票头 / 发票行 / 匹配结果
-- 2) 科目最小集种子（INSERT IGNORE，编码唯一）
-- 3) M2-7-1 / M2-7-2 菜单 PERM 回填（M2-7-3 付款管理不动）
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / UPDATE 天然幂等（045 范式）

-- ---------- 1) 科目表 ----------
CREATE TABLE IF NOT EXISTS erp_fin_account (
    ID VARCHAR(64) NOT NULL,
    ACCOUNT_CODE VARCHAR(32) NOT NULL COMMENT '科目编码（唯一）',
    ACCOUNT_NAME VARCHAR(128) NOT NULL COMMENT '科目名称',
    DIRECTION VARCHAR(2) NOT NULL DEFAULT 'DR' COMMENT '余额方向：DR 借 / CR 贷',
    CATEGORY VARCHAR(32) DEFAULT NULL COMMENT '类别：ASSET 资产 / LIAB 负债 / COST 成本 / PROFIT 损益 / CASH 资金',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE 生效 / DISABLED 停用（停用科目拒绝新凭证行引用）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_ACCT_CODE (ACCOUNT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) 凭证头 ----------
CREATE TABLE IF NOT EXISTS erp_fin_voucher (
    ID VARCHAR(64) NOT NULL,
    VOUCHER_NO VARCHAR(32) NOT NULL COMMENT '凭证号（类型前缀+年月+流水，全局唯一，不可手工改，BR-4.6-07）',
    VOUCHER_TYPE VARCHAR(16) NOT NULL COMMENT 'ACC 暂估 / AP 正式应付 / APD 应付借项 / REV 红字冲销 / PADJ 价差调整',
    VOUCHER_DATE DATE NOT NULL COMMENT '凭证日期',
    PERIOD VARCHAR(6) NOT NULL COMMENT '会计期间 YYYYMM（本期=自然月近似，design D8）',
    LEGAL_ENTITY VARCHAR(64) DEFAULT NULL COMMENT '法人主体（C-0-08 必填，取默认法人）',
    CURRENCY VARCHAR(8) NOT NULL DEFAULT 'CNY' COMMENT '记账币种（C-0-08 必填）',
    SUMMARY VARCHAR(255) DEFAULT NULL COMMENT '摘要',
    SOURCE_TYPE VARCHAR(32) DEFAULT NULL COMMENT '来源单据类型：GR / RETURN / MATCH / REVERSE / VMI_TRANSFER / MIGRATION',
    SOURCE_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '来源单据号（业财一体锚点，反查用）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'POSTED' COMMENT 'DRAFT / POSTED（生成即 POSTED，design D2）',
    REVERSES_ID VARCHAR(64) DEFAULT NULL COMMENT '红字冲销关联的原凭证 ID（BR-4.6-09）',
    TOTAL_DR DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '借方合计（= 贷方合计，借贷平衡）',
    TOTAL_CR DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '贷方合计',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_VOUCHER_NO (VOUCHER_NO),
    KEY IDX_FIN_VOUCHER_SRC (SOURCE_TYPE, SOURCE_DOC_NO),
    KEY IDX_FIN_VOUCHER_PERIOD (PERIOD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 凭证行 ----------
CREATE TABLE IF NOT EXISTS erp_fin_voucher_line (
    ID VARCHAR(64) NOT NULL,
    VOUCHER_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    ACCOUNT_CODE VARCHAR(32) NOT NULL COMMENT '科目编码',
    ACCOUNT_NAME VARCHAR(128) DEFAULT NULL COMMENT '科目名称快照',
    DIRECTION VARCHAR(2) NOT NULL COMMENT 'DR 借 / CR 贷',
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '金额（精确到分，可为负表示红字行）',
    SUMMARY VARCHAR(255) DEFAULT NULL,
    SUPPLIER_ID VARCHAR(64) DEFAULT NULL COMMENT '辅助核算-供应商',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_FIN_VL_VOUCHER (VOUCHER_ID),
    KEY IDX_FIN_VL_ACCOUNT (ACCOUNT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 应付暂估单（头级，明细反查 erp_proc_gr_line，design D1） ----------
CREATE TABLE IF NOT EXISTS erp_fin_accrual (
    ID VARCHAR(64) NOT NULL,
    ACCRUAL_NO VARCHAR(32) NOT NULL COMMENT '暂估单号 AC+yyyyMMdd+流水',
    SOURCE_TYPE VARCHAR(16) NOT NULL DEFAULT 'GR' COMMENT 'GR 收货过账 / VMI_TRANSFER 寄售转自有（FR-4.2-8-3 预留）',
    GR_NO VARCHAR(32) DEFAULT NULL COMMENT '关联收货单（SOURCE_TYPE=GR）',
    POSTING_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '入库凭证号（IV，锚点）',
    PO_NO VARCHAR(32) DEFAULT NULL COMMENT '关联 PO',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂估金额 = Σ 容差内核销量 × PO 行单价（与入库凭证行金额一致）',
    OFFSETTED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '退货累计冲减金额（部分冲减用累加表达，design D5）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN 未冲回 / REVERSED 已冲回',
    REVERSE_SOURCE VARCHAR(16) DEFAULT NULL COMMENT 'MANUAL 手工 / AUTO_MATCH 三方匹配自动',
    REVERSE_INVOICE_NO VARCHAR(64) DEFAULT NULL COMMENT '关联发票号',
    REVERSE_REASON VARCHAR(255) DEFAULT NULL COMMENT '冲回原因',
    REVERSE_BY VARCHAR(64) DEFAULT NULL,
    REVERSE_AT DATETIME DEFAULT NULL,
    VOUCHER_ID VARCHAR(64) DEFAULT NULL COMMENT '暂估凭证 ID',
    ORIGINAL_SUPPLIER_CODE VARCHAR(32) DEFAULT NULL COMMENT '合并迁移前源供应商编码快照（BR-4.1-28）',
    MIGRATION_BATCH_NO VARCHAR(32) DEFAULT NULL COMMENT '合并迁移批次号（NULL=未迁移）',
    MIGRATION_CONFIRMED TINYINT DEFAULT NULL COMMENT 'NULL=未迁移 / 0=挂起待财务确认 / 1=已确认（BR-4.1-29）',
    MIGRATION_CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    MIGRATION_CONFIRM_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_ACCRUAL_NO (ACCRUAL_NO),
    KEY IDX_FIN_ACCRUAL_SUP (SUPPLIER_ID),
    KEY IDX_FIN_ACCRUAL_STATUS (STATUS),
    KEY IDX_FIN_ACCRUAL_GR (GR_NO),
    KEY IDX_FIN_ACCRUAL_PO (PO_NO),
    KEY IDX_FIN_ACCRUAL_BATCH (MIGRATION_BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 供应商发票头 ----------
CREATE TABLE IF NOT EXISTS erp_fin_ap_invoice (
    ID VARCHAR(64) NOT NULL,
    INVOICE_NO VARCHAR(64) NOT NULL COMMENT '发票号（同供应商内唯一）',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    INVOICE_DATE DATE NOT NULL COMMENT '发票日期（跨期判定用，design D8）',
    CURRENCY VARCHAR(8) NOT NULL DEFAULT 'CNY',
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '含税总额（本期不拆进项税，design D9）',
    PO_NO VARCHAR(32) DEFAULT NULL COMMENT '主关联 PO（缺 PO 关联不入自动匹配）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT / MATCHED / EXCEPTION / POSTED',
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_INV_NO (SUPPLIER_ID, INVOICE_NO),
    KEY IDX_FIN_INV_SUP (SUPPLIER_ID),
    KEY IDX_FIN_INV_STATUS (STATUS),
    KEY IDX_FIN_INV_PO (PO_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) 供应商发票行 ----------
CREATE TABLE IF NOT EXISTS erp_fin_ap_invoice_line (
    ID VARCHAR(64) NOT NULL,
    INVOICE_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    PO_ID VARCHAR(64) DEFAULT NULL,
    PO_NO VARCHAR(32) DEFAULT NULL,
    PO_LINE_ID VARCHAR(64) DEFAULT NULL,
    ITEM_CODE VARCHAR(64) DEFAULT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    UNIT VARCHAR(16) DEFAULT NULL,
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '发票数量',
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL COMMENT '发票单价',
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '行金额',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_FIN_INV_LINE_INV (INVOICE_ID),
    KEY IDX_FIN_INV_LINE_PO (PO_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7) 匹配结果 / 异常对账单 ----------
CREATE TABLE IF NOT EXISTS erp_fin_match_result (
    ID VARCHAR(64) NOT NULL,
    MATCH_NO VARCHAR(32) NOT NULL COMMENT '匹配单号 MT+yyyyMMdd+流水',
    INVOICE_ID VARCHAR(64) NOT NULL,
    INVOICE_NO VARCHAR(64) DEFAULT NULL,
    PO_NO VARCHAR(32) DEFAULT NULL,
    SUPPLIER_ID VARCHAR(64) DEFAULT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        COMMENT 'MATCHED 匹配通过（已自动冲回）/ EXCEPTION 异常冻结待确认 / CONFIRMED 已确认待过账 / POSTED 已过账 / FAILED 匹配失败',
    DIFF_QTY_RATE DECIMAL(10,6) DEFAULT NULL COMMENT '数量差异率最大值',
    DIFF_PRICE_RATE DECIMAL(10,6) DEFAULT NULL COMMENT '单价差异率最大值',
    DIFF_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '金额差（发票额 − 暂估额）',
    DIFF_AMOUNT_RATE DECIMAL(10,6) DEFAULT NULL COMMENT '金额差异率',
    DETAIL TEXT COMMENT '逐行差异明细（JSON）',
    EXCEPTION_TYPE VARCHAR(32) DEFAULT NULL COMMENT 'PRICE_DIFF 价差超容差 / QTY_DIFF 数量不符 / NO_RECEIPT 无收货',
    PERIOD_CROSS TINYINT NOT NULL DEFAULT 0 COMMENT '跨会计期间（发票自然月 < 当前自然月，design D8）',
    CONFIRM_OPINION VARCHAR(255) DEFAULT NULL COMMENT '采购员价差确认意见',
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    POST_BY VARCHAR(64) DEFAULT NULL,
    POST_AT DATETIME DEFAULT NULL,
    VOUCHER_ID VARCHAR(64) DEFAULT NULL COMMENT '正式应付/价差调整凭证 ID',
    ACCRUAL_BATCH_REVERSED TINYINT NOT NULL DEFAULT 0 COMMENT '是否已执行暂估自动冲回',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_MATCH_NO (MATCH_NO),
    KEY IDX_FIN_MATCH_INV (INVOICE_ID),
    KEY IDX_FIN_MATCH_STATUS (STATUS),
    KEY IDX_FIN_MATCH_SUP (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 8) 科目最小集种子（design D1 / gl-voucher spec） ----------
INSERT IGNORE INTO erp_fin_account (ID, ACCOUNT_CODE, ACCOUNT_NAME, DIRECTION, CATEGORY, STATUS) VALUES
('ACC-1403',  '1403',  '原材料',           'DR', 'ASSET',  'ACTIVE'),
('ACC-1405',  '1405',  '库存商品',         'DR', 'ASSET',  'ACTIVE'),
('ACC-2203',  '2203',  '应付暂估',         'CR', 'LIAB',   'ACTIVE'),
('ACC-2202',  '2202',  '应付账款',         'CR', 'LIAB',   'ACTIVE'),
('ACC-222101','222101','应交税费-进项税',   'DR', 'ASSET',  'ACTIVE'),
('ACC-1406',  '1406',  '物资采购价差',     'DR', 'COST',   'ACTIVE'),
('ACC-1002',  '1002',  '银行存款',         'DR', 'CASH',   'ACTIVE');

-- ---------- 9) 菜单 PERM（M2-7-1 应付暂估 / M2-7-2 三方匹配；M2-7-3 不动） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_PM,ROLE_ADMIN'
 WHERE ID = 'M2-7-1' AND (PERM IS NULL OR PERM = '');

UPDATE erp_admin_menu
   SET PERM = 'ROLE_PM,ROLE_ADMIN'
 WHERE ID = 'M2-7-2' AND (PERM IS NULL OR PERM = '');
