-- 047-payment-management.sql
-- 付款管理（2.7.3，change add-payment-management design D1）
-- 1) 六表：银行账户 / 供应商对账单 / 付款申请 / 预付款申请 / 付款单 / 核销记录
-- 2) 增列：erp_fin_ap_invoice.PAID_AMOUNT、erp_proc_po.PREPAY_RATIO
-- 3) 种子：科目 1123 预付账款、角色 role-fin-mgr / role-gm、M2-7-3 PERM
-- 幂等：CREATE IF NOT EXISTS / information_schema+PREPARE / INSERT IGNORE / UPDATE 天然幂等（045/046 范式）

-- ---------- 1) 银行账户 ----------
CREATE TABLE IF NOT EXISTS erp_fin_bank_account (
    ID VARCHAR(64) NOT NULL,
    ACCOUNT_NAME VARCHAR(64) NOT NULL COMMENT '户名',
    ACCOUNT_NO VARCHAR(32) NOT NULL COMMENT '账号（唯一）',
    CURRENCY VARCHAR(8) NOT NULL DEFAULT 'CNY',
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '实时余额（BR-4.6-21，条件更新防透支）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE / DISABLED',
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_BANK_NO (ACCOUNT_NO),
    KEY IDX_FIN_BANK_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) 供应商对账单（含差异对账单，C-4.2-15） ----------
CREATE TABLE IF NOT EXISTS erp_fin_supplier_statement (
    ID VARCHAR(64) NOT NULL,
    STMT_NO VARCHAR(32) NOT NULL COMMENT '对账单号 ST+yyyyMMdd+流水',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    STMT_DATE DATE NOT NULL COMMENT '对账日期',
    STMT_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '供应商对账单金额（手工录入）',
    BASE_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '比对基准 = 该供应商 OPEN 暂估余额合计',
    DIFF_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '差异 = 对账金额 − 暂估余额',
    DIFF_RATE DECIMAL(10,6) NOT NULL DEFAULT 0 COMMENT '差异率（余额为 0 且对账额>0 取 1）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACCEPTED' COMMENT 'ACCEPTED 容差内 / EXCEPTION 差异对账单（冻结付款）/ CLOSED 双签关闭',
    PM_CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '采购员节点确认人',
    PM_CONFIRM_AT DATETIME DEFAULT NULL,
    PM_OPINION VARCHAR(255) DEFAULT NULL,
    FIN_CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '财务节点确认人',
    FIN_CONFIRM_AT DATETIME DEFAULT NULL,
    FIN_OPINION VARCHAR(255) DEFAULT NULL,
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_STMT_NO (STMT_NO),
    KEY IDX_FIN_STMT_SUP (SUPPLIER_ID, STATUS),
    KEY IDX_FIN_STMT_DATE (STMT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 付款申请 ----------
CREATE TABLE IF NOT EXISTS erp_fin_payment_request (
    ID VARCHAR(64) NOT NULL,
    REQ_NO VARCHAR(32) NOT NULL COMMENT '申请单号 PA+yyyyMMdd+流水',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    APPLY_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '申请金额',
    INVOICE_IDS TEXT COMMENT '关联发票 ID 集合（JSON 数组，同供应商；design D1）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
        COMMENT 'DRAFT / PENDING_APPROVE / APPROVED / REJECTED / SCHEDULED / WAIT_FUNDS / PAID / CLOSED',
    PLAN_DATE DATE DEFAULT NULL COMMENT '计划付款日（FR-4.6-3-9）',
    SCHEDULE_BY VARCHAR(64) DEFAULT NULL,
    SCHEDULE_AT DATETIME DEFAULT NULL,
    EXECUTED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '累计已执行付款',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL,
    REJECT_REASON VARCHAR(255) DEFAULT NULL,
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_PAY_REQ_NO (REQ_NO),
    KEY IDX_FIN_PAY_REQ_SUP (SUPPLIER_ID),
    KEY IDX_FIN_PAY_REQ_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 预付款申请 ----------
CREATE TABLE IF NOT EXISTS erp_fin_prepayment (
    ID VARCHAR(64) NOT NULL,
    PP_NO VARCHAR(32) NOT NULL COMMENT '预付单号 PP+yyyyMMdd+流水',
    PO_ID VARCHAR(64) NOT NULL,
    PO_NO VARCHAR(32) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    PREPAY_RATIO DECIMAL(6,4) NOT NULL COMMENT '本次所用预付比例（PO.PREPAY_RATIO 空则默认参数，design D8）',
    APPLY_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '申请金额',
    PO_TOTAL_AMT DECIMAL(18,2) NOT NULL COMMENT 'PO 总金额（校验快照）',
    PO_OPEN_AMT DECIMAL(18,2) NOT NULL COMMENT 'PO 未清金额 = 总额 − 已过账入库额（C-4.2-13 校验快照）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT / PENDING_APPROVE / APPROVED / REJECTED / PAID / CLOSED',
    EXECUTED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '累计已付预付款',
    SETTLED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '已冲抵应付金额',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL,
    REJECT_REASON VARCHAR(255) DEFAULT NULL,
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_PP_NO (PP_NO),
    KEY IDX_FIN_PP_PO (PO_NO),
    KEY IDX_FIN_PP_SUP (SUPPLIER_ID),
    KEY IDX_FIN_PP_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 付款单（PAYMENT 正常付款 / PREPAY 预付付款） ----------
CREATE TABLE IF NOT EXISTS erp_fin_payment (
    ID VARCHAR(64) NOT NULL,
    PAY_NO VARCHAR(32) NOT NULL COMMENT '付款单号 PY+yyyyMMdd+流水',
    PAY_TYPE VARCHAR(16) NOT NULL DEFAULT 'PAYMENT' COMMENT 'PAYMENT 应付付款 / PREPAY 预付付款',
    REQ_ID VARCHAR(64) NOT NULL COMMENT '付款申请或预付款申请 ID',
    REQ_NO VARCHAR(32) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    APPLY_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '本次执行的申请金额（≤ 审批金额，L1）',
    DEDUCT_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'SCAR 抵扣合计',
    ACTUAL_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '实付 = 申请 − 抵扣（银行扣减额）',
    PAY_METHOD VARCHAR(16) NOT NULL COMMENT '电汇/支票/商业汇票/银行承兑汇票/现金（BR-4.6-20）',
    BANK_ACCOUNT_ID VARCHAR(64) NOT NULL,
    ACCOUNT_NAME VARCHAR(64) DEFAULT NULL,
    ACCOUNT_NO VARCHAR(32) DEFAULT NULL,
    PAY_DATE DATE NOT NULL COMMENT '付款日期（凭证日期，BR-4.6-19）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PAID' COMMENT 'PAID',
    DEDUCT_IDS TEXT COMMENT '抵扣扣款单 ID 集合（JSON）',
    VOUCHER_ID VARCHAR(64) DEFAULT NULL COMMENT '付款凭证 ID',
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_PAY_NO (PAY_NO),
    KEY IDX_FIN_PAY_REQ (REQ_ID),
    KEY IDX_FIN_PAY_SUP (SUPPLIER_ID),
    KEY IDX_FIN_PAY_DATE (PAY_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) 核销/冲抵记录（付款核销 KIND=PAYMENT，预付冲抵 KIND=SETTLE） ----------
CREATE TABLE IF NOT EXISTS erp_fin_payment_writeoff (
    ID VARCHAR(64) NOT NULL,
    KIND VARCHAR(16) NOT NULL COMMENT 'PAYMENT 付款核销 / SETTLE 预付冲抵',
    PAYMENT_ID VARCHAR(64) DEFAULT NULL COMMENT '付款单 ID（KIND=PAYMENT）',
    PP_ID VARCHAR(64) DEFAULT NULL COMMENT '预付单 ID（KIND=SETTLE）',
    INVOICE_ID VARCHAR(64) NOT NULL COMMENT '被核销发票 ID',
    INVOICE_NO VARCHAR(64) DEFAULT NULL,
    SUPPLIER_ID VARCHAR(64) DEFAULT NULL,
    PO_NO VARCHAR(32) DEFAULT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL COMMENT '核销/冲抵金额',
    WRITEOFF_DATE DATE NOT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_WO_PAY (PAYMENT_ID, INVOICE_ID),
    UNIQUE KEY UK_FIN_WO_SETTLE (PP_ID, INVOICE_ID),
    KEY IDX_FIN_WO_INV (INVOICE_ID),
    KEY IDX_FIN_WO_SUP (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7) 增列（幂等） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_fin_ap_invoice'
        AND COLUMN_NAME = 'PAID_AMOUNT') = 0,
    'ALTER TABLE erp_fin_ap_invoice
       ADD COLUMN PAID_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0
         COMMENT ''已核销金额（FIFO 核销，未清 = TOTAL_AMOUNT − PAID_AMOUNT）'' AFTER TOTAL_AMOUNT',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_po'
        AND COLUMN_NAME = 'PREPAY_RATIO') = 0,
    'ALTER TABLE erp_proc_po
       ADD COLUMN PREPAY_RATIO DECIMAL(6,4) DEFAULT NULL
         COMMENT ''约定预付比例（C-4.2-13；空则按 app.proc.prepay-ratio 默认 0.30）'' AFTER TOTAL_AMT',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_qms_scar_deduction'
        AND COLUMN_NAME = 'PAYMENT_ID') = 0,
    'ALTER TABLE erp_qms_scar_deduction
       ADD COLUMN PAYMENT_ID VARCHAR(64) DEFAULT NULL COMMENT ''抵扣付款单 ID（D3 落地）'',
       ADD COLUMN DEDUCT_DATE DATETIME DEFAULT NULL COMMENT ''实际抵扣时间'',
       ADD COLUMN DEDUCT_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT ''实际抵扣金额''',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 8) 种子：银行账户 / 科目 1123 / 角色 / 菜单 PERM ----------
INSERT IGNORE INTO erp_fin_bank_account (ID, ACCOUNT_NAME, ACCOUNT_NO, CURRENCY, BALANCE, STATUS, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('bank-icbc-basic', '福建民翔基本户（工行）', '1102020109200001', 'CNY', 1000000.00, 'ACTIVE', '期初余额（047 种子）', 'seed', '0', 0),
('bank-cmb-gen',    '福建民翔一般户（招行）', '75590088888888',   'CNY',  500000.00, 'ACTIVE', '期初余额（047 种子）', 'seed', '0', 0);

INSERT IGNORE INTO erp_fin_account (ID, ACCOUNT_CODE, ACCOUNT_NAME, DIRECTION, CATEGORY, STATUS) VALUES
('ACC-1123', '1123', '预付账款', 'DR', 'ASSET', 'ACTIVE');

INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('role-fin-mgr', 'ROLE_FINANCE_MGR', '财务主管', '90', '1', 'seed', '0', 0),
('role-gm',      'ROLE_GM',         '总经理',   '95', '1', 'seed', '0', 0);

UPDATE erp_admin_menu
   SET PERM = 'ROLE_PM,ROLE_ADMIN'
 WHERE ID = 'M2-7-3' AND (PERM IS NULL OR PERM = '');
