-- 048-consignment-procurement.sql
-- 寄售采购 VMI（2.8.1）+ 领料出库（4.5.2），change add-consignment-procurement design D1/D11
-- 1) 九表：VMI 协议头/行、寄售库存、领料单头/行、结算单头/行、处置建议单、告警
-- 2) 增列：erp_fin_ap_invoice.SETTLE_ID（VMI 发票关联结算单，design D8）
-- 3) 菜单 PERM：M2-8-1、M4-5-2（design D11）
-- 幂等：CREATE IF NOT EXISTS / information_schema+PREPARE / UPDATE 天然幂等（045/046/047 范式）

-- ---------- 1) VMI 寄售协议头（FR-4.2-8-1） ----------
CREATE TABLE IF NOT EXISTS erp_proc_vmi_agreement (
    ID VARCHAR(64) NOT NULL,
    AGREE_NO VARCHAR(32) NOT NULL COMMENT '协议编号 VM+yyyyMMdd+流水',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    SETTLE_CYCLE VARCHAR(8) NOT NULL DEFAULT 'MONTH' COMMENT '结算周期 WEEK 周 / MONTH 月',
    TRANSFER_TIME VARCHAR(16) NOT NULL DEFAULT 'ISSUE' COMMENT '物权转移时点（本期仅 ISSUE 领用时转移）',
    EFFECTIVE_DATE DATE NOT NULL COMMENT '生效日期',
    EXPIRE_DATE DATE NOT NULL COMMENT '失效日期（下达卡控：须 >= PO 交期，BR-4.2-35）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT 草稿 / EFFECTIVE 生效 / EXPIRED 过期 / DISABLED 停用',
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VMI_AGREE_NO (AGREE_NO),
    KEY IDX_VMI_AGREE_SUP (SUPPLIER_ID, STATUS),
    KEY IDX_VMI_AGREE_DATE (EXPIRE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) VMI 协议行：寄售物料清单 + 水位 + 价格条款 ----------
CREATE TABLE IF NOT EXISTS erp_proc_vmi_agreement_line (
    ID VARCHAR(64) NOT NULL,
    AGREE_ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    UNIT VARCHAR(16) DEFAULT NULL,
    MIN_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '最低库存水位（低于生成补货建议，FR-4.2-8-1）',
    MAX_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '最高库存水位（超出阻断收货，BR-4.2-36；0=不限）',
    UNIT_PRICE DECIMAL(18,4) NOT NULL COMMENT '协议单价（领用计价基准）',
    PRICE_START DATE NOT NULL COMMENT '价格条款起（领用日须在条款内，C-4.2-09）',
    PRICE_END DATE NOT NULL COMMENT '价格条款止',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_VMI_AGREE_L_AGREE (AGREE_ID, ITEM_CODE),
    KEY IDX_VMI_AGREE_L_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 寄售库存（物权=供应商，独立分账，BR-4.2-01 / design D1） ----------
CREATE TABLE IF NOT EXISTS erp_inv_vmi_stock (
    ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) NOT NULL DEFAULT '',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '寄售现有量（物权供应商）',
    ISSUED_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '累计领用量（账龄处置判断，BR-4.2-39）',
    INBOUND_DATE DATE NOT NULL COMMENT '首次入库日期（FIFO 依据，补货不刷新）',
    AGREE_NO VARCHAR(32) DEFAULT NULL COMMENT '最近入库关联协议号',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VMI_STOCK (ITEM_CODE, BATCH_NO, SUPPLIER_ID),
    KEY IDX_VMI_STOCK_SUP (SUPPLIER_ID),
    KEY IDX_VMI_STOCK_INBOUND (INBOUND_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 领料单头（4.5.2，DRAFT → POSTED | CANCELLED，design D5） ----------
CREATE TABLE IF NOT EXISTS erp_inv_material_issue (
    ID VARCHAR(64) NOT NULL,
    ISSUE_NO VARCHAR(32) NOT NULL COMMENT '领料单号 MI+yyyyMMdd+流水',
    ISSUE_TYPE VARCHAR(8) NOT NULL DEFAULT 'OWN' COMMENT 'OWN 自有库存 / VMI 寄售领用（物权转移）',
    WORK_ORDER_NO VARCHAR(64) NOT NULL COMMENT '领用工单号（BR-4.2-37 逐笔记录）',
    DEPT VARCHAR(64) DEFAULT NULL COMMENT '领料部门',
    PURPOSE VARCHAR(255) DEFAULT NULL COMMENT '用途',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT / POSTED / CANCELLED',
    CANCEL_REASON VARCHAR(255) DEFAULT NULL,
    TRANSFER_DOC_NO VARCHAR(32) DEFAULT NULL COMMENT '《寄售转自有凭证》VT+yyyyMMdd+流水（仅 VMI）',
    POST_BY VARCHAR(64) DEFAULT NULL,
    POST_DATE DATETIME DEFAULT NULL,
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MI_NO (ISSUE_NO),
    KEY IDX_MI_TYPE_STATUS (ISSUE_TYPE, STATUS),
    KEY IDX_MI_WO (WORK_ORDER_NO),
    KEY IDX_MI_DATE (CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 领料单行（FIFO 配批结果固化） ----------
CREATE TABLE IF NOT EXISTS erp_inv_material_issue_line (
    ID VARCHAR(64) NOT NULL,
    ISSUE_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) NOT NULL DEFAULT '',
    QTY DECIMAL(18,4) NOT NULL COMMENT '本批领用数量',
    STOCK_TYPE VARCHAR(8) NOT NULL DEFAULT 'OWN' COMMENT 'OWN / VMI（头冗余便于检索）',
    SUPPLIER_ID VARCHAR(64) DEFAULT NULL COMMENT '寄售供应商（VMI 行）',
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL COMMENT '领用时点协议价（VMI 行，物权转移计价）',
    AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '金额 = QTY × UNIT_PRICE（VMI 行）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MI_L_ISSUE (ISSUE_ID),
    KEY IDX_MI_L_ITEM (ITEM_CODE, BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) VMI 结算单头（FR-4.2-8-4 / BR-4.2-38 双确认，design D7） ----------
CREATE TABLE IF NOT EXISTS erp_proc_vmi_settlement (
    ID VARCHAR(64) NOT NULL,
    SETTLE_NO VARCHAR(32) NOT NULL COMMENT '结算单号 VS+yyyyMMdd+流水',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    PERIOD_START DATE NOT NULL COMMENT '结算期间起',
    PERIOD_END DATE NOT NULL COMMENT '结算期间止',
    SETTLE_CYCLE VARCHAR(8) NOT NULL DEFAULT 'MONTH',
    CALC_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '逐笔汇总 = Σ(领用量 × 领用时点协议价)',
    TRIAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '期末价试算金额',
    DIFF_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '差额 = CALC − TRIAL',
    DIFF_RATE DECIMAL(10,6) NOT NULL DEFAULT 0 COMMENT '差率 = |差额| / TRIAL（TRIAL=0 取 0/1）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT / ON_HOLD 超容差挂起 / CONFIRMED / INVOICED / CANCELLED',
    PM_CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '采购员确认人（双确认之一）',
    PM_CONFIRM_AT DATETIME DEFAULT NULL,
    SUPPLIER_CONFIRM_BY VARCHAR(128) DEFAULT NULL COMMENT '供应商确认人（线下确认登记，design D7）',
    SUPPLIER_CONFIRM_AT DATETIME DEFAULT NULL,
    SUPPLIER_CONFIRM_WAY VARCHAR(64) DEFAULT NULL COMMENT '确认方式：邮件/传真/对账单回签等',
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VMI_SETTLE_NO (SETTLE_NO),
    KEY IDX_VMI_SETTLE_SUP (SUPPLIER_ID, STATUS),
    KEY IDX_VMI_SETTLE_PERIOD (PERIOD_END)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7) VMI 结算单行（引用领料行，可对账视图） ----------
CREATE TABLE IF NOT EXISTS erp_proc_vmi_settlement_line (
    ID VARCHAR(64) NOT NULL,
    SETTLE_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    ISSUE_ID VARCHAR(64) NOT NULL COMMENT '领料单 ID',
    ISSUE_LINE_ID VARCHAR(64) NOT NULL COMMENT '领料行 ID（唯一引用，一结算单一发票 design D8）',
    ISSUE_NO VARCHAR(32) DEFAULT NULL,
    WORK_ORDER_NO VARCHAR(64) DEFAULT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL,
    QTY DECIMAL(18,4) NOT NULL COMMENT '领用数量',
    UNIT_PRICE DECIMAL(18,4) NOT NULL COMMENT '领用时点协议价',
    AMOUNT DECIMAL(18,2) NOT NULL COMMENT '行金额',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VMI_SETTLE_L_IL (ISSUE_LINE_ID),
    KEY IDX_VMI_SETTLE_L_SETTLE (SETTLE_ID),
    KEY IDX_VMI_SETTLE_L_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 8) 处置建议单（BR-4.2-39，L4 不阻断结算） ----------
CREATE TABLE IF NOT EXISTS erp_proc_vmi_disposal (
    ID VARCHAR(64) NOT NULL,
    DISPOSAL_NO VARCHAR(32) NOT NULL COMMENT '处置单号 VD+yyyyMMdd+流水',
    STOCK_ID VARCHAR(64) NOT NULL COMMENT '寄售库存批次 ID',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '批次现有量',
    AGE_DAYS INT NOT NULL DEFAULT 0 COMMENT '生成时库龄',
    SUGGEST_TYPE VARCHAR(16) NOT NULL COMMENT 'CONVERT 转自有采购 / RETURN 退回供应商',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / DONE / CANCELLED',
    RESOLVED_VIA VARCHAR(16) DEFAULT NULL COMMENT '实际处置方式（处理时可与建议不同）',
    RESOLVE_BY VARCHAR(64) DEFAULT NULL,
    RESOLVE_AT DATETIME DEFAULT NULL,
    RESOLVE_NOTE VARCHAR(255) DEFAULT NULL,
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VMI_DISPOSAL_NO (DISPOSAL_NO),
    KEY IDX_VMI_DISPOSAL_STOCK (STOCK_ID, STATUS),
    KEY IDX_VMI_DISPOSAL_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 9) 告警/建议（WATER_HIGH 超水位确认放行 / REPLENISH 补货建议，design D3/D4） ----------
CREATE TABLE IF NOT EXISTS erp_proc_vmi_alert (
    ID VARCHAR(64) NOT NULL,
    ALERT_NO VARCHAR(32) NOT NULL COMMENT '告警号 VA+yyyyMMdd+流水',
    ALERT_TYPE VARCHAR(16) NOT NULL COMMENT 'WATER_HIGH 超最高水位 / REPLENISH 低于最低水位',
    AGREE_ID VARCHAR(64) DEFAULT NULL,
    AGREE_NO VARCHAR(32) DEFAULT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    SUPPLIER_ID VARCHAR(64) DEFAULT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    CURRENT_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '触发时寄售库存量',
    LIMIT_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '水位阈值（WATER_HIGH=MAX / REPLENISH=MIN）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / CONFIRMED 已确认放行 / RESOLVED 已处理',
    CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '采购员确认人（BR-4.2-36 确认放行留痕）',
    CONFIRM_AT DATETIME DEFAULT NULL,
    CONFIRM_OPINION VARCHAR(255) DEFAULT NULL,
    REMARK VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VMI_ALERT_NO (ALERT_NO),
    KEY IDX_VMI_ALERT_TYPE (ALERT_TYPE, STATUS),
    KEY IDX_VMI_ALERT_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 10) 增列：发票关联 VMI 结算单 / 领料单供应商（design D8，幂等） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_fin_ap_invoice'
        AND COLUMN_NAME = 'SETTLE_ID') = 0,
    'ALTER TABLE erp_fin_ap_invoice
       ADD COLUMN SETTLE_ID VARCHAR(64) DEFAULT NULL
         COMMENT ''关联 VMI 结算单 ID（CONSIGN PO 发票必填，MODIFIED three-way-match）''',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_material_issue'
        AND COLUMN_NAME = 'SUPPLIER_ID') = 0,
    'ALTER TABLE erp_inv_material_issue
       ADD COLUMN SUPPLIER_ID VARCHAR(64) DEFAULT NULL COMMENT ''寄售供应商（VMI 领用必填）'',
       ADD COLUMN SUPPLIER_NAME VARCHAR(128) DEFAULT NULL COMMENT ''寄售供应商名称''',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 11) 菜单 PERM（design D11，幂等） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_PM,ROLE_ADMIN'
 WHERE ID = 'M2-8-1' AND (PERM IS NULL OR PERM = '');

UPDATE erp_admin_menu
   SET PERM = 'ROLE_ADMIN,ROLE_WAREHOUSE,ROLE_PM'
 WHERE ID = 'M4-5-2' AND (PERM IS NULL OR PERM = '');
