-- 049-supplier-portal-collaboration.sql
-- 门户协同 2.8.2，change add-supplier-portal-collaboration design D1/D3/D11/D14
-- 1) 四表：PO 交期协同流水 / ASN 头 / ASN 行 / 补货确认
-- 2) 增列：erp_proc_po.PROMISE_DATE/CONFIRM_STATUS/COOP_LOCK、erp_proc_gr.ASN_ID、
--         erp_admin_user.SUPPLIER_ID、erp_fin_supplier_statement.MATCH_RESULT/MATCH_BY/MATCH_AT
-- 3) 种子：角色 role-supplier、测试门户账号（绑定 sup-test-001）、M2-8-2 PERM
-- 幂等：CREATE IF NOT EXISTS / information_schema+PREPARE / INSERT IGNORE / UPDATE 天然幂等（045~048 范式）

-- ---------- 1) PO 交期协同流水（design D3：时间线与"协同异常工单"由流水行承载） ----------
CREATE TABLE IF NOT EXISTS erp_proc_po_coop (
    ID VARCHAR(64) NOT NULL,
    PO_ID VARCHAR(64) NOT NULL,
    PO_NO VARCHAR(32) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    ACTION_TYPE VARCHAR(24) NOT NULL
        COMMENT 'PUSHED 推送 / REMIND 催办 / ESCALATE 升级 / CONFIRM 确认 / CHANGE_ACCEPTED 改期接受 / LOCK 锁定 / UNLOCK 解锁',
    PROMISE_DATE DATE DEFAULT NULL COMMENT 'CONFIRM/CHANGE_ACCEPTED 的承诺交期',
    SOURCE VARCHAR(16) NOT NULL DEFAULT 'SYSTEM'
        COMMENT 'PORTAL 门户 / OFFLINE 代录 / SYSTEM 系统动作',
    OPERATOR_NAME VARCHAR(64) DEFAULT NULL COMMENT '动作操作人（门户=账号名）',
    DETAIL LONGTEXT COMMENT '动作明细 JSON（改期申请、锁定供应商近三单等）',
    REMARK VARCHAR(500) DEFAULT NULL,
    ACTION_AT DATETIME NOT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_PO_COOP_PO (PO_ID, ACTION_AT),
    KEY IDX_PO_COOP_SUP (SUPPLIER_ID, ACTION_AT),
    KEY IDX_PO_COOP_TYPE (ACTION_TYPE, ACTION_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) ASN 发货通知头（spec asn-collaboration，design D8/D9） ----------
CREATE TABLE IF NOT EXISTS erp_proc_asn (
    ID VARCHAR(64) NOT NULL,
    ASN_NO VARCHAR(32) NOT NULL COMMENT 'ASN+yyyyMMdd+流水',
    PO_ID VARCHAR(64) DEFAULT NULL COMMENT '常规 ASN 必填（REPLENISH 来源可空，design D9）',
    PO_NO VARCHAR(32) DEFAULT NULL,
    SOURCE VARCHAR(16) NOT NULL DEFAULT 'PO' COMMENT 'PO 常规 / REPLENISH 补货确认联动',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    SUPPLIER_NAME VARCHAR(128) DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED' COMMENT 'DRAFT 草稿 / CONFIRMED 待到货 / CLOSED 已核销',
    OVER_TOLERANCE_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '超容差数量（C-4.9-07 待审批）',
    OVER_STATUS VARCHAR(16) NOT NULL DEFAULT 'NONE'
        COMMENT 'NONE 无超收 / PENDING 待审批 / RELEASED 已放行 / REJECTED 已驳回',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL COMMENT '超收审批实例 ID（ApprovalEngine）',
    EXPECT_ARRIVAL DATE DEFAULT NULL COMMENT '预计到货时间（收货预约视图，design D8）',
    LOGISTICS_NO VARCHAR(64) DEFAULT NULL COMMENT '物流单号',
    ARRIVAL_DEVIATION_HOURS INT DEFAULT NULL COMMENT '实际到货 vs 承诺交期偏差小时（BR-4.9-01 绩效留痕）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ASN_NO (ASN_NO),
    KEY IDX_ASN_PO (PO_ID, STATUS),
    KEY IDX_ASN_SUP (SUPPLIER_ID, STATUS),
    KEY IDX_ASN_ARRIVAL (EXPECT_ARRIVAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) ASN 行 ----------
CREATE TABLE IF NOT EXISTS erp_proc_asn_line (
    ID VARCHAR(64) NOT NULL,
    ASN_ID VARCHAR(64) NOT NULL,
    PO_LINE_ID VARCHAR(64) DEFAULT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    UNIT VARCHAR(16) DEFAULT NULL,
    QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '发货数量（含容差内与超容差合计）',
    OVER_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '本行超容差数量',
    RECEIVED_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '已核销收货数量',
    BATCH_NO VARCHAR(64) DEFAULT NULL,
    LINE_STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / CLOSED',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_ASN_L_ASN (ASN_ID, LINE_NO),
    KEY IDX_ASN_L_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 补货确认（spec vmi-portal-sync，design D9） ----------
CREATE TABLE IF NOT EXISTS erp_proc_replenish_confirm (
    ID VARCHAR(64) NOT NULL,
    ALERT_ID VARCHAR(64) NOT NULL COMMENT 'VmiAlert REPLENISH 告警 ID',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    SUGGEST_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '建议量',
    CONFIRM_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '确认量（可下修，不得突破协议最高水位）',
    ASN_ID VARCHAR(64) DEFAULT NULL COMMENT '联动生成的 ASN',
    SOURCE VARCHAR(16) NOT NULL DEFAULT 'PORTAL' COMMENT 'PORTAL 门户 / OFFLINE 代录',
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_REPLENISH_ALERT (ALERT_ID),
    KEY IDX_REPLENISH_SUP (SUPPLIER_ID, ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 增列（information_schema 守卫 + PREPARE，幂等） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_po'
        AND COLUMN_NAME = 'PROMISE_DATE') = 0,
    'ALTER TABLE erp_proc_po
       ADD COLUMN PROMISE_DATE DATE DEFAULT NULL COMMENT ''供应商确认的承诺交期（po-collaboration）'',
       ADD COLUMN CONFIRM_STATUS VARCHAR(16) DEFAULT NULL
         COMMENT ''PUSHED/CONFIRMED/CHANGE_PENDING/ESCATED（NULL=未推送）'',
       ADD COLUMN COOP_LOCK VARCHAR(1) NOT NULL DEFAULT ''0''
         COMMENT ''供应商确认入口锁定（连续 3 张超时，design D5）''',
    'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_proc_gr'
        AND COLUMN_NAME = 'ASN_ID') = 0,
    'ALTER TABLE erp_proc_gr
       ADD COLUMN ASN_ID VARCHAR(64) DEFAULT NULL
         COMMENT ''关联 ASN（到货带出/过账核销，design D8）''',
    'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_admin_user'
        AND COLUMN_NAME = 'SUPPLIER_ID') = 0,
    'ALTER TABLE erp_admin_user
       ADD COLUMN SUPPLIER_ID VARCHAR(64) DEFAULT NULL
         COMMENT ''门户账号绑定供应商（ROLE_SUPPLIER 行级隔离锚点，design D1/D2）''',
    'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_fin_supplier_statement'
        AND COLUMN_NAME = 'MATCH_RESULT') = 0,
    'ALTER TABLE erp_fin_supplier_statement
       ADD COLUMN MATCH_RESULT LONGTEXT COMMENT ''系统匹配结果 JSON（差异清单，design D11）'',
       ADD COLUMN MATCH_BY VARCHAR(64) DEFAULT NULL,
       ADD COLUMN MATCH_AT DATETIME DEFAULT NULL',
    'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------- 6) 种子：角色 / 门户账号 / 菜单 PERM（design D14） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('role-supplier', 'ROLE_SUPPLIER', '供应商门户', '80', '1', 'seed', '0', 0);

-- 测试门户账号（密码同 Admin@123 线下交付；绑定测试供应商A）
INSERT IGNORE INTO erp_admin_user (ID, USERNAME, PASSWORD, NICK_NAME, STATUS, SUPPLIER_ID, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('user-portal-sup001', 'portal-sup001',
 '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W',
 '测试供应商A门户', '1', 'sup-test-001', 'seed', '0', 0);

INSERT IGNORE INTO erp_admin_user_role (ID, USER_ID, ROLE_ID) VALUES
('ur-portal-sup001', 'user-portal-sup001', 'role-supplier');

UPDATE erp_admin_menu
   SET PERM = 'ROLE_PM,ROLE_ADMIN,ROLE_WAREHOUSE'
 WHERE ID = 'M2-8-2' AND (PERM IS NULL OR PERM = '');
