-- 050-interface-integration.sql
-- 接口对接 2.8.3，change add-interface-integration design D1~D9
-- 1) 15 张 erp_intf_* 新表（前缀登记见 01-architecture-style 1.4 节，design Context）
--    通道与凭证 / 契约与评审 / 沙箱与放行 / 调用审计与限流 / 事件投递 / 报文与映射 / 人工工单 / SLA 指标·告警·月报
-- 2) 种子：role-intf-ops 角色、测试接口运维账号、M2-8-3 PERM 回填
-- 幂等：CREATE IF NOT EXISTS / information_schema+PREPARE / INSERT IGNORE / UPDATE 天然幂等（045~049 范式）

-- ---------- 1) 伙伴与通道（design D1/D2：限流档位、熔断状态机落库） ----------
CREATE TABLE IF NOT EXISTS erp_intf_channel (
    ID VARCHAR(64) NOT NULL,
    PARTNER_CODE VARCHAR(64) NOT NULL COMMENT '伙伴编码（唯一，接口调用方锚点）',
    PARTNER_NAME VARCHAR(128) DEFAULT NULL,
    PARTNER_TIER VARCHAR(16) NOT NULL DEFAULT 'NORMAL'
        COMMENT 'STRATEGIC 战略 / NORMAL 普通 / NEW 新伙伴（RATE_LIMIT_QPS 档位）',
    CHANNEL_TYPE VARCHAR(16) NOT NULL DEFAULT 'API' COMMENT 'API / EDI',
    PROTOCOL VARCHAR(16) NOT NULL DEFAULT 'HTTPS'
        COMMENT 'HTTPS / AS2 / OFTP2 / SFTP（偏差表：仅登记，不真连）',
    CALLBACK_URL VARCHAR(255) DEFAULT NULL,
    CERT_FINGERPRINT VARCHAR(128) DEFAULT NULL COMMENT '证书指纹（台账，不验签）',
    CERT_EXPIRE_DATE DATE DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'SANDBOX'
        COMMENT 'SANDBOX 沙箱 / TRIAL 试运行 / PROD 正式 / DISABLED 停用',
    RATE_TIER VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '当前限流档位（BR-4.9-19 降档后为 LOWEST）',
    LIMIT_PER_MIN INT NOT NULL DEFAULT 100 COMMENT '每分钟限流值（桶容量 = 该值 × 1.5）',
    CIRCUIT_STATE VARCHAR(16) NOT NULL DEFAULT 'CLOSED'
        COMMENT 'CLOSED 正常 / HALF_OPEN 半熔断 / OPEN 熔断（C-5.5-09）',
    CIRCUIT_SINCE DATETIME DEFAULT NULL,
    CIRCUIT_RECOVER_AT DATETIME DEFAULT NULL COMMENT '半开探测起始时间（30 分钟）',
    CIRCUIT_PROBE_OK INT NOT NULL DEFAULT 0 COMMENT '半开探测连续成功笔数（≥10 恢复）',
    PROBE_HITS INT NOT NULL DEFAULT 0 COMMENT '半开期探测尝试序号（每 20 次放行 1 次 ≈5%，C-5.5-09）',
    CIRCUIT_TRIP_COUNT INT NOT NULL DEFAULT 0 COMMENT '24 小时内熔断次数（≥3 升级告警）',
    CIRCUIT_TRIP_DAY DATE DEFAULT NULL,
    DOWNGRADE_AT DATETIME DEFAULT NULL COMMENT '最近一次自动降档时间',
    DOWNGRADE_FROM VARCHAR(16) DEFAULT NULL COMMENT '降档前档位',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_CHANNEL_PARTNER (PARTNER_CODE),
    KEY IDX_INTF_CHANNEL_STATE (STATUS, CIRCUIT_STATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 2) API 凭证（spec api-credential-management） ----------
CREATE TABLE IF NOT EXISTS erp_intf_credential (
    ID VARCHAR(64) NOT NULL,
    CHANNEL_ID VARCHAR(64) NOT NULL,
    PARTNER_CODE VARCHAR(64) NOT NULL,
    API_KEY VARCHAR(64) NOT NULL COMMENT '公开标识，唯一',
    SECRET_HASH VARCHAR(128) NOT NULL COMMENT 'SHA-256 加盐哈希（口令校验，不可逆）',
    SECRET_SALT VARCHAR(64) NOT NULL,
    SIGN_KEY VARCHAR(128) NOT NULL COMMENT 'HMAC-SHA256 报文签名密钥（C-5.5-05 校验需服务端可重算，签发时一次性展示）',
    SCOPE VARCHAR(500) DEFAULT NULL COMMENT '权限范围，逗号分隔（C-5.5-06 出参按 Scope 脱敏）',
    ENV VARCHAR(8) NOT NULL DEFAULT 'SANDBOX' COMMENT 'SANDBOX / PROD（凭证不可跨环境，SOP-5.5-A 步骤4）',
    RATE_TIER VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    LIMIT_PER_MIN INT NOT NULL DEFAULT 100,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        COMMENT 'PENDING / ACTIVE / DEPRECATED / REVOKED / EXPIRED',
    ISSUE_AT DATETIME DEFAULT NULL,
    EXPIRE_AT DATETIME DEFAULT NULL COMMENT '默认 API_KEY_ROTATE_DAYS=90 天',
    REMIND_30 TINYINT(1) NOT NULL DEFAULT 0,
    REMIND_7 TINYINT(1) NOT NULL DEFAULT 0,
    REMIND_1 TINYINT(1) NOT NULL DEFAULT 0,
    GRAY_FROM DATETIME DEFAULT NULL COMMENT '计划内轮换灰度起点（观察 24h）',
    DEPRECATE_UNTIL DATETIME DEFAULT NULL COMMENT 'DEPRECATED 后保留 7 天可回滚',
    OLD_CRED_ID VARCHAR(64) DEFAULT NULL COMMENT '轮换时指向被替换的旧凭证',
    PENDING_SECRET VARCHAR(128) DEFAULT NULL COMMENT '签发时临时留存的明文口令，首次下载/确认后即清空（SOP-5.5-B 步骤2）',
    DOWNLOAD_TOKEN VARCHAR(64) DEFAULT NULL COMMENT '一次性分发链接令牌（10 分钟有效）',
    DOWNLOAD_TOKEN_AT DATETIME DEFAULT NULL,
    DOWNLOAD_AT DATETIME DEFAULT NULL,
    DOWNLOAD_IP VARCHAR(64) DEFAULT NULL,
    DOWNLOAD_UA VARCHAR(255) DEFAULT NULL,
    ACK_AT DATETIME DEFAULT NULL COMMENT '调用方门户「已接收」确认时间',
    ISSUED_BY VARCHAR(64) DEFAULT NULL,
    REVOKE_BY VARCHAR(64) DEFAULT NULL,
    REVOKE_AT DATETIME DEFAULT NULL,
    REVOKE_REASON VARCHAR(500) DEFAULT NULL,
    LAST_USED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_CRED_KEY (API_KEY),
    KEY IDX_INTF_CRED_PARTNER (PARTNER_CODE, STATUS),
    KEY IDX_INTF_CRED_CHANNEL (CHANNEL_ID, STATUS),
    KEY IDX_INTF_CRED_EXPIRE (EXPIRE_AT, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 3) 接口契约（spec interface-onboarding 6.1/6.2） ----------
CREATE TABLE IF NOT EXISTS erp_intf_contract (
    ID VARCHAR(64) NOT NULL,
    CONTRACT_NO VARCHAR(32) NOT NULL COMMENT 'IC+yyyyMMdd+000001',
    NAME VARCHAR(128) NOT NULL,
    PARTNER_CODE VARCHAR(64) DEFAULT NULL COMMENT '伙伴级契约可空（平台级）',
    PROTOCOL VARCHAR(16) NOT NULL DEFAULT 'REST',
    MSG_STANDARD VARCHAR(32) DEFAULT NULL COMMENT 'OpenAPI 3.0 / EDI JSON Schema',
    ENDPOINT_PATH VARCHAR(128) DEFAULT NULL,
    FIELDS_JSON LONGTEXT COMMENT '字段清单：必填/类型/长度/值域',
    ERROR_CODES VARCHAR(500) DEFAULT NULL,
    RATE_TIER VARCHAR(16) DEFAULT NULL,
    IDEMPOTENCY_RULE VARCHAR(255) DEFAULT NULL COMMENT '幂等键规则（契约固化，BR-4.9-01/7.1.3）',
    DESENSITIZE_RULE LONGTEXT COMMENT '出参脱敏规则（C-5.5-11 未声明不得发布）',
    VERSION VARCHAR(16) NOT NULL DEFAULT 'v1.0.0' COMMENT '语义化版本',
    MAJOR_VERSION INT NOT NULL DEFAULT 1,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
        COMMENT 'DRAFT / REVIEWING / PUBLISHED / DEPRECATED',
    COMPAT_LEVEL VARCHAR(16) DEFAULT NULL COMMENT '兼容 / 不兼容（BR-5.5-12）',
    PREV_VERSION VARCHAR(16) DEFAULT NULL,
    KEEP_UNTIL DATE DEFAULT NULL COMMENT '不兼容变更旧版本保留 ≥180 天',
    SUNSET_AT DATE DEFAULT NULL COMMENT '废弃日（API_SUNSET_NOTICE_DAYS=30 倒计时）',
    REVIEW_DUE_AT DATETIME DEFAULT NULL COMMENT '评审截止（登记后 3 个工作日）',
    REJECT_COUNT INT NOT NULL DEFAULT 0,
    CLOSE_REASON VARCHAR(500) DEFAULT NULL,
    PUBLISH_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_CONTRACT_NO (CONTRACT_NO),
    KEY IDX_INTF_CONTRACT_STATUS (STATUS, PARTNER_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 4) 契约评审记录 ----------
CREATE TABLE IF NOT EXISTS erp_intf_contract_review (
    ID VARCHAR(64) NOT NULL,
    CONTRACT_ID VARCHAR(64) NOT NULL,
    REVIEWER VARCHAR(64) NOT NULL,
    RESULT VARCHAR(16) NOT NULL COMMENT 'PASS / REJECT',
    OPINION VARCHAR(1000) NOT NULL COMMENT '审核意见（不可留空，SOP-5.5-A 步骤2）',
    DUE_AT DATETIME DEFAULT NULL,
    REMIND_AT DATETIME DEFAULT NULL COMMENT '超 3 工作日催办时间',
    REVIEW_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_INTF_REVIEW_CONTRACT (CONTRACT_ID, REVIEW_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 5) 沙箱联调用例 ----------
CREATE TABLE IF NOT EXISTS erp_intf_sandbox_case (
    ID VARCHAR(64) NOT NULL,
    CONTRACT_ID VARCHAR(64) DEFAULT NULL,
    PARTNER_CODE VARCHAR(64) NOT NULL,
    CASE_NO VARCHAR(32) NOT NULL,
    CASE_TYPE VARCHAR(16) NOT NULL DEFAULT 'POSITIVE' COMMENT 'POSITIVE / BORDER / EXCEPTION',
    FIELD_PATH VARCHAR(128) DEFAULT NULL COMMENT '覆盖的契约字段或错误码',
    EXPECT VARCHAR(500) DEFAULT NULL,
    ACTUAL VARCHAR(1000) DEFAULT NULL,
    RESULT VARCHAR(8) NOT NULL DEFAULT 'PASS' COMMENT 'PASS / FAIL',
    ERROR_LOC VARCHAR(128) DEFAULT NULL COMMENT '行/段/字段定位',
    RUN_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_CASE_NO (PARTNER_CODE, CASE_NO),
    KEY IDX_INTF_CASE_CONTRACT (CONTRACT_ID, RESULT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 6) 生产放行单与观察期（SOP-5.5-A 步骤 7/8） ----------
CREATE TABLE IF NOT EXISTS erp_intf_release (
    ID VARCHAR(64) NOT NULL,
    RELEASE_NO VARCHAR(32) NOT NULL,
    CONTRACT_ID VARCHAR(64) DEFAULT NULL,
    PARTNER_CODE VARCHAR(64) NOT NULL,
    CHANNEL_ID VARCHAR(64) DEFAULT NULL,
    PASS_RATE DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT '沙箱联调通过率（<100 阻断 C-5.5-07）',
    SECURITY_NOTE VARCHAR(1000) DEFAULT NULL COMMENT '安全评估结论登记（偏差表：不接外部扫描）',
    RECEIPT_SAMPLE VARCHAR(1000) DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        COMMENT 'PENDING 待复核 / REJECTED 驳回 / APPROVED 已放行 / TRIAL 试运行 / FORMAL 正式运行 / ARCHIVED 已归档',
    INITIATED_BY VARCHAR(64) NOT NULL,
    INITIATED_AT DATETIME DEFAULT NULL,
    REVIEWED_BY VARCHAR(64) DEFAULT NULL COMMENT '复核人（MUST NOT = 发起人，C-0-03）',
    REVIEWED_AT DATETIME DEFAULT NULL,
    REVIEW_DUE_AT DATETIME DEFAULT NULL COMMENT '超 2 个工作日升级（SOP-5.5-A 步骤7）',
    PROD_KEY_ID VARCHAR(64) DEFAULT NULL COMMENT '放行后签发的生产凭证',
    TRIAL_START DATE DEFAULT NULL,
    TRIAL_END DATE DEFAULT NULL,
    TRIAL_ERR_RATE DECIMAL(6,2) DEFAULT NULL,
    TRIAL_LIMIT_HITS INT NOT NULL DEFAULT 0,
    ARCHIVE_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_RELEASE_NO (RELEASE_NO),
    KEY IDX_INTF_RELEASE_PARTNER (PARTNER_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 7) 调用审计日志（BR-4.9-21，fail-closed 写失败即 503） ----------
CREATE TABLE IF NOT EXISTS erp_intf_call_log (
    ID VARCHAR(64) NOT NULL,
    CALLER VARCHAR(64) NOT NULL COMMENT 'API_KEY 或伙伴编码',
    PARTNER_CODE VARCHAR(64) DEFAULT NULL,
    API_PATH VARCHAR(255) NOT NULL,
    HTTP_METHOD VARCHAR(8) DEFAULT NULL,
    REQ_ID VARCHAR(64) NOT NULL COMMENT 'X-Request-Id 全链路追踪',
    RESP_CODE INT NOT NULL DEFAULT 200,
    ERR_CODE VARCHAR(64) DEFAULT NULL,
    COST_MS INT NOT NULL DEFAULT 0,
    PARAM_SUMMARY VARCHAR(1000) DEFAULT NULL COMMENT '参数摘要（敏感字段脱敏后写入）',
    RATE_HIT TINYINT(1) NOT NULL DEFAULT 0 COMMENT '本次是否触发限流',
    CIRCUIT_HIT TINYINT(1) NOT NULL DEFAULT 0,
    ENV VARCHAR(8) DEFAULT NULL,
    IP VARCHAR(64) DEFAULT NULL,
    USER_AGENT VARCHAR(255) DEFAULT NULL,
    CALL_AT DATETIME NOT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_INTF_CALL_CALLER (CALLER, CALL_AT),
    KEY IDX_INTF_CALL_CODE (RESP_CODE, CALL_AT),
    KEY IDX_INTF_CALL_REQ (REQ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 8) 令牌桶限流窗口状态（design D2：DB 计数，可断言可跨重启） ----------
CREATE TABLE IF NOT EXISTS erp_intf_rate_state (
    ID VARCHAR(64) NOT NULL,
    CALLER VARCHAR(64) NOT NULL,
    WINDOW_MIN VARCHAR(12) NOT NULL COMMENT 'yyyyMMddHHmm 统计窗口（1 分钟）',
    HIT_COUNT INT NOT NULL DEFAULT 0,
    LIMIT_PER_MIN INT NOT NULL DEFAULT 100,
    BUCKET_CAPACITY INT NOT NULL DEFAULT 150 COMMENT '桶容量 = 限值 × 1.5',
    OVER_COUNT INT NOT NULL DEFAULT 0 COMMENT '本窗口内 429 次数（BR-5.5-06 降档判定）',
    LAST_OVER_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_RATE_WINDOW (CALLER, WINDOW_MIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 9) 事件投递台账（spec interface-event-delivery） ----------
CREATE TABLE IF NOT EXISTS erp_intf_delivery (
    ID VARCHAR(64) NOT NULL,
    EVENT_ID VARCHAR(64) NOT NULL COMMENT 'erp_ops_outbox.EVENT_ID',
    EVENT_TYPE VARCHAR(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL COMMENT '重放 MUST 复用原键（C-4.9-04）',
    BIZ_CODE VARCHAR(128) DEFAULT NULL,
    PARTNER_CODE VARCHAR(64) DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        COMMENT 'PENDING / DELIVERING / DELIVERED / RETRYING / DEAD / STAGED 暂存',
    RETRY_COUNT INT NOT NULL DEFAULT 0,
    NEXT_AT DATETIME DEFAULT NULL COMMENT '下次投递时间（指数退避）',
    LAST_AT DATETIME DEFAULT NULL,
    ACK_AT DATETIME DEFAULT NULL,
    COST_MS INT NOT NULL DEFAULT 0,
    FAIL_REASON VARCHAR(1000) DEFAULT NULL,
    REPLAY_COUNT INT NOT NULL DEFAULT 0,
    REPLAY_BY VARCHAR(64) DEFAULT NULL,
    TICKET_ID VARCHAR(64) DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_DELIVERY_EVENT (EVENT_ID),
    KEY IDX_INTF_DELIVERY_STATUS (STATUS, NEXT_AT),
    KEY IDX_INTF_DELIVERY_TYPE (EVENT_TYPE, CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 10) EDI 报文台账（spec edi-message-processing） ----------
CREATE TABLE IF NOT EXISTS erp_intf_message (
    ID VARCHAR(64) NOT NULL,
    MSG_NO VARCHAR(32) NOT NULL COMMENT 'IM+yyyyMMdd+000001',
    PARTNER_CODE VARCHAR(64) NOT NULL,
    MSG_TYPE VARCHAR(16) NOT NULL COMMENT 'ORDERS / DESADV / INVOIC',
    MSG_VERSION VARCHAR(16) DEFAULT NULL COMMENT '报文声明版本（与契约不一致即阻断）',
    IDEMPOTENCY_KEY VARCHAR(128) NOT NULL COMMENT '调用方+类型+业务单号+版本',
    RAW_PAYLOAD LONGTEXT COMMENT '原始报文文本（保留 ≥ AUDIT_RETENTION_DAYS）',
    PAYLOAD_HASH VARCHAR(64) DEFAULT NULL COMMENT '同键异载荷 → 409（BR-4.9-26 变体）',
    SOURCE VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN 开放入口 / UPLOAD 上传 / SIMULATE 模拟推送',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'RECEIVED'
        COMMENT 'RECEIVED / REJECTED / PROCESSED / PARTIAL / FAILED / MANUAL 待人工',
    SYNTAX_RESULT LONGTEXT COMMENT '语法层校验结果（行+段+字段定位）',
    MAP_RESULT LONGTEXT COMMENT '映射层结果（原始值可回溯）',
    BIZ_RESULT LONGTEXT COMMENT '业务层结果（violated_rule 等）',
    BIZ_TYPE VARCHAR(16) DEFAULT NULL COMMENT 'PO / ASN / INVOICE',
    BIZ_NO VARCHAR(64) DEFAULT NULL COMMENT '生成的业务单号',
    LINE_TOTAL INT NOT NULL DEFAULT 0,
    LINE_OK INT NOT NULL DEFAULT 0,
    LINE_FAIL INT NOT NULL DEFAULT 0,
    RETRY_COUNT INT NOT NULL DEFAULT 0 COMMENT '语法重发次数（≤ API_RETRY_MAX）',
    RECEIVED_AT DATETIME NOT NULL,
    FINISHED_AT DATETIME DEFAULT NULL,
    RECEIPT_SENT TINYINT(1) NOT NULL DEFAULT 0,
    RECEIPT_SENT_AT DATETIME DEFAULT NULL,
    TICKET_ID VARCHAR(64) DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_MSG_NO (MSG_NO),
    UNIQUE KEY UK_INTF_MSG_IDEM (IDEMPOTENCY_KEY),
    KEY IDX_INTF_MSG_PARTNER (PARTNER_CODE, MSG_TYPE, RECEIVED_AT),
    KEY IDX_INTF_MSG_STATUS (STATUS, RECEIVED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 11) EDI-ERP 字段映射规则（BR-4.9-25 缺失即 L1 阻断） ----------
CREATE TABLE IF NOT EXISTS erp_intf_edimap (
    ID VARCHAR(64) NOT NULL,
    PARTNER_CODE VARCHAR(64) NOT NULL,
    MSG_TYPE VARCHAR(16) NOT NULL,
    RULE_JSON LONGTEXT NOT NULL COMMENT '字段路径、代码表、日期与单位转换、时区归一',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED / DISABLED',
    VERSION VARCHAR(16) NOT NULL DEFAULT 'v1',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_EDIMAP (PARTNER_CODE, MSG_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 12) 人工处理工单（C-4.9-02：死信 / 报文待人工 / 版本不兼容共用） ----------
CREATE TABLE IF NOT EXISTS erp_intf_ticket (
    ID VARCHAR(64) NOT NULL,
    TICKET_NO VARCHAR(32) NOT NULL COMMENT 'IT+yyyyMMdd+000001',
    SOURCE VARCHAR(16) NOT NULL COMMENT 'EVENT_DEAD 事件死信 / EDI_MANUAL 报文待人工 / CONFLICT 幂等冲突 / VERSION 版本不兼容',
    REF_ID VARCHAR(64) DEFAULT NULL COMMENT '投递 ID / 报文 ID / 契约 ID',
    PARTNER_CODE VARCHAR(64) DEFAULT NULL,
    IDEMPOTENCY_KEY VARCHAR(128) DEFAULT NULL COMMENT '重放必须保留（C-4.9-04）',
    TITLE VARCHAR(200) NOT NULL,
    ERROR_LOC VARCHAR(500) DEFAULT NULL COMMENT '错误位置清单（行+段+字段）',
    DETAIL LONGTEXT,
    PRIORITY VARCHAR(8) NOT NULL DEFAULT 'P2',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / PROCESSING / DONE / CLOSED',
    ASSIGN_TO VARCHAR(64) DEFAULT NULL COMMENT '分派接口运维工程师',
    DUE_AT DATETIME DEFAULT NULL COMMENT '1 个工作日处置时限',
    HANDLED_BY VARCHAR(64) DEFAULT NULL,
    HANDLED_AT DATETIME DEFAULT NULL,
    HANDLER_NOTE VARCHAR(1000) DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_TICKET_NO (TICKET_NO),
    KEY IDX_INTF_TICKET_STATUS (STATUS, DUE_AT),
    KEY IDX_INTF_TICKET_REF (SOURCE, REF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 13) SLA 指标（spec interface-sla-monitoring 7.1/7.2） ----------
CREATE TABLE IF NOT EXISTS erp_intf_sla_metric (
    ID VARCHAR(64) NOT NULL,
    METRIC_KEY VARCHAR(32) NOT NULL COMMENT 'AVAILABILITY / P95 / ERROR_RATE / E2E_DELAY / EDI时效',
    PARTNER_CODE VARCHAR(64) DEFAULT NULL,
    API_DOMAIN VARCHAR(64) DEFAULT NULL,
    WINDOW_START DATETIME NOT NULL,
    WINDOW_END DATETIME NOT NULL,
    METRIC_VALUE DECIMAL(18,4) DEFAULT NULL,
    UNIT VARCHAR(16) DEFAULT NULL,
    TARGET_VALUE DECIMAL(18,4) DEFAULT NULL,
    LEVEL VARCHAR(16) NOT NULL DEFAULT 'OK' COMMENT 'OK / WARNING / CRITICAL / EMERGENCY / DATA_MISSING',
    DATA_STATUS VARCHAR(16) NOT NULL DEFAULT 'OK' COMMENT 'OK / MISSING（BR-4.9-30 禁止填 0）',
    SAMPLE_COUNT INT NOT NULL DEFAULT 0,
    MONTH_TAG VARCHAR(6) DEFAULT NULL COMMENT 'yyyyMM（月报口径）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_INTF_METRIC_KEY (METRIC_KEY, WINDOW_START),
    KEY IDX_INTF_METRIC_MONTH (MONTH_TAG, METRIC_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 14) SLA 告警与升级（BR-4.9-27/28：5 分钟聚合去重 + 连续 Critical 升级） ----------
CREATE TABLE IF NOT EXISTS erp_intf_sla_alert (
    ID VARCHAR(64) NOT NULL,
    ALERT_KEY VARCHAR(128) NOT NULL COMMENT '指标 + 伙伴（同键 5 分钟窗口唯一）',
    ALERT_WINDOW DATETIME NOT NULL COMMENT '5 分钟聚合窗口起点',
    METRIC_KEY VARCHAR(32) NOT NULL,
    PARTNER_CODE VARCHAR(64) DEFAULT NULL,
    LEVEL VARCHAR(16) NOT NULL COMMENT 'WARNING / CRITICAL / EMERGENCY',
    ACTUAL_VALUE DECIMAL(18,4) DEFAULT NULL,
    THRESHOLD_VALUE DECIMAL(18,4) DEFAULT NULL,
    MESSAGE VARCHAR(500) DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / ACK / RESOLVED',
    CRIT_COUNT INT NOT NULL DEFAULT 0 COMMENT '连续 Critical 次数（≥3 升级）',
    ESCALATION_LEVEL INT NOT NULL DEFAULT 1 COMMENT '1 接口运维 / 2 运维主管 / 3 供应链协同管理员',
    ESCALATED_TO VARCHAR(64) DEFAULT NULL,
    RESPONSE_DUE_AT DATETIME DEFAULT NULL COMMENT 'ESCALATION_RESPONSE_MIN=30 分钟响应截止',
    RESPONDED_BY VARCHAR(64) DEFAULT NULL,
    RESPONDED_AT DATETIME DEFAULT NULL,
    ALERT_AT DATETIME NOT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_ALERT_WINDOW (ALERT_KEY, ALERT_WINDOW),
    KEY IDX_INTF_ALERT_STATUS (STATUS, ALERT_AT),
    KEY IDX_INTF_ALERT_ESC (ESCALATION_LEVEL, RESPONSE_DUE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 15) 月度 SLA 报告（SOP-5.5-D：生成→审核→归档→发布） ----------
CREATE TABLE IF NOT EXISTS erp_intf_sla_report (
    ID VARCHAR(64) NOT NULL,
    MONTH_TAG VARCHAR(6) NOT NULL COMMENT 'yyyyMM',
    TITLE VARCHAR(200) NOT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'GENERATED'
        COMMENT 'GENERATED / REVIEWED / ARCHIVED / PUBLISHED',
    VERSION VARCHAR(16) NOT NULL DEFAULT 'v1' COMMENT '归档后修订须升版本',
    METRICS_JSON LONGTEXT COMMENT '指标达成总览',
    UNREACHED_JSON LONGTEXT COMMENT '未达标子项清单 + 根因归类 + 改进措施',
    GENERATED_BY VARCHAR(64) DEFAULT NULL COMMENT '生成作业执行人',
    GENERATED_AT DATETIME DEFAULT NULL,
    REVIEWED_BY VARCHAR(64) DEFAULT NULL COMMENT '审核人 MUST NOT = 生成执行人',
    REVIEWED_AT DATETIME DEFAULT NULL,
    REVIEW_OPINION VARCHAR(1000) DEFAULT NULL COMMENT '不可留空',
    ARCHIVED_BY VARCHAR(64) DEFAULT NULL,
    ARCHIVED_AT DATETIME DEFAULT NULL,
    PUBLISH_AT DATETIME DEFAULT NULL,
    PUBLISH_SCOPE VARCHAR(500) DEFAULT NULL COMMENT '按合作方分级发布范围',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INTF_REPORT_MONTH (MONTH_TAG, VERSION),
    KEY IDX_INTF_REPORT_STATUS (STATUS, MONTH_TAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------- 16) 种子：角色 / 测试账号 / 菜单 PERM（design D5） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('role-intf-ops', 'ROLE_INTF_OPS', '接口运维工程师', '85', '1', 'seed', '0', 0);

-- 测试接口运维账号（密码同 Admin@123）
INSERT IGNORE INTO erp_admin_user (ID, USERNAME, PASSWORD, NICK_NAME, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('user-intf-ops01', 'intf-ops01',
 '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W',
 '测试接口运维', '1', 'seed', '0', 0);

INSERT IGNORE INTO erp_admin_user_role (ID, USER_ID, ROLE_ID) VALUES
('ur-intf-ops01', 'user-intf-ops01', 'role-intf-ops');

-- M2-8-3 PERM 回填（099 生成的 PERM 为空；INSERT IGNORE 重新生成不会覆盖已回填值）
UPDATE erp_admin_menu
   SET PERM = 'ROLE_INTF_OPS,ROLE_ADMIN'
 WHERE ID = 'M2-8-3' AND (PERM IS NULL OR PERM = '');

-- ---------- 17) 演示伙伴通道与凭证（开放入口联调/测试用，SOP-5.5-A 步骤4 沙箱与生产分离） ----------
INSERT IGNORE INTO erp_intf_channel
(ID, PARTNER_CODE, PARTNER_NAME, PARTNER_TIER, CHANNEL_TYPE, PROTOCOL, STATUS, RATE_TIER, LIMIT_PER_MIN,
 CIRCUIT_STATE, CIRCUIT_PROBE_OK, PROBE_HITS, CIRCUIT_TRIP_COUNT, CREATE_BY, DEL_FLAG, VER_NO)
VALUES
('ifch-demo-001', 'INTF-DEMO', '演示集成伙伴', 'NORMAL', 'API', 'HTTPS', 'PROD', 'NORMAL', 100,
 'CLOSED', 0, 0, 0, 'seed', '0', 0);

-- 生产凭证：API Key=ik-demo-0001，Secret=Admin@123（SHA-256 加盐），签名密钥 sign-demo-0001
INSERT IGNORE INTO erp_intf_credential
(ID, CHANNEL_ID, PARTNER_CODE, API_KEY, SECRET_HASH, SECRET_SALT, SIGN_KEY, SCOPE, ENV,
 RATE_TIER, LIMIT_PER_MIN, STATUS, ISSUE_AT, EXPIRE_AT, CREATE_BY, DEL_FLAG, VER_NO)
VALUES
('ifcr-demo-prod-01', 'ifch-demo-001', 'INTF-DEMO', 'ik-demo-0001',
 '9625a6c207ba950ac83bbd856c466408c021a28e296a970ece60f1fe2244742e',
 'a1b2c3d4e5f60718', 'sign-demo-0001', 'EDI_WRITE,PO_READ,SLA_READ', 'PROD',
 'NORMAL', 100, 'ACTIVE', NOW(), DATE_ADD(NOW(), INTERVAL 90 DAY), 'seed', '0', 0);

-- 沙箱凭证：同伙伴，ENV=SANDBOX（跨环境调用必 401，spec SOP-5.5-A 步骤4）
INSERT IGNORE INTO erp_intf_credential
(ID, CHANNEL_ID, PARTNER_CODE, API_KEY, SECRET_HASH, SECRET_SALT, SIGN_KEY, SCOPE, ENV,
 RATE_TIER, LIMIT_PER_MIN, STATUS, ISSUE_AT, EXPIRE_AT, CREATE_BY, DEL_FLAG, VER_NO)
VALUES
('ifcr-demo-sbox-01', 'ifch-demo-001', 'INTF-DEMO', 'ik-demo-sandbox-01',
 '9625a6c207ba950ac83bbd856c466408c021a28e296a970ece60f1fe2244742e',
 'a1b2c3d4e5f60718', 'sign-demo-sandbox-01', 'EDI_WRITE', 'SANDBOX',
 'NEW', 30, 'ACTIVE', NOW(), DATE_ADD(NOW(), INTERVAL 90 DAY), 'seed', '0', 0);

-- ---------- 18) 采购订单增列：EDI 第四入口溯源（spec purchase-order ADDED） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_proc_po'
        AND COLUMN_NAME = 'EDI_MSG_NO') = 0,
    'ALTER TABLE erp_proc_po
       ADD COLUMN EDI_MSG_NO VARCHAR(64) DEFAULT NULL COMMENT ''EDI 报文来源编号（第四入口溯源）'',
       ADD COLUMN EDI_IDEM_KEY VARCHAR(128) DEFAULT NULL COMMENT ''来源报文幂等键''',
    'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
