-- 051-procurement-analysis.sql
-- 采购分析 2.9.1/2.9.2/2.9.3，change add-procurement-analysis design D1~D10
-- 1) 10 张新表：erp_bi_ 6（口径字典/抽取任务/权限规则/导出审计/成本快照/价格异动）
--                erp_scm_ 4（记分卡模型/结果/整改/申诉）
-- 2) 种子：M2-9-1/2/3 PERM 回填（与 generate-menu-seed.cjs EXTRA_PERM 同口径）
-- 参数（PRICE_TREND_ALERT_PCT 等）进 application.yml app.bi.* / app.scorecard.*（design D9）
-- 幂等：CREATE IF NOT EXISTS / UPDATE 天然幂等 / INSERT IGNORE（045~050 范式）
-- 前缀登记：erp_bi_、erp_scm_ 已在 01-architecture-style.md 1.4 节（无需新增）

-- ---------- 1) 指标口径字典（design D4，七要素 + 行级版本单表） ----------
CREATE TABLE IF NOT EXISTS erp_bi_metric_dict (
    ID VARCHAR(64) NOT NULL,
    METRIC_KEY VARCHAR(64) NOT NULL COMMENT '指标唯一键（如 COST_PO_AMT）',
    NAME VARCHAR(128) NOT NULL COMMENT '指标名称',
    DEFINITION TEXT COMMENT '业务定义',
    FORMULA TEXT NOT NULL COMMENT '计算公式（JSON 结构化，diff 校验对象）',
    DATA_PRECISION INT NOT NULL DEFAULT 2 COMMENT '数据精度（小数位）',
    TIME_DIM VARCHAR(32) NOT NULL DEFAULT 'MONTH' COMMENT '时间维度 DAY/MONTH/QUARTER/YEAR',
    FILTER_COND VARCHAR(500) DEFAULT NULL COMMENT '过滤条件（JSON）',
    SRC_MAPPING TEXT COMMENT '来源字段映射（JSON：表.列 → 公式变量）',
    VERSION INT NOT NULL DEFAULT 1 COMMENT '版本号（同 METRIC_KEY 递增，行级历史）',
    IS_CURRENT TINYINT(1) NOT NULL DEFAULT 1 COMMENT '当前生效版本（历史行=0，design D4 回溯）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
        COMMENT 'DRAFT 草稿 / PUBLISHED 已发布 / PENDING_UPDATE 待更新',
    USED_BY TEXT COMMENT '引用方清单（JSON：能力标识列表，反向扫描对象）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_bi_dict_key_ver (METRIC_KEY, VERSION),
    KEY idx_bi_dict_status (STATUS, IS_CURRENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='指标口径字典（C-4.10-01 唯一权威，行级版本）';

-- ---------- 2) 抽取任务与批次（design D9，DAG + 水位 + READY） ----------
CREATE TABLE IF NOT EXISTS erp_bi_extract_task (
    ID VARCHAR(64) NOT NULL,
    BATCH_NO VARCHAR(32) NOT NULL COMMENT '批次号 yyyyMMdd-SEQ',
    BATCH_DATE DATE NOT NULL,
    TASK_TYPE VARCHAR(24) NOT NULL COMMENT 'PO / GR / AP / COST_SNAPSHOT / PRICE_ALERT / COST_SAVE',
    SEQ INT NOT NULL DEFAULT 10 COMMENT 'DAG 层序（同批次内上游 SEQ 小）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING'
        COMMENT 'PENDING / RUNNING / READY / PAUSED 波动暂停 / FAILED / SKIPPED',
    ROW_COUNT BIGINT NOT NULL DEFAULT 0,
    PREV_ROW_COUNT BIGINT DEFAULT NULL COMMENT '前一日行数（波动判定对照）',
    WATERMARK VARCHAR(64) DEFAULT NULL COMMENT '增量水位（最后处理位置，断点续抽）',
    RETRY INT NOT NULL DEFAULT 0,
    ERROR_MSG VARCHAR(500) DEFAULT NULL,
    MANUAL_CONFIRM TINYINT(1) NOT NULL DEFAULT 0 COMMENT '波动暂停后人工确认标记',
    FINISHED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_bi_extract_type (BATCH_DATE, TASK_TYPE),
    KEY idx_bi_extract_status (STATUS, SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='BI 抽取任务批次（依赖驱动 + 时间窗口）';

-- ---------- 3) 行列权限规则（design D6，查询层显式注入） ----------
CREATE TABLE IF NOT EXISTS erp_bi_perm_rule (
    ID VARCHAR(64) NOT NULL,
    RULE_TYPE VARCHAR(16) NOT NULL COMMENT 'ROW_LE 法人主体行级 / COL_MASK 列掩码 / COL_SENSITIVE 敏感登记',
    TARGET_KEY VARCHAR(128) NOT NULL COMMENT '对象（字段名 / 通配 *）',
    USER_NAME VARCHAR(64) DEFAULT NULL COMMENT '行级绑定用户（ROW_LE 必填）',
    ENTITY_ID VARCHAR(64) DEFAULT NULL COMMENT '允许访问的法人主体（ROW_LE）',
    ROLE_CODE VARCHAR(64) DEFAULT NULL COMMENT '适用角色（COL_* 时）',
    ACTION VARCHAR(16) NOT NULL DEFAULT 'PASS' COMMENT 'PASS / MASK / DENY',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY idx_bi_perm_type (RULE_TYPE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分析查询行列权限规则（C-4.10-02 执行依据）';

-- ---------- 4) 后台导出与查询审计一体（design D6：审计并入本表） ----------
CREATE TABLE IF NOT EXISTS erp_bi_export_task (
    ID VARCHAR(64) NOT NULL,
    TASK_TYPE VARCHAR(16) NOT NULL COMMENT 'QUERY 查询审计 / EXPORT 后台导出',
    TASK_NO VARCHAR(32) DEFAULT NULL COMMENT '导出任务号（QUERY 为空）',
    API_PATH VARCHAR(255) DEFAULT NULL,
    PARAMS_JSON TEXT COMMENT '参数摘要 / 过滤条件',
    MASK_COLS VARCHAR(500) DEFAULT NULL COMMENT '本次命中的掩码字段列表',
    USER_NAME VARCHAR(64) DEFAULT NULL,
    ROW_COUNT BIGINT DEFAULT NULL COMMENT '结果行数（导出完成后回填）',
    EST_ROWS BIGINT DEFAULT NULL COMMENT '预估行数（>EXPORT_ROW_LIMIT 转审批依据）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DONE'
        COMMENT 'QUERY 恒 DONE；EXPORT：QUEUED / RUNNING / DONE / FAILED / REJECTED',
    APPROVAL_STATUS VARCHAR(16) DEFAULT NULL COMMENT '超量审批 PENDING / APPROVED / REJECTED（C-4.10-05）',
    FILE_PATH VARCHAR(255) DEFAULT NULL,
    WATERMARK VARCHAR(128) DEFAULT NULL COMMENT '用户名+时间戳+唯一流水号水印',
    REQ_ID VARCHAR(64) DEFAULT NULL COMMENT '请求标识（全链路）',
    NOTIFY TINYINT(1) NOT NULL DEFAULT 0 COMMENT '站内通知已发标记',
    EXPIRE_AT DATETIME DEFAULT NULL COMMENT '文件保留 7 天',
    ERROR_MSG VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY idx_bi_export_type (TASK_TYPE, CREATE_DATE),
    KEY idx_bi_export_user (USER_NAME, CREATE_DATE),
    KEY idx_bi_export_status (STATUS, TASK_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台导出任务与查询审计（≥365 天，design D6 合表）';

-- ---------- 5) 成本快照（design D2：单快照行双金额列） ----------
CREATE TABLE IF NOT EXISTS erp_bi_cost_snapshot (
    ID VARCHAR(64) NOT NULL,
    BATCH_NO VARCHAR(32) DEFAULT NULL COMMENT '生成批次（READY 前置）',
    MONTH_TAG CHAR(6) NOT NULL COMMENT 'yyyyMM 归属月',
    LEGAL_ENTITY_ID VARCHAR(64) NOT NULL DEFAULT 'LE-DEFAULT',
    CATEGORY_CODE VARCHAR(64) DEFAULT NULL COMMENT '品类（趋势同品类分位用）',
    ITEM_CODE VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    BUYER VARCHAR(64) DEFAULT NULL COMMENT '采购员（降本三维之一）',
    PO_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    PO_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'PO 承诺成本（含税）',
    PO_AMT_NO_TAX DECIMAL(18,2) NOT NULL DEFAULT 0,
    TAX_AMT DECIMAL(18,2) NOT NULL DEFAULT 0,
    FREIGHT_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '运费单列',
    RETURN_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '退货红字冲减（正数表示扣减）',
    INV_QTY DECIMAL(18,4) DEFAULT NULL,
    INV_AMT DECIMAL(18,2) DEFAULT NULL COMMENT '发票实付（含税）；NULL=未开票',
    INV_AMT_NO_TAX DECIMAL(18,2) DEFAULT NULL,
    INV_TAX DECIMAL(18,2) DEFAULT NULL,
    DIFF_AMT DECIMAL(18,2) DEFAULT NULL COMMENT '差异 = INV_AMT - PO_AMT',
    ESTIMATING TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1=暂估中（发票口径为空不冒充实付）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_bi_snap_dim (MONTH_TAG, LEGAL_ENTITY_ID, ITEM_CODE, SUPPLIER_ID),
    KEY idx_bi_snap_item (ITEM_CODE, MONTH_TAG),
    KEY idx_bi_snap_supp (SUPPLIER_ID, MONTH_TAG),
    KEY idx_bi_snap_buyer (BUYER, MONTH_TAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购成本日聚合快照（双口径并列，design D2）';

-- ---------- 6) 价格异动台账（spec procurement-cost-analysis 幂等 + 状态机） ----------
CREATE TABLE IF NOT EXISTS erp_bi_price_alert (
    ID VARCHAR(64) NOT NULL,
    ALERT_NO VARCHAR(32) NOT NULL COMMENT 'PA+yyyyMMdd+000001',
    MONTH_TAG CHAR(6) NOT NULL COMMENT '判定归属月',
    ITEM_CODE VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) DEFAULT NULL COMMENT '物料级趋势可跨供应商',
    CATEGORY_CODE VARCHAR(64) DEFAULT NULL,
    ALERT_TYPE VARCHAR(24) NOT NULL DEFAULT 'TREND_SPIKE' COMMENT 'TREND_SPIKE 环比超阈',
    PCT DECIMAL(8,2) NOT NULL COMMENT '实际环比（%）',
    THRESHOLD_PCT DECIMAL(8,2) NOT NULL COMMENT '判定时阈值（留痕）',
    PREV_PRICE DECIMAL(18,4) DEFAULT NULL,
    CURR_PRICE DECIMAL(18,4) DEFAULT NULL,
    SOURCE VARCHAR(16) NOT NULL DEFAULT 'EXTRACT' COMMENT 'EXTRACT 每日抽取 / MANUAL 实时补算',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / HANDLED / IGNORED',
    HANDLE_BY VARCHAR(64) DEFAULT NULL,
    HANDLE_AT DATETIME DEFAULT NULL,
    HANDLE_NOTE VARCHAR(500) DEFAULT NULL COMMENT '处置备注（不可篡改）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_bi_alert_key (MONTH_TAG, ITEM_CODE),
    KEY idx_bi_alert_status (STATUS, MONTH_TAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='价格异动清单（物料+月份唯一幂等，处置状态机）';

-- ---------- 7) 记分卡模型（4.9 FR-4.9-7-1：权重/阈值/品类差异化/版本） ----------
CREATE TABLE IF NOT EXISTS erp_scm_scorecard_model (
    ID VARCHAR(64) NOT NULL,
    MODEL_CODE VARCHAR(32) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    CATEGORY_CODE VARCHAR(64) DEFAULT NULL COMMENT '品类（NULL=通用默认模型）',
    W_QUALITY DECIMAL(5,2) NOT NULL DEFAULT 30.00 COMMENT '质量权重%（FR-4.9-7-1 默认 30）',
    W_DELIVERY DECIMAL(5,2) NOT NULL DEFAULT 30.00,
    W_COST DECIMAL(5,2) NOT NULL DEFAULT 20.00,
    W_RESPONSE DECIMAL(5,2) NOT NULL DEFAULT 20.00,
    COST_INDEX_WEIGHT DECIMAL(5,2) NOT NULL DEFAULT 60.00 COMMENT '成本维度内：价格竞争力指数权重（D7，余为降本）',
    THRESH_A DECIMAL(5,2) NOT NULL DEFAULT 90.00,
    THRESH_B DECIMAL(5,2) NOT NULL DEFAULT 75.00,
    THRESH_C DECIMAL(5,2) NOT NULL DEFAULT 60.00,
    VERSION INT NOT NULL DEFAULT 1,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT / ACTIVE / RETIRED',
    APPROVAL_STATUS VARCHAR(16) DEFAULT NULL COMMENT '变更审批 PENDING / APPROVED / REJECTED',
    EFFECTIVE_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY idx_bi_model_cat (CATEGORY_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商记分卡模型（权重合计须=100% 服务端校验）';

-- ---------- 8) 记分卡结果（月度不可变 + 修正版多版本） ----------
CREATE TABLE IF NOT EXISTS erp_scm_scorecard_result (
    ID VARCHAR(64) NOT NULL,
    MONTH_TAG CHAR(6) NOT NULL COMMENT '评分周期（自然月）',
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    MODEL_ID VARCHAR(64) NOT NULL,
    MODEL_VERSION INT NOT NULL DEFAULT 1 COMMENT '所用模型版本（可追溯）',
    Q_VALUE DECIMAL(8,2) DEFAULT NULL COMMENT '质量维度值（合格率%/PPM 等，穿透用）',
    Q_SCORE DECIMAL(6,2) DEFAULT NULL,
    D_VALUE DECIMAL(8,2) DEFAULT NULL COMMENT '交付维度值（准时率%）',
    D_SCORE DECIMAL(6,2) DEFAULT NULL,
    C_VALUE DECIMAL(8,2) DEFAULT NULL COMMENT '成本维度值（价格竞争力指数）',
    C_SCORE DECIMAL(6,2) DEFAULT NULL,
    R_VALUE DECIMAL(8,2) DEFAULT NULL COMMENT '响应维度值（PO 确认及时率%）',
    R_SCORE DECIMAL(6,2) DEFAULT NULL,
    TOTAL_SCORE DECIMAL(6,2) DEFAULT NULL,
    GRADE VARCHAR(4) DEFAULT NULL COMMENT 'A / B / C / D；异常时 NULL 不输出等级',
    DATA_STATUS VARCHAR(16) NOT NULL DEFAULT 'OK'
        COMMENT 'OK / MISSING_DIM 数据缺失 / INCOMPLETE 数据不完整暂缓发布 / ABNORMAL 计算异常转人工',
    VERSION_TAG VARCHAR(24) NOT NULL DEFAULT 'v1' COMMENT 'v1 / v2修正版…（申诉修正递增）',
    ORIGIN_ID VARCHAR(64) DEFAULT NULL COMMENT '修正版指向原结果 ID（原版保留备查）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'GENERATED'
        COMMENT 'GENERATED / REVIEWED / PUBLISHED / SUSPENDED 暂缓',
    SOURCE_JSON TEXT COMMENT '采集明细（穿透查看数据来源）',
    CALC_AT DATETIME DEFAULT NULL,
    REVIEW_BY VARCHAR(64) DEFAULT NULL,
    REVIEW_AT DATETIME DEFAULT NULL,
    PUBLISH_AT DATETIME DEFAULT NULL,
    APPEAL_DEADLINE DATETIME DEFAULT NULL COMMENT '公示 +7 工作日',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_scorecard_ver (MONTH_TAG, SUPPLIER_ID, VERSION_TAG),
    KEY idx_scorecard_supp (SUPPLIER_ID, MONTH_TAG),
    KEY idx_scorecard_status (STATUS, MONTH_TAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商绩效记分卡（采集不可手工修改，申诉出修正版新行）';

-- ---------- 9) 整改与冻结（BR-4.9-05：D 级冻结新单，整改关闭解冻） ----------
CREATE TABLE IF NOT EXISTS erp_scm_scorecard_rectify (
    ID VARCHAR(64) NOT NULL,
    RECTIFY_NO VARCHAR(32) NOT NULL COMMENT 'SR+yyyyMMdd+000001',
    RESULT_ID VARCHAR(64) NOT NULL COMMENT '触发的记分卡结果',
    MONTH_TAG CHAR(6) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    TRIGGER_TYPE VARCHAR(24) NOT NULL COMMENT 'GRADE_D / C_TWO_MONTHS',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN / CLOSED',
    FROZEN TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1=冻结新建 PO（仅拦新单，在途不受影响）',
    ITEMS_JSON TEXT COMMENT '整改项（逐条关闭）',
    DUE_AT DATETIME DEFAULT NULL COMMENT '整改限期（60 天）',
    CLOSE_BY VARCHAR(64) DEFAULT NULL,
    CLOSE_AT DATETIME DEFAULT NULL,
    UNFREEZE_APPROVAL VARCHAR(64) DEFAULT NULL COMMENT '解冻审批人（采购经理，C-0-03 非发起人）',
    UNFREEZE_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_rectify_no (RECTIFY_NO),
    KEY idx_rectify_supp (SUPPLIER_ID, STATUS),
    KEY idx_rectify_frozen (FROZEN, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='记分卡整改与配额冻结（BR-4.9-05）';

-- ---------- 10) 申诉（BR-4.9-07：7 工作日申诉期，复核成立出修正版） ----------
CREATE TABLE IF NOT EXISTS erp_scm_scorecard_appeal (
    ID VARCHAR(64) NOT NULL,
    APPEAL_NO VARCHAR(32) NOT NULL COMMENT 'SA+yyyyMMdd+000001',
    RESULT_ID VARCHAR(64) NOT NULL,
    SUPPLIER_ID VARCHAR(64) NOT NULL,
    MONTH_TAG CHAR(6) NOT NULL,
    REASON VARCHAR(1000) NOT NULL COMMENT '申诉理由',
    EVIDENCE VARCHAR(500) DEFAULT NULL COMMENT '证据说明/附件指引',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'SUBMITTED'
        COMMENT 'SUBMITTED / CONFIRMED 成立 / REJECTED 不成立',
    REVIEWER VARCHAR(64) DEFAULT NULL COMMENT '数据治理复核人',
    REVIEW_AT DATETIME DEFAULT NULL,
    CONCLUSION VARCHAR(1000) DEFAULT NULL,
    NEW_RESULT_ID VARCHAR(64) DEFAULT NULL COMMENT '修正版记分卡 ID',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_appeal_no (APPEAL_NO),
    KEY idx_appeal_result (RESULT_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='记分卡申诉（公示后 7 工作日内发起）';

-- ---------- 11) 菜单 PERM 回填（design D10；与 generate-menu-seed.cjs EXTRA_PERM 同口径） ----------
-- 角色口径：现网无 ROLE_PURCHASE，按 D10 「用最接近既有角色」取 ROLE_PM/ROLE_FINANCE_MGR/ROLE_GM/ROLE_ADMIN
UPDATE erp_admin_menu SET PERM = 'ROLE_PM,ROLE_FINANCE_MGR,ROLE_GM,ROLE_ADMIN'
 WHERE ID IN ('M2-9-1', 'M2-9-2', 'M2-9-3');
UPDATE erp_admin_menu SET PERM = 'ROLE_INTF_OPS,ROLE_ADMIN'
 WHERE ID = 'M2-8-3' AND (PERM IS NULL OR PERM = '');

-- ---------- 12) 行级权限种子（design D6：查询层显式注入；admin 全量通配） ----------
INSERT IGNORE INTO erp_bi_perm_rule
(ID, RULE_TYPE, TARGET_KEY, USER_NAME, ENTITY_ID, ROLE_CODE, ACTION, STATUS, REMARK, CREATE_BY, DEL_FLAG, VER_NO)
VALUES
('bipr-admin-star', 'ROW_LE', '*', 'user-admin', '*', NULL, 'PASS', 'ENABLED', '管理员全量通配（登录主体带 user- 前缀）', 'seed', '0', 0),
('bipr-intf-ops-star', 'ROW_LE', '*', 'user-intf-ops01', '*', NULL, 'PASS', 'ENABLED', '接口运维全量通配', 'seed', '0', 0),
('bipr-admin-plain', 'ROW_LE', '*', 'admin', '*', NULL, 'PASS', 'ENABLED', '兼容无前缀形式', 'seed', '0', 0);

-- ---------- 13) 监测阈值在线配置（spec price-monitoring：调整留痕、对新判定生效不追溯） ----------
CREATE TABLE IF NOT EXISTS erp_bi_config (
    ID VARCHAR(64) NOT NULL,
    CONFIG_KEY VARCHAR(64) NOT NULL COMMENT '参数键（如 PRICE_TREND_ALERT_PCT）',
    CONFIG_VALUE VARCHAR(128) NOT NULL,
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '当前值说明',
    HISTORY_JSON TEXT COMMENT '调整历史 [{old,new,by,at}]（留痕）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_bi_config_key (CONFIG_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='BI 在线参数配置（阈值调整留痕）';

INSERT IGNORE INTO erp_bi_config (ID, CONFIG_KEY, CONFIG_VALUE, REMARK, HISTORY_JSON, CREATE_BY, DEL_FLAG, VER_NO)
VALUES ('bicfg-trend-pct', 'PRICE_TREND_ALERT_PCT', '10', '价格异动环比阈值（%）', '[]', 'seed', '0', 0),
       ('bicfg-price-tol', 'PRICE_TOLERANCE_PCT', '5', '协议价上浮容差（%，同 PRICE_TOLERANCE）', '[]', 'seed', '0', 0);
