-- 052-crm-lead-opportunity.sql
-- 销售 Lead-to-Cash 第 1 段：通用参数 + 销售域角色（change add-sales-lead-to-cash，design D13/D15）
-- 1) erp_sys_param 通用业务参数表 + 本轮全部阈值种子
-- 2) 4 个销售域角色 + 4 个测试账号（密码同 Admin@123）
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE（045~051 范式）
-- 前缀登记：erp_sys_ 已在 01-architecture-style.md 1.4 节（erp_sys_approval 同前缀）
-- 备注：既有参数存在两套先例（yml+@Value 与 erp_bi_config 表）；本变更 D13 选表，
--       因 DISCOUNT_STACK_MODE 等需运行时切换且要留痕

-- ---------- 1) 通用业务参数表（design D13） ----------
CREATE TABLE IF NOT EXISTS erp_sys_param (
    ID VARCHAR(64) NOT NULL,
    PARAM_KEY VARCHAR(64) NOT NULL COMMENT '参数键（如 SO_APPROVAL_AUTO）',
    PARAM_VALUE VARCHAR(128) NOT NULL COMMENT '当前值',
    VALUE_TYPE VARCHAR(16) NOT NULL DEFAULT 'STRING' COMMENT 'STRING / NUMBER / RATE / AMOUNT / DAYS / ENUM',
    PARAM_GROUP VARCHAR(32) NOT NULL DEFAULT 'COMMON' COMMENT '分组 SD 销售 / CREDIT 信用 / DISCOUNT 折扣 / ATP / RETURN / COMMON',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '口径说明（含默认值与规则出处）',
    HISTORY_JSON TEXT COMMENT '调整历史 [{old,new,by,at}]（留痕）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_sys_param_key (PARAM_KEY),
    KEY idx_sys_param_group (PARAM_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通用业务参数（阈值在线调整留痕）';

-- 本轮全部阈值种子（design D13 / tasks 1.1）
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-so-approval-auto', 'SO_APPROVAL_AUTO', '100000', 'AMOUNT', 'SD',
 'SO 金额低于该值自动确认免审（FR-4.3-4-5，design D6 默认 10 万）', 'seed', '0', 0),
('param-so-approval-major', 'SO_APPROVAL_MAJOR', '2000000', 'AMOUNT', 'SD',
 'SO 金额高于该值追加销售总监审批节点（FR-4.3-4-5，design D6 默认 200 万）', 'seed', '0', 0),
('param-min-margin-rate', 'MIN_MARGIN_RATE', '0.05', 'RATE', 'SD',
 '最低毛利率阈值：最终价 < 成本×(1+该值) 硬阻断（BR-4.3-34 默认 5%）', 'seed', '0', 0),
('param-safety-days', 'SAFETY_DAYS', '30', 'DAYS', 'ATP',
 '安全库存折算天数，按日均销量扣除（BR-4.3-21 默认 30 天）', 'seed', '0', 0),
('param-discount-stack-mode', 'DISCOUNT_STACK_MODE', 'BEST_SINGLE', 'ENUM', 'DISCOUNT',
 '折扣叠加模式：BEST_SINGLE 最优单层（默认）/ STACKED 按渠道>量价>时间逐层递减（BR-4.3-31）', 'seed', '0', 0),
('param-credit-special-limit', 'CREDIT_SPECIAL_LIMIT', '500000', 'AMOUNT', 'CREDIT',
 '信用特批默认金额上限，实际以授权上限较小者为准（BR-4.3-18）', 'seed', '0', 0),
('param-return-overdue-days', 'RETURN_OVERDUE_DAYS', '30', 'DAYS', 'RETURN',
 '退货申请超期天数，超期须附加说明并加签（3.10 退货判定）', 'seed', '0', 0),
('param-quote-valid-days', 'QUOTE_VALID_DAYS', '30', 'DAYS', 'SD',
 '报价单默认有效期（天），可调整（FR-4.3-1-7）', 'seed', '0', 0),
('param-tolerance-default', 'TOLERANCE_DEFAULT', '0.005', 'RATE', 'COMMON',
 '通用容差 0.5%：开票与发货金额容差（C-0-02）、退货与收货容差', 'seed', '0', 0);

-- ---------- 2) 销售域角色与测试账号（design D15，tasks 1.2） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('role-sales',          'ROLE_SALES',          '销售',       '31', '1', 'seed', '0', 0),
('role-sales-mgr',      'ROLE_SALES_MGR',      '销售经理',   '32', '1', 'seed', '0', 0),
('role-sales-director', 'ROLE_SALES_DIRECTOR', '销售总监',   '33', '1', 'seed', '0', 0),
('role-credit-admin',   'ROLE_CREDIT_ADMIN',   '信用管理员', '86', '1', 'seed', '0', 0);

-- 测试账号（密码同 Admin@123）
INSERT IGNORE INTO erp_admin_user (ID, USERNAME, PASSWORD, NICK_NAME, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('user-sales01', 'sales01',
 '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W',
 '测试销售', '1', 'seed', '0', 0),
('user-salesmgr01', 'salesmgr01',
 '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W',
 '测试销售经理', '1', 'seed', '0', 0),
('user-creditadmin01', 'creditadmin01',
 '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W',
 '测试信用管理员', '1', 'seed', '0', 0),
('user-sddirector01', 'sddirector01',
 '$2a$10$KvoqroXik9qiqRA8MLTZTe4XrU1QurZ3dLZVEg9CJNfImhr1AGD3W',
 '测试销售总监', '1', 'seed', '0', 0);

INSERT IGNORE INTO erp_admin_user_role (ID, USER_ID, ROLE_ID) VALUES
('ur-sales01',        'user-sales01',        'role-sales'),
('ur-salesmgr01',     'user-salesmgr01',     'role-sales-mgr'),
('ur-creditadmin01',  'user-creditadmin01',  'role-credit-admin'),
('ur-sddirector01',   'user-sddirector01',   'role-sales-director');

-- ---------- 3) 菜单 PERM 回填与隐藏菜单（design D2/D15，与 099 种子同口径） ----------
-- 099 用 INSERT IGNORE，存量库行不会被覆盖；此处按「PERM 为空才回填」幂等补齐，
-- 与 050/051 的回填范式一致（不覆盖运行期在菜单管理中的手工修改）

-- 3.1 一级域 M3：取其下各组权限并集
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_SALES_DIRECTOR,ROLE_CREDIT_ADMIN,ROLE_FINANCE_MGR,ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID = 'M3' AND (PERM IS NULL OR PERM = '');

-- 3.2 商机（3.1）/ 报价（3.2）/ 线索（11.1）：销售与销售经理
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_ADMIN'
 WHERE ID IN ('M3-1','M3-1-1','M3-1-2','M3-1-3','M3-2','M3-2-1','M3-2-2','M3-2-3','M11-1','M11-1-1','M11-1-2')
   AND (PERM IS NULL OR PERM = '');

-- 3.3 信用管控（3.3）
UPDATE erp_admin_menu SET PERM = 'ROLE_CREDIT_ADMIN,ROLE_FINANCE_MGR,ROLE_ADMIN'
 WHERE ID IN ('M3-3','M3-3-1','M3-3-2','M3-3-3') AND (PERM IS NULL OR PERM = '');

-- 3.4 可承诺量（3.4）：销售 + 仓库
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M3-4','M3-4-1','M3-4-2') AND (PERM IS NULL OR PERM = '');

-- 3.5 订单（3.5）与价格折扣（3.6）：加销售总监
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_SALES_DIRECTOR,ROLE_ADMIN'
 WHERE ID IN ('M3-5','M3-5-1','M3-5-2','M3-5-3','M3-5-4','M3-6','M3-6-1','M3-6-2','M3-6-3','M3-6-4')
   AND (PERM IS NULL OR PERM = '');

-- 3.6 发货管理（3.7）：销售 + 仓库
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M3-7','M3-7-1','M3-7-2','M3-7-3','M3-7-4') AND (PERM IS NULL OR PERM = '');

-- 3.7 开票核销（3.8）
UPDATE erp_admin_menu SET PERM = 'ROLE_FINANCE_MGR,ROLE_ADMIN'
 WHERE ID IN ('M3-8','M3-8-1','M3-8-2','M3-8-3') AND (PERM IS NULL OR PERM = '');

-- 3.8 返利结算（3.9）
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES_MGR,ROLE_SALES_DIRECTOR,ROLE_FINANCE_MGR,ROLE_ADMIN'
 WHERE ID IN ('M3-9','M3-9-1','M3-9-2','M3-9-3') AND (PERM IS NULL OR PERM = '');

-- 3.9 退货管理（3.10）
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_FINANCE_MGR,ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M3-10','M3-10-1','M3-10-2','M3-10-3') AND (PERM IS NULL OR PERM = '');

-- 3.10 框架合同（3.11）
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_SALES_DIRECTOR,ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M3-11','M3-11-1','M3-11-2') AND (PERM IS NULL OR PERM = '');

-- 3.11 合同管理（11.11）
UPDATE erp_admin_menu SET PERM = 'ROLE_SALES,ROLE_SALES_MGR,ROLE_FINANCE_MGR,ROLE_ADMIN'
 WHERE ID IN ('M11-11','M11-11-1','M11-11-2','M11-11-3') AND (PERM IS NULL OR PERM = '');

-- 3.12 仓库档案（4.1.1）：仅叶子（父级 4.1.2/4.1.3 未纳入本轮，父级保持开放避免子节点成为孤儿）
UPDATE erp_admin_menu SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID = 'M4-1-1' AND (PERM IS NULL OR PERM = '');

-- 3.13 隐藏 11.1.3/11.1.4（商机操作集中到 3.1，design D2；幂等）
UPDATE erp_admin_menu SET STATUS = '0'
 WHERE ID IN ('M11-1-3','M11-1-4');

-- ---------- 4) 线索域四表（tasks 2.1，spec crm-lead-management） ----------

-- 4.1 线索主档（FR-4.8-1-1~1-5；BR-4.8-08 单人锁定 = OWNER_ID 唯一负责）
CREATE TABLE IF NOT EXISTS erp_crm_lead (
    ID VARCHAR(64) NOT NULL,
    -- LD + yyyyMMdd + 4 位流水
    LEAD_NO VARCHAR(32) NOT NULL COMMENT '线索编号',
    -- 展会/网络/渠道/转介绍/主动开拓（FR-4.8-1-1 预设渠道枚举）
    SOURCE_CHANNEL VARCHAR(32) NOT NULL COMMENT '来源渠道 EXPO/WEB/CHANNEL/REFERRAL/OUTBOUND',
    COMPANY_NAME VARCHAR(128) NOT NULL COMMENT '公司名称（查重键之一）',
    CONTACT_NAME VARCHAR(64) NOT NULL COMMENT '联系人（查重键之二）',
    CONTACT_PHONE VARCHAR(32) DEFAULT NULL,
    DEMAND_DESC VARCHAR(1000) DEFAULT NULL COMMENT '需求描述',
    EXPECT_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '预期金额',
    EXPECT_CLOSE_DATE DATE DEFAULT NULL COMMENT '预期成交日期',
    -- 五维评分（FR-4.8-1-2，1-5 分；NULL = 未评，按 0 分计并 L4 提示）
    SCORE_NEED INT DEFAULT NULL COMMENT '需求明确度 1-5（权重 30%）',
    SCORE_BUDGET INT DEFAULT NULL COMMENT '预算确认度 1-5（权重 25%）',
    SCORE_CHAIN INT DEFAULT NULL COMMENT '决策链清晰度 1-5（权重 20%）',
    SCORE_URGENCY INT DEFAULT NULL COMMENT '时间紧迫度 1-5（权重 15%）',
    SCORE_COMPETE INT DEFAULT NULL COMMENT '竞争态势 1-5（权重 10%）',
    SCORE DECIMAL(6,2) DEFAULT NULL COMMENT '加权总分（0-100）',
    GRADE VARCHAR(2) DEFAULT NULL COMMENT '等级 A≥80 / B 60-79 / C 40-59 / D <40',
    SCORE_MODEL_ID VARCHAR(64) DEFAULT NULL COMMENT '所用评分模型',
    SCORE_MODEL_VERSION INT DEFAULT NULL COMMENT '所用模型版本（可回溯）',
    SCORE_AT DATETIME DEFAULT NULL,
    OWNER_ID VARCHAR(64) DEFAULT NULL COMMENT '跟进负责人（BR-4.8-08 单人锁定）',
    OWNER_NAME VARCHAR(64) DEFAULT NULL,
    ASSIGNED_AT DATETIME DEFAULT NULL COMMENT '分配时间（3 工作日提醒基准）',
    POOL_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 在线索池待指派',
    LAST_FOLLOWUP_AT DATETIME DEFAULT NULL COMMENT '最后跟进时间（30 天回收基准）',
    REMIND_AT DATETIME DEFAULT NULL COMMENT '超 3 工作日未跟进的最近提醒时间（FR-4.8-1-3）',
    NEXT_PLAN_DATE DATE DEFAULT NULL COMMENT '下次跟进计划日（按等级节奏生成）',
    -- OPEN 跟进中 / CONVERTED 已转化商机 / CLOSED 已关闭 / RECYCLED 已回收待指派
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN/CONVERTED/CLOSED/RECYCLED',
    CONVERTED_OPP_ID VARCHAR(64) DEFAULT NULL COMMENT '转化后的商机 ID',
    DUPLICATE_OF VARCHAR(64) DEFAULT NULL COMMENT '查重命中的既有线索 ID（关联标记）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CRM_LEAD_NO (LEAD_NO),
    KEY IDX_CRM_LEAD_STATUS (STATUS, GRADE),
    KEY IDX_CRM_LEAD_OWNER (OWNER_ID, STATUS),
    KEY IDX_CRM_LEAD_COMPANY (COMPANY_NAME, CONTACT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商机线索（4.8 流程一 FR-4.8-1-1~1-5）';

-- 4.2 评分模型（BR-4.8-07 按行业/产品线差异化，多套可配；权重合计必须 100%）
CREATE TABLE IF NOT EXISTS erp_crm_lead_score_model (
    ID VARCHAR(64) NOT NULL,
    MODEL_KEY VARCHAR(64) NOT NULL COMMENT '模型唯一键',
    MODEL_NAME VARCHAR(128) NOT NULL,
    INDUSTRY VARCHAR(64) DEFAULT NULL COMMENT '适用行业（空 = 默认模型）',
    PRODUCT_LINE VARCHAR(64) DEFAULT NULL COMMENT '适用产品线（空 = 不限）',
    W_NEED INT NOT NULL DEFAULT 30 COMMENT '需求明确度权重%',
    W_BUDGET INT NOT NULL DEFAULT 25 COMMENT '预算确认度权重%',
    W_CHAIN INT NOT NULL DEFAULT 20 COMMENT '决策链清晰度权重%',
    W_URGENCY INT NOT NULL DEFAULT 15 COMMENT '时间紧迫度权重%',
    W_COMPETE INT NOT NULL DEFAULT 10 COMMENT '竞争态势权重%',
    GRADE_A_MIN INT NOT NULL DEFAULT 80 COMMENT 'A 级下限',
    GRADE_B_MIN INT NOT NULL DEFAULT 60 COMMENT 'B 级下限',
    GRADE_C_MIN INT NOT NULL DEFAULT 40 COMMENT 'C 级下限',
    VERSION INT NOT NULL DEFAULT 1 COMMENT '版本号',
    IS_CURRENT TINYINT(1) NOT NULL DEFAULT 1 COMMENT '当前生效版本',
    -- ACTIVE 生效 / DRAFT 草稿 / RETIRED 停用
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CRM_MODEL_KEY_VER (MODEL_KEY, VERSION),
    KEY IDX_CRM_MODEL_CUR (IS_CURRENT, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线索评分模型（BR-4.8-07 多套可配，权重合计 100%）';

-- 4.3 跟进记录（FR-4.8-1-4：仅可追加，不可删除或修改）
CREATE TABLE IF NOT EXISTS erp_crm_lead_followup (
    ID VARCHAR(64) NOT NULL,
    LEAD_ID VARCHAR(64) NOT NULL,
    -- 电话/拜访/演示/方案发送/微信/其他
    FOLLOW_TYPE VARCHAR(24) NOT NULL COMMENT '跟进方式 CALL/VISIT/DEMO/PROPOSAL/WECHAT/OTHER',
    CONTENT VARCHAR(2000) NOT NULL COMMENT '跟进内容',
    NEXT_PLAN DATE DEFAULT NULL COMMENT '下次跟进计划日（写入线索 NEXT_PLAN_DATE）',
    OPERATOR_ID VARCHAR(64) NOT NULL,
    OPERATOR_NAME VARCHAR(64) DEFAULT NULL,
    FOLLOW_AT DATETIME NOT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_CRM_FOLLOW_LEAD (LEAD_ID, FOLLOW_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线索跟进记录（只增不改不删）';

-- 4.4 线索池（FR-4.8-1-3 D 级入池待指派；FR-4.8-1-4 30 天未跟进回收）
CREATE TABLE IF NOT EXISTS erp_crm_lead_pool (
    ID VARCHAR(64) NOT NULL,
    LEAD_ID VARCHAR(64) NOT NULL,
    -- D_GRADE D 级入池 / RECYCLE 30 天未跟进回收 / MANUAL 手工入池
    REASON VARCHAR(24) NOT NULL COMMENT '入池原因 D_GRADE/RECYCLE/MANUAL',
    GRADE_AT_ENTRY VARCHAR(2) DEFAULT NULL COMMENT '入池时等级',
    POOLED_AT DATETIME NOT NULL,
    -- PENDING 待指派 / ASSIGNED 已指派
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/ASSIGNED',
    ASSIGNED_TO VARCHAR(64) DEFAULT NULL COMMENT '指派人（线索池出池的负责人）',
    ASSIGNED_BY VARCHAR(64) DEFAULT NULL COMMENT '指派操作人（销售经理）',
    ASSIGNED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_CRM_POOL_LEAD (LEAD_ID, STATUS),
    KEY IDX_CRM_POOL_STATUS (STATUS, POOLED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='线索池（D 级入池与超期回收）';

-- 4.5 默认评分模型种子（FR-4.8-1-2 五维权重 30/25/20/15/10，等级 80/60/40）
INSERT IGNORE INTO erp_crm_lead_score_model
(ID, MODEL_KEY, MODEL_NAME, INDUSTRY, PRODUCT_LINE, W_NEED, W_BUDGET, W_CHAIN, W_URGENCY, W_COMPETE,
 GRADE_A_MIN, GRADE_B_MIN, GRADE_C_MIN, VERSION, IS_CURRENT, STATUS, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('lead-model-default', 'DEFAULT', '默认评分模型', NULL, NULL, 30, 25, 20, 15, 10,
 80, 60, 40, 1, 1, 'ACTIVE', 'FR-4.8-1-2 默认权重与 A/B/C/D 阈值', 'seed', '0', 0);

-- ---------- 5) 线索提醒列补丁（本库 4.1 已建表时追加；新建库由 CREATE 直接带上） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_crm_lead'
        AND COLUMN_NAME = 'REMIND_AT') = 0,
    'ALTER TABLE erp_crm_lead
       ADD COLUMN REMIND_AT DATETIME DEFAULT NULL
         COMMENT ''超 3 工作日未跟进的最近提醒时间（FR-4.8-1-3）'' AFTER LAST_FOLLOWUP_AT',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 6) 商机域（tasks 3.1，spec opportunity-management） ----------

-- 6.1 商机主档（FR-4.8-1-5/1-6：两入口创建、5 阶段、丢失归档、漏斗统计）
CREATE TABLE IF NOT EXISTS erp_crm_opportunity (
    ID VARCHAR(64) NOT NULL,
    -- OPP + yyyyMMdd + 4 位流水
    OPP_NO VARCHAR(32) NOT NULL COMMENT '商机编号（创建后不可修改）',
    OPP_NAME VARCHAR(200) NOT NULL COMMENT '商机名称',
    CUSTOMER_ID VARCHAR(64) NOT NULL COMMENT '客户集团视图 ID（erp_mdm_customer_group）',
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL COMMENT '客户编码快照',
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL COMMENT '客户名称快照',
    -- 线索转化时回填，手工创建为空
    LEAD_ID VARCHAR(64) DEFAULT NULL COMMENT '来源线索 ID',
    EXPECT_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '预期金额（>100 万自动通知销售经理）',
    EXPECT_CLOSE_DATE DATE DEFAULT NULL COMMENT '预计成交日期',
    COMPETITION VARCHAR(500) DEFAULT NULL COMMENT '竞争分析',
    DEMAND_SUMMARY VARCHAR(1000) DEFAULT NULL COMMENT '客户需求摘要',
    BUDGET_REF VARCHAR(255) DEFAULT NULL COMMENT '预期项目预算（线索转化带出）',
    -- REQUIREMENT 需求确认 → DEMO 方案演示 → NEGOTIATION 商务谈判 → QUOTE 报价 → CONTRACT 合同签订
    STAGE VARCHAR(24) NOT NULL DEFAULT 'REQUIREMENT' COMMENT '当前阶段',
    STAGE_ENTERED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '进入当前阶段时间（30 天超期基准）',
    STAGE_OVERDUE VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 同阶段停留 >30 天（调度标记，查询亦实时计算）',
    STAGE_PROBABILITY INT DEFAULT NULL COMMENT '阶段概率 %（阶段转换必填）',
    NEXT_ACTION VARCHAR(500) DEFAULT NULL COMMENT '下一步行动（阶段转换必填）',
    NEXT_ACTION_DATE DATE DEFAULT NULL COMMENT '下一步预计完成日期（阶段转换必填）',
    -- OPEN 跟进中 / WON 已赢单（推进到合同签订） / LOST 丢失归档 / CLOSED 关闭
    STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN/WON/LOST/CLOSED',
    LOSS_CATEGORY VARCHAR(32) DEFAULT NULL COMMENT '丢失原因分类 PRICE/FUNCTION/COMPETITOR/DEMAND_CHANGE/OTHER',
    LOSS_REMARK VARCHAR(500) DEFAULT NULL COMMENT '丢失说明（归档必填）',
    LOSS_AT DATETIME DEFAULT NULL,
    CLOSE_AT DATETIME DEFAULT NULL COMMENT '关闭/赢单时间（销售周期统计基准）',
    -- 3.1.2 转化闸口回写（BR-4.3-07 不可引用原因）
    QUOTE_BLOCK_REASON VARCHAR(500) DEFAULT NULL COMMENT '最近一次转化闸口校验的不可引用原因',
    OWNER_ID VARCHAR(64) DEFAULT NULL COMMENT '负责人',
    OWNER_NAME VARCHAR(64) DEFAULT NULL,
    -- 在途阶段审批实例（erp_sys_approval.ID）
    APPROVAL_ID VARCHAR(64) DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CRM_OPP_NO (OPP_NO),
    KEY IDX_CRM_OPP_STATUS (STATUS, STAGE),
    KEY IDX_CRM_OPP_CUSTOMER (CUSTOMER_ID),
    KEY IDX_CRM_OPP_OWNER (OWNER_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商机主档（4.8 流程一 FR-4.8-1-5~1-7）';

-- 6.2 阶段推进日志（FR-4.8-1-6 每次转换走审批；PENDING 期间商机停在原阶段）
CREATE TABLE IF NOT EXISTS erp_crm_opp_stage_log (
    ID VARCHAR(64) NOT NULL,
    OPP_ID VARCHAR(64) NOT NULL,
    FROM_STAGE VARCHAR(24) NOT NULL,
    TO_STAGE VARCHAR(24) NOT NULL,
    PROBABILITY INT DEFAULT NULL COMMENT '本阶段概率 %（必填）',
    NEXT_ACTION VARCHAR(500) DEFAULT NULL COMMENT '下一步行动（必填）',
    NEXT_ACTION_DATE DATE DEFAULT NULL COMMENT '预计完成日期（必填）',
    -- PENDING 审批中 / APPROVED 已通过（阶段已跃迁） / REJECTED 已驳回（可改重提）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED',
    APPLY_BY VARCHAR(64) DEFAULT NULL,
    APPLY_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    APPROVAL_ID VARCHAR(64) DEFAULT NULL COMMENT '审批实例 ID',
    DECIDE_BY VARCHAR(64) DEFAULT NULL,
    DECIDE_AT DATETIME DEFAULT NULL,
    OPINION VARCHAR(500) DEFAULT NULL COMMENT '审批意见（驳回必填）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_CRM_STLOG_OPP (OPP_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商机阶段推进日志（审批驱动）';

-- 6.3 商机跟进记录（与线索侧同规约：仅追加，不改不删）
CREATE TABLE IF NOT EXISTS erp_crm_opp_followup (
    ID VARCHAR(64) NOT NULL,
    OPP_ID VARCHAR(64) NOT NULL,
    -- 电话/拜访/演示/方案发送/微信/系统（闸口回写等自动记录）/其他
    FOLLOW_TYPE VARCHAR(24) NOT NULL COMMENT '跟进方式 CALL/VISIT/DEMO/PROPOSAL/WECHAT/SYSTEM/OTHER',
    CONTENT VARCHAR(2000) NOT NULL COMMENT '跟进内容',
    NEXT_PLAN DATE DEFAULT NULL COMMENT '下次跟进计划日',
    OPERATOR_ID VARCHAR(64) NOT NULL,
    OPERATOR_NAME VARCHAR(64) DEFAULT NULL,
    FOLLOW_AT DATETIME NOT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_CRM_OPPFU_OPP (OPP_ID, FOLLOW_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商机跟进记录（只增不改不删）';

-- 6.4 站内通知记录（FR-4.8-1-5 金额超百万通知销售经理；spec 场景「推送一条通知记录」）
CREATE TABLE IF NOT EXISTS erp_sys_notice (
    ID VARCHAR(64) NOT NULL,
    -- 接收角色（按角色投递，与审批待办同一聚合口径）；可选指定用户
    TARGET_ROLE VARCHAR(64) DEFAULT NULL COMMENT '接收角色（如 ROLE_SALES_MGR）',
    TARGET_USER VARCHAR(64) DEFAULT NULL COMMENT '指定接收人（可空）',
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(1000) DEFAULT NULL,
    BIZ_TYPE VARCHAR(64) DEFAULT NULL COMMENT '业务类型（如 OPP_LARGE_AMOUNT）',
    BIZ_ID VARCHAR(64) DEFAULT NULL COMMENT '业务单据 ID',
    READ_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 已读',
    READ_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SYS_NOTICE_TARGET (TARGET_ROLE, TARGET_USER, READ_FLAG),
    KEY IDX_SYS_NOTICE_BIZ (BIZ_TYPE, BIZ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='站内通知记录（按角色投递）';
