-- 053-sd-quote-pricing.sql
-- 销售 Lead-to-Cash：客户渠道属性 + 三层折扣价源（change add-sales-lead-to-cash，design D4）
-- 1) erp_mdm_customer_view 加 CHANNEL 列（modified spec customer-admission）
-- 2) 渠道字典种子（CUSTOMER_CHANNEL）
-- 后续追加：渠道折扣表、促销活动表、价格审计表（tasks 5.1）
-- 幂等：information_schema + PREPARE 动态 DDL / INSERT IGNORE（040/052 范式）

-- ---------- 1) 客户法人视图渠道属性（spec customer-admission ADDED：渠道属性登记与维护） ----------
-- 可空：未维护按无渠道折扣计算并由销售侧 L4 提示（BR-4.3-32），不阻断建档
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_mdm_customer_view'
        AND COLUMN_NAME = 'CHANNEL') = 0,
    'ALTER TABLE erp_mdm_customer_view
       ADD COLUMN CHANNEL VARCHAR(32) DEFAULT NULL
         COMMENT ''渠道属性：DIRECT 直销 / DEALER 经销 / ECOM 电商 / KA 大客户（三层折扣渠道维度，FR-4.3-5-1）''
         AFTER PAYMENT_TERMS',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 2) 渠道字典（复用 erp_mdm_item_dict，DICT_TYPE = CUSTOMER_CHANNEL） ----------
INSERT IGNORE INTO erp_mdm_item_dict (ID, DICT_TYPE, DICT_CODE, DICT_NAME, SORT_ORDER, STATUS, CREATE_BY) VALUES
    ('d-ch-dir', 'CUSTOMER_CHANNEL', 'DIRECT', '直销', 10, '1', 'system'),
    ('d-ch-deal', 'CUSTOMER_CHANNEL', 'DEALER', '经销', 20, '1', 'system'),
    ('d-ch-ecom', 'CUSTOMER_CHANNEL', 'ECOM',   '电商', 30, '1', 'system'),
    ('d-ch-ka',   'CUSTOMER_CHANNEL', 'KA',     'KA 大客户', 40, '1', 'system');

-- ---------- 3) 报价域（tasks 4.1，spec sales-quote） ----------

-- 3.1 报价单头
-- 状态机：DRAFT 草稿 → PENDING 审批中（负毛利锁定也在此态）→ PUBLISHED 已发布
--        → SUPERSEDED 被新版本替代（历史可查不可转）/ CONVERTED 已转化 / REJECTED 驳回可改重提
CREATE TABLE IF NOT EXISTS erp_sd_quote (
    ID VARCHAR(64) NOT NULL,
    -- 草稿号 QD + yyyyMMdd + 4 位流水（创建即生成）
    DRAFT_NO VARCHAR(32) NOT NULL COMMENT '草稿编号',
    -- 正式报价编号 QT + yyyyMMdd + 4 位流水（发布时生成，FR-4.3-1-7）
    QUOTE_NO VARCHAR(32) DEFAULT NULL COMMENT '正式报价编号（发布后唯一）',
    OPP_ID VARCHAR(64) NOT NULL COMMENT '商机 ID（报价由商机入口创建，BR-4.3-07）',
    OPP_NO VARCHAR(32) DEFAULT NULL COMMENT '商机编号快照（引用不重复建档）',
    CUSTOMER_ID VARCHAR(64) NOT NULL COMMENT '客户集团视图 ID（取价挂靠）',
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    -- STANDARD 标准单 / SAMPLE 样品单（样品单豁免 MOQ，BR-4.3-09）
    ORDER_TYPE VARCHAR(16) NOT NULL DEFAULT 'STANDARD' COMMENT 'STANDARD/SAMPLE',
    CONTACT_NAME VARCHAR(64) DEFAULT NULL COMMENT '客户联系人',
    SHIP_ADDRESS VARCHAR(255) DEFAULT NULL COMMENT '收货地址（不完整 L4 提示补充）',
    REMARK VARCHAR(500) DEFAULT NULL,

    -- 金额与毛利（毛利公式 FR-4.3-1-5）
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '报价含税总额',
    TOTAL_COST DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '标准成本总额',
    MARGIN_RATE DECIMAL(8,4) DEFAULT NULL COMMENT '毛利率（小数，0.05 = 5%）',
    -- 0 ≤ 毛利率 < MIN_MARGIN_RATE 的二次确认留痕（确认人+时间；不构成价格授权）
    MARGIN_CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    MARGIN_CONFIRM_AT DATETIME DEFAULT NULL,
    -- 价格协议匹配记录 JSON：命中/未命中清单（《价格协议匹配记录》）
    PRICE_MATCH JSON DEFAULT NULL,

    -- 1 版本起；新版本保留历史（FR-4.3-1-7 修改生成新版本）
    VERSION_NO INT NOT NULL DEFAULT 1,
    SUPERSEDED_BY VARCHAR(64) DEFAULT NULL COMMENT '被哪个新版本替代（旧版本不可转 SO）',

    VALID_FROM DATE DEFAULT NULL COMMENT '有效期起（发布日）',
    VALID_TO DATE DEFAULT NULL COMMENT '有效期止（发布日 + QUOTE_VALID_DAYS 默认 30 天）',

    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING/REJECTED/PUBLISHED/SUPERSEDED/CONVERTED',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL COMMENT '在途审批实例',
    -- 转化回写（FR-4.3-1-8）
    SO_ID VARCHAR(64) DEFAULT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    CONVERTED_AT DATETIME DEFAULT NULL,
    PUBLISH_BY VARCHAR(64) DEFAULT NULL,
    PUBLISH_AT DATETIME DEFAULT NULL,

    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_QUOTE_DRAFT (DRAFT_NO),
    UNIQUE KEY UK_SD_QUOTE_NO (QUOTE_NO),
    KEY IDX_SD_QUOTE_OPP (OPP_ID, STATUS),
    KEY IDX_SD_QUOTE_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_SD_QUOTE_STATUS (STATUS, VALID_TO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售报价单头（4.3 流程一 FR-4.3-1-1~1-8）';

-- 3.2 报价明细行
CREATE TABLE IF NOT EXISTS erp_sd_quote_line (
    ID VARCHAR(64) NOT NULL,
    QUOTE_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT 'SKU（须启用在售）',
    ITEM_NAME VARCHAR(255) DEFAULT NULL,
    QTY DECIMAL(18,3) NOT NULL COMMENT '数量',
    BASE_UNIT VARCHAR(16) DEFAULT NULL,
    EXPECT_DELIVERY_DATE DATE DEFAULT NULL COMMENT '期望交期（早于最早可交货日期 L4 提示）',
    SPECIAL_PACK VARCHAR(500) DEFAULT NULL COMMENT '特殊包装要求',
    -- 取价结果（三类协议 trial：EXCLUSIVE > LADDER > TIME；无命中 L1 阻断）
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL COMMENT '含税单价（取价结果）',
    PRICE_SOURCE VARCHAR(16) DEFAULT NULL COMMENT '命中协议类型 EXCLUSIVE/LADDER/TIME',
    PA_CODE VARCHAR(32) DEFAULT NULL COMMENT '命中协议编码',
    AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '行金额 = QTY × UNIT_PRICE',
    STANDARD_COST DECIMAL(18,4) DEFAULT NULL COMMENT '取价时点标准成本快照',
    LINE_COST DECIMAL(18,2) DEFAULT NULL COMMENT '行成本 = QTY × STANDARD_COST',
    MOQ DECIMAL(18,3) DEFAULT NULL COMMENT '取价时点 MOQ 快照（行校验展示）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_QLINE_QUOTE (QUOTE_ID, LINE_NO),
    KEY IDX_SD_QLINE_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售报价明细行';

-- 3.3 报价版本快照（创建/发布/修订/转化全留痕，历史版本可查）
CREATE TABLE IF NOT EXISTS erp_sd_quote_version (
    ID VARCHAR(64) NOT NULL,
    QUOTE_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    -- CREATE 建草稿 / SUBMIT 提交审批 / PUBLISH 发布 / REVISE 开新版本 / REJECT 驳回 / CONVERT 转化
    OP_TYPE VARCHAR(16) NOT NULL COMMENT 'CREATE/SUBMIT/PUBLISH/REVISE/REJECT/CONVERT',
    SNAPSHOT_JSON JSON DEFAULT NULL COMMENT '头+行快照',
    OPERATOR_ID VARCHAR(64) DEFAULT NULL,
    OPERATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_QVER_QUOTE (QUOTE_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售报价版本快照';

-- ---------- 4) SO 头行（提前建：4.9 报价转化需落 SO；7.1 的 so_version/so_change 仍在 054） ----------
CREATE TABLE IF NOT EXISTS erp_sd_so (
    ID VARCHAR(64) NOT NULL,
    SO_NO VARCHAR(32) NOT NULL COMMENT '订单编号 SO + yyyyMMdd + 4 位流水',
    -- QUOTE 报价转化 / MANUAL 手工 / EDI / FRAMEWORK 框架下达（四入口，7.2 细化）
    SOURCE_TYPE VARCHAR(16) NOT NULL DEFAULT 'MANUAL' COMMENT '来源 QUOTE/MANUAL/EDI/FRAMEWORK',
    SOURCE_ID VARCHAR(64) DEFAULT NULL COMMENT '来源单据 ID（报价转化 = 报价 ID）',
    OPP_ID VARCHAR(64) DEFAULT NULL COMMENT '关联商机 ID',
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    ORDER_TYPE VARCHAR(16) NOT NULL DEFAULT 'STANDARD',
    PAYMENT_TERMS VARCHAR(32) DEFAULT NULL,
    TRADE_TERMS VARCHAR(32) DEFAULT NULL COMMENT '贸易条款',
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- DRAFT 草稿（转化即落草稿；信用/审批/确认状态机在第 7 组展开）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING/CONFIRMED/PARTIAL_SHIPPED/SHIPPED/SIGNED/INVOICED/CLOSED/CREDIT_FREEZE/CHANGING/CANCELLED',
    PREV_STATUS VARCHAR(16) DEFAULT NULL COMMENT '挂起前的稳定状态（业务逻辑6：解除后回前一状态）',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL COMMENT '在途审批实例（erp_sys_approval.ID）',
    MARGIN_RATE DECIMAL(8,4) DEFAULT NULL COMMENT '订单毛利率（小数，链尾加签判定）',
    PAY_CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '付款条件差异的销售主管确认人（BR-4.3-25）',
    PAY_CONFIRM_AT DATETIME DEFAULT NULL,
    PAY_CONFIRM_REASON VARCHAR(500) DEFAULT NULL,
    CLOSE_REASON VARCHAR(1000) DEFAULT NULL COMMENT '关闭原因（手动关闭必填）',
    CLOSED_BY VARCHAR(64) DEFAULT NULL,
    CLOSED_AT DATETIME DEFAULT NULL,
    CLOSE_CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '关闭的销售经理确认人（手动关闭）',
    EVENT_VERSION INT NOT NULL DEFAULT 0 COMMENT '事件快照版本（outbox recordVersion）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_SO_NO (SO_NO),
    KEY IDX_SD_SO_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_SD_SO_SOURCE (SOURCE_TYPE, SOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单头（转化提前建，状态机第 7 组细化）';

CREATE TABLE IF NOT EXISTS erp_sd_so_line (
    ID VARCHAR(64) NOT NULL,
    SO_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    QUOTE_LINE_ID VARCHAR(64) DEFAULT NULL COMMENT '来源报价行（转化带出）',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(255) DEFAULT NULL,
    QTY DECIMAL(18,3) NOT NULL,
    BASE_UNIT VARCHAR(16) DEFAULT NULL,
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL,
    PRICE_SOURCE VARCHAR(16) DEFAULT NULL,
    PA_CODE VARCHAR(32) DEFAULT NULL,
    AMOUNT DECIMAL(18,2) DEFAULT NULL,
    EXPECT_DELIVERY_DATE DATE DEFAULT NULL,
    -- ---- 执行列（tasks 7.1，第 7 组补齐）----
    WAREHOUSE_CODE VARCHAR(32) NOT NULL DEFAULT 'WH-MAIN' COMMENT '发货仓库（BR-4.3-19 逐 SKU+仓库）',
    PRICE_LOCKED VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 手动改价锁行，价格变更审批通过前禁止 SO 确认（BR-4.3-26）',
    ORIGINAL_UNIT_PRICE DECIMAL(18,4) DEFAULT NULL COMMENT '协议带出原价（改价对比）',
    PRICE_APPROVAL_ID VARCHAR(64) DEFAULT NULL COMMENT '价格变更审批实例',
    PLAN_SHIP_DATE DATE DEFAULT NULL COMMENT '计划发货日期',
    CUSTOMER_EXPECT_DATE DATE DEFAULT NULL COMMENT '客户期望交期',
    DELIVERY_PENDING VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 交期待确认（计划晚于期望且客户未确认，BR-4.3-28）',
    LINE_STATUS VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN/PARTIAL/SHIPPED/INVOICED/CANCELLED（7.8 状态机行级）',
    SHIPPED_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '已发量（9 组回写）',
    INVOICED_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '已开票量（10 组回写）',
    RESERVED_QTY DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '已预留量（确认时生成，8.8 释放回写）',
    -- ---- 执行列完 ----
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_SOLINE_SO (SO_ID, LINE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单行';

-- ---------- 5) 物料 MOQ / 标准成本列（4.4 行校验、4.6 毛利公式的输入，动态 ALTER） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_mdm_item'
        AND COLUMN_NAME = 'MIN_ORDER_QTY') = 0,
    'ALTER TABLE erp_mdm_item
       ADD COLUMN MIN_ORDER_QTY DECIMAL(18,3) DEFAULT NULL COMMENT ''MOQ 最小起订量（BR-4.3-09 行级校验）'' AFTER SAFETY_STOCK,
       ADD COLUMN STANDARD_COST DECIMAL(18,4) DEFAULT NULL COMMENT ''标准成本（毛利公式 FR-4.3-1-5）'' AFTER MIN_ORDER_QTY',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 物料种子回填（只补空值，幂等；毛利与 MOQ 校验需要基线数据）
UPDATE erp_mdm_item SET MIN_ORDER_QTY = 100, STANDARD_COST = 45.0000
 WHERE ITEM_CODE = 'RM0001000001' AND MIN_ORDER_QTY IS NULL;
UPDATE erp_mdm_item SET MIN_ORDER_QTY = 50, STANDARD_COST = 12.5000
 WHERE ITEM_CODE = 'RM0002000001' AND MIN_ORDER_QTY IS NULL;

-- ---------- 6) 客户证照有效期列（BR-4.3-08 证照过期 L1 阻断，动态 ALTER） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_mdm_customer_group'
        AND COLUMN_NAME = 'LICENSE_EXPIRE') = 0,
    'ALTER TABLE erp_mdm_customer_group
       ADD COLUMN LICENSE_EXPIRE DATE DEFAULT NULL
         COMMENT ''营业执照/资质证照有效期（BR-4.3-08 过期阻断报价；空=不校验）'' AFTER USCC',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 7) 报价审批参数（4.7 金额分档，design 迁移计划 053 参数种子） ----------
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-quote-approval-auto', 'QUOTE_APPROVAL_AUTO', '50000', 'AMOUNT', 'SD',
 '报价金额低于该值且毛利率达标 → 自动审批直接发布（FR-4.3-1-6 小额高毛利自动）', 'seed', '0', 0),
('param-quote-approval-major', 'QUOTE_APPROVAL_MAJOR', '500000', 'AMOUNT', 'SD',
 '报价金额高于该值 → 销售经理后追加销售总监审批节点（FR-4.3-1-6 金额分档）', 'seed', '0', 0);

-- ---------- 8) 价格折扣域（tasks 5.1，spec sales-pricing-discount，design D4） ----------

-- 8.1 渠道折扣（FR-4.3-5-1：按客户渠道属性匹配；渠道缺失置 0 + L4 提示 BR-4.3-32）
CREATE TABLE IF NOT EXISTS erp_sd_discount_channel (
    ID VARCHAR(64) NOT NULL,
    -- DIRECT 直销 / DEALER 经销 / ECOM 电商 / KA 大客户（CUSTOMER_CHANNEL 字典）
    CHANNEL VARCHAR(32) NOT NULL COMMENT '渠道属性',
    -- 折扣率（0.05 = 5%）
    DISCOUNT_RATE DECIMAL(6,4) NOT NULL COMMENT '渠道折扣率',
    EFFECTIVE_FROM DATE NOT NULL DEFAULT (CURRENT_DATE),
    EFFECTIVE_TO DATE DEFAULT NULL COMMENT '空 = 长期有效',
    -- ACTIVE 生效 / STOPPED 停用
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_DISC_CHANNEL (CHANNEL, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='渠道折扣（三层之一）';

-- 8.2 时间促销活动（FR-4.3-5-3：已发布且窗口内才参与；重叠取最大 BR-4.3-33）
CREATE TABLE IF NOT EXISTS erp_sd_promotion (
    ID VARCHAR(64) NOT NULL,
    -- PM + yyyyMMdd + 4 位流水
    PROMO_NO VARCHAR(32) NOT NULL COMMENT '活动编号（输出未采用清单用）',
    PROMO_NAME VARCHAR(200) NOT NULL,
    -- 单 SKU 活动（行级匹配，不跨 SKU）
    ITEM_CODE VARCHAR(64) NOT NULL,
    DISCOUNT_RATE DECIMAL(6,4) NOT NULL COMMENT '促销折扣率（0.08 = 8%）',
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    -- DRAFT 草稿 / PUBLISHED 已发布 / STOPPED 停用（EXPIRED 由日期推算不落状态）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED/STOPPED',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_PROMO_NO (PROMO_NO),
    KEY IDX_SD_PROMO_ITEM (ITEM_CODE, STATUS, START_DATE, END_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='时间促销活动（三层之一，重叠取最大）';

-- 8.3 价格审计日志（C-4.3-04 / BR-4.3-35/36：只增不改、保留 AUDIT_RETENTION_DAYS、关联 SO 行）
CREATE TABLE IF NOT EXISTS erp_sd_price_audit (
    ID VARCHAR(64) NOT NULL,
    -- 来源：SO 行 / 报价行 / 矩阵试算
    SRC_TYPE VARCHAR(16) NOT NULL COMMENT 'SRC_TYPE SO/QUOTE/CALC',
    SRC_ID VARCHAR(64) DEFAULT NULL COMMENT 'SO/报价 ID',
    LINE_NO INT DEFAULT NULL COMMENT '行号（关联 SO 行号）',
    CUSTOMER_ID VARCHAR(64) DEFAULT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    QTY DECIMAL(18,3) DEFAULT NULL,
    -- 计算全过程留痕（BR-4.3-36）
    BASE_PRICE DECIMAL(18,4) DEFAULT NULL COMMENT '原始基准价（协议试算价）',
    CHANNEL_RATE DECIMAL(6,4) DEFAULT NULL COMMENT '渠道层折扣率',
    LADDER_RATE DECIMAL(6,4) DEFAULT NULL COMMENT '量价阶梯层折算率（1 - 阶梯价/基准价）',
    PROMO_RATE DECIMAL(6,4) DEFAULT NULL COMMENT '时间促销层折扣率',
    STACK_MODE VARCHAR(24) DEFAULT NULL COMMENT 'BEST_SINGLE/STACKED 叠加规则',
    APPLIED_SOURCE VARCHAR(16) DEFAULT NULL COMMENT '实际采用的来源 CHANNEL/LADDER/PROMO/PROTOCAL/NONE',
    FINAL_PRICE DECIMAL(18,4) NOT NULL COMMENT '最终生效价',
    -- 冲突裁决（C-4.3-04 最后生效价）
    CONFLICT_JSON JSON DEFAULT NULL COMMENT '冲突来源与裁决结果（最后生效价）',
    REJECTED_JSON JSON DEFAULT NULL COMMENT '未采用来源清单（促销重叠未选中等）',
    SPECIAL_APPROVAL_NO VARCHAR(32) DEFAULT NULL COMMENT '特批单号（毛利阻断放行时回写）',
    OPERATOR_ID VARCHAR(64) DEFAULT NULL,
    OPERATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    RETENTION_UNTIL DATE DEFAULT NULL COMMENT '保留到期日（AUDIT_RETENTION_DAYS）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_AUDIT_SRC (SRC_TYPE, SRC_ID, LINE_NO),
    KEY IDX_SD_AUDIT_ITEM (CUSTOMER_ID, ITEM_CODE),
    KEY IDX_SD_AUDIT_TIME (OPERATE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='价格审计日志（只增不改，保留期参数化）';

-- 8.4 特殊价格审批单载体（FR-4.3-5-5 / S-4.3-08：低于毛利阈值须特批放行并回写单号）
--     审批走 approval-workflow（BIZ_TYPE=SpecialPrice，销售总监 + 财务会签）
CREATE TABLE IF NOT EXISTS erp_sd_special_price (
    ID VARCHAR(64) NOT NULL,
    -- SP + yyyyMMdd + 4 位流水（特批单号）
    SP_NO VARCHAR(32) NOT NULL COMMENT '特批单号（回写 SO 行/报价）',
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    -- 空 = 该客户全部 SKU；非空限定单品
    ITEM_CODE VARCHAR(64) DEFAULT NULL COMMENT '限定 SKU（空 = 全部）',
    ORIGIN_PRICE DECIMAL(18,4) NOT NULL COMMENT '申请突破的原价',
    SPECIAL_PRICE DECIMAL(18,4) NOT NULL COMMENT '申请特批价',
    STANDARD_COST DECIMAL(18,4) DEFAULT NULL,
    VALID_FROM DATE NOT NULL,
    VALID_TO DATE NOT NULL COMMENT '特批有效期（超期失效）',
    REASON VARCHAR(1000) NOT NULL COMMENT '申请原因（客户要求/竞标等）',
    -- DRAFT / PENDING 审批中 / APPROVED 生效 / REJECTED / EXPIRED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING/APPROVED/REJECTED/EXPIRED',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL,
    DECIDE_BY VARCHAR(64) DEFAULT NULL,
    DECIDE_AT DATETIME DEFAULT NULL,
    OPINION VARCHAR(500) DEFAULT NULL,
    APPLY_BY VARCHAR(64) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_SP_NO (SP_NO),
    KEY IDX_SD_SP_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_SD_SP_STATUS (STATUS, VALID_TO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='特殊价格审批单（S-4.3-08 销售总监+财务会签）';

-- 8.5 审计保留期参数（BR-4.3-35 保留 ≥365 天）
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-audit-retention-days', 'AUDIT_RETENTION_DAYS', '365', 'DAYS', 'SD',
 '价格审计日志保留天数（BR-4.3-35 不低于 365 天）', 'seed', '0', 0);
