-- =====================================================================
-- 054-sd-order-credit.sql
-- add-sales-lead-to-cash · 第 6 组 客户信用（spec customer-credit-control）
-- design 迁移计划 3：SO 状态版本、信用检查/冻结/预收、应收历史种子（12 个月）
--
-- 依赖前置说明：
--   * erp_sd_so / erp_sd_so_line 已在 053 提前建（4.9 报价转化）；
--     本文件补 so_version / so_change（7.1 的另两表，7.1 幂等跳过）。
--   * 应收核心两表（erp_fin_ar_invoice / erp_fin_ar_writeoff）原计划 056（第 10 组），
--     因 BR-4.3-14/15/16 的账龄与及时率种子必须先有表，提前到本文件建；
--     第 10 组 CREATE IF NOT EXISTS 幂等并按需扩展列（同 053 提前建 SO 的处理）。
-- 幂等：全部 CREATE TABLE IF NOT EXISTS / INSERT IGNORE / information_schema 动态 ALTER。
-- =====================================================================

-- ---------- 1) SO 版本与变更（tasks 7.1 后半，提前到 054） ----------

CREATE TABLE IF NOT EXISTS erp_sd_so_version (
    ID VARCHAR(64) NOT NULL,
    SO_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    -- CREATE 建单 / APPROVE 审批 / CONFIRM 确认 / CHANGE 变更 / CLOSE 关闭
    OP_TYPE VARCHAR(16) NOT NULL,
    SNAPSHOT_JSON JSON DEFAULT NULL,
    OPERATOR_ID VARCHAR(64) DEFAULT NULL,
    OPERATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_SOV_SO (SO_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单版本快照';

CREATE TABLE IF NOT EXISTS erp_sd_so_change (
    ID VARCHAR(64) NOT NULL,
    SO_ID VARCHAR(64) NOT NULL,
    LINE_NO INT DEFAULT NULL,
    FIELD_NAME VARCHAR(64) NOT NULL,
    OLD_VALUE VARCHAR(500) DEFAULT NULL,
    NEW_VALUE VARCHAR(500) DEFAULT NULL,
    -- 重跑信用/ATP 的结论（BR-4.3-30）
    CREDIT_RERUN VARCHAR(16) DEFAULT NULL COMMENT 'PASS/FROZEN/NEED_APPROVAL',
    REASON VARCHAR(1000) DEFAULT NULL,
    OPERATOR_ID VARCHAR(64) DEFAULT NULL,
    OPERATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_SOC_SO (SO_ID, OPERATE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售订单变更记录（含信用重跑结论）';

-- ---------- 2) 应收核心两表（第 10 组提前到本文件；账龄/及时率种子与信用计算依赖） ----------

CREATE TABLE IF NOT EXISTS erp_fin_ar_invoice (
    ID VARCHAR(64) NOT NULL,
    -- AR + yyyyMMdd + 4 位流水
    AR_NO VARCHAR(32) NOT NULL COMMENT '应收单号',
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    SO_ID VARCHAR(64) DEFAULT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    -- 应收发生日（开票/发货确认）；账龄与到期从此推算
    INVOICE_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL COMMENT '到期日（付款条件基准）',
    AMOUNT DECIMAL(18,2) NOT NULL COMMENT '应收金额',
    PAID_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '已核销金额',
    -- UNPAID / PARTIAL / PAID / RED（红冲）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'UNPAID',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_AR_NO (AR_NO),
    KEY IDX_FIN_AR_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_FIN_AR_DUE (DUE_DATE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='应收账款头（第 10 组扩展开票/核销联动）';

CREATE TABLE IF NOT EXISTS erp_fin_ar_writeoff (
    ID VARCHAR(64) NOT NULL,
    -- WO + yyyyMMdd + 4 位流水
    WO_NO VARCHAR(32) NOT NULL COMMENT '核销单号',
    AR_ID VARCHAR(64) NOT NULL,
    AR_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL COMMENT '核销/回款金额',
    -- 实际付款日 vs 应收到期日 → 及时率（BR-4.3-15）
    PAY_DATE DATE NOT NULL COMMENT '实际付款日',
    DUE_DATE DATE NOT NULL COMMENT '对应到期日',
    ON_TIME VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 按时（PAY_DATE ≤ DUE_DATE）',
    -- MANUAL 人工 / AUTO FIFO 自动（第 10 组扩展）
    WRITE_TYPE VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_WO_NO (WO_NO),
    KEY IDX_FIN_WO_AR (AR_ID),
    KEY IDX_FIN_WO_CUST (CUSTOMER_ID, PAY_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='应收核销/回款记录（及时率与连续逾期统计源）';

-- ---------- 3) 信用三表（tasks 6.1，spec customer-credit-control） ----------

-- 3.1 信用检查记录（BR-4.3-13 四因子快照；判定留痕）
CREATE TABLE IF NOT EXISTS erp_sd_credit_check (
    ID VARCHAR(64) NOT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    -- 关联 SO（建单即检时非空；客户级体检可空）
    SO_ID VARCHAR(64) DEFAULT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    ORDER_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '本次订单金额（四因子之一）',
    -- 四因子快照（BR-4.3-13）
    CREDIT_LIMIT_TOTAL DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '信用额度（含有效临时额度）',
    AR_BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '应收账款余额',
    SO_RESERVED DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '未清 SO 预占金额',
    CONSIGN_OCCUPIED DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '寄售专项额度占用',
    AVAILABLE DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '可用额度 = 额度 − AR − 预占 − 本次 − 寄售',
    -- 账龄（BR-4.3-14）
    AR_OVER90 DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '超期 90 天以上应收',
    OVER90_RATIO DECIMAL(6,4) DEFAULT NULL COMMENT '超 90 天占比',
    -- 付款及时率（BR-4.3-15）
    PAY_ON_TIME_RATE DECIMAL(6,4) DEFAULT NULL COMMENT '近 12 个月及时率',
    -- PASS 通过 / FROZEN 信用冻结 / NEED_APPROVAL 需审批（账龄超比）
    RESULT VARCHAR(16) NOT NULL COMMENT 'PASS/FROZEN/NEED_APPROVAL',
    REASON VARCHAR(1000) DEFAULT NULL,
    -- 账龄分析报告 JSON（L2 派发信用管理员时附）
    AGING_REPORT JSON DEFAULT NULL,
    CHECK_BY VARCHAR(64) DEFAULT NULL,
    CHECK_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_CC_CUST (CUSTOMER_ID, CHECK_AT),
    KEY IDX_SD_CC_SO (SO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='信用检查记录（四因子与账龄及时率快照）';

-- 3.2 信用冻结单（D5 挂起态：PREV_STATUS 回前一稳定状态；解冻不重跑审批不释放预留）
CREATE TABLE IF NOT EXISTS erp_sd_credit_freeze (
    ID VARCHAR(64) NOT NULL,
    SO_ID VARCHAR(64) NOT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    CREDIT_CHECK_ID VARCHAR(64) DEFAULT NULL COMMENT '触发的信用检查记录',
    GAP_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '缺口金额 = −可用额度（预收目标）',
    -- FROZEN 冻结中 / UNFROZEN 已解冻
    STATUS VARCHAR(16) NOT NULL DEFAULT 'FROZEN',
    -- 冻结时 SO 的前一稳定状态（D5：审批前 → 回待审批；已确认 → 回已确认）
    PREV_STATUS VARCHAR(16) DEFAULT NULL COMMENT '前一稳定状态',
    -- 触发原因：额度不足 / 账龄超比需审批
    FREEZE_REASON VARCHAR(32) NOT NULL COMMENT 'LIMIT/AGING',
    FROZEN_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    -- 解冻：PREPAY 预收到账 / SPECIAL 信用特批 / MANUAL 人工（账龄审批通过）
    UNFREEZE_METHOD VARCHAR(16) DEFAULT NULL,
    UNFREEZE_NO VARCHAR(32) DEFAULT NULL COMMENT '《SO 解冻确认单》编号 UF-...',
    UNFROZEN_BY VARCHAR(64) DEFAULT NULL,
    UNFROZEN_AT DATETIME DEFAULT NULL,
    UNFREEZE_REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_CF_SO (SO_ID, STATUS),
    KEY IDX_SD_CF_CUST (CUSTOMER_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='信用冻结单（挂起态与解冻确认）';

-- 3.3 预收款通知与到账登记（FR-4.3-2-6/2-7，BR-4.3-17）
CREATE TABLE IF NOT EXISTS erp_sd_prepayment_notice (
    ID VARCHAR(64) NOT NULL,
    -- PN + yyyyMMdd + 4 位流水
    NOTICE_NO VARCHAR(32) NOT NULL COMMENT '预收款通知单号',
    FREEZE_ID VARCHAR(64) NOT NULL COMMENT '关联冻结单',
    SO_ID VARCHAR(64) NOT NULL COMMENT '关联 SO',
    SO_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    GAP_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '预收目标金额 = 缺口',
    -- 通知留痕（通知销售员与客户）
    NOTIFY_SALES_AT DATETIME DEFAULT NULL,
    NOTIFY_CUSTOMER_AT DATETIME DEFAULT NULL,
    -- 到账登记（销售/客服登记）与财务确认（FINANCE_MGR/ADMIN）
    RECEIVED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '累计到账登记金额',
    RECEIVED_AT DATETIME DEFAULT NULL,
    CONFIRM_BY VARCHAR(64) DEFAULT NULL COMMENT '财务确认人（仅 FINANCE_MGR/ADMIN）',
    CONFIRM_AT DATETIME DEFAULT NULL,
    -- SETTLED 已足额并解冻 / REGISTERED 已登记待确认 / NOTIFIED 已通知 / PENDING 待通知
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/NOTIFIED/REGISTERED/SETTLED',
    REMAIN_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '尚差金额（登记后计算）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_PN_NO (NOTICE_NO),
    KEY IDX_SD_PN_FREEZE (FREEZE_ID),
    KEY IDX_SD_PN_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='预收款通知单与到账登记';

-- ---------- 4) 应收历史种子（tasks 6.1：12 个月，CREATE_BY='seed'） ----------
-- 样本设计（BR-4.3-14/15/16 四条规则全部可触发、可断言）：
--   9001 超期 90 天+ 占比 83%（>20% → 账龄 L2）      9002 连续 3 次逾期（→ 临时降额 50%）
--   9003 近 12 月及时率 60%（<80% → 评级下调）          9004 正常（100% 及时、无超期，对照组）
--   9005 额度紧张（可用仅 2 万，新单 5 万即冻结）
-- 日期一律相对当前（DATE_SUB），首插即落、二次执行 INSERT IGNORE 跳过。

-- 4.1 种子客户（信用额度与评级）
INSERT IGNORE INTO erp_mdm_customer_group
(ID, CUSTOMER_CODE, CUSTOMER_NAME, TAX_NO, CREDIT_RATING, CREDIT_LIMIT_TOTAL, STATUS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('seed-cust-9001', 'CUST-9001', '长江贸易滞纳样本户', '91320000SEED9001', 'C', 200000.00, '1', 'seed', '0', 0),
('seed-cust-9002', 'CUST-9002', '黄河设备连续逾期户', '91370000SEED9002', 'D', 150000.00, '1', 'seed', '0', 0),
('seed-cust-9003', 'CUST-9003', '珠江电子迟付样本户', '91440000SEED9003', 'C', 100000.00, '1', 'seed', '0', 0),
('seed-cust-9004', 'CUST-9004', '渤海粮油优质客户', '91110000SEED9004', 'A', 300000.00, '1', 'seed', '0', 0),
('seed-cust-9005', 'CUST-9005', '东海精密额度紧张户', '91310000SEED9005', 'B', 200000.00, '1', 'seed', '0', 0);

-- 4.2 应收单（9001：2 笔超期 90 天+ 未付 + 1 笔未到期；余额 18 万，超期 15 万 → 占比 83%）
INSERT IGNORE INTO erp_fin_ar_invoice
(ID, AR_NO, CUSTOMER_ID, CUSTOMER_CODE, CUSTOMER_NAME, INVOICE_DATE, DUE_DATE, AMOUNT, PAID_AMOUNT, STATUS, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('seed-ar-9001-1', 'AR-SEED-9001-01', 'seed-cust-9001', 'CUST-9001', '长江贸易滞纳样本户',
 DATE_SUB(CURDATE(), INTERVAL 150 DAY), DATE_SUB(CURDATE(), INTERVAL 120 DAY), 100000.00, 0.00, 'UNPAID', '超期 120 天未付', 'seed', '0', 0),
('seed-ar-9001-2', 'AR-SEED-9001-02', 'seed-cust-9001', 'CUST-9001', '长江贸易滞纳样本户',
 DATE_SUB(CURDATE(), INTERVAL 130 DAY), DATE_SUB(CURDATE(), INTERVAL 100 DAY), 50000.00, 0.00, 'UNPAID', '超期 100 天未付', 'seed', '0', 0),
('seed-ar-9001-3', 'AR-SEED-9001-03', 'seed-cust-9001', 'CUST-9001', '长江贸易滞纳样本户',
 DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_ADD(CURDATE(), INTERVAL 20 DAY), 30000.00, 0.00, 'UNPAID', '未到期', 'seed', '0', 0),

-- 9002：3 笔均已付但各晚 10 天（连续 3 次逾期）+ 1 笔未付
('seed-ar-9002-1', 'AR-SEED-9002-01', 'seed-cust-9002', 'CUST-9002', '黄河设备连续逾期户',
 DATE_SUB(CURDATE(), INTERVAL 230 DAY), DATE_SUB(CURDATE(), INTERVAL 200 DAY), 20000.00, 20000.00, 'PAID', '逾期 10 天付款', 'seed', '0', 0),
('seed-ar-9002-2', 'AR-SEED-9002-02', 'seed-cust-9002', 'CUST-9002', '黄河设备连续逾期户',
 DATE_SUB(CURDATE(), INTERVAL 180 DAY), DATE_SUB(CURDATE(), INTERVAL 150 DAY), 20000.00, 20000.00, 'PAID', '逾期 10 天付款', 'seed', '0', 0),
('seed-ar-9002-3', 'AR-SEED-9002-03', 'seed-cust-9002', 'CUST-9002', '黄河设备连续逾期户',
 DATE_SUB(CURDATE(), INTERVAL 130 DAY), DATE_SUB(CURDATE(), INTERVAL 100 DAY), 20000.00, 20000.00, 'PAID', '逾期 10 天付款', 'seed', '0', 0),
('seed-ar-9002-4', 'AR-SEED-9002-04', 'seed-cust-9002', 'CUST-9002', '黄河设备连续逾期户',
 DATE_SUB(CURDATE(), INTERVAL 20 DAY), DATE_ADD(CURDATE(), INTERVAL 10 DAY), 40000.00, 0.00, 'UNPAID', '未到期', 'seed', '0', 0),

-- 9003：5 笔全部结清，其中 2 笔晚 5 天（及时率 60% < 80%）
('seed-ar-9003-1', 'AR-SEED-9003-01', 'seed-cust-9003', 'CUST-9003', '珠江电子迟付样本户',
 DATE_SUB(CURDATE(), INTERVAL 300 DAY), DATE_SUB(CURDATE(), INTERVAL 270 DAY), 10000.00, 10000.00, 'PAID', '', 'seed', '0', 0),
('seed-ar-9003-2', 'AR-SEED-9003-02', 'seed-cust-9003', 'CUST-9003', '珠江电子迟付样本户',
 DATE_SUB(CURDATE(), INTERVAL 250 DAY), DATE_SUB(CURDATE(), INTERVAL 220 DAY), 10000.00, 10000.00, 'PAID', '', 'seed', '0', 0),
('seed-ar-9003-3', 'AR-SEED-9003-03', 'seed-cust-9003', 'CUST-9003', '珠江电子迟付样本户',
 DATE_SUB(CURDATE(), INTERVAL 200 DAY), DATE_SUB(CURDATE(), INTERVAL 170 DAY), 10000.00, 10000.00, 'PAID', '逾期 5 天', 'seed', '0', 0),
('seed-ar-9003-4', 'AR-SEED-9003-04', 'seed-cust-9003', 'CUST-9003', '珠江电子迟付样本户',
 DATE_SUB(CURDATE(), INTERVAL 150 DAY), DATE_SUB(CURDATE(), INTERVAL 120 DAY), 10000.00, 10000.00, 'PAID', '', 'seed', '0', 0),
('seed-ar-9003-5', 'AR-SEED-9003-05', 'seed-cust-9003', 'CUST-9003', '珠江电子迟付样本户',
 DATE_SUB(CURDATE(), INTERVAL 100 DAY), DATE_SUB(CURDATE(), INTERVAL 70 DAY), 10000.00, 10000.00, 'PAID', '逾期 5 天', 'seed', '0', 0),

-- 9004：正常优质——3 笔按时结清（及时率 100%，无未付）
('seed-ar-9004-1', 'AR-SEED-9004-01', 'seed-cust-9004', 'CUST-9004', '渤海粮油优质客户',
 DATE_SUB(CURDATE(), INTERVAL 260 DAY), DATE_SUB(CURDATE(), INTERVAL 230 DAY), 80000.00, 80000.00, 'PAID', '', 'seed', '0', 0),
('seed-ar-9004-2', 'AR-SEED-9004-02', 'seed-cust-9004', 'CUST-9004', '渤海粮油优质客户',
 DATE_SUB(CURDATE(), INTERVAL 190 DAY), DATE_SUB(CURDATE(), INTERVAL 160 DAY), 90000.00, 90000.00, 'PAID', '', 'seed', '0', 0),
('seed-ar-9004-3', 'AR-SEED-9004-03', 'seed-cust-9004', 'CUST-9004', '渤海粮油优质客户',
 DATE_SUB(CURDATE(), INTERVAL 110 DAY), DATE_SUB(CURDATE(), INTERVAL 80 DAY), 70000.00, 70000.00, 'PAID', '', 'seed', '0', 0),

-- 9005：额度紧张——1 笔未付 18 万（额度 20 万 → 可用 2 万）
('seed-ar-9005-1', 'AR-SEED-9005-01', 'seed-cust-9005', 'CUST-9005', '东海精密额度紧张户',
 DATE_SUB(CURDATE(), INTERVAL 25 DAY), DATE_ADD(CURDATE(), INTERVAL 5 DAY), 180000.00, 0.00, 'UNPAID', '未到期大额应收', 'seed', '0', 0);

-- 4.3 回款核销记录（及时率与连续逾期统计源）
INSERT IGNORE INTO erp_fin_ar_writeoff
(ID, WO_NO, AR_ID, AR_NO, CUSTOMER_ID, AMOUNT, PAY_DATE, DUE_DATE, ON_TIME, WRITE_TYPE, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
-- 9002 连续 3 次逾期（每次晚 10 天）
('seed-wo-9002-1', 'WO-SEED-9002-01', 'seed-ar-9002-1', 'AR-SEED-9002-01', 'seed-cust-9002', 20000.00,
 DATE_SUB(CURDATE(), INTERVAL 190 DAY), DATE_SUB(CURDATE(), INTERVAL 200 DAY), '0', 'MANUAL', '晚 10 天', 'seed', '0', 0),
('seed-wo-9002-2', 'WO-SEED-9002-02', 'seed-ar-9002-2', 'AR-SEED-9002-02', 'seed-cust-9002', 20000.00,
 DATE_SUB(CURDATE(), INTERVAL 140 DAY), DATE_SUB(CURDATE(), INTERVAL 150 DAY), '0', 'MANUAL', '晚 10 天', 'seed', '0', 0),
('seed-wo-9002-3', 'WO-SEED-9002-03', 'seed-ar-9002-3', 'AR-SEED-9002-03', 'seed-cust-9002', 20000.00,
 DATE_SUB(CURDATE(), INTERVAL 90 DAY), DATE_SUB(CURDATE(), INTERVAL 100 DAY), '0', 'MANUAL', '晚 10 天', 'seed', '0', 0),
-- 9003 五笔回款：3 按时 + 2 晚 5 天（60%）
('seed-wo-9003-1', 'WO-SEED-9003-01', 'seed-ar-9003-1', 'AR-SEED-9003-01', 'seed-cust-9003', 10000.00,
 DATE_SUB(CURDATE(), INTERVAL 275 DAY), DATE_SUB(CURDATE(), INTERVAL 270 DAY), '1', 'MANUAL', '', 'seed', '0', 0),
('seed-wo-9003-2', 'WO-SEED-9003-02', 'seed-ar-9003-2', 'AR-SEED-9003-02', 'seed-cust-9003', 10000.00,
 DATE_SUB(CURDATE(), INTERVAL 225 DAY), DATE_SUB(CURDATE(), INTERVAL 220 DAY), '1', 'MANUAL', '', 'seed', '0', 0),
('seed-wo-9003-3', 'WO-SEED-9003-03', 'seed-ar-9003-3', 'AR-SEED-9003-03', 'seed-cust-9003', 10000.00,
 DATE_SUB(CURDATE(), INTERVAL 165 DAY), DATE_SUB(CURDATE(), INTERVAL 170 DAY), '0', 'MANUAL', '晚 5 天', 'seed', '0', 0),
('seed-wo-9003-4', 'WO-SEED-9003-04', 'seed-ar-9003-4', 'AR-SEED-9003-04', 'seed-cust-9003', 10000.00,
 DATE_SUB(CURDATE(), INTERVAL 115 DAY), DATE_SUB(CURDATE(), INTERVAL 120 DAY), '1', 'MANUAL', '', 'seed', '0', 0),
('seed-wo-9003-5', 'WO-SEED-9003-05', 'seed-ar-9003-5', 'AR-SEED-9003-05', 'seed-cust-9003', 10000.00,
 DATE_SUB(CURDATE(), INTERVAL 65 DAY), DATE_SUB(CURDATE(), INTERVAL 70 DAY), '0', 'MANUAL', '晚 5 天', 'seed', '0', 0),
-- 9004 三笔全部按时
('seed-wo-9004-1', 'WO-SEED-9004-01', 'seed-ar-9004-1', 'AR-SEED-9004-01', 'seed-cust-9004', 80000.00,
 DATE_SUB(CURDATE(), INTERVAL 235 DAY), DATE_SUB(CURDATE(), INTERVAL 230 DAY), '1', 'MANUAL', '', 'seed', '0', 0),
('seed-wo-9004-2', 'WO-SEED-9004-02', 'seed-ar-9004-2', 'AR-SEED-9004-02', 'seed-cust-9004', 90000.00,
 DATE_SUB(CURDATE(), INTERVAL 165 DAY), DATE_SUB(CURDATE(), INTERVAL 160 DAY), '1', 'MANUAL', '', 'seed', '0', 0),
('seed-wo-9004-3', 'WO-SEED-9004-03', 'seed-ar-9004-3', 'AR-SEED-9004-03', 'seed-cust-9004', 70000.00,
 DATE_SUB(CURDATE(), INTERVAL 85 DAY), DATE_SUB(CURDATE(), INTERVAL 80 DAY), '1', 'MANUAL', '', 'seed', '0', 0);

-- ---------- 5) 种子客户法人视图（临时额度载体，BR-4.1-33 在法人视图列上） ----------
INSERT IGNORE INTO erp_mdm_customer_view
(ID, GROUP_ID, LEGAL_ENTITY_ID, SHIP_ADDRESS, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('seed-view-9001', 'seed-cust-9001', 'le-0001', '南京仓库', 'seed', '0', 0),
('seed-view-9002', 'seed-cust-9002', 'le-0001', '济南仓库', 'seed', '0', 0),
('seed-view-9003', 'seed-cust-9003', 'le-0001', '广州仓库', 'seed', '0', 0),
('seed-view-9004', 'seed-cust-9004', 'le-0001', '天津仓库', 'seed', '0', 0),
('seed-view-9005', 'seed-cust-9005', 'le-0001', '上海仓库', 'seed', '0', 0);

-- ---------- 6) SO 头/行执行列补丁（tasks 7.1，spec sales-order；053 的 CREATE 同步带列） ----------
-- 用 JSON_TABLE + information_schema 生成缺失列的 ADD COLUMN，幂等且对"部分列已存在"安全。

SET SESSION group_concat_max_len = 1000000;

SET @so_cols = JSON_ARRAY(
  JSON_ARRAY('APPROVAL_ID', 'VARCHAR(64) DEFAULT NULL COMMENT ''在途审批实例（erp_sys_approval.ID）'''),
  JSON_ARRAY('MARGIN_RATE', 'DECIMAL(8,4) DEFAULT NULL COMMENT ''订单毛利率（小数，链尾加签判定）'''),
  JSON_ARRAY('PREV_STATUS', 'VARCHAR(16) DEFAULT NULL COMMENT ''挂起前的稳定状态（业务逻辑6：解除后回前一状态）'''),
  JSON_ARRAY('PAY_CONFIRM_BY', 'VARCHAR(64) DEFAULT NULL COMMENT ''付款条件差异的销售主管确认人（BR-4.3-25）'''),
  JSON_ARRAY('PAY_CONFIRM_AT', 'DATETIME DEFAULT NULL'),
  JSON_ARRAY('PAY_CONFIRM_REASON', 'VARCHAR(500) DEFAULT NULL'),
  JSON_ARRAY('CLOSE_REASON', 'VARCHAR(1000) DEFAULT NULL COMMENT ''关闭原因（手动关闭必填）'''),
  JSON_ARRAY('CLOSED_BY', 'VARCHAR(64) DEFAULT NULL'),
  JSON_ARRAY('CLOSED_AT', 'DATETIME DEFAULT NULL'),
  JSON_ARRAY('CLOSE_CONFIRM_BY', 'VARCHAR(64) DEFAULT NULL COMMENT ''关闭的销售经理确认人（手动关闭）'''),
  JSON_ARRAY('EVENT_VERSION', 'INT NOT NULL DEFAULT 0 COMMENT ''事件快照版本（outbox recordVersion）''')
);
SET @ddl = (
  SELECT IF(COUNT(*) = 0, 'SELECT 1',
         CONCAT('ALTER TABLE erp_sd_so ',
                GROUP_CONCAT(CONCAT('ADD COLUMN `', j.name, '` ', j.def) SEPARATOR ',\n       ')))
  FROM JSON_TABLE(@so_cols, '$[*]' COLUMNS (name VARCHAR(64) PATH '$[0]', def VARCHAR(500) PATH '$[1]')) j
  LEFT JOIN information_schema.COLUMNS c
    ON c.TABLE_SCHEMA = DATABASE() AND c.TABLE_NAME = 'erp_sd_so' AND c.COLUMN_NAME = j.name
  WHERE c.COLUMN_NAME IS NULL
);
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @line_cols = JSON_ARRAY(
  JSON_ARRAY('WAREHOUSE_CODE', 'VARCHAR(32) NOT NULL DEFAULT ''WH-MAIN'' COMMENT ''发货仓库（BR-4.3-19 逐 SKU+仓库）'''),
  JSON_ARRAY('PRICE_LOCKED', 'VARCHAR(1) NOT NULL DEFAULT ''0'' COMMENT ''1 = 手动改价锁行，价格变更审批通过前禁止 SO 确认（BR-4.3-26）'''),
  JSON_ARRAY('ORIGINAL_UNIT_PRICE', 'DECIMAL(18,4) DEFAULT NULL COMMENT ''协议带出原价（改价对比）'''),
  JSON_ARRAY('PRICE_APPROVAL_ID', 'VARCHAR(64) DEFAULT NULL COMMENT ''价格变更审批实例'''),
  JSON_ARRAY('PLAN_SHIP_DATE', 'DATE DEFAULT NULL COMMENT ''计划发货日期'''),
  JSON_ARRAY('CUSTOMER_EXPECT_DATE', 'DATE DEFAULT NULL COMMENT ''客户期望交期'''),
  JSON_ARRAY('DELIVERY_PENDING', 'VARCHAR(1) NOT NULL DEFAULT ''0'' COMMENT ''1 = 交期待确认（计划晚于期望且客户未确认，BR-4.3-28）'''),
  JSON_ARRAY('LINE_STATUS', 'VARCHAR(16) NOT NULL DEFAULT ''OPEN'' COMMENT ''OPEN/PARTIAL/SHIPPED/INVOICED/CANCELLED（7.8 状态机行级）'''),
  JSON_ARRAY('SHIPPED_QTY', 'DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT ''已发量（9 组回写）'''),
  JSON_ARRAY('INVOICED_QTY', 'DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT ''已开票量（10 组回写）'''),
  JSON_ARRAY('RESERVED_QTY', 'DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT ''已预留量（确认时生成，8.8 释放回写）''')
);
SET @ddl = (
  SELECT IF(COUNT(*) = 0, 'SELECT 1',
         CONCAT('ALTER TABLE erp_sd_so_line ',
                GROUP_CONCAT(CONCAT('ADD COLUMN `', j.name, '` ', j.def) SEPARATOR ',\n       ')))
  FROM JSON_TABLE(@line_cols, '$[*]' COLUMNS (name VARCHAR(64) PATH '$[0]', def VARCHAR(500) PATH '$[1]')) j
  LEFT JOIN information_schema.COLUMNS c
    ON c.TABLE_SCHEMA = DATABASE() AND c.TABLE_NAME = 'erp_sd_so_line' AND c.COLUMN_NAME = j.name
  WHERE c.COLUMN_NAME IS NULL
);
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------- 7) 批次预留表（tasks 8.1 提前：7.7 确认同事务生成预留依赖） ----------
CREATE TABLE IF NOT EXISTS erp_sd_reservation (
    ID VARCHAR(64) NOT NULL,
    SO_ID VARCHAR(64) NOT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    LINE_ID VARCHAR(64) NOT NULL COMMENT 'SO 行 ID',
    LINE_NO INT DEFAULT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    WAREHOUSE_CODE VARCHAR(32) NOT NULL DEFAULT 'WH-MAIN',
    -- 无批次物料用 '' 占位（8.6）
    BATCH_NO VARCHAR(64) NOT NULL DEFAULT '',
    QTY DECIMAL(18,3) NOT NULL COMMENT '预留数量',
    -- ACTIVE 生效 / CONSUMED 已消耗（发货）/ RELEASED 已释放（取消/关闭/变更减量）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/CONSUMED/RELEASED',
    -- 先到先得裁决基准（BR-4.3-24 时间戳）
    LOCK_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RELEASED_AT DATETIME DEFAULT NULL,
    RELEASE_REASON VARCHAR(128) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_RSV_SO (SO_ID, STATUS),
    KEY IDX_SD_RSV_BATCH (WAREHOUSE_CODE, ITEM_CODE, BATCH_NO, STATUS),
    KEY IDX_SD_RSV_LINE (LINE_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SO 批次预留（BR-4.3-24/29；ATP 的 Reserved = SUM(ACTIVE)）';
