-- 055-sd-atp-shipment.sql
-- 销售 Lead-to-Cash：仓库档案 + 库存仓库维度改造（change add-sales-lead-to-cash，design D16）
-- 后续追加：批次预留表、发货单头行（tasks 8.1 / 9.1）
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / information_schema + PREPARE 动态 DDL（040 范式）

-- ---------- 1) 仓库档案（tasks 1.6，spec warehouse-master） ----------
CREATE TABLE IF NOT EXISTS erp_inv_warehouse (
    ID VARCHAR(64) NOT NULL,
    -- 系统生成，形如 WH-0003；创建后不可修改
    WH_CODE VARCHAR(32) NOT NULL COMMENT '仓库编码（系统生成，创建后不可改）',
    WH_NAME VARCHAR(128) NOT NULL COMMENT '仓库名称',
    ORG_UNIT VARCHAR(64) DEFAULT NULL COMMENT '所属组织',
    -- 1 启用 / 0 停用（停用后不可被新发货单与新预留选用）
    STATUS VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '1 启用 / 0 停用',
    CAPACITY_DESC VARCHAR(255) DEFAULT NULL COMMENT '容量属性（描述性）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_WH_CODE (WH_CODE),
    KEY IDX_INV_WH_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='仓库档案（4.1.1）';

INSERT IGNORE INTO erp_inv_warehouse
(ID, WH_CODE, WH_NAME, ORG_UNIT, STATUS, CAPACITY_DESC, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('wh-main', 'WH-MAIN', '主仓库', NULL, '1', '默认仓', '库存仓库维度改造的存量回填目标仓（design D16）', 'seed', '0', 0),
('wh-02',   'WH-02',   '成品仓', NULL, '1', '', '多仓演示与分仓 ATP 验证用', 'seed', '0', 0);

-- ---------- 2) erp_inv_stock 增加仓库维度：加列（NOT NULL DEFAULT 即完成存量回填） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_stock'
        AND COLUMN_NAME = 'WAREHOUSE_CODE') = 0,
    'ALTER TABLE erp_inv_stock
       ADD COLUMN WAREHOUSE_CODE VARCHAR(32) NOT NULL DEFAULT ''WH-MAIN''
         COMMENT ''仓库编码（design D16，ATP 与发货按 SKU+仓库维度）'' AFTER ID',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 存量回填（加列时已按默认值填充；此处兜底清理空串）
UPDATE erp_inv_stock SET WAREHOUSE_CODE = 'WH-MAIN'
 WHERE WAREHOUSE_CODE IS NULL OR WAREHOUSE_CODE = '';

-- ---------- 3) 唯一键升级：(ITEM_CODE, BATCH_NO) → (WAREHOUSE_CODE, ITEM_CODE, BATCH_NO) ----------
-- 先删旧唯一键（存在才删），再建新唯一键（不存在才建）；两步均幂等
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_stock'
        AND INDEX_NAME = 'UK_STOCK_ITEM_BATCH') > 0,
    'ALTER TABLE erp_inv_stock DROP INDEX UK_STOCK_ITEM_BATCH',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @ddl = IF(
    (SELECT COUNT(DISTINCT INDEX_NAME) FROM information_schema.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_stock'
        AND INDEX_NAME = 'UK_STOCK_WH_ITEM_BATCH') = 0,
    'ALTER TABLE erp_inv_stock
       ADD UNIQUE KEY UK_STOCK_WH_ITEM_BATCH (WAREHOUSE_CODE, ITEM_CODE, BATCH_NO)',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 3) ATP 承诺试算台账（tasks 8.10 补：spec 场景「可保存试算记录」） ----------
CREATE TABLE IF NOT EXISTS erp_sd_atp_trial (
    ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(255) DEFAULT NULL,
    WAREHOUSE_CODE VARCHAR(32) NOT NULL DEFAULT 'WH-MAIN',
    QTY DECIMAL(18,3) NOT NULL COMMENT '需求量',
    EXPECT_DATE DATE DEFAULT NULL COMMENT '客户期望交期（延迟剔除基准）',
    -- 四因子快照（BR-4.3-19）
    ON_HAND DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '在手（AVAILABLE_QTY，已排除待检）',
    EXCLUDED_QC DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '被排除：待检/让步锁定',
    EXCLUDED_VMI DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '被排除：寄售库存',
    IN_PROCESS DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '在制（生产域未接入恒 0）',
    INCOMING DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '在途（已批 PO 且到货 ≤ 交期）',
    INCOMING_DELAYED DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '被剔除：计划延迟不计入',
    RESERVED DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '预留（SUM(ACTIVE)）',
    SAFETY_STOCK DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT '安全库存占用（日均×SAFETY_DAYS 与字段取大）',
    AVAILABLE DECIMAL(18,3) NOT NULL DEFAULT 0 COMMENT 'ATP = OnHand+InProcess+Incoming−Reserved−SafetyStock',
    ENOUGH VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 满足需求（否则 L4 提示不削量）',
    EARLIEST_PROMISE_DATE DATE DEFAULT NULL COMMENT '最早可承诺日期',
    -- DRAFT 草稿 / SAVED 已保存
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/SAVED',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_ATP_ITEM (ITEM_CODE, WAREHOUSE_CODE, CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ATP 承诺试算台账（3.4.1）';

-- ---------- 4) 销售发货（tasks 9.1，spec sales-shipment，D8 只做销售侧策略与确认） ----------

CREATE TABLE IF NOT EXISTS erp_sd_shipment (
    ID VARCHAR(64) NOT NULL,
    -- SH + yyyyMMdd + 4 位流水
    SHIP_NO VARCHAR(32) NOT NULL COMMENT '发货单号',
    -- PARTIAL 部分 / MERGE 合并 / BATCH 分批 / EXCHANGE 换货（12.6 复用）
    SHIP_TYPE VARCHAR(16) NOT NULL COMMENT 'PARTIAL/MERGE/BATCH/EXCHANGE',
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    WAREHOUSE_CODE VARCHAR(32) NOT NULL DEFAULT 'WH-MAIN',
    -- DRAFT 草稿 / POSTED 已出库过账 / CONFIRMED 已发货确认 / SIGNED 已签收 / REJECTED 拒收 / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/POSTED/CONFIRMED/SIGNED/REJECTED/CANCELLED',
    TOTAL_QTY DECIMAL(18,3) NOT NULL DEFAULT 0,
    TOTAL_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '应收事件金额 = Σ 行数量×单价',
    -- 9.7 物流信息
    LOGISTICS_CO VARCHAR(64) DEFAULT NULL COMMENT '物流公司',
    LOGISTICS_NO VARCHAR(64) DEFAULT NULL COMMENT '物流单号',
    SHIP_AT DATETIME DEFAULT NULL COMMENT '发货确认时间',
    -- 9.8 签收
    SIGN_DUE_DATE DATE DEFAULT NULL COMMENT '签收时限（确认日 + SIGN_TIMEOUT_DAYS）',
    SIGN_AT DATETIME DEFAULT NULL COMMENT '签收时间',
    SIGN_WARNED VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 = 超时未签收已预警',
    -- 9.7 物流异常（记录并通知销售）
    EXCEPT_NOTE VARCHAR(500) DEFAULT NULL COMMENT '物流异常信息',
    EXCEPT_NOTIFY_AT DATETIME DEFAULT NULL,
    -- 9.8 拒收
    REJECT_REASON VARCHAR(500) DEFAULT NULL,
    REJECTED_AT DATETIME DEFAULT NULL,
    RETURN_ID VARCHAR(64) DEFAULT NULL COMMENT '拒收生成的退货申请 ID（12 组）',
    POST_BY VARCHAR(64) DEFAULT NULL,
    POST_AT DATETIME DEFAULT NULL COMMENT '出库过账时间',
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_SHIP_NO (SHIP_NO),
    KEY IDX_SD_SHIP_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_SD_SHIP_WH (WAREHOUSE_CODE, STATUS),
    KEY IDX_SD_SHIP_STATUS (STATUS, CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售发货单（3.7 部分/合并/分批策略与确认）';

CREATE TABLE IF NOT EXISTS erp_sd_shipment_line (
    ID VARCHAR(64) NOT NULL,
    SHIP_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    -- 来源引用（合并发货保留多 SO 行级引用，spec 场景「多单合并」）
    SO_ID VARCHAR(64) NOT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    SO_LINE_ID VARCHAR(64) NOT NULL,
    SO_LINE_NO INT DEFAULT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(255) DEFAULT NULL,
    QTY DECIMAL(18,3) NOT NULL COMMENT '发货数量（≤ 未发余量与可锁预留量，9.5）',
    BASE_UNIT VARCHAR(16) DEFAULT NULL,
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL COMMENT '来自 SO 行（应收事件金额口径）',
    AMOUNT DECIMAL(18,2) DEFAULT NULL,
    WAREHOUSE_CODE VARCHAR(32) NOT NULL DEFAULT 'WH-MAIN',
    PLAN_SHIP_DATE DATE DEFAULT NULL COMMENT '分批交期（9.4 行级带出）',
    -- PENDING 待过账 / POSTED 已过账 / CANCELLED
    LINE_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    -- 过账 FIFO 选批结果 [{batchNo, qty}]（9.6 回填）
    BATCH_ALLOC JSON DEFAULT NULL,
    POST_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_SHIPLINE_SHIP (SHIP_ID, LINE_NO),
    KEY IDX_SD_SHIPLINE_SO (SO_ID, SO_LINE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售发货单行（来源 SO 行引用与选批结果）';

-- ---------- 5) 销售退货骨架（tasks 12.1 提前建：9.8 拒收生成退货申请草稿的载体；
--              12 组按 JSON_TABLE 范式补判定/红冲/换货列） ----------

CREATE TABLE IF NOT EXISTS erp_sd_return (
    ID VARCHAR(64) NOT NULL,
    -- RT + yyyyMMdd + 4 位流水
    RETURN_NO VARCHAR(32) NOT NULL COMMENT '退货单号',
    -- CUSTOMER 客户退货 / REJECT 客户拒收转入
    SOURCE_TYPE VARCHAR(16) NOT NULL DEFAULT 'CUSTOMER' COMMENT 'CUSTOMER/REJECT',
    SHIP_ID VARCHAR(64) DEFAULT NULL COMMENT '原发货单（拒收自动关联，spec 场景「拒收自动带入」）',
    SHIP_NO VARCHAR(32) DEFAULT NULL,
    SO_ID VARCHAR(64) DEFAULT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    TOTAL_QTY DECIMAL(18,3) NOT NULL DEFAULT 0,
    TOTAL_AMT DECIMAL(18,2) NOT NULL DEFAULT 0,
    -- REFUND 退款 / EXCHANGE 换货（期望处理方式）
    HANDLE_TYPE VARCHAR(16) NOT NULL DEFAULT 'REFUND' COMMENT 'REFUND/EXCHANGE',
    RETURN_REASON VARCHAR(1000) DEFAULT NULL,
    REASON_TYPE VARCHAR(32) DEFAULT NULL COMMENT '质量/客户/物流破损/拒收等分类',
    -- 开票状态分流：UNINVOICED 未开票 / INVOICED 已开票（12.2）
    INVOICE_FLAG VARCHAR(16) NOT NULL DEFAULT 'UNINVOICED',
    -- DRAFT 草稿 / JUDGED 已判定 / APPROVING 审批中 / APPROVED 通过 / REJECTED 驳回 / DONE 完成 / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    APPROVAL_ID VARCHAR(64) DEFAULT NULL,
    APPLY_BY VARCHAR(64) DEFAULT NULL,
    APPLY_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_RT_NO (RETURN_NO),
    KEY IDX_SD_RT_SO (SO_ID),
    KEY IDX_SD_RT_SHIP (SHIP_ID),
    KEY IDX_SD_RT_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售退货申请（12 组判定/审批/退款换货扩展；9.8 拒收草稿载体）';

CREATE TABLE IF NOT EXISTS erp_sd_return_line (
    ID VARCHAR(64) NOT NULL,
    RETURN_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL,
    SO_LINE_ID VARCHAR(64) DEFAULT NULL,
    SO_LINE_NO INT DEFAULT NULL,
    SHIP_LINE_ID VARCHAR(64) DEFAULT NULL COMMENT '来源发货行（拒收带入）',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(255) DEFAULT NULL,
    QTY DECIMAL(18,3) NOT NULL COMMENT '退货数量（≤ 已发可退余量，12.2）',
    BASE_UNIT VARCHAR(16) DEFAULT NULL,
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL,
    AMOUNT DECIMAL(18,2) DEFAULT NULL,
    WAREHOUSE_CODE VARCHAR(32) DEFAULT NULL COMMENT '回补仓库',
    LINE_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SD_RTLINE_RT (RETURN_ID, LINE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售退货申请行';

-- ---------- 6) 签收时限参数（9.8 超时未签收预警基准） ----------
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-sign-timeout-days', 'SIGN_TIMEOUT_DAYS', '7', 'DAYS', 'SD',
 '发货确认后签收时限（天），超时未签收触发预警（FR-4.3-6-7）', 'seed', '0', 0);
