-- 056 开票与应收核销（第 10 组，spec sales-invoicing-receivable）
-- 范围：按次开票申请（发货确认触发）/ 销项发票与红字发票台账 / 应收明细与回款登记 /
--       FIFO 核销与月度对账 / 合同与收款计划提前建（10.8 计划达成依赖，14 组复用）
-- 幂等：全部 CREATE TABLE IF NOT EXISTS / INSERT IGNORE / information_schema 动态 ALTER，可重复执行。

-- ---------- 1) 开票申请单（tasks 10.2/10.3/10.4 载体） ----------
-- 一一对应约束：同一发货单仅一张申请（UK_SD_INVAPPLY_SHIP），SO 可挂多张。
CREATE TABLE IF NOT EXISTS erp_sd_invoice_apply (
    ID VARCHAR(64) NOT NULL,
    -- IA + yyyyMMdd + 4 位流水
    APPLY_NO VARCHAR(32) NOT NULL COMMENT '开票申请单号',
    SHIP_ID VARCHAR(64) NOT NULL COMMENT '来源发货单（发票与发货一一对应 FR-4.3-7-1）',
    SHIP_NO VARCHAR(32) DEFAULT NULL,
    SO_ID VARCHAR(64) DEFAULT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    -- 发货确认金额（基准）与申请开票金额（可修改，提交时按 TOLERANCE_DEFAULT 校验）
    SHIP_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '该次发货金额',
    APPLY_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '申请开票金额（与发货额差超容差阻断）',
    -- 税率取客户/物料税码（FR-4.3-7-1），含税口径：APPLY_AMOUNT 为含税额
    TAX_CODE VARCHAR(32) DEFAULT NULL,
    TAX_RATE DECIMAL(10,4) DEFAULT NULL,
    NET_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '不含税额',
    TAX_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '税额',
    -- 税务资质校验（C-4.3-06 L1）：提交时判定，未过阻断开具增值税专用发票
    TAX_QUALIFIED VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '1 通过 / 0 未通过',
    TAX_FAIL_REASON VARCHAR(255) DEFAULT NULL,
    INVOICE_TYPE VARCHAR(16) NOT NULL DEFAULT 'VAT_SPECIAL' COMMENT 'VAT_SPECIAL 专票 / VAT_GENERAL 普票',
    -- DRAFT 已生成 / AUDITING 待财务审核 / APPROVED 审核通过 / RETURNED 退回修改 /
    -- ISSUED 已开具 / CONFIRMED 客户确认 / DISPUTED 客户异议 / RED 已红冲 / CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    AUDIT_BY VARCHAR(64) DEFAULT NULL,
    AUDIT_AT DATETIME DEFAULT NULL,
    AUDIT_OPINION VARCHAR(500) DEFAULT NULL,
    ISSUE_BY VARCHAR(64) DEFAULT NULL,
    ISSUE_AT DATETIME DEFAULT NULL,
    INVOICE_ID VARCHAR(64) DEFAULT NULL COMMENT '销项发票 ID（开具回写）',
    INVOICE_NO VARCHAR(64) DEFAULT NULL COMMENT '发票号（回写 SO 与应收）',
    AR_ID VARCHAR(64) DEFAULT NULL,
    AR_NO VARCHAR(32) DEFAULT NULL,
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    DISPUTE_NOTE VARCHAR(500) DEFAULT NULL COMMENT '客户异议说明（协商或转红字）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SD_INVAPPLY_NO (APPLY_NO),
    UNIQUE KEY UK_SD_INVAPPLY_SHIP (SHIP_ID),
    KEY IDX_SD_INVAPPLY_STATUS (STATUS),
    KEY IDX_SD_INVAPPLY_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_SD_INVAPPLY_SO (SO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='开票申请单（按次开票，3.8.1）';

-- ---------- 2) 销项发票台账（tasks 10.4/10.5，外部开票系统按桩口径） ----------
CREATE TABLE IF NOT EXISTS erp_fin_sales_invoice (
    ID VARCHAR(64) NOT NULL,
    -- FP + yyyyMMdd + 4 位流水
    INVOICE_NO VARCHAR(64) NOT NULL COMMENT '发票号码（回写 SO 与应收）',
    EXTERNAL_NO VARCHAR(64) DEFAULT NULL COMMENT '外部开票系统流水（桩返回）',
    APPLY_ID VARCHAR(64) DEFAULT NULL,
    APPLY_NO VARCHAR(32) DEFAULT NULL,
    SHIP_ID VARCHAR(64) DEFAULT NULL,
    SHIP_NO VARCHAR(32) DEFAULT NULL,
    SO_ID VARCHAR(64) DEFAULT NULL,
    SO_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    TAX_NO VARCHAR(64) DEFAULT NULL COMMENT '购方税号快照',
    INVOICE_TYPE VARCHAR(16) NOT NULL DEFAULT 'VAT_SPECIAL' COMMENT 'VAT_SPECIAL 专票 / VAT_GENERAL 普票',
    INVOICE_DATE DATE NOT NULL COMMENT '开票日期',
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '含税总额',
    NET_AMOUNT DECIMAL(18,2) DEFAULT NULL,
    TAX_RATE DECIMAL(10,4) DEFAULT NULL,
    TAX_AMOUNT DECIMAL(18,2) DEFAULT NULL,
    -- ISSUED 已开具 / CONFIRMED 客户确认 / DISPUTED 异议 / VOID 作废
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ISSUED',
    AR_ID VARCHAR(64) DEFAULT NULL,
    AR_NO VARCHAR(32) DEFAULT NULL,
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    DISPUTE_NOTE VARCHAR(500) DEFAULT NULL,
    RED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '累计红字冲销额',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_SINV_NO (INVOICE_NO),
    KEY IDX_FIN_SINV_APPLY (APPLY_ID),
    KEY IDX_FIN_SINV_CUST (CUSTOMER_ID, INVOICE_DATE),
    KEY IDX_FIN_SINV_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销项发票台账（本地建模，外部开票系统桩）';

-- ---------- 3) 红字发票台账（task 10.5，spec 红字发票与应收红冲 D14） ----------
CREATE TABLE IF NOT EXISTS erp_fin_red_invoice (
    ID VARCHAR(64) NOT NULL,
    -- FPZ + yyyyMMdd + 4 位流水
    RED_NO VARCHAR(64) NOT NULL COMMENT '红字发票号',
    ORIGIN_INVOICE_ID VARCHAR(64) DEFAULT NULL COMMENT '原发票 ID',
    ORIGIN_INVOICE_NO VARCHAR(64) DEFAULT NULL COMMENT '原发票号（spec：关联原发票编号）',
    AR_ID VARCHAR(64) DEFAULT NULL,
    AR_NO VARCHAR(32) DEFAULT NULL COMMENT '被红冲的应收单号',
    RETURN_ID VARCHAR(64) DEFAULT NULL COMMENT '退货单 ID（12 组回填）',
    RETURN_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    RED_DATE DATE NOT NULL COMMENT '红字开具日期',
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '冲销金额（含税）',
    NET_AMOUNT DECIMAL(18,2) DEFAULT NULL,
    TAX_RATE DECIMAL(10,4) DEFAULT NULL,
    TAX_AMOUNT DECIMAL(18,2) DEFAULT NULL,
    REASON VARCHAR(500) DEFAULT NULL COMMENT '红冲原因（客户异议/退货退款）',
    -- ISSUED 已开具
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ISSUED',
    ISSUE_BY VARCHAR(64) DEFAULT NULL,
    ISSUE_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_RED_NO (RED_NO),
    KEY IDX_FIN_RED_ORIGIN (ORIGIN_INVOICE_ID),
    KEY IDX_FIN_RED_AR (AR_ID),
    KEY IDX_FIN_RED_RETURN (RETURN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='红字发票台账（关联原票与退货单，应收红冲留痕）';

-- ---------- 4) 应收明细行（task 10.1；对账逐笔与物料级追溯） ----------
CREATE TABLE IF NOT EXISTS erp_fin_ar_item (
    ID VARCHAR(64) NOT NULL,
    AR_ID VARCHAR(64) NOT NULL,
    AR_NO VARCHAR(32) DEFAULT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    SO_LINE_ID VARCHAR(64) DEFAULT NULL,
    SHIP_LINE_ID VARCHAR(64) DEFAULT NULL COMMENT '来源发货行（一一对应追溯）',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(255) DEFAULT NULL,
    QTY DECIMAL(18,3) DEFAULT NULL,
    BASE_UNIT VARCHAR(16) DEFAULT NULL,
    UNIT_PRICE DECIMAL(18,4) DEFAULT NULL,
    AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '行含税金额',
    TAX_RATE DECIMAL(10,4) DEFAULT NULL,
    TAX_AMOUNT DECIMAL(18,2) DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_FIN_ARI_AR (AR_ID, LINE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='应收明细行（物料级，支撑对账明细）';

-- ---------- 5) 客户回款登记（task 10.6：FIFO 自动核销输入 + 无法匹配转人工） ----------
CREATE TABLE IF NOT EXISTS erp_fin_ar_receipt (
    ID VARCHAR(64) NOT NULL,
    -- RC + yyyyMMdd + 4 位流水
    RCPT_NO VARCHAR(32) NOT NULL COMMENT '回款单号',
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL COMMENT '到账金额',
    PAY_DATE DATE NOT NULL COMMENT '到账日期',
    MATCHED_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '已自动核销金额',
    UNMATCHED_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '未匹配余额（转人工）',
    -- AUTO 全额自动匹配 / PARTIAL 部分匹配余量待人工 / PENDING 无法匹配（无未清应收）/ MANUAL 人工核销完成
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    VOUCHER_ID VARCHAR(64) DEFAULT NULL COMMENT '核销凭证 ID',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_RC_NO (RCPT_NO),
    KEY IDX_FIN_RC_CUST (CUSTOMER_ID, PAY_DATE),
    KEY IDX_FIN_RC_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户回款登记（FIFO 核销输入，3.8.2）';

-- ---------- 6) 月度对账单（task 10.7，FR-4.3-7-6） ----------
CREATE TABLE IF NOT EXISTS erp_fin_ar_statement (
    ID VARCHAR(64) NOT NULL,
    -- ST + yyyyMMdd + 4 位流水
    STMT_NO VARCHAR(32) NOT NULL COMMENT '对账单号',
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    PERIOD VARCHAR(6) NOT NULL COMMENT '对账期间 yyyyMM',
    OPEN_BAL DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '期初余额',
    INVOICE_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '本期开票',
    WRITEOFF_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '本期核销/回款',
    CLOSE_BAL DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '期末余额',
    UNPAID_CNT INT NOT NULL DEFAULT 0 COMMENT '未核销笔数',
    -- GENERATED 已生成 / CONFIRMED 已与客户确认
    STATUS VARCHAR(16) NOT NULL DEFAULT 'GENERATED',
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FIN_STMT_NO (STMT_NO),
    UNIQUE KEY UK_FIN_STMT_CUST_PERIOD (CUSTOMER_ID, PERIOD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='月度应收对账单头';

CREATE TABLE IF NOT EXISTS erp_fin_ar_statement_line (
    ID VARCHAR(64) NOT NULL,
    STMT_ID VARCHAR(64) NOT NULL,
    AR_ID VARCHAR(64) NOT NULL,
    AR_NO VARCHAR(32) DEFAULT NULL,
    INVOICE_NO VARCHAR(64) DEFAULT NULL COMMENT '关联销项发票号',
    INVOICE_DATE DATE DEFAULT NULL,
    DUE_DATE DATE DEFAULT NULL,
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    PAID_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '期末余额',
    WRITEOFF_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '本期核销额',
    OVERDUE_DAYS INT NOT NULL DEFAULT 0 COMMENT '超期天数（正数=逾期）',
    DIFF_AMT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '与客户确认的差异金额',
    -- PENDING 待排查 / CHECKED 已核对 / DIFF 有差异
    CHECK_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    CHECK_NOTE VARCHAR(500) DEFAULT NULL COMMENT '逐笔排查记录',
    CHECK_BY VARCHAR(64) DEFAULT NULL,
    CHECK_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_FIN_STL_STMT (STMT_ID),
    KEY IDX_FIN_STL_AR (AR_ID),
    KEY IDX_FIN_STL_CHECK (CHECK_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='对账单明细行（未核销逐笔 + 差异排查）';

-- ---------- 7) 合同与收款计划提前建（task 10.8 计划达成依赖；14 组 tasks 14.1 复用） ----------
CREATE TABLE IF NOT EXISTS erp_crm_contract (
    ID VARCHAR(64) NOT NULL,
    -- CT + yyyyMMdd + 4 位流水，创建后不可改（spec sales-contract）
    CONTRACT_NO VARCHAR(32) NOT NULL COMMENT '合同编号（生成后锁定）',
    OPP_ID VARCHAR(64) DEFAULT NULL COMMENT '来源商机（金额带出）',
    OPP_NAME VARCHAR(255) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) NOT NULL,
    CUSTOMER_CODE VARCHAR(32) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    TITLE VARCHAR(255) NOT NULL COMMENT '合同名称',
    OPP_AMOUNT DECIMAL(18,2) DEFAULT NULL COMMENT '商机预期金额（差异校验基准）',
    AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '合同金额',
    DIFF_RATE DECIMAL(8,4) DEFAULT NULL COMMENT '差异率（(AMOUNT-OPP_AMOUNT)/OPP_AMOUNT）',
    SIGN_DATE DATE DEFAULT NULL COMMENT '签订日期',
    START_DATE DATE DEFAULT NULL,
    END_DATE DATE DEFAULT NULL,
    -- DRAFT 草稿 / APPROVING 审批中 / LEGAL_REVIEW 法务审核 / SIGNED 已签订 /
    -- REJECTED 驳回 / CHANGED 已变更 / TERMINATED 已终止
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    PREV_STATUS VARCHAR(16) DEFAULT NULL,
    APPROVAL_ID VARCHAR(64) DEFAULT NULL,
    LEGAL_REVIEW_BY VARCHAR(64) DEFAULT NULL COMMENT '法务审核人（占位登记，意见必填）',
    LEGAL_REVIEW_OPINION VARCHAR(500) DEFAULT NULL,
    LEGAL_REVIEW_AT DATETIME DEFAULT NULL,
    VERSION_NO INT NOT NULL DEFAULT 1 COMMENT '当前版本（变更 +1，历史只读）',
    SO_COUNT INT NOT NULL DEFAULT 0 COMMENT '名下 SO 数（关联回写）',
    TERMINATE_REASON VARCHAR(500) DEFAULT NULL,
    CLOSED_BY VARCHAR(64) DEFAULT NULL,
    CLOSED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CRM_CT_NO (CONTRACT_NO),
    KEY IDX_CRM_CT_CUST (CUSTOMER_ID, STATUS),
    KEY IDX_CRM_CT_OPP (OPP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售合同（11.11，与框架协议独立 D11）';

CREATE TABLE IF NOT EXISTS erp_crm_contract_plan (
    ID VARCHAR(64) NOT NULL,
    CONTRACT_ID VARCHAR(64) NOT NULL,
    CONTRACT_NO VARCHAR(32) DEFAULT NULL,
    CUSTOMER_ID VARCHAR(64) DEFAULT NULL,
    PERIOD_NO INT NOT NULL COMMENT '期数（1 起）',
    PLAN_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '计划收款金额（不参与记账 D10）',
    DUE_DATE DATE NOT NULL COMMENT '计划到期日',
    PAID_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '实际已核销（关联核销记录汇总）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CRM_CTP (CONTRACT_ID, PERIOD_NO),
    KEY IDX_CRM_CTP_CUST (CUSTOMER_ID, DUE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合同收款计划分期（计划达成对比 10.8/11.11.2）';

CREATE TABLE IF NOT EXISTS erp_crm_contract_version (
    ID VARCHAR(64) NOT NULL,
    CONTRACT_ID VARCHAR(64) NOT NULL,
    VERSION_NO INT NOT NULL,
    SNAPSHOT_JSON LONGTEXT NOT NULL COMMENT '版本快照',
    DIFF_SUMMARY VARCHAR(500) DEFAULT NULL,
    OP_TYPE VARCHAR(16) NOT NULL COMMENT 'CREATE / UPDATE / TERMINATE',
    CHANGE_REASON VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CRM_CTV (CONTRACT_ID, VERSION_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合同版本历史（14.6 变更留痕，历史只读）';

-- ---------- 8) 动态扩展列（information_schema + PREPARE 幂等，040/053 范式） ----------

-- 8.1 应收头：开票/发货/税务回写列（tasks 10.2/10.4/10.5）
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_fin_ar_invoice'
        AND COLUMN_NAME = 'APPLY_NO') = 0,
    'ALTER TABLE erp_fin_ar_invoice
       ADD COLUMN APPLY_ID VARCHAR(64) DEFAULT NULL COMMENT ''开票申请 ID'' AFTER SO_NO,
       ADD COLUMN APPLY_NO VARCHAR(32) DEFAULT NULL COMMENT ''开票申请单号'' AFTER APPLY_ID,
       ADD COLUMN SHIP_ID VARCHAR(64) DEFAULT NULL COMMENT ''来源发货单（一一对应）'' AFTER APPLY_NO,
       ADD COLUMN SHIP_NO VARCHAR(32) DEFAULT NULL AFTER SHIP_ID,
       ADD COLUMN INVOICE_ID VARCHAR(64) DEFAULT NULL COMMENT ''销项发票 ID（开具回写）'' AFTER SHIP_NO,
       ADD COLUMN INVOICE_NO VARCHAR(64) DEFAULT NULL COMMENT ''发票号回写'' AFTER INVOICE_ID,
       ADD COLUMN TAX_CODE VARCHAR(32) DEFAULT NULL AFTER INVOICE_NO,
       ADD COLUMN TAX_RATE DECIMAL(10,4) DEFAULT NULL AFTER TAX_CODE,
       ADD COLUMN TAX_AMOUNT DECIMAL(18,2) DEFAULT NULL AFTER TAX_RATE,
       ADD COLUMN RED_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT ''累计红字冲销额'' AFTER PAID_AMOUNT',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 8.2 核销记录：回款单与凭证关联（task 10.6/10.7）
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_fin_ar_writeoff'
        AND COLUMN_NAME = 'RECEIPT_ID') = 0,
    'ALTER TABLE erp_fin_ar_writeoff
       ADD COLUMN RECEIPT_ID VARCHAR(64) DEFAULT NULL COMMENT ''回款单 ID'' AFTER WRITE_TYPE,
       ADD COLUMN RECEIPT_NO VARCHAR(32) DEFAULT NULL AFTER RECEIPT_ID,
       ADD COLUMN VOUCHER_ID VARCHAR(64) DEFAULT NULL COMMENT ''核销凭证 ID'' AFTER RECEIPT_NO,
       ADD COLUMN WO_AMT_BEFORE DECIMAL(18,2) DEFAULT NULL COMMENT ''核销前该应收已核销额'' AFTER VOUCHER_ID',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 8.3 SO 头：合同关联（task 14.3 提前，10.8 计划达成链路 合同→SO→应收）
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_sd_so'
        AND COLUMN_NAME = 'CONTRACT_ID') = 0,
    'ALTER TABLE erp_sd_so
       ADD COLUMN CONTRACT_ID VARCHAR(64) DEFAULT NULL COMMENT ''来源合同 ID（14.3 回写）'' AFTER OPP_ID,
       ADD COLUMN CONTRACT_NO VARCHAR(32) DEFAULT NULL COMMENT ''来源合同编号'' AFTER CONTRACT_ID,
       ADD COLUMN INVOICE_NO VARCHAR(64) DEFAULT NULL COMMENT ''最近发票号（开具回写）'' AFTER CLOSE_CONFIRM_BY',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 8.4 客户主数据：税务资质（C-4.3-06 L1 阻断：税号 + 一般纳税人资格有效期）
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_mdm_customer_group'
        AND COLUMN_NAME = 'TAXPAYER_TYPE') = 0,
    'ALTER TABLE erp_mdm_customer_group
       ADD COLUMN TAXPAYER_TYPE VARCHAR(16) DEFAULT NULL COMMENT ''GENERAL 一般纳税人 / SMALL 小规模 / NULL 未维护'' AFTER LICENSE_EXPIRE,
       ADD COLUMN TAX_QUAL_EXPIRE DATE DEFAULT NULL COMMENT ''一般纳税人资格有效期（空=不校验）'' AFTER TAXPAYER_TYPE,
       ADD COLUMN TAX_CODE VARCHAR(32) DEFAULT NULL COMMENT ''销售税码（税率来源之一）'' AFTER TAX_QUAL_EXPIRE',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 8.5 物料主数据：税码（税率来源之二，FR-4.3-7-1）
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'erp_mdm_item'
        AND COLUMN_NAME = 'TAX_CODE') = 0,
    'ALTER TABLE erp_mdm_item
       ADD COLUMN TAX_CODE VARCHAR(32) DEFAULT NULL COMMENT ''销项税码（空则取客户税码，再缺省 VAT13）'' AFTER STANDARD_COST',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 9) 税码种子（erp_mdm_tax_code 本轮为空，按闭区间生效） ----------
INSERT IGNORE INTO erp_mdm_tax_code
(ID, TAX_CODE, TAX_RATE, EFFECTIVE_DATE, EXPIRE_DATE, SCOPE, POLICY_NO, CALC_TYPE, RATE_KIND, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('seed-tax-vat13', 'VAT13', 0.1300, '2020-01-01', '2030-12-31', 'DOMESTIC', 'POL-VAT-STD', 'GENERAL', 'STANDARD', 'seed', '0', 0),
('seed-tax-vat09', 'VAT09', 0.0900, '2020-01-01', '2030-12-31', 'DOMESTIC', 'POL-VAT-STD', 'GENERAL', 'LOW', 'seed', '0', 0),
('seed-tax-vat06', 'VAT06', 0.0600, '2020-01-01', '2030-12-31', 'DOMESTIC', 'POL-VAT-STD', 'GENERAL', 'LOW', 'seed', '0', 0),
('seed-tax-vat00', 'VAT00', 0.0000, '2020-01-01', '2030-12-31', 'DOMESTIC', 'POL-VAT-ZERO', 'GENERAL', 'ZERO', 'seed', '0', 0);

-- 客户/物料税码与税务资质回填（只补空值，幂等）
UPDATE erp_mdm_customer_group SET TAX_CODE = 'VAT13', TAXPAYER_TYPE = 'GENERAL',
       TAX_QUAL_EXPIRE = DATE_ADD(CURDATE(), INTERVAL 2 YEAR)
 WHERE TAX_CODE IS NULL;
-- 9005 作为 C-4.3-06 过期样本（资格已过期 → 阻断开专票）
UPDATE erp_mdm_customer_group SET TAXPAYER_TYPE = 'GENERAL', TAX_QUAL_EXPIRE = DATE_SUB(CURDATE(), INTERVAL 10 DAY)
 WHERE ID = 'seed-cust-9005';
UPDATE erp_mdm_item SET TAX_CODE = 'VAT13' WHERE TAX_CODE IS NULL;

-- ---------- 10) 科目种子（核销凭证：借 1002 银行存款 / 贷 1122 应收账款） ----------
INSERT IGNORE INTO erp_fin_account (ID, ACCOUNT_CODE, ACCOUNT_NAME, DIRECTION, CATEGORY, STATUS) VALUES
('ACC-1122',    '1122',    '应收账款',        'DR', 'ASSET', 'ACTIVE'),
('ACC-222102',  '222102',  '应交税费-销项税',  'CR', 'LIAB',  'ACTIVE'),
('ACC-6001',    '6001',    '主营业务收入',    'CR', 'PROFIT', 'ACTIVE');

-- ---------- 11) 参数种子（应收到期日基准） ----------
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-ar-due-days', 'AR_DUE_DAYS', '30', 'DAYS', 'FIN',
 '应收到期日 = 开票日 + 该天数（SO 付款条件含数字时以付款条件为准）', 'seed', '0', 0);
