-- 102 批次与序列主数据（change add-batch-serial-master，spec batch-master / serial-master）
-- 4.2.1 批次台账 + 库存入库日期（FIFO 数据地基）；4.2.2 序列台账与流转留痕 + 物料序列标识
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / information_schema + PREPARE 动态 DDL（040、055、101 范式）

-- ---------- 1) 批次台账（spec batch-master，design D1） ----------
CREATE TABLE IF NOT EXISTS erp_inv_batch (
    ID VARCHAR(64) NOT NULL,
    -- 同物料唯一（UK: ITEM_CODE + BATCH_NO）；系统生成 B+yyMMdd+-+4位日流水或手工录入
    BATCH_NO VARCHAR(64) NOT NULL COMMENT '批次号（创建后不可改）',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    PRODUCTION_DATE DATE DEFAULT NULL COMMENT '生产日期',
    EXPIRY_DATE DATE DEFAULT NULL COMMENT '有效期至（批次管理物料必填，BR-4.1-08）',
    SUPPLIER_BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '供应商批次号（追溯索引 BR-4.4-48）',
    SOURCE_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '来源单据号',
    -- 1 正常 / 0 关闭（关闭=退出后续可选范围，不影响既有引用）
    STATUS VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '1 正常 / 0 关闭',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_BATCH (ITEM_CODE, BATCH_NO),
    KEY IDX_INV_BATCH_EXPIRY (EXPIRY_DATE),
    KEY IDX_INV_BATCH_SUPPLIER (SUPPLIER_BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='批次台账（4.2.1）';

-- ---------- 2) 序列号台账（spec serial-master，design D1：全局唯一防串码） ----------
CREATE TABLE IF NOT EXISTS erp_inv_serial (
    ID VARCHAR(64) NOT NULL,
    -- 全局唯一（跨物料），录入侧直接暴露 BR-4.11-15 串码
    SERIAL_NO VARCHAR(64) NOT NULL COMMENT '序列号（创建后不可改）',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '批次号（可空，不强制存在于批次台账）',
    -- IN_STOCK / OUT / FROZEN / SCRAPPED；OUT 与 SCRAPPED 为终态
    STATUS VARCHAR(16) NOT NULL DEFAULT 'IN_STOCK' COMMENT '状态机状态',
    SOURCE_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '来源单据号',
    LOCATION_REMARK VARCHAR(255) DEFAULT NULL COMMENT '存放位置备注',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_SERIAL (SERIAL_NO),
    KEY IDX_INV_SERIAL_ITEM (ITEM_CODE, STATUS),
    KEY IDX_INV_SERIAL_BATCH (BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='序列号台账（4.2.2）';

-- ---------- 3) 序列状态流转留痕（纯追加日志，design D1/D3） ----------
CREATE TABLE IF NOT EXISTS erp_inv_serial_log (
    ID VARCHAR(64) NOT NULL,
    SERIAL_ID VARCHAR(64) NOT NULL,
    SERIAL_NO VARCHAR(64) NOT NULL,
    FROM_STATUS VARCHAR(16) NOT NULL,
    TO_STATUS VARCHAR(16) NOT NULL,
    REASON VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    KEY IDX_INV_SERLOG_SERIAL (SERIAL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='序列状态流转留痕（4.2.2）';

-- ---------- 4) 库存加入库日期列（spec batch-master FIFO 数据地基，055 幂等 ALTER 范式） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_stock'
        AND COLUMN_NAME = 'INBOUND_DATE') = 0,
    'ALTER TABLE erp_inv_stock
       ADD COLUMN INBOUND_DATE DATE DEFAULT NULL
         COMMENT ''入库日期（首插记录、补货不刷新，BR-4.4-19 FIFO 排序依据）'' AFTER AVAILABLE_QTY',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 存量回填：以行首次创建日期近似入库日期（幂等，只填空值）
UPDATE erp_inv_stock SET INBOUND_DATE = DATE(CREATE_DATE)
 WHERE INBOUND_DATE IS NULL;

-- ---------- 5) 物料加序列管理标识（spec serial-master） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_mdm_item'
        AND COLUMN_NAME = 'SERIAL_FLAG') = 0,
    'ALTER TABLE erp_mdm_item
       ADD COLUMN SERIAL_FLAG VARCHAR(1) NOT NULL DEFAULT ''0''
         COMMENT ''序列管理标识（1=开启，出入库强制逐件校验序列号的判定依据）'' AFTER BATCH_FLAG',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 6) 存量库菜单 PERM 补丁（任务 6.2 同 101 尾部范式） ----------
-- 099 已被 marker 跳过不会重跑：099 产物中两行 PERM 已更新，存量库由此处幂等补齐。
UPDATE erp_admin_menu
   SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-2-1', 'M4-2-2');
