-- 103 库存快照与冻结管理（change add-stock-snapshot-three-state，spec stock-snapshot / freeze-management）
-- 4.3.1/4.3.2/4.3.3 三态快照：FIN_QTY 双轨冻结 + 冻结台账 + 恒等式校验报告 + 日结余额快照
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / information_schema + PREPARE 动态 DDL（040、055、101、102 范式）

-- ---------- 1) 库存加财务冻结列（spec freeze-management，design D1：与 QC_QTY 并列可叠加） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_stock'
        AND COLUMN_NAME = 'FIN_QTY') = 0,
    'ALTER TABLE erp_inv_stock
       ADD COLUMN FIN_QTY DECIMAL(18,4) NOT NULL DEFAULT 0
         COMMENT ''财务冻结数量（与 QC_QTY 并列，两类可叠加，C-4.4-05）'' AFTER QC_QTY',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 2) 冻结台账（spec freeze-management，design D1：PENDING→ACTIVE→RELEASED 一表流转） ----------
CREATE TABLE IF NOT EXISTS erp_inv_freeze (
    ID VARCHAR(64) NOT NULL,
    -- FZ+yyyyMMdd+4位流水；NCR 来源同样生成冻结单号（来源=NCR 只读展示）
    FREEZE_NO VARCHAR(64) NOT NULL COMMENT '冻结单号',
    -- QUALITY / FINANCE：单笔唯一（C-4.4-05），同一库存行两类可叠加
    FREEZE_TYPE VARCHAR(16) NOT NULL COMMENT '冻结类型 QUALITY/FINANCE',
    WAREHOUSE_CODE VARCHAR(32) NOT NULL COMMENT '仓库编码',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '批次号',
    QTY DECIMAL(18,4) NOT NULL COMMENT '冻结数量',
    REASON VARCHAR(500) NOT NULL COMMENT '冻结原因（必填 FR-4.4-5-1）',
    SCOPE VARCHAR(32) NOT NULL DEFAULT 'BATCH' COMMENT '影响范围：ALL/BATCH/BIN',
    -- PENDING 待审批 / ACTIVE 生效中 / RELEASED 已解冻 / REJECTED 审批驳回
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态机',
    SOURCE VARCHAR(8) NOT NULL DEFAULT 'MANUAL' COMMENT '来源 MANUAL/NCR',
    NCR_ID VARCHAR(64) DEFAULT NULL COMMENT '关联 NCR（SOURCE=NCR）',
    APPR_ID VARCHAR(64) DEFAULT NULL COMMENT '冻结审批实例 ID（BIZ_TYPE=FREEZE）',
    UNFREEZE_APPR_ID VARCHAR(64) DEFAULT NULL COMMENT '解冻审批实例 ID（独立审批 FR-4.4-5-7）',
    APPLY_BY VARCHAR(64) NOT NULL COMMENT '发起人（解冻仅原发起人 FR-4.4-5-6）',
    RELEASE_RESULT VARCHAR(500) DEFAULT NULL COMMENT '解冻-问题处理结果（必填）',
    RELEASE_BASIS VARCHAR(500) DEFAULT NULL COMMENT '解冻-依据（必填）',
    RELEASED_BY VARCHAR(64) DEFAULT NULL,
    RELEASED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_FREEZE_NO (FREEZE_NO),
    KEY IDX_INV_FREEZE_DIM (ITEM_CODE, BATCH_NO, STATUS),
    KEY IDX_INV_FREEZE_TYPE (FREEZE_TYPE, STATUS),
    KEY IDX_INV_FREEZE_NCR (NCR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='冻结台账（4.3.2 / FR-4.4-5）';

-- ---------- 3) 恒等式校验报告（spec stock-snapshot，FR-4.4-2-5 / BR-4.4-15） ----------
CREATE TABLE IF NOT EXISTS erp_inv_check_report (
    ID VARCHAR(64) NOT NULL,
    RUN_DATE DATE NOT NULL COMMENT '运行日（每日一次）',
    MISMATCH_CNT INT NOT NULL DEFAULT 0 COMMENT '差异行数（0=零差异留痕）',
    -- OK / MISMATCH
    STATUS VARCHAR(16) NOT NULL COMMENT 'OK/MISMATCH',
    DETAIL_JSON MEDIUMTEXT COMMENT '差异明细 JSON（维度+三列+标记「待核实」）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_CHECK_DATE (RUN_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存恒等式校验报告（4.3.1 待核实标记来源）';

-- ---------- 4) 日结余额快照（spec stock-snapshot，FR-4.4-2-6 / BR-4.4-17） ----------
-- 插入即终态：应用侧不提供 update 路径；已结算日的行永不修改，同日重跑 = 不存在才插入（单事务全有或全无）
CREATE TABLE IF NOT EXISTS erp_inv_daily_balance (
    ID VARCHAR(64) NOT NULL,
    BAL_DATE DATE NOT NULL COMMENT '结算日',
    WAREHOUSE_CODE VARCHAR(32) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL,
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '在手',
    AVAILABLE_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '可用工作列',
    QC_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '质量冻结',
    FIN_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '财务冻结',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_DAILY (BAL_DATE, WAREHOUSE_CODE, ITEM_CODE, BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存日结余额快照（4.3，只读语义）';

-- ---------- 5) 角色种子：财务专员（design D7：发起财务冻结，避免主管自审自批） ----------
-- SORT_ORDER 89 < ROLE_FINANCE_MGR(90)
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS)
VALUES ('role-finance', 'ROLE_FINANCE', '财务专员', 89, '1');

-- ---------- 6) 存量库菜单 PERM 补丁（沿 101/102 尾部范式） ----------
-- 099 已被 marker 跳过不会重跑：099 产物三行 PERM 已更新，存量库由此处幂等补齐。
UPDATE erp_admin_menu
   SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-3-1', 'M4-3-2', 'M4-3-3');
