-- 106 调拨单/报废单/内部发票 + 法人挂仓 + 科目参数种子（change add-outbound-workbench，
--     spec transfer-order / scrap-order / internal-transfer-accounting / outbound-workbench）
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / information_schema + PREPARE 动态 DDL（040/055/101/105 范式）

-- ---------- 1) erp_inv_warehouse 加 LE_CODE（跨法人判定唯一依据，design D4） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_warehouse'
        AND COLUMN_NAME = 'LE_CODE') = 0,
    'ALTER TABLE erp_inv_warehouse
       ADD COLUMN LE_CODE VARCHAR(32) DEFAULT NULL
         COMMENT ''所属法人 LE_CODE（空按 LE-0001，跨法人调拨判定依据）'' AFTER ORG_UNIT',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 存量回填（仅 NULL 行，幂等）
UPDATE erp_inv_warehouse SET LE_CODE = 'LE-0001' WHERE LE_CODE IS NULL;

-- ---------- 2) 调拨单头 ----------
CREATE TABLE IF NOT EXISTS erp_inv_transfer_order (
    ID VARCHAR(64) NOT NULL,
    TRANSFER_NO VARCHAR(32) NOT NULL COMMENT '调拨单号 TR+yyyyMMdd+流水',
    OUT_WH_CODE VARCHAR(32) NOT NULL COMMENT '调出仓',
    IN_WH_CODE VARCHAR(32) NOT NULL COMMENT '调入仓',
    OUT_LE_CODE VARCHAR(32) NOT NULL COMMENT '调出方法人（解析自调出仓 LE_CODE，空=LE-0001）',
    IN_LE_CODE VARCHAR(32) NOT NULL COMMENT '调入方法人',
    -- 1=跨法人（触发成对凭证/内部发票链），0=同法人移库（零凭证）
    CROSS_LE VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '跨法人标记 1/0',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT→OUT_POSTED→IN_POSTED→CLOSED（+CANCELLED）',
    -- 超 TRANSIT_ALERT_DAYS 未入库由调度置 1（保留 OUT_POSTED 语义，C-4.4-09）
    SUSPENDED_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '在途超期挂起 1/0',
    OUT_POST_AT DATETIME DEFAULT NULL COMMENT '出库过账时间（在途起算）',
    IN_POST_AT DATETIME DEFAULT NULL COMMENT '入库过账时间',
    CLOSE_BY VARCHAR(64) DEFAULT NULL,
    CLOSE_AT DATETIME DEFAULT NULL,
    CANCEL_REASON VARCHAR(255) DEFAULT NULL,
    TOTAL_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'Σ行金额（内部转移价×数量）',
    ALLOC_JSON TEXT COMMENT '出库过账分配结果 [{lineNo,itemCode,batchNo,binCode,qty}]（入库段按批入账依据）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TR_NO (TRANSFER_NO),
    KEY IDX_TR_STATUS (STATUS, SUSPENDED_FLAG),
    KEY IDX_TR_OUTWH (OUT_WH_CODE, STATUS),
    KEY IDX_TR_INWH (IN_WH_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='调拨单头（4.12.1/4.12.2/4.5.3/4.4.4 共享实体）';

-- ---------- 2b) erp_inv_transfer_order 加 ALLOC_JSON（首跑后补列场景，动态幂等） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_transfer_order'
        AND COLUMN_NAME = 'ALLOC_JSON') = 0,
    'ALTER TABLE erp_inv_transfer_order
       ADD COLUMN ALLOC_JSON TEXT
         COMMENT ''出库过账分配结果（入库段按批入账依据）'' AFTER TOTAL_AMOUNT',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 3) 调拨单行 ----------
CREATE TABLE IF NOT EXISTS erp_inv_transfer_order_line (
    ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) NOT NULL DEFAULT '' COMMENT '批次（空=过账时引擎 FIFO 分配）',
    QTY DECIMAL(18,4) NOT NULL COMMENT '调拨数量（>0）',
    -- 取价方案 a：单据行手工必填（>0），跨法人凭证/发票金额依据
    INTERNAL_PRICE DECIMAL(18,4) NOT NULL COMMENT '内部转移价（必填 >0）',
    LINE_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'QTY×INTERNAL_PRICE',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_TRL_ORDER (ORDER_ID, LINE_NO),
    KEY IDX_TRL_ITEM (ITEM_CODE, BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='调拨单行（行级内部转移价）';

-- ---------- 4) 报废单头 ----------
CREATE TABLE IF NOT EXISTS erp_inv_scrap_order (
    ID VARCHAR(64) NOT NULL,
    SCRAP_NO VARCHAR(32) NOT NULL COMMENT '报废单号 SC+yyyyMMdd+流水',
    -- STALE 呆滞（三方会签 C-4.4-14）/ QUALITY 质量（挂 NCR）/ DAMAGE 损坏 / OTHER 其他（免会签，偏差 D1）
    REASON VARCHAR(16) NOT NULL COMMENT '报废原因 STALE/QUALITY/DAMAGE/OTHER',
    NCR_NO VARCHAR(64) DEFAULT NULL COMMENT 'NCR 关联号（QUALITY 必填）',
    WAREHOUSE_CODE VARCHAR(32) NOT NULL COMMENT '报废仓库',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT→APPROVED→POSTED→DISPOSED（+CANCELLED）',
    APPR_ID VARCHAR(64) DEFAULT NULL COMMENT '三方会签审批实例 ID（仅 STALE）',
    CANCEL_REASON VARCHAR(255) DEFAULT NULL,
    POST_BY VARCHAR(64) DEFAULT NULL,
    POST_AT DATETIME DEFAULT NULL,
    DISPOSE_BY VARCHAR(64) DEFAULT NULL COMMENT '处置核销人',
    DISPOSE_AT DATETIME DEFAULT NULL,
    TOTAL_QTY DECIMAL(18,4) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '凭证金额合计（Σ行 QTY×UNIT_COST）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SC_NO (SCRAP_NO),
    KEY IDX_SC_STATUS (STATUS, REASON),
    KEY IDX_SC_NCR (NCR_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报废出库单（4.5.4，按原因分门槛）';

-- ---------- 5) 报废单行 ----------
CREATE TABLE IF NOT EXISTS erp_inv_scrap_order_line (
    ID VARCHAR(64) NOT NULL,
    ORDER_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) NOT NULL DEFAULT '',
    QTY DECIMAL(18,4) NOT NULL COMMENT '报废数量（≤该批次在手量）',
    STOCK_AGE_DAYS INT NOT NULL DEFAULT 0 COMMENT '库龄快照（创建时按位行 MIN(INBOUND_DATE) 固化）',
    -- 序列管理物料报废须携带序列号（C-4.4-02）；普通物料留空
    SERIALS VARCHAR(2000) DEFAULT NULL COMMENT '序列号清单（逗号分隔，serialFlag=1 物料必填）',
    UNIT_COST DECIMAL(18,4) DEFAULT NULL COMMENT '单位成本（凭证金额依据，可空按 0 计入合计）',
    LINE_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT 'QTY×UNIT_COST',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_SCL_ORDER (ORDER_ID, LINE_NO),
    KEY IDX_SCL_ITEM (ITEM_CODE, BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报废单行（库龄快照/单位成本）';

-- ---------- 5b) 报废行加 SERIALS（首跑后补列场景，动态幂等） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_scrap_order_line'
        AND COLUMN_NAME = 'SERIALS') = 0,
    'ALTER TABLE erp_inv_scrap_order_line
       ADD COLUMN SERIALS VARCHAR(2000) DEFAULT NULL
         COMMENT ''序列号清单（逗号分隔，serialFlag=1 物料必填）'' AFTER STOCK_AGE_DAYS',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 6) 内部发票台账（F3/I2：独立台账，不进销售开票域） ----------
CREATE TABLE IF NOT EXISTS erp_fin_internal_invoice (
    ID VARCHAR(64) NOT NULL,
    INT_INV_NO VARCHAR(32) NOT NULL COMMENT '内部发票号 IT+yyyyMMdd+流水（桩口径自生成）',
    DIRECTION VARCHAR(4) NOT NULL COMMENT 'OUT=内部销售票（调出方视角）/ IN=内部采购票（调入方视角）',
    TRANSFER_NO VARCHAR(32) NOT NULL COMMENT '调拨单号（1:1 配对锚点）',
    OUT_LE_CODE VARCHAR(32) NOT NULL COMMENT '调出方法人',
    IN_LE_CODE VARCHAR(32) NOT NULL COMMENT '调入方法人',
    ISSUER_LE_CODE VARCHAR(32) NOT NULL COMMENT '开票方法人（OUT=调出方 / IN=调入方）',
    NET_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '不含税金额',
    TAX_RATE DECIMAL(6,4) NOT NULL DEFAULT 0.1300 COMMENT '税率（缺省 VAT13）',
    TAX_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT DECIMAL(18,2) NOT NULL COMMENT '含税金额（配对核销比较口径）',
    PAIR_ID VARCHAR(64) DEFAULT NULL COMMENT '配对票 ID（入库过账自动核销时回填）',
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ISSUED' COMMENT 'ISSUED→SETTLED',
    SETTLED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_IT_NO (INT_INV_NO),
    KEY IDX_IT_TRANSFER (TRANSFER_NO, DIRECTION, STATUS),
    KEY IDX_IT_LE_PAIR (OUT_LE_CODE, IN_LE_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='跨法人内部发票台账（成对配对核销，spec internal-transfer-accounting）';

-- ---------- 7) 科目种子：调拨在途 / 待处理财产损溢 / 营业外支出（104/46/47 INSERT IGNORE 范式） ----------
INSERT IGNORE INTO erp_fin_account (ID, ACCOUNT_CODE, ACCOUNT_NAME, DIRECTION, CATEGORY, STATUS) VALUES
('ACC-1461', '1461', '调拨在途',       'DR', 'ASSET', 'ACTIVE'),
('ACC-1901', '1901', '待处理财产损溢', 'DR', 'ASSET', 'ACTIVE'),
('ACC-6711', '6711', '营业外支出',     'DR', '损益',  'ACTIVE');

-- ---------- 8) 参数种子：呆滞阈值 / 在途超期阈值 ----------
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-slow-moving-age', 'SLOW_MOVING_AGE_DAYS', '180', 'DAYS', 'INV',
 '呆滞判定库龄阈值：库龄超过该天数的报废单强制技术/质量/财务三方会签（C-4.4-14）', 'seed', '0', 0),
('param-transit-alert', 'TRANSIT_ALERT_DAYS', '30', 'DAYS', 'INV',
 '跨仓/跨法人调拨在途超期阈值：出库后超过该天数未入库自动挂起并通知双方主管（C-4.4-09）', 'seed', '0', 0);

-- ---------- 9) 法人种子：LE-0001 回填税号（仅 NULL 行）+ 新增 LE-0002（跨法人链路演示） ----------
UPDATE erp_mdm_legal_entity
   SET LOCAL_TAX_NO = USCC
 WHERE LE_CODE = 'LE-0001' AND LOCAL_TAX_NO IS NULL AND USCC IS NOT NULL;

INSERT IGNORE INTO erp_mdm_legal_entity
    (ID, LE_CODE, LE_NAME, USCC, STATUS, BOOKKEEPING_CURRENCY, REG_PLACE, FISCAL_CALENDAR_TYPE, DEFAULT_TIMEZONE, CURRENCY_DECIMALS, L10N_PACK, LOCAL_TAX_NO, CREATE_BY)
VALUES
    ('le-0002', 'LE-0002', '示例法人主体（苏州）', '91320500MA1NX0000Y', '1', 'CNY', '苏州', 'NATURAL', 'Asia/Shanghai', 2, 'CN', '91320500MA1NX0000Y', 'system');

-- 跨法人演示仓（属 LE-0002；存量仓已在本迁移第 1 步回填 LE-0001）
INSERT IGNORE INTO erp_inv_warehouse
(ID, WH_CODE, WH_NAME, ORG_UNIT, LE_CODE, STATUS, CAPACITY_DESC, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('wh-le2', 'WH-LE2', '苏州跨法人调拨演示仓', NULL, 'LE-0002', '1', '', 'add-outbound-workbench 跨法人链路演示仓', 'seed', '0', 0);

-- ---------- 9b) SCRAP_OUT 类型开关修正 ----------
-- 104 预注册为 NEED_SERIAL=1：type 标志使引擎对**全部**行强制序列（非序列物料报废被误拦）。
-- 改为 0：C-4.4-02 序列校验由物料 serialFlag 驱动（stock-doc-type「物料主数据优先，配置不解除硬校验」），
-- 序列管理物料报废行经 SERIALS 列携带序列走引擎判重。
UPDATE erp_inv_doc_type SET NEED_SERIAL = 0
 WHERE TYPE_CODE = 'SCRAP_OUT' AND NEED_SERIAL = 1;

-- ---------- 10) 存量库菜单 PERM 补丁（099 产物由生成器覆盖，存量库由此处幂等补齐） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-5-1', 'M4-5-2', 'M4-5-3', 'M4-5-4', 'M4-12-1', 'M4-12-2');
