-- 110 拣货复核：拣货任务/任务行/通用差异单/扫码校验记录 + 4.7 菜单 PERM 存量回填
--     （change add-picking-review，spec picking-review；design D6）
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / information_schema+PREPARE 动态 DDL / UPDATE 幂等

-- ---------- 1) 拣货任务（单据级，SRC UK 防 4.6.3 重复确认重复生成） ----------
CREATE TABLE IF NOT EXISTS erp_pick_task (
    ID VARCHAR(64) NOT NULL,
    TASK_NO VARCHAR(32) NOT NULL COMMENT '任务号 PT+yyyyMMdd+流水',
    -- 来源单据：SALES_OUT / MATERIAL_OUT / TRANSFER_OUT / SCRAP_OUT
    SRC_TYPE VARCHAR(32) NOT NULL COMMENT '来源出库类型',
    SRC_DOC_ID VARCHAR(64) DEFAULT NULL,
    SRC_DOC_NO VARCHAR(64) NOT NULL COMMENT '来源单据号（活跃任务幂等由锁定读保证）',
    -- CREATED→PICKING→PICKED→REVIEWING→DONE→COMPLETED；分支 DIFF_PENDING/QUALITY_PENDING/CANCELLED
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED' COMMENT '任务状态机',
    PICKER VARCHAR(64) DEFAULT NULL COMMENT '拣货员',
    REVIEWER VARCHAR(64) DEFAULT NULL COMMENT '复核员',
    -- 改派留痕（design D3）
    PREV_PICKER VARCHAR(64) DEFAULT NULL COMMENT '改派前拣货员',
    ASSIGN_BY VARCHAR(64) DEFAULT NULL,
    ASSIGN_AT DATETIME DEFAULT NULL,
    CANCEL_REASON VARCHAR(500) DEFAULT NULL,
    PICK_AT DATETIME DEFAULT NULL COMMENT '拣货完成时间',
    REVIEW_AT DATETIME DEFAULT NULL COMMENT '复核完成时间',
    COMPLETE_AT DATETIME DEFAULT NULL COMMENT '过账联动完成时间',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 非唯一索引：作废(CANCELLED)后重新确认须生成新任务，唯一键会挡；
    -- 幂等靠 createFromDoc 的 SELECT...FOR UPDATE 锁定读（design D1）
    KEY IDX_PICK_TASK_SRC (SRC_TYPE, SRC_DOC_NO),
    KEY IDX_PICK_TASK_STATUS (STATUS),
    KEY IDX_PICK_TASK_NO (TASK_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='拣货任务（4.7.1，单据级任务+行级明细）';

-- ---------- 2) 拣货任务行（批次/仓位来自 4.6.3 回写单据行） ----------
CREATE TABLE IF NOT EXISTS erp_pick_task_line (
    ID VARCHAR(64) NOT NULL,
    TASK_ID VARCHAR(64) NOT NULL,
    LINE_NO INT NOT NULL DEFAULT 1,
    SRC_LINE_ID VARCHAR(64) DEFAULT NULL COMMENT '来源单据行 ID',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    WAREHOUSE_CODE VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '4.6.3 回写批次',
    BIN_CODE VARCHAR(64) DEFAULT NULL COMMENT '4.6.3 回写仓位',
    QTY DECIMAL(18,4) NOT NULL COMMENT '应拣数量',
    PICKED_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '实拣数量',
    -- PENDING→PICKED（扫码确认）；SHORT=短少转差异
    LINE_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '行状态',
    SCAN_OK_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '码校验放行标记 1/0',
    -- PASS / DIFF / QUALITY（复核三分支结论）
    REVIEW_RESULT VARCHAR(16) DEFAULT NULL COMMENT '复核结论',
    SERIALS VARCHAR(2000) DEFAULT NULL COMMENT '录入序列号（逗号分隔）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_PICK_LINE_TASK (TASK_ID, LINE_NO),
    KEY IDX_PICK_LINE_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='拣货任务行（4.7.2/4.7.3 行级作业）';

-- ---------- 3) 通用差异单（4.7.4 拣货差异；DIFF_TYPE=COUNT 预留 4.11 盘点） ----------
CREATE TABLE IF NOT EXISTS erp_inv_check_diff (
    ID VARCHAR(64) NOT NULL,
    DIFF_NO VARCHAR(32) DEFAULT NULL COMMENT '差异单号（可空：行级差异以任务聚合展示）',
    -- PICK 拣货差异（本组） / COUNT 盘点差异（4.11 写入）
    DIFF_TYPE VARCHAR(16) NOT NULL DEFAULT 'PICK' COMMENT '差异大类',
    SRC_TASK_ID VARCHAR(64) DEFAULT NULL COMMENT '关联拣货任务',
    SRC_DOC_TYPE VARCHAR(32) DEFAULT NULL COMMENT '来源出库类型',
    SRC_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '来源单据号',
    LINE_NO INT DEFAULT NULL COMMENT '来源行号',
    ITEM_CODE VARCHAR(64) NOT NULL,
    WAREHOUSE_CODE VARCHAR(32) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL,
    -- QTY 数量 / BATCH 批次 / SERIAL 序列 / QUALITY 质量（四分类）
    DIFF_KIND VARCHAR(16) NOT NULL COMMENT '差异类型四分类',
    EXPECT_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '应拣/账面数量',
    ACTUAL_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '实拣/实盘数量',
    DELTA_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '差额 = ACTUAL - EXPECT',
    DIFF_NOTE VARCHAR(500) DEFAULT NULL COMMENT '差异说明（登记必填）',
    -- PENDING → RESOLVED（主管确认闭环，处理说明必填；本组不挂审批 = 偏差 D3）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '差异状态',
    RESOLVE_NOTE VARCHAR(500) DEFAULT NULL COMMENT '处理说明（闭环必填）',
    RESOLVE_BY VARCHAR(64) DEFAULT NULL,
    RESOLVE_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_CHECK_DIFF_DOC (SRC_DOC_NO, STATUS),
    KEY IDX_CHECK_DIFF_TYPE (DIFF_TYPE, STATUS),
    KEY IDX_CHECK_DIFF_TASK (SRC_TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='通用差异单（4.7.4 拣货差异闭环；盘点差异 4.11 复用）';

-- ---------- 4) 扫码校验记录（仅失败事件 + 行放行标记，偏差 D1 不做逐码事件流） ----------
CREATE TABLE IF NOT EXISTS erp_inv_pick_scan_log (
    ID VARCHAR(64) NOT NULL,
    TASK_ID VARCHAR(64) NOT NULL,
    LINE_ID VARCHAR(64) NOT NULL,
    -- BIN 仓位 / ITEM 物料 / BATCH 批次 / SERIAL 序列 / PASS 行放行
    SCAN_TYPE VARCHAR(16) NOT NULL COMMENT '校验对象类型',
    INPUT_CODE VARCHAR(128) DEFAULT NULL COMMENT '扫码输入值',
    EXPECT_CODE VARCHAR(128) DEFAULT NULL COMMENT '任务行期望值',
    RESULT VARCHAR(16) NOT NULL COMMENT 'FAIL 失败 / OK 放行标记',
    FAIL_REASON VARCHAR(255) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_PICK_SCAN_TASK (TASK_ID),
    KEY IDX_PICK_SCAN_RESULT (RESULT, CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='拣货扫码校验记录（BR-4.4-27 失败明细 + 放行标记）';

-- ---------- 5) 菜单 PERM 存量回填（099 为 INSERT IGNORE，已执行库须 UPDATE，109 范式） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-7-1', 'M4-7-2', 'M4-7-3', 'M4-7-4');
