-- 111 波次管理：配送线路/波次头/单据归属/分配行/改批调整 + 线路挂载 + WAVE 任务扩列
--     + WAVE_SORT 差异关联列 + 参数 WAVE_MAX_DOCS + 4.8 菜单 PERM 存量回填
--     （change add-wave-management，spec wave-management；design D1/D9）
-- 幂等：CREATE IF NOT EXISTS / INSERT IGNORE / information_schema+PREPARE 动态 DDL / UPDATE 幂等

-- ---------- 1) 配送线路主数据（C-0-05 停用退役，不物理删除） ----------
CREATE TABLE IF NOT EXISTS erp_inv_route (
    ID VARCHAR(64) NOT NULL,
    ROUTE_CODE VARCHAR(32) NOT NULL COMMENT '线路编码',
    ROUTE_NAME VARCHAR(128) NOT NULL COMMENT '线路名称',
    -- ACTIVE 启用 / INACTIVE 停用（停用后不可被新发货单挂线，存量快照不受影响）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（停用=退役语义）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_ROUTE_CODE (ROUTE_CODE),
    KEY IDX_INV_ROUTE_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='配送线路主数据（4.8 波次聚类第一优先级键；wave-management 需求 配送线路主数据）';

-- ---------- 2) 客户挂默认线路（集团级：CUSTOMER_CODE/发货单客户编码来自集团，跨法人共享线路）
--            + 发货单线路快照（可空） ----------
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE()
                 AND TABLE_NAME = 'erp_mdm_customer_group'
                 AND COLUMN_NAME = 'ROUTE_ID') = 0,
  'ALTER TABLE erp_mdm_customer_group
     ADD COLUMN ROUTE_ID VARCHAR(64) DEFAULT NULL
       COMMENT ''客户默认配送线路 ID（可空；波次聚类读发货单快照而非本列）''
       AFTER CUSTOMER_CODE', 'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE()
                 AND TABLE_NAME = 'erp_sd_shipment'
                 AND COLUMN_NAME = 'ROUTE_ID') = 0,
  'ALTER TABLE erp_sd_shipment
     ADD COLUMN ROUTE_ID VARCHAR(64) DEFAULT NULL
       COMMENT ''配送线路快照（生成时从客户默认线带出；聚类只读本列，客户改线不影响已开单据）''
       AFTER LOGISTICS_CO', 'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------- 3) 波次头（状态机 CREATED→ALLOCATED→PICKING→SORTING→STAGING→SHIPPING→CLOSED；分支 CANCELLED） ----------
CREATE TABLE IF NOT EXISTS erp_inv_wave (
    ID VARCHAR(64) NOT NULL,
    WAVE_NO VARCHAR(32) NOT NULL COMMENT '波次号 WV+yyyyMMdd+流水',
    -- 聚类键快照（预览确认时写入；用于详情展示与追溯）
    CLUSTER_KEY VARCHAR(64) DEFAULT NULL COMMENT '聚类键值（线路/承运商/客户 标识）',
    CLUSTER_TYPE VARCHAR(16) DEFAULT NULL COMMENT '聚类主键类型 ROUTE/CARRIER/CUSTOMER',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED' COMMENT '波次状态机',
    DOC_COUNT INT NOT NULL DEFAULT 0 COMMENT '单据数',
    ALLOC_AT DATETIME DEFAULT NULL COMMENT '分配完成时间',
    PICK_AT DATETIME DEFAULT NULL COMMENT '全部拣毕时间（进 SORTING）',
    SORT_AT DATETIME DEFAULT NULL COMMENT '全部分播通过时间（进 STAGING）',
    LOAD_AT DATETIME DEFAULT NULL COMMENT '全部装车完成时间（进 SHIPPING）',
    CLOSE_AT DATETIME DEFAULT NULL COMMENT '全部过账完成时间（CLOSED）',
    CANCEL_REASON VARCHAR(500) DEFAULT NULL COMMENT '作废原因（必填）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INV_WAVE_NO (WAVE_NO),
    KEY IDX_INV_WAVE_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='拣货波次头（4.8.1，spec wave-management 波次状态机）';

-- ---------- 4) 波次单据归属（1 单 1 行；拆出/作废=解绑保留行，C-0-05 不物理删除） ----------
CREATE TABLE IF NOT EXISTS erp_inv_wave_doc (
    ID VARCHAR(64) NOT NULL,
    WAVE_ID VARCHAR(64) NOT NULL,
    SHIP_ID VARCHAR(64) NOT NULL COMMENT '发货单 ID',
    SHIP_NO VARCHAR(64) NOT NULL COMMENT '发货单号',
    -- BOUND 在波次内 / UNBOUND 已拆出（BR-4.4-47 批次不足拆单；作废波次时全量置 UNBOUND）
    BIND_STATUS VARCHAR(16) NOT NULL DEFAULT 'BOUND' COMMENT '归属状态',
    UNBOUND_REASON VARCHAR(500) DEFAULT NULL COMMENT '拆出原因',
    -- 分播复核结果（4.8.2）：PENDING→PASSED；RESULT JSON 存复核快照供装车比对（design D6）
    SORT_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '分播状态',
    SORT_RESULT VARCHAR(4000) DEFAULT NULL COMMENT '复核结果快照 JSON（装车比对基准）',
    SORT_BY VARCHAR(64) DEFAULT NULL,
    SORT_AT DATETIME DEFAULT NULL,
    -- 装车确认（C-4.4-06 比对通过后置 LOADED）
    LOAD_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '装车状态',
    LOAD_BY VARCHAR(64) DEFAULT NULL,
    LOAD_AT DATETIME DEFAULT NULL,
    -- 发运过账失败留痕（BR-4.4-46 单独重试）
    SHIP_ERR VARCHAR(500) DEFAULT NULL COMMENT '最近一次过账失败原因',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_INV_WAVE_DOC_WAVE (WAVE_ID, BIND_STATUS),
    UNIQUE KEY UK_INV_WAVE_DOC_SHIP (SHIP_ID),
    KEY IDX_INV_WAVE_DOC_SHIPNO (SHIP_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='波次单据归属与分播/装车/发运状态（BR-4.4-47 拆单=置 UNBOUND 保留行）';

-- ---------- 5) 波次分配行（波次级统一分配视图 + C-4.4-08 改批锁载体；发货行为过账事实源双写） ----------
CREATE TABLE IF NOT EXISTS erp_inv_wave_line (
    ID VARCHAR(64) NOT NULL,
    WAVE_ID VARCHAR(64) NOT NULL,
    SHIP_ID VARCHAR(64) NOT NULL,
    SHIP_LINE_ID VARCHAR(64) DEFAULT NULL COMMENT '发货单行 ID',
    LINE_NO INT NOT NULL DEFAULT 1,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    WAREHOUSE_CODE VARCHAR(32) NOT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '分配批次（FIFO+FEFO 波次共享预算）',
    BIN_CODE VARCHAR(64) DEFAULT NULL COMMENT '分配仓位',
    QTY DECIMAL(18,4) NOT NULL COMMENT '分配数量',
    -- C-4.4-08：1=改批审批中冻结拣货；0/NULL=正常（ALLOCATED 前置：无 LOCK_FLAG=1 行）
    LOCK_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '改批锁 1/0',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_INV_WAVE_LINE_WAVE (WAVE_ID, ITEM_CODE),
    KEY IDX_INV_WAVE_LINE_SHIP (SHIP_ID),
    KEY IDX_INV_WAVE_LINE_LOCK (WAVE_ID, LOCK_FLAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='波次分配行（BR-4.4-43 波次级统一分配、C-4.4-08 行级改批锁）';

-- ---------- 6) 改批调整记录（审批 bizId 载体：前值/后值/原因全程留痕，C-4.4-08） ----------
CREATE TABLE IF NOT EXISTS erp_inv_wave_adjust (
    ID VARCHAR(64) NOT NULL,
    WAVE_ID VARCHAR(64) NOT NULL,
    LINE_ID VARCHAR(64) NOT NULL COMMENT '被调整的分配行',
    FIELD VARCHAR(16) NOT NULL COMMENT '调整字段 BATCH/BIN',
    OLD_VALUE VARCHAR(128) DEFAULT NULL COMMENT '调整前值（驳回回退目标）',
    NEW_VALUE VARCHAR(128) NOT NULL COMMENT '调整后值',
    REASON VARCHAR(500) NOT NULL COMMENT '调整原因（必填）',
    -- 审批实例（bizType=WaveAdjust, bizId=本表 ID）；PENDING→APPROVED/REJECTED
    APPR_ID VARCHAR(64) DEFAULT NULL,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '调整状态',
    ADJUST_BY VARCHAR(64) NOT NULL COMMENT '发起人（签署防同人闭环 applyBy）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_WAVE_ADJUST_WAVE (WAVE_ID, STATUS),
    KEY IDX_WAVE_ADJUST_LINE (LINE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='波次改批调整记录（C-4.4-08 强制审批 bizId 载体，design D4）';

-- ---------- 7) WAVE 任务扩列（PickTask WAVE 源类型 + 行归属明细，design D1/D5） ----------
-- SRC_TYPE 无 DDL 变更（VARCHAR(32) 已容纳 'WAVE'），仅注释语义扩展由实体维护
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE()
                 AND TABLE_NAME = 'erp_pick_task_line'
                 AND COLUMN_NAME = 'SRC_ALLOC') = 0,
  'ALTER TABLE erp_pick_task_line
     ADD COLUMN SRC_ALLOC VARCHAR(4000) DEFAULT NULL
       COMMENT ''WAVE 任务行归属明细 JSON：[{shipId, shipNo, qty}]（分播按订单拆回）''
       AFTER BIN_CODE', 'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------- 8) 差异单加波次关联列（WAVE_SORT 差异；srcDocNo=订单号使门闩零改动） ----------
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE()
                 AND TABLE_NAME = 'erp_inv_check_diff'
                 AND COLUMN_NAME = 'WAVE_ID') = 0,
  'ALTER TABLE erp_inv_check_diff
     ADD COLUMN WAVE_ID VARCHAR(64) DEFAULT NULL COMMENT ''关联波次（DIFF_TYPE=WAVE_SORT 时非空）'',
     ADD COLUMN WAVE_DOC_ID VARCHAR(64) DEFAULT NULL COMMENT ''关联波次单据归属行''
       AFTER SRC_DOC_NO', 'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------- 9) 参数种子：单次拣货容量上限（BR-4.4-42 拆分依据） ----------
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-wave-max-docs', 'WAVE_MAX_DOCS', '50', 'COUNT', 'INV',
 '单次拣货容量上限：单波次发货单数超过该值自动拆分为多个候选波次（BR-4.4-42），下一次按规则生成波次生效', 'seed', '0', 0);

-- ---------- 10) 菜单 PERM 存量回填（099 INSERT IGNORE 对已执行库不更新 → UPDATE；沿 109 范式） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-8-1', 'M4-8-2');
