-- 113 效期管理三菜单：每日预警报告 + 效期质量评估单 + 锁定变更历史
--     + 批次人工锁/放行豁免三列 + 4.10 菜单 PERM 存量回填
--     （change add-expiry-management-menus，spec expiry-management ADDED 六需求；design D1/D2/D7）
-- 幂等：CREATE TABLE IF NOT EXISTS / INSERT IGNORE / UPDATE 幂等 / information_schema+PREPARE 动态 DDL

-- ---------- 1) 每日效期预警报告（FR-4.4-3-6，REPORT_DATE 唯一幂等覆盖） ----------
CREATE TABLE IF NOT EXISTS erp_inv_expiry_report (
    ID VARCHAR(64) NOT NULL,
    REPORT_DATE DATE NOT NULL COMMENT '报告日（每日一份，重复生成覆盖）',
    YELLOW_CNT INT NOT NULL DEFAULT 0 COMMENT '黄色预警批次数（剩余 ≤90 天）',
    ORANGE_CNT INT NOT NULL DEFAULT 0 COMMENT '橙色预警批次数（剩余 ≤60 天）',
    RED_CNT INT NOT NULL DEFAULT 0 COMMENT '红色预警批次数（剩余 ≤30 天）',
    LOCKED_CNT INT NOT NULL DEFAULT 0 COMMENT '锁定批次数（EXPIRY_LOCK_FLAG=1）',
    -- [{itemCode,batchNo,expiryDate,remainingDays,level}] 全量快照
    DETAIL_JSON MEDIUMTEXT NULL COMMENT '三级预警明细快照',
    -- {yellow:[...],orange:[...],red:[...]} 较最近一份报告的新增/解除（首日无基线为空+noBaseline 标记）
    NEW_JSON MEDIUMTEXT NULL COMMENT '较前报新增清单',
    CLEARED_JSON MEDIUMTEXT NULL COMMENT '较前报解除清单',
    NO_BASELINE CHAR(1) NOT NULL DEFAULT '0' COMMENT '1=首日无前报基线',
    GEN_AT DATETIME DEFAULT NULL COMMENT '生成时间',
    GEN_BY VARCHAR(64) DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_EXPIRY_REPORT_DATE (REPORT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='每日效期预警报告（4.10.1，FR-4.4-3-6 黄橙红三级留痕）';

-- ---------- 2) 效期质量评估单（4.10.3，C-4.4-03 处置链：报废/放行/转冻结） ----------
CREATE TABLE IF NOT EXISTS erp_inv_expiry_eval (
    ID VARCHAR(64) NOT NULL,
    EVAL_NO VARCHAR(64) NOT NULL COMMENT '评估单号 EV+yyMMdd+4位日流水',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) NOT NULL COMMENT '锁定批次（非锁定发起 422）',
    WAREHOUSE_CODE VARCHAR(32) DEFAULT NULL COMMENT '发起时批次所在仓库（展示用）',
    LOCK_SOURCE VARCHAR(8) DEFAULT NULL COMMENT '发起时锁定来源快照 AUTO/MANUAL',
    -- PENDING_EVAL 待判定 / PENDING_APPR 审批中 / CLOSED 已关闭
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING_EVAL' COMMENT '状态机',
    -- SCRAP 报废 / RELEASE 让步放行 / FREEZE 转质量冻结
    CONCLUSION VARCHAR(16) DEFAULT NULL COMMENT '判定结论',
    EVAL_NOTE VARCHAR(1000) NOT NULL COMMENT '评估说明（必填）',
    RELEASE_UNTIL DATE DEFAULT NULL COMMENT '放行有效期（RELEASE 必填且 > 今日）',
    SCRAP_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '关联报废单号（SCRAP 分支）',
    FREEZE_NO VARCHAR(64) DEFAULT NULL COMMENT '关联冻结单号（FREEZE 分支）',
    APPR_ID VARCHAR(64) DEFAULT NULL COMMENT '审批实例 ID（BIZ_TYPE=ExpiryEval）',
    APPR_OPINION VARCHAR(500) DEFAULT NULL COMMENT '驳回意见（回 PENDING_EVAL 留痕）',
    EVAL_BY VARCHAR(64) NOT NULL COMMENT '判定人（签署同人拦截）',
    CLOSE_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_EXPIRY_EVAL_NO (EVAL_NO),
    KEY IDX_EXPIRY_EVAL_BATCH (BATCH_NO, STATUS),
    KEY IDX_EXPIRY_EVAL_ITEM (ITEM_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='效期质量评估单（4.10.3，锁定批次处置：报废/让步放行/转质量冻结）';

-- ---------- 3) 锁定变更历史（4.10.2 台账；仅 flag 实际变化时写入） ----------
CREATE TABLE IF NOT EXISTS erp_inv_expiry_lock_log (
    ID VARCHAR(64) NOT NULL,
    BATCH_NO VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    FROM_FLAG VARCHAR(1) NOT NULL COMMENT '变更前标记 0/1',
    TO_FLAG VARCHAR(1) NOT NULL COMMENT '变更后标记 0/1',
    -- SCAN 每日扫描 / MANUAL 人工锁定 / EVAL_RELEASE 评估放行
    SOURCE VARCHAR(16) NOT NULL COMMENT '变更来源',
    OPERATOR VARCHAR(64) NOT NULL COMMENT '操作人（扫描=system:scan）',
    REASON VARCHAR(500) DEFAULT NULL COMMENT '原因（人工锁定必填/放行记录评估单号）',
    CHANGE_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
    PRIMARY KEY (ID),
    KEY IDX_EXPIRY_LOCK_LOG_BATCH (BATCH_NO, CHANGE_AT),
    KEY IDX_EXPIRY_LOCK_LOG_ITEM (ITEM_CODE, CHANGE_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='效期锁定变更历史（4.10.2；flag 变化才写入，扫描幂等零噪音）';

-- ---------- 4) 批次三列：人工锁来源 + 让步放行豁免（design D1/D2） ----------
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA = DATABASE()
                 AND TABLE_NAME = 'erp_inv_batch'
                 AND COLUMN_NAME = 'LOCK_SOURCE') = 0,
  'ALTER TABLE erp_inv_batch
     ADD COLUMN LOCK_SOURCE VARCHAR(8) NOT NULL DEFAULT ''AUTO''
       COMMENT ''锁定来源 AUTO 系统扫描 / MANUAL 人工锁定（MANUAL 扫描只评估不清除）''
       AFTER EXPIRY_LOCK_FLAG,
     ADD COLUMN EVAL_EXEMPT_UNTIL DATE NULL
       COMMENT ''让步放行截止日（NULL=无豁免；未过期扫描强制不锁、引擎④放行）''
       AFTER LOCK_SOURCE,
     ADD COLUMN EVAL_EXEMPT_ID VARCHAR(64) NULL
       COMMENT ''放行评估单号（来源追溯）''
       AFTER EVAL_EXEMPT_UNTIL', 'SELECT 1');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ---------- 5) 菜单 PERM 存量回填（099 已重生成含三行 PERM，存量库由本迁移 UPDATE；沿 109 范式） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-10-1', 'M4-10-2');
UPDATE erp_admin_menu
   SET PERM = 'ROLE_QUALITY_ENG,ROLE_QUALITY_MGR,ROLE_ADMIN'
 WHERE ID = 'M4-10-3';
