-- 114 盘点管理（4.11）：盘点任务头/行两表 + 三菜单 PERM 存量回填
--     （change add-count-management，spec count-management ADDED 八需求；design D3/D7）
-- 幂等：CREATE TABLE IF NOT EXISTS / UPDATE 幂等

-- ---------- 1) 盘点任务头（design D3：CYCLE 周期手工选范围 / FULL 一键全仓共用状态机） ----------
CREATE TABLE IF NOT EXISTS erp_inv_count_task (
    ID VARCHAR(64) NOT NULL,
    TASK_NO VARCHAR(32) NOT NULL COMMENT '任务号 COUNT+yyMMdd+4位日流水',
    -- CYCLE 周期盘点（4.11.1 手工选范围）/ FULL 全面盘点（4.11.2 一键全仓）
    TASK_TYPE VARCHAR(16) NOT NULL COMMENT 'CYCLE / FULL',
    WAREHOUSE_CODE VARCHAR(32) NOT NULL COMMENT '盘点仓库',
    -- DRAFT 生成即置 COUNTING（首期无草稿停留）→ ADJUSTING（差异单挂审批）→ DONE
    STATUS VARCHAR(16) NOT NULL DEFAULT 'COUNTING' COMMENT '状态机',
    TOTAL_LINES INT NOT NULL DEFAULT 0 COMMENT '盘点行数',
    COUNTED_LINES INT NOT NULL DEFAULT 0 COMMENT '已录行数',
    ADJUSTED_LINES INT NOT NULL DEFAULT 0 COMMENT '已调整行数（自动+审批）',
    -- DONE 时物化（design D8）：{range:{...},diff:{...},autoCnt,apprCnt,watchBins:[...]}
    REPORT_JSON MEDIUMTEXT NULL COMMENT '盘点报告快照（置 DONE 同事务生成）',
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_COUNT_TASK_NO (TASK_NO),
    KEY IDX_COUNT_TASK_WH (WAREHOUSE_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='盘点任务头（4.11，FR-4.4-6-1/2，BR-4.4-36 锁仓来源）';

-- ---------- 2) 盘点任务行（行粒度 = 仓库×仓位×物料×批次；BOOK_QTY 锁生效时定格） ----------
CREATE TABLE IF NOT EXISTS erp_inv_count_line (
    ID VARCHAR(64) NOT NULL,
    TASK_ID VARCHAR(64) NOT NULL COMMENT '所属任务',
    BIN_CODE VARCHAR(64) NOT NULL COMMENT '盘点仓位（锁仓集合来源，''=未分配位不锁）',
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '批次（无批次物料空串）',
    -- 账面快照：任务进入 COUNTING 时定格，后续账面漂移不改差异口径（spec 任务状态机）
    BOOK_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '账面快照（COUNTING 生效时定格）',
    ACTUAL_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '实盘数（录入）',
    DIFF_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '差异数 = ACTUAL - BOOK',
    -- DIFF_RATE = |DIFF| / BOOK（BOOK=0 且实盘>0 按 100%）
    DIFF_RATE DECIMAL(9,6) DEFAULT NULL COMMENT '差异率',
    DIFF_AMOUNT DECIMAL(18,4) DEFAULT NULL COMMENT '差异金额 = |DIFF_QTY| × standardCost',
    -- PENDING 未盘 → COUNTED 已录（≤容差当场 ADJUSTED / >容差挂差异单）→ ADJUSTED
    -- RECOUNT >10% 阻断标记（spec 待复盘：L1 保留，重录清除）
    COUNT_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/COUNTED/ADJUSTED/RECOUNT',
    AUTO_ADJUST CHAR(1) NOT NULL DEFAULT '0' COMMENT '1=容差内自动调整（无需审批）',
    DIFF_ID VARCHAR(64) DEFAULT NULL COMMENT '关联差异单（DIFF_TYPE=COUNT，超容差）',
    ADJUST_DOC_NO VARCHAR(64) DEFAULT NULL COMMENT '调整单据号（ADJUST_IN/OUT 来源单号）',
    ABNORMAL_FLAG VARCHAR(16) DEFAULT NULL COMMENT '实物异常：DAMAGED 破损 / EXPIRED 过期 / NO_LABEL 无标识',
    COUNTED_BY VARCHAR(64) DEFAULT NULL,
    COUNTED_AT DATETIME DEFAULT NULL,
    REMARK VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_COUNT_LINE_TASK (TASK_ID, COUNT_STATUS),
    KEY IDX_COUNT_LINE_BIN (BIN_CODE),
    KEY IDX_COUNT_LINE_ITEM (ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='盘点任务行（4.11，FR-4.4-6-3~7 实盘/差异/调整留痕）';

-- ---------- 3) 三菜单 PERM 存量回填（099 产物三行已由生成器更新，存量库由此处幂等补齐；
--              沿 109/112 范式） ----------
UPDATE erp_admin_menu SET PERM = 'ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-11-1', 'M4-11-2', 'M4-11-3');
