-- 115 追溯召回（4.13，流程 8）：追溯单/流向行/审计三表 + RECALL_IN 单据类型
--     + 每启用仓补建 RETURN/SCRAP 受限区种子仓位 + 报废单 TRACE_NO 列
--     + 4.13 两菜单 PERM 存量回填（change add-trace-recall，spec trace-recall ADDED 十需求；design D1/D5）
-- 幂等：CREATE TABLE IF NOT EXISTS / IF NOT EXISTS / INSERT IGNORE / UPDATE 幂等

-- ---------- 1) 追溯单头（design D1：TR 单号、三索引归一、三态机、REPORT_JSON 双段） ----------
CREATE TABLE IF NOT EXISTS erp_inv_trace_order (
    ID VARCHAR(64) NOT NULL,
    TRACE_NO VARCHAR(32) NOT NULL COMMENT '追溯单号 TR+yyMMdd+4位日流水',
    -- 三索引（FR-4.4-8-1）：BATCH 批次号 / SERIAL 序列号（经 erp_inv_serial 反查）
    -- / SUPPLIER_BATCH 供应商批次号（经 SUPPLIER_BATCH_NO 查找）
    INDEX_TYPE VARCHAR(24) NOT NULL COMMENT 'BATCH / SERIAL / SUPPLIER_BATCH',
    INDEX_VALUE VARCHAR(128) NOT NULL COMMENT '录入的索引值',
    BATCH_NO VARCHAR(64) NOT NULL COMMENT '归一解析出的批次号（重复发起拦截键）',
    ITEM_CODE VARCHAR(64) DEFAULT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    DEFECT_REASON VARCHAR(500) NOT NULL COMMENT '缺陷描述（发起必填）',
    -- ANALYZING 分析中 → EXECUTING 流向物化完成执行中 → CLOSED 结案
    STATUS VARCHAR(16) NOT NULL DEFAULT 'ANALYZING' COMMENT '状态机',
    -- 双段：①五类流向快照（物化时写入）②结案报告（召回率+未召回明细）
    REPORT_JSON MEDIUMTEXT NULL COMMENT '流向快照 + 结案报告',
    CLOSE_BY VARCHAR(64) DEFAULT NULL,
    CLOSE_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TRACE_NO (TRACE_NO),
    KEY IDX_TRACE_BATCH (BATCH_NO, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='追溯单头（4.13.1，FR-4.4-8-1/7，BR-4.4-53 保存期）';

-- ---------- 2) 流向行（五类，行级动作状态，应召量物化定格） ----------
CREATE TABLE IF NOT EXISTS erp_inv_trace_flow (
    ID VARCHAR(64) NOT NULL,
    TRACE_ID VARCHAR(64) NOT NULL COMMENT '所属追溯单',
    -- 五类流向（BR-4.4-48）
    FLOW_TYPE VARCHAR(20) NOT NULL COMMENT 'STOCK_AVAILABLE/STOCK_FROZEN/IN_TRANSIT/OUT_UNSIGNED/OUT_SIGNED',
    -- PENDING 未处置 → FROZEN 已冻结 / LINKED 已关联 / INTERCEPTED 拦截成功
    -- / FAILED 拦截失败（升级出新召回行）/ RECEIVED 实退 / REJECTED 拒退 → DISPOSED 处置完成
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '行级状态机',
    WAREHOUSE_CODE VARCHAR(32) DEFAULT NULL COMMENT '库存类流向仓库',
    BIN_CODE VARCHAR(64) DEFAULT NULL COMMENT '库存类流向仓位',
    ITEM_CODE VARCHAR(64) DEFAULT NULL,
    ITEM_NAME VARCHAR(128) DEFAULT NULL,
    BATCH_NO VARCHAR(64) DEFAULT NULL COMMENT '流向批次',
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '流向数量（在途/发运数量）',
    -- 召回清单（OUT_SIGNED）：应召量在物化时定格，客户变更不改基数（FR-4.4-8-5）
    EXPECT_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '应召数量（定格）',
    ACTUAL_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '实退数量',
    RETURNED_BATCH VARCHAR(64) DEFAULT NULL COMMENT '退回批次',
    REJECT_REASON VARCHAR(500) DEFAULT NULL COMMENT '拒退/失败原因（拒退必填）',
    -- 来源单据维度（在途/发运）
    SRC_DOC_TYPE VARCHAR(24) DEFAULT NULL COMMENT 'TRANSFER / SHIPMENT',
    SRC_DOC_NO VARCHAR(32) DEFAULT NULL COMMENT '调拨单号 / 发运单号',
    CUSTOMER_CODE VARCHAR(64) DEFAULT NULL,
    CUSTOMER_NAME VARCHAR(128) DEFAULT NULL,
    SIGN_AT DATETIME DEFAULT NULL COMMENT '签收时间（OUT_SIGNED）',
    -- 数据缺口（发运行批次字段缺失但物料命中疑似流向）→ 1 待人工核查，不丢弃（spec 流向需求）
    CHECK_FLAG CHAR(1) NOT NULL DEFAULT '0' COMMENT '1=待人工核查',
    NOTE VARCHAR(500) DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_TRACE_FLOW_TRACE (TRACE_ID, FLOW_TYPE, STATUS),
    KEY IDX_TRACE_FLOW_BATCH (BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='追溯流向行（4.13，五类流向 + 召回清单 + 行级动作状态）';

-- ---------- 3) 审计留痕（C-4.4-10/BR-4.4-53：User/Action/Object/Before/After/TS，简化表） ----------
CREATE TABLE IF NOT EXISTS erp_inv_trace_log (
    ID VARCHAR(64) NOT NULL,
    TRACE_ID VARCHAR(64) NOT NULL COMMENT '所属追溯单（按单回放键）',
    ACTION_USER VARCHAR(64) NOT NULL COMMENT '操作人（system:analyze 等系统动作）',
    ACTION VARCHAR(48) NOT NULL COMMENT '动作（ANALYZE/FREEZE/INTERCEPT/RETURN/RECEIVE/DISPOSE/CLOSE...）',
    OBJECT_TYPE VARCHAR(32) DEFAULT NULL COMMENT '对象类型（FLOW/ORDER/STOCK...）',
    OBJECT_ID VARCHAR(64) DEFAULT NULL COMMENT '对象标识',
    BEFORE_VAL VARCHAR(1000) DEFAULT NULL COMMENT '动作前值',
    AFTER_VAL VARCHAR(1000) DEFAULT NULL COMMENT '动作后值',
    OP_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    PRIMARY KEY (ID),
    KEY IDX_TRACE_LOG_TRACE (TRACE_ID, OP_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='追溯操作审计（BR-4.4-53，保存期 AUDIT_RETENTION_DAYS=180；链式哈希记偏差）';

-- ---------- 4) RECALL_IN 单据类型（design D5：召回按批次+受限区手工指定 → MANUAL） ----------
INSERT IGNORE INTO erp_inv_doc_type (ID, TYPE_CODE, DIRECTION, TYPE_NAME, FLOW_PREFIX, DEFAULT_ALLOC, NEED_BATCH, NEED_SERIAL, ENABLED, CREATE_BY) VALUES
  ('dt-recall-in', 'RECALL_IN', 'IN', '召回入库', 'TX', 'MANUAL', 1, 0, 1, 'system');

-- ---------- 5) 受限区种子仓位（design D5：每启用仓补建退货区/残次品区，BIN_CODE 全局 UK 保证幂等） ----------
-- 已有同 BIN_TYPE 仓位的仓库跳过（LEFT JOIN 判定）；ZONE_CODE 沿存量分区惯例（分区字典未建，仅标识用）
INSERT IGNORE INTO erp_inv_bin (ID, WH_CODE, ZONE_CODE, BIN_CODE, BIN_SEQ, COL_NO, LAYER_NO, BIN_TYPE, STATUS, CREATE_BY, DEL_FLAG, VER_NO)
SELECT CONCAT('bin-recall-rt-', w.ID), w.WH_CODE, 'RT', CONCAT('RECALL-RETURN-', w.WH_CODE), 9, 9, 9, 'RETURN', '1', 'system', '0', 0
  FROM erp_inv_warehouse w
 WHERE w.STATUS = '1'
   AND NOT EXISTS (SELECT 1 FROM erp_inv_bin b WHERE b.WH_CODE = w.WH_CODE AND b.BIN_TYPE = 'RETURN' AND b.DEL_FLAG = '0');
INSERT IGNORE INTO erp_inv_bin (ID, WH_CODE, ZONE_CODE, BIN_CODE, BIN_SEQ, COL_NO, LAYER_NO, BIN_TYPE, STATUS, CREATE_BY, DEL_FLAG, VER_NO)
SELECT CONCAT('bin-recall-sp-', w.ID), w.WH_CODE, 'SP', CONCAT('RECALL-SCRAP-', w.WH_CODE), 9, 9, 9, 'SCRAP', '1', 'system', '0', 0
  FROM erp_inv_warehouse w
 WHERE w.STATUS = '1'
   AND NOT EXISTS (SELECT 1 FROM erp_inv_bin b WHERE b.WH_CODE = w.WH_CODE AND b.BIN_TYPE = 'SCRAP' AND b.DEL_FLAG = '0');

-- ---------- 6) 报废单头 TRACE_NO 可空列（design D6：处置关联原追溯单号，FR-4.4-8-6） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_inv_scrap_order'
        AND COLUMN_NAME = 'TRACE_NO') = 0,
    'ALTER TABLE erp_inv_scrap_order
       ADD COLUMN TRACE_NO VARCHAR(32) DEFAULT NULL COMMENT ''关联追溯单号（召回处置闭环，可空）'' AFTER NCR_NO',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 7) 4.13 两菜单 PERM 存量回填（099 产物同步两行，存量库由此幂等补齐） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_QUALITY_ENG,ROLE_QUALITY_MGR,ROLE_WAREHOUSE,ROLE_ADMIN'
 WHERE ID IN ('M4-13-1', 'M4-13-2');
