-- 117 生产管理-物料清单（5.1，spec 4.5-1）：BOM 三表 + 工艺两角色 + 5.1 菜单 PERM 存量回填
--     + 参数 BOM_MAX_NESTING_DEPTH（change add-bom-management，spec bom-management ADDED 十一需求；
--       design D1 一行=一版本 / D5 角色 / D6 菜单权限双写 / D7 本迁移）
-- 幂等：CREATE TABLE IF NOT EXISTS / INSERT IGNORE / UPDATE 幂等（可重复执行）

-- ---------- 1) BOM 版本头（design D1：一行 = 一个版本；状态机 + 变更链 + 发布留痕） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_bom (
    ID VARCHAR(64) NOT NULL,
    PARENT_ITEM_CODE VARCHAR(64) NOT NULL COMMENT '父项物料编码',
    PARENT_ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '父项物料名称（冗余展示）',
    VERSION_MAJOR INT NOT NULL DEFAULT 1 COMMENT '主版本号（自动分配，不可手填）',
    VERSION_MINOR INT NOT NULL DEFAULT 0 COMMENT '次版本号（变更默认 +1）',
    -- DRAFT 草稿 → PENDING 待审核 → PUBLISHED 已发布 → REVISED 已变更 → OBSOLETE 已废止；退回回 DRAFT
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态机（白名单 CAS 迁移）',
    CHANGE_REASON VARCHAR(500) DEFAULT NULL COMMENT '变更原因（发起变更必填）',
    CHANGE_FROM_ID VARCHAR(64) DEFAULT NULL COMMENT '变更来源版本 ID（自引用变更链）',
    COPY_FROM_ID VARCHAR(64) DEFAULT NULL COMMENT '复制来源版本 ID',
    EFFECTIVE_DATE DATE DEFAULT NULL COMMENT '生效日期',
    EXPIRY_DATE DATE DEFAULT NULL COMMENT '失效日期（到期不自动改状态，下游按区间过滤）',
    PUBLISH_BY VARCHAR(64) DEFAULT NULL COMMENT '发布人（FR-4.5-1-7 降级留痕）',
    PUBLISH_AT DATETIME DEFAULT NULL COMMENT '发布时间（FR-4.5-1-7 降级留痕）',
    REJECT_REASON VARCHAR(500) DEFAULT NULL COMMENT '最近驳回意见（审批留痕）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 版本号唯一（BR-4.5-08 唯一已发布与唯一在途由服务层父项锁保证；本键兜底版本冲突自动递增）
    UNIQUE KEY UK_MRP_BOM_VER (PARENT_ITEM_CODE, VERSION_MAJOR, VERSION_MINOR),
    KEY IDX_MRP_BOM_PARENT_STATUS (PARENT_ITEM_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='BOM 版本头（5.1，FR-4.5-1-1/5/6，BR-4.5-08/09）';

-- ---------- 2) BOM 行明细（FR-4.5-1-2：子项/用量/损耗率/生效失效） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_bom_item (
    ID VARCHAR(64) NOT NULL,
    BOM_ID VARCHAR(64) NOT NULL COMMENT '所属 BOM 版本',
    LINE_NO INT NOT NULL DEFAULT 0 COMMENT '行号',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '子项物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '子项名称（冗余展示）',
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '用量（必须 > 0，L1 阻断）',
    LOSS_RATE DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '损耗率%（0~100；MRP 实际需求=基础用量×(1+损耗率)，BR-4.5-10）',
    UOM VARCHAR(32) DEFAULT NULL COMMENT '计量单位快照（替代料同单位校验基准）',
    EFFECTIVE_DATE DATE DEFAULT NULL COMMENT '行生效日期',
    EXPIRY_DATE DATE DEFAULT NULL COMMENT '行失效日期',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '行备注',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 行号唯一性由服务层在草稿覆盖保存时保证（逻辑删除行仍占唯一键，故不设 UK）
    KEY IDX_MRP_BOM_ITEM_LINE (BOM_ID, LINE_NO),
    KEY IDX_MRP_BOM_ITEM_BOM (BOM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='BOM 行明细（5.1，FR-4.5-1-2）';

-- ---------- 3) 行级替代料（FR-4.5-1-3：1:N 比例+优先级，支撑 MRP 按优先级分配 FR-4.5-2-4） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_bom_substitute (
    ID VARCHAR(64) NOT NULL,
    BOM_ITEM_ID VARCHAR(64) NOT NULL COMMENT '所属 BOM 行',
    SUBSTITUTE_ITEM_CODE VARCHAR(64) NOT NULL COMMENT '替代物料编码',
    SUBSTITUTE_ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '替代物料名称（冗余展示）',
    RATIO DECIMAL(12,4) NOT NULL DEFAULT 1 COMMENT '替代比例（1 单位主料 = RATIO 单位替代料，如 1:1.2）',
    PRIORITY INT NOT NULL DEFAULT 1 COMMENT '优先级（数值小者优先，MRP 按优先级分配）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 同行同替代料的重复由服务层校验（逻辑删除行仍占唯一键，故不设 UK）
    KEY IDX_MRP_BOM_SUB (BOM_ITEM_ID, SUBSTITUTE_ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='BOM 行级替代料（5.1，FR-4.5-1-3；单位不一致由服务层 L1 阻断，偏差 D2）';

-- ---------- 4) 工艺两角色（design D5：ENG 维护提交 / MGR 审核发布废止；排序取 50/51 段） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, CREATE_DATE) VALUES
('role-process-eng', 'ROLE_PROCESS_ENG', '工艺工程师', 50, '1', 'system', NOW()),
('role-process-mgr', 'ROLE_PROCESS_MGR', '工艺主管',   51, '1', 'system', NOW());

-- ---------- 5) 5.1 物料清单菜单 PERM 存量回填（design D6：新装库由 099 生成，
--     已执行过 099 的库靠本 UPDATE 收敛；父 M5-1 与四子同权限防孤儿，M6 先例） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_PROCESS_ENG,ROLE_PROCESS_MGR,ROLE_ADMIN'
 WHERE ID IN ('M5-1', 'M5-1-1', 'M5-1-2', 'M5-1-3', 'M5-1-4');

-- ---------- 6) 参数：BOM 最大嵌套层数（BR-4.5-07，design D3 校验引擎按值截断） ----------
INSERT IGNORE INTO erp_sys_param
(ID, PARAM_KEY, PARAM_VALUE, VALUE_TYPE, PARAM_GROUP, REMARK, CREATE_BY, DEL_FLAG, VER_NO) VALUES
('param-bom-max-nesting-depth', 'BOM_MAX_NESTING_DEPTH', '8', 'COUNT', 'MRP',
 'BOM 多层嵌套最大层数：循环校验遍历超过该层返回超限提示而非死循环（BR-4.5-07）', 'seed', '0', 0);
