-- 118 生产管理-工艺管理（5.2，spec 4.5 消费方反推）：工艺五表
--     + M5-2-4 菜单行补偿 + 5.2 菜单 PERM 存量回填（change add-routing-management，
--     spec routing-management ADDED 十一需求；design D1 五表 / D5 本迁移；
--     本期无新角色（沿 117 的 ROLE_PROCESS_ENG/MGR）、无系统参数）
-- 幂等：CREATE TABLE IF NOT EXISTS / INSERT IGNORE / UPDATE 幂等（可重复执行）

-- ---------- 1) 工序字典（5.2.1：全局复用；编码建后不可改由服务层保证） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_operation (
    ID VARCHAR(64) NOT NULL,
    OP_CODE VARCHAR(64) NOT NULL COMMENT '工序编码（创建后不可修改）',
    OP_NAME VARCHAR(128) NOT NULL COMMENT '工序名称',
    SKILL_REQ VARCHAR(255) DEFAULT NULL COMMENT '技能要求（自由文本，结构化口径待 5.4 人员匹配定）',
    STATUS VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '状态 1启用/0停用（停用不可选入新路线行）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MRP_OP_CODE (OP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工序字典（5.2.1，spec L2367 工艺路线管理含工序）';

-- ---------- 2) 工作中心台账（5.2.2：产能三要素 = 负荷率分母，spec L2357/L2714/公式4） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_work_center (
    ID VARCHAR(64) NOT NULL,
    WC_CODE VARCHAR(64) NOT NULL COMMENT '工作中心编码（创建后不可修改）',
    WC_NAME VARCHAR(128) NOT NULL COMMENT '工作中心名称',
    WC_TYPE VARCHAR(16) NOT NULL DEFAULT 'INTERNAL' COMMENT '类型 INTERNAL内部/OUTSOURCED外协',
    SUPPLIER_CODE VARCHAR(64) DEFAULT NULL COMMENT '外协供应商编码（OUTSOURCED 必填，C-4.5-05 数据源头）',
    CAL_HOURS DECIMAL(8,2) NOT NULL DEFAULT 8 COMMENT '日历工时（小时/日，班次口径，须 > 0）',
    EQUIP_AVAIL DECIMAL(5,2) NOT NULL DEFAULT 100 COMMENT '设备可用率%（0~100）',
    LABOR_AVAIL DECIMAL(5,2) NOT NULL DEFAULT 100 COMMENT '人员出勤率%（0~100；可用工时=日历工时×设备×人员，公式4）',
    STATUS VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '状态 1启用/0停用（停用不可选入新路线行，FR-4.5-3-4）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MRP_WC_CODE (WC_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工作中心台账（5.2.2，spec L2357/L2714、C-4.5-05）';

-- ---------- 3) 工序×工作中心工时定额矩阵（5.2.3：组合唯一 = 适配关系表达，
--     无定额行 = 不支持该工序（FR-4.5-3-4「不支持→提示更换」）；四类工时 spec L2330） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_op_wc_standard (
    ID VARCHAR(64) NOT NULL,
    OP_CODE VARCHAR(64) NOT NULL COMMENT '工序编码',
    WC_CODE VARCHAR(64) NOT NULL COMMENT '工作中心编码',
    SETUP_HOURS DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '准备工时（≥0）',
    RUN_HOURS DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '标准/加工工时（≥0）',
    WAIT_HOURS DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '等待工时（≥0）',
    MOVE_HOURS DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '移动工时（≥0）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 组合天然唯一（无逻辑删除语义：同一组合只应有一行当前定额，重复由服务层+本键双保险）
    UNIQUE KEY UK_MRP_STD_OPWC (OP_CODE, WC_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工序×工作中心工时定额（5.2.3，FR-4.5-3-4 分配带出 + 适配关系）';

-- ---------- 4) 工艺路线版本头（5.2.4：结构同 erp_mrp_bom，design D2 生命周期复刻） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_routing (
    ID VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '父项（产品）物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '产品名称（冗余展示）',
    VERSION_MAJOR INT NOT NULL DEFAULT 1 COMMENT '主版本号（自动分配，不可手填）',
    VERSION_MINOR INT NOT NULL DEFAULT 0 COMMENT '次版本号（变更默认 +1，可勾主升级归零）',
    -- DRAFT 草稿 → PENDING 待审核 → PUBLISHED 已发布 → REVISED 已变更 → OBSOLETE 已废止；退回回 DRAFT
    STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态机（白名单 CAS 迁移）',
    CHANGE_REASON VARCHAR(500) DEFAULT NULL COMMENT '变更原因（发起变更必填）',
    CHANGE_FROM_ID VARCHAR(64) DEFAULT NULL COMMENT '变更来源版本 ID（自引用变更链）',
    PUBLISH_BY VARCHAR(64) DEFAULT NULL COMMENT '发布人（留痕）',
    PUBLISH_AT DATETIME DEFAULT NULL COMMENT '发布时间（留痕）',
    REJECT_REASON VARCHAR(500) DEFAULT NULL COMMENT '最近驳回意见（审批留痕）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 版本唯一（唯一在途/唯一已发布由服务层产品行锁保证；本键兜底版本冲突自动递增）
    UNIQUE KEY UK_MRP_ROUTING_VER (ITEM_CODE, VERSION_MAJOR, VERSION_MINOR),
    KEY IDX_MRP_ROUTING_ITEM_STATUS (ITEM_CODE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工艺路线版本头（5.2.4，BR-4.5-06 同路线引用、角色表版本发布）';

-- ---------- 5) 工艺路线工序行（纯串行 op_seq，偏差 D2 无并行分支；
--     LEAD_TIME 供 FR-4.5-2-5 串行 Σ 提前期倒排） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_routing_op (
    ID VARCHAR(64) NOT NULL,
    ROUTING_ID VARCHAR(64) NOT NULL COMMENT '所属路线版本',
    OP_SEQ INT NOT NULL DEFAULT 0 COMMENT '工序序号（纯串行递增，10/20/30 步进由服务层分配）',
    OP_CODE VARCHAR(64) NOT NULL COMMENT '工序编码',
    OP_NAME VARCHAR(128) DEFAULT NULL COMMENT '工序名称（冗余展示）',
    WC_CODE VARCHAR(64) NOT NULL COMMENT '工作中心编码（须与定额组合存在，保存时 L1 校验）',
    WC_NAME VARCHAR(128) DEFAULT NULL COMMENT '工作中心名称（冗余展示）',
    LEAD_TIME DECIMAL(12,4) DEFAULT NULL COMMENT '工序提前期（天，供 MRP 串行 Σ；缺失由下游回落物料默认提前期）',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '行备注',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    -- 行号唯一性由服务层草稿覆盖保存保证（逻辑删除旧行仍占唯一键，BOM 先例故不设 UK）
    KEY IDX_MRP_ROUTING_OP_ROUTING (ROUTING_ID, OP_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工艺路线工序行（5.2.4，FR-4.5-2-5/FR-4.5-3-4 消费）';

-- ---------- 6) M5-2-4 菜单行补偿（099 重生成含此行，已执行过 099 的存量库靠本条补齐） ----------
INSERT IGNORE INTO erp_admin_menu (ID, PARENT_ID, MENU_CODE, TITLE, PATH, ICON, SORT_ORDER, PERM, STATUS) VALUES
('M5-2-4', 'M5-2', '5.2.4', '路线装配', '/m/5.2.4', '', '40',
 'ROLE_PROCESS_ENG,ROLE_PROCESS_MGR,ROLE_ADMIN', '1');

-- ---------- 7) 5.2 工艺管理菜单 PERM 存量回填（design D4：新装库由 099 生成，
--     已执行过 099 的库靠本 UPDATE 收敛；父 M5-2 与四子同权限防孤儿） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_PROCESS_ENG,ROLE_PROCESS_MGR,ROLE_ADMIN'
 WHERE ID IN ('M5-2', 'M5-2-1', 'M5-2-2', 'M5-2-3', 'M5-2-4');
