-- 119 生产管理-需求计划（5.3，spec 4.5-2 FR-4.5-2-1~7 单期快照口径）：
--     MRP 运行头 + 建议行两表 + ROLE_PLANNER 计划员角色 + M5-3 菜单 PERM 存量回填
--     + 物料主数据补 ROP_QTY（BR-4.5-14 再订货点）
--     （change add-mrp-demand-planning，spec mrp-demand-planning ADDED 十三需求；
--     design D1 两表一表喂三菜单 / D4 角色 / D5 ROP 列 / D4 本迁移）
-- 幂等：CREATE TABLE IF NOT EXISTS / INSERT IGNORE / UPDATE 幂等；
--       ADD COLUMN 走 information_schema 守卫（MySQL 8 无 IF NOT EXISTS，032/033 先例）

-- ---------- 1) MRP 运行头（design D1：RUN_NO 唯一，RUN_STATUS 兼作并发互斥位） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_run (
    ID VARCHAR(64) NOT NULL,
    RUN_NO VARCHAR(32) NOT NULL COMMENT '运行流水号 RUN-YYYYMMDD-NNN',
    SCOPE_TYPE VARCHAR(16) NOT NULL DEFAULT 'FULL' COMMENT '范围 FULL/CATEGORY/GROUP（BR-4.5-11，产品族以分类代理、计划员维度延后 D5）',
    SCOPE_VALUE VARCHAR(64) DEFAULT NULL COMMENT '范围值（分类码/物料组；FULL 为空）',
    -- RUNNING 运行中（互斥位，同刻至多一个）/ DONE 完成 / FAILED 失败（整体回滚后落此状态）
    RUN_STATUS VARCHAR(16) NOT NULL DEFAULT 'RUNNING' COMMENT '运行状态（互斥位）',
    RUN_BY VARCHAR(64) DEFAULT NULL COMMENT '运行人',
    RUN_AT DATETIME DEFAULT NULL COMMENT '运行时间',
    FINISH_AT DATETIME DEFAULT NULL COMMENT '完成时间',
    STAT_SCANNED INT NOT NULL DEFAULT 0 COMMENT '扫描物料数',
    STAT_SUGGESTED INT NOT NULL DEFAULT 0 COMMENT '建议行数（PURCHASE+PRODUCTION）',
    STAT_EXCEPTION INT NOT NULL DEFAULT 0 COMMENT '异常行数（EXCESS+OVERDUE）',
    FAIL_MSG VARCHAR(500) DEFAULT NULL COMMENT '失败原因（FAILED 时）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MRP_RUN_NO (RUN_NO),
    KEY IDX_MRP_RUN_STATUS (RUN_STATUS, CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='MRP 运行头（5.3，FR-4.5-2-1 范围 / BR-4.5-11）';

-- ---------- 2) 建议行（design D1：一表喂三菜单；TYPE=PURCHASE/PRODUCTION/EXCESS） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_suggestion (
    ID VARCHAR(64) NOT NULL,
    RUN_ID VARCHAR(64) NOT NULL COMMENT '所属运行',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '物料名称（冗余展示）',
    PURCHASE_TYPE VARCHAR(16) DEFAULT NULL COMMENT '物料采购类型 BUY/MAKE（分派依据）',
    -- PURCHASE 采购建议(5.3.1) / PRODUCTION 生产建议(5.3.2) / EXCESS 过量供给(仅异常页,不可转正)
    TYPE VARCHAR(16) NOT NULL COMMENT '建议类型',
    -- 净算五值留痕（FR-4.5-2-3，审核可见算式）
    DEMAND_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '需求量（SO+ROP 补货+上层展开聚合）',
    ON_HAND_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '现有库存 OnHand（ΣAVAILABLE_QTY）',
    IN_PROCESS_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '在制 InProcess（本期恒 0 桩，D4）',
    IN_TRANSIT_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '在途 Incoming（PO 未收）',
    NET_REQ DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '净需求（EXCESS 行为负值）',
    REQ_DATE DATE DEFAULT NULL COMMENT '需求日期（SO 最早未交期/父件开工日）',
    ORDER_DATE DATE DEFAULT NULL COMMENT '建议下单日期（逐层倒排结果）',
    OVERDUE_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '逾期标记 1=下单日<今日（FR-4.5-2-5）',
    SUGGEST_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '建议量（替代分配后该物料应建议量）',
    -- STATUS PENDING 待审核 → CONFIRMED 已确认 → CONVERTED 已转换；
    --        PENDING/CONFIRMED → CANCELLED 已取消 / SUPERSEDED 被新运行取代（终态）
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态机（CAS 迁移）',
    ORIG_SUGGEST_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '原建议量（确认改量时留痕）',
    CONFIRM_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '确认量（可改）',
    CONFIRM_DATE DATE DEFAULT NULL COMMENT '确认需求日期（可改）',
    CONFIRM_BY VARCHAR(64) DEFAULT NULL,
    CONFIRM_AT DATETIME DEFAULT NULL,
    CANCEL_REASON VARCHAR(500) DEFAULT NULL COMMENT '取消原因（必填留痕）',
    CANCEL_BY VARCHAR(64) DEFAULT NULL,
    CANCEL_AT DATETIME DEFAULT NULL,
    TARGET_NO VARCHAR(32) DEFAULT NULL COMMENT '转正单号（PR-*/PMO-*）',
    CONVERT_AT DATETIME DEFAULT NULL,
    SUPERSEDED_BY_RUN VARCHAR(32) DEFAULT NULL COMMENT '取代者 RUN_NO（重跑取代规则）',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '替代溯源等备注（替代自 X 优先级 N / 缺路线兜底提示）',
    HANDLED_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '异常已处理标记（仅 EXCESS/OVERDUE 行）',
    HANDLED_NOTE VARCHAR(500) DEFAULT NULL COMMENT '处理备注（必填）',
    HANDLED_BY VARCHAR(64) DEFAULT NULL,
    HANDLED_AT DATETIME DEFAULT NULL,
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MRP_SUG_RUN (RUN_ID, TYPE),
    KEY IDX_MRP_SUG_ITEM_TYPE (ITEM_CODE, TYPE, STATUS),
    KEY IDX_MRP_SUG_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='MRP 建议行（5.3.1/5.3.2/5.3.3 一表三视图，FR-4.5-2-6/7）';

-- ---------- 3) 计划员角色（design D4：规格角色表「计划员」，排序 52 接工艺 50/51） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, CREATE_DATE) VALUES
('role-planner', 'ROLE_PLANNER', '计划员', 52, '1', 'system', NOW());

-- ---------- 4) 5.3 需求计划菜单 PERM 存量回填（design D4：新装库由 099 生成，
--     已执行过 099 的库靠本 UPDATE 收敛；父 M5-3 与三子同权限防孤儿） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_PLANNER,ROLE_ADMIN'
 WHERE ID IN ('M5-3', 'M5-3-1', 'M5-3-2', 'M5-3-3');

-- ---------- 5) 物料主数据补再订货点 ROP_QTY（BR-4.5-14，design D5；032/033 守卫先例） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_mdm_item'
        AND COLUMN_NAME = 'ROP_QTY') = 0,
    'ALTER TABLE erp_mdm_item ADD COLUMN ROP_QTY DECIMAL(18,4) DEFAULT NULL COMMENT ''再订货点（0/NULL=不启用安全库存补货策略，BR-4.5-14）'' AFTER SAFETY_STOCK',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ---------- 6) 物料主数据补最大库存 MAX_STOCK（FR-4.5-2-6 超库存提示，实施期补入） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_mdm_item'
        AND COLUMN_NAME = 'MAX_STOCK') = 0,
    'ALTER TABLE erp_mdm_item ADD COLUMN MAX_STOCK DECIMAL(18,4) DEFAULT NULL COMMENT ''最大库存（0/NULL=不启用超库存提示，FR-4.5-2-6）'' AFTER ROP_QTY',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
