-- 120 生产管理-工单管理（5.4，spec 4.5-3 FR-4.5-3-1~7 七步 SOP）：
--     工单头 + BOM 快照行 + 工序快照行 + 缺料清单行 四表 + ROLE_PLAN_MGR 计划主管
--     + M5-4 菜单 PERM 存量回填 + 建议行 MO_NO 回写列（D6 PMO 对接兑现）
--     （change add-work-order-management，spec work-order-management ADDED 十一需求；
--     design D1 四表一列 / D5 角色与菜单 / D1 PMO 双向关联）
-- 幂等：CREATE TABLE IF NOT EXISTS / INSERT IGNORE / UPDATE 幂等；
--       ADD COLUMN 走 information_schema 守卫（MySQL 8 无 IF NOT EXISTS，032/033/119 先例）

-- ---------- 1) 工单头（design D1：MO_NO 唯一；STATUS 白名单 CAS；PMO 双向关联） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_mo (
    ID VARCHAR(64) NOT NULL,
    MO_NO VARCHAR(32) NOT NULL COMMENT '工单号 MO-YYYYMMDD-NNN（冲突自动递增）',
    PRODUCT_CODE VARCHAR(64) NOT NULL COMMENT '产品编码（自制件 MAKE）',
    PRODUCT_NAME VARCHAR(128) DEFAULT NULL COMMENT '产品名称（冗余展示）',
    QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '计划数量（>0，FR-4.5-3-2）',
    PLAN_START_DATE DATE DEFAULT NULL COMMENT '计划开工日期',
    PLAN_END_DATE DATE DEFAULT NULL COMMENT '计划完工日期（<今日 L1 阻断，C-4.5-06）',
    PRIORITY INT NOT NULL DEFAULT 5 COMMENT '优先级 1~9（1 最高，缺省按计划开工日期排序）',
    -- PLANNED→PENDING→CONFIRMED→RELEASED→COMPLETED→CLOSED；旁路 HOLD/CANCELLED
    STATUS VARCHAR(16) NOT NULL DEFAULT 'PLANNED' COMMENT '状态机（白名单 CAS 迁移）',
    PLANNED_MO_NO VARCHAR(32) DEFAULT NULL COMMENT '来源 PMO 单号（PMO 入口建单留痕，手工为空）',
    SHORTAGE_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '缺料待料标记 1=缺料（释放不阻断仅标记，L2496 场景）',
    SOURCE_BOM_ID VARCHAR(64) DEFAULT NULL COMMENT 'BOM 快照来源版本 ID（BR-4.5-16 隔离）',
    BOM_VERSION VARCHAR(16) DEFAULT NULL COMMENT 'BOM 快照版本号（主.次）',
    SOURCE_ROUTING_ID VARCHAR(64) DEFAULT NULL COMMENT '路线快照来源版本 ID',
    QUALIFIED_QTY DECIMAL(18,4) DEFAULT NULL COMMENT '完工确认合格产出（5.4.5 手动完工填入）',
    CHANGE_REASON VARCHAR(500) DEFAULT NULL COMMENT '变更原因（拆分等操作留痕）',
    HOLD_REASON VARCHAR(500) DEFAULT NULL COMMENT '挂起原因（必填）',
    CANCEL_REASON VARCHAR(500) DEFAULT NULL COMMENT '取消原因（必填）',
    REJECT_REASON VARCHAR(500) DEFAULT NULL COMMENT '审批驳回意见',
    SPLIT_FROM_MO VARCHAR(32) DEFAULT NULL COMMENT '拆分来源工单号（C-4.5-15 拆分链）',
    MERGED_FROM_MO VARCHAR(32) DEFAULT NULL COMMENT '合并来源（预留，D6 本期不写）',
    SUBMIT_BY VARCHAR(64) DEFAULT NULL, SUBMIT_AT DATETIME DEFAULT NULL COMMENT '提交审批留痕',
    APPROVE_BY VARCHAR(64) DEFAULT NULL, APPROVE_AT DATETIME DEFAULT NULL COMMENT '审批通过留痕',
    RELEASE_BY VARCHAR(64) DEFAULT NULL, RELEASE_AT DATETIME DEFAULT NULL COMMENT '释放留痕',
    COMPLETE_BY VARCHAR(64) DEFAULT NULL, COMPLETE_AT DATETIME DEFAULT NULL COMMENT '完工确认留痕',
    CLOSE_BY VARCHAR(64) DEFAULT NULL, CLOSE_AT DATETIME DEFAULT NULL COMMENT '关闭留痕',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MRP_MO_NO (MO_NO),
    KEY IDX_MRP_MO_PRODUCT (PRODUCT_CODE, STATUS),
    KEY IDX_MRP_MO_STATUS (STATUS),
    KEY IDX_MRP_MO_PMO (PLANNED_MO_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='生产工单头（5.4，FR-4.5-3 六态状态机，spec 4.5-3）';

-- ---------- 2) BOM 快照行（BR-4.5-16：创建时拷贝，源 BOM 变更不回写；5.4.1 一次性写入不供行级编辑） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_mo_bom (
    ID VARCHAR(64) NOT NULL,
    MO_ID VARCHAR(64) NOT NULL COMMENT '所属工单',
    LINE_NO INT NOT NULL COMMENT '行号（展平序）',
    TREE_LEVEL INT NOT NULL DEFAULT 1 COMMENT 'BOM 层级（1=产品直接子项；多层展平 design D4）',
    OWNER_ITEM VARCHAR(64) DEFAULT NULL COMMENT '所属父件编码（本行挂在哪个件下）',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '子项物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '子项名称（冗余展示）',
    UNIT_QTY DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '单位用量（展平行为相对工单产品的有效单耗=链上乘积）',
    LOSS_RATE DECIMAL(7,4) NOT NULL DEFAULT 0 COMMENT '损耗率（展平行为有效损耗：Π(1+损耗)−1，保持 REQ=QTY×用量×(1+损耗) 口径）',
    BASE_UNIT VARCHAR(16) DEFAULT NULL COMMENT '单位',
    SUBSTITUTE_INFO TEXT DEFAULT NULL COMMENT '替代料信息快照（JSON：编码/比例/优先级）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MRP_MO_BOM_MO (MO_ID, LINE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工单 BOM 快照行（FR-4.5-3-3，BR-4.5-16 隔离后续变更）';

-- ---------- 3) 工序快照行（FR-4.5-3-4：路线快照 + 四类标准工时带入） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_mo_op (
    ID VARCHAR(64) NOT NULL,
    MO_ID VARCHAR(64) NOT NULL COMMENT '所属工单',
    OP_SEQ INT NOT NULL COMMENT '工序序号',
    OP_CODE VARCHAR(32) NOT NULL COMMENT '工序编码（快照自 5.2.1 字典）',
    OP_NAME VARCHAR(64) DEFAULT NULL COMMENT '工序名称（冗余展示）',
    WC_CODE VARCHAR(32) DEFAULT NULL COMMENT '工作中心编码（快照分配）',
    WC_NAME VARCHAR(64) DEFAULT NULL COMMENT '工作中心名称（冗余展示）',
    LEAD_TIME DECIMAL(10,2) DEFAULT NULL COMMENT '工序提前期（天）',
    SETUP_HOURS DECIMAL(12,4) DEFAULT NULL COMMENT '准备工时',
    RUN_HOURS DECIMAL(12,4) DEFAULT NULL COMMENT '标准（加工）工时',
    WAIT_HOURS DECIMAL(12,4) DEFAULT NULL COMMENT '等待工时',
    MOVE_HOURS DECIMAL(12,4) DEFAULT NULL COMMENT '移动工时',
    -- PENDING 待执行 / DONE 完成（预留工序级状态，5.7 报工推进）
    OP_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '工序状态（预留）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MRP_MO_OP_MO (MO_ID, OP_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工单工序快照行（FR-4.5-3-4 分配工作中心 + 自动带入标准工时）';

-- ---------- 4) 缺料清单行（FR-4.5-3-6 库存预检输出；与 5.5 齐套检查共用，KittingService 唯一算法） ----------
CREATE TABLE IF NOT EXISTS erp_mrp_mo_shortage (
    ID VARCHAR(64) NOT NULL,
    MO_ID VARCHAR(64) NOT NULL COMMENT '所属工单',
    BOM_LINE INT NOT NULL COMMENT '对应 BOM 快照行号',
    ITEM_CODE VARCHAR(64) NOT NULL COMMENT '子项物料编码',
    ITEM_NAME VARCHAR(128) DEFAULT NULL COMMENT '子项名称（冗余展示）',
    REQ_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '需求数量 = QTY×用量×(1+损耗率)',
    AVAIL_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '可用数量 = 库存 + 在途',
    SHORT_QTY DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '缺料数量（>0 行）',
    RESOLVED_FLAG VARCHAR(1) NOT NULL DEFAULT '0' COMMENT '已齐套 1（在途到货后自动置位清标记）',
    CREATE_BY VARCHAR(64) DEFAULT NULL,
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT NULL,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEL_FLAG VARCHAR(1) NOT NULL DEFAULT '0',
    VER_NO INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY IDX_MRP_MO_SHORT_MO (MO_ID, ITEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='工单缺料清单行（FR-4.5-3-6，BR-4.5-04 齐套算法输出，5.5 复用）';

-- ---------- 5) 计划主管角色（design D5：审批签署侧，排序 53 接计划员 52） ----------
INSERT IGNORE INTO erp_admin_role (ID, ROLE_CODE, ROLE_NAME, SORT_ORDER, STATUS, CREATE_BY, CREATE_DATE) VALUES
('role-plan-mgr', 'ROLE_PLAN_MGR', '计划主管', 53, '1', 'system', NOW());

-- ---------- 6) 5.4 工单管理菜单 PERM 存量回填（design D5：新装库由 099 生成，
--     已执行过 099 的库靠本 UPDATE 收敛；父 M5-4 与五子同权限防孤儿） ----------
UPDATE erp_admin_menu
   SET PERM = 'ROLE_PLANNER,ROLE_PLAN_MGR,ROLE_ADMIN'
 WHERE ID IN ('M5-4', 'M5-4-1', 'M5-4-2', 'M5-4-3', 'M5-4-4', 'M5-4-5');

-- ---------- 7) 建议行 MO_NO 回写列（design D1：D6 PMO 对接兑现——
--     PMO 入口建单时 UPDATE ... WHERE targetNo=? AND MO_NO IS NULL 幂等） ----------
SET @ddl = IF(
    (SELECT COUNT(*) FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = DATABASE()
        AND TABLE_NAME = 'erp_mrp_suggestion'
        AND COLUMN_NAME = 'MO_NO') = 0,
    'ALTER TABLE erp_mrp_suggestion ADD COLUMN MO_NO VARCHAR(32) DEFAULT NULL COMMENT ''已关联工单号（PMO 转正后建单回写，NULL=未建）'' AFTER TARGET_NO',
    'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
